<hgroup class="box">
    <header>
        <h3>合同管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/people/newBusiness">添加商务组成员</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<div class="panel panel panel-primary">
    <div class="panel-heading">商务组成员列表</div>
    <div class="panel-body">

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">id</th>
                <th scope="col">名称</th>
                <th scope="col">城市</th>
                <th scope="col">操作</th>
            </tr>
            <?php foreach ($data as $v): ?>
                <tr>
                    <td><?php echo $v['id']; ?></td>
                    <td><?php echo $v['name']; ?></td>
                    <td><?php echo $city[$v['city']]; ?></td>
                    <td></td>
                </tr>
            <?php endforeach; ?>
        </table>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>

