<hgroup class="box">
    <header>
        <h3>合同管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/people/business">商务组成员列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/people/saveBusiness" method="post">
    <header class="box-title">添加商务组成员</header>
    <table class="table">
        <tr>
            <th width="160">名称</th>
            <th colspan="3"><input type="text" class="cssInput" name="name" value="">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3" width="600">
                <button id="ti-place" class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>