<hgroup class="box">
    <header>
        <h3>积分管理</h3>
        <i class="icon icon-add"></i>
<!--        <a href="/wftadlogin/authmenu/new">添加菜单资源</a>-->
        &nbsp;&nbsp;&nbsp;
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>

        <div>温馨提示：<span style="color:green">有问题 请及时联系</span></div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $uid = null;
    $typeid = null;
    $city = null;


    if (isset($_GET['type']) && $_GET['type']) {
        $typeid = $_GET['type'];
    }

    if (isset($_GET['uid']) && $_GET['uid']) {
        $uid = $_GET['uid'];
    }

    if (isset($_GET['city']) && $_GET['city']) {
        $city = $_GET['city'];
    }

    if (isset($_GET['time']) && $_GET['time']) {
        $time = $_GET['time'];
    }

    ?>
    <table class="table">
        <tr>
            <th width="160">积分类型</th>
            <th>
                <select name="type" id="select">
                    <option value="0" <?php echo ($code_status == 0) ? 'selected' : '';?>>全部</option>
                    <?php foreach($types as $k => $t): ?>
                        <option value="<?php echo $k; ?>" <?php echo ((int)$k === (int)$typeid) ? 'selected' : '';?>><?php echo $t; ?></option>
                    <?php endforeach; ?>
                </select>
            </th>
            <th width="160">用户id</th>
            <th>
                <input type="text" class="cssInput" name="uid" value="<?php echo $uid;?>" />
                <input type="hidden" name="city" value="<?php echo $city;?>" />
            </th>
            <th width="160">时间区间</th>
            <th>
                <select name="time" id="select">
                    <option value="0" <?php echo ($time == 0) ? 'selected' : '';?>>全部</option>
                    <option value="7" <?php echo ($time == 7) ? 'selected' : '';?>>一周内</option>
                    <option value="30" <?php echo ($time == 30) ? 'selected' : '';?>>一个月内</option>
                    <option value="180" <?php echo ($time == 180) ? 'selected' : '';?>>半年内</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="5">
                <a href="/wftadlogin/integral/cityintegral?city=<?php echo $_GET['city']; ?>" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/order/outaccount" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>
<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">编号</th>
                <th class="size1">用户ID</th>
                <th class="size1">积分类型</th>
                <th class="size1">总积分</th>
                <th class="size1">基础积分</th>
                <th class="size1">奖励积分</th>
                <th class="size1">对应商品</th>
                <th class="size1">对应游玩地</th>
            </tr>
            <?php if (count($data)):  ?>
                <?php foreach ($data as $row): ?>
                    <tr style="text-align: left">
                        <td class="size1">
                                <?php echo $row['id']; ?>
                        </td>
                        <td class="size1"><?php echo $row['uid']; ?></td>
                        <td class="size1"><?php echo $row['desc']; ?></td>
                        <td class="size1"><?php echo $row['total_score']; ?></td>
                        <td class="size1"><?php echo $row['base_score']; ?></td>
                        <td class="size1"><?php echo $row['total_score'] - $row['base_score']; ?></td>
                        <?php if($row['type'] == 5 or $row['type'] == 102){
                            $row['object_id'] = str_pad($row['object_id'], 9, "0", STR_PAD_LEFT);
                        } ?>
                        <td class="size1"><?php if(in_array((int)$row['type'],[3,4,5,102,17],true)){echo array_key_exists($row['object_id'],$goods)?$goods[$row['object_id']]:'';} ?></td>
                        <td class="size1"><?php if(in_array((int)$row['type'],[1,2,18],true)){echo array_key_exists($row['object_id'].'',$places)?$places[$row['object_id']]:'';} ?></td>

                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无数据</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    $(function () {
    })
</script>