<hgroup class="box">
    <header>
        <h3>资格券管理</h3>
        <i class="icon icon-add"></i>
<!--        <a href="/wftadlogin/authmenu/new">添加菜单资源</a>-->
        &nbsp;&nbsp;&nbsp;
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>

        <div>温馨提示：<span style="color:green">有问题 请及时联系</span></div>
    </aside>
</hgroup>

<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">
                    城市
                </th>
                <th class="size2">
                    累计积分
                </th>
                <th class="size1">
                    累计基础积分
                </th>
                <th class="size2">
                    累计奖励积分
                </th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size2">
                            <a href="/wftadlogin/integral/cityintegral?city=<?php echo $row['city']; ?>">
                                <?php echo $city[$row['city']]; ?>
                            </a>
                        </td>
                        <td class="size1"><?php echo $row['total_score']; ?></td>
                        <td class="size1"><?php echo $row['base_score']; ?></td>
                        <td class="size1"><?php echo $row['award_score']; ?></td>

                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无数据</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    $(function () {
    })
</script>