<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <title>武汉十佳遛娃基地评选</title>
    <link href="/activity/px/css/h5-selection.css" rel="stylesheet"  type="text/css"/>
    <style>
        body{
            background: #f0e4d5;
        }
    </style>
</head>
<body>
<img class="link" src="/activity/px/images/link.png" />
</body>
</html>