<hgroup class="box">
    <header>
        <h3>好评有礼设置</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/setting/marketing">返回</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>

        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/setting/goodcommentsave" method="post">
    <header class="box-title">好评有礼设置&nbsp;&nbsp;<?php echo $filtercity; ?></header>

    <table class="table">
        <tr>
            <th width="160">点评规则</th>
            <th colspan="3">
                <textarea class="cssTextArea" name="rule"><?php echo $data ? $data->rule : '';?></textarea>　<span style="color:red">1000汉字内</span>
            </th>
        </tr>

        <tr>
            <th width="160">点评示例</th>
            <th colspan="3">
                <textarea class="cssTextArea" name="eg"><?php echo $data ? $data->eg : '';?></textarea>　<span style="color:red">1000汉字内</span>
            </th>
        </tr>

        <tr>
            <th width="160">奖品名称</th>
            <th colspan="3"><input type="text" class="cssInput" name="title" value="<?php echo $data->title; ?>"/>
            </th>
        </tr>
        <tr>
            <th width="160">点评之后获奖时间</th>
            <th colspan="3"><input type="text" class="cssInput" name="prize_day" value="<?php echo $data->prize_day; ?>"/>
            </th>
        </tr>

        <tr>
            <th width="160">安卓应用市场网址</th>
            <th colspan="3"><input type="text" class="cssInput" name="url" value="<?php echo $data->url; ?>"/>
            </th>
        </tr>
        <tr>
            <th width="160">好评有礼提示</th>
            <th colspan="3"><input type="text" class="cssInput" name="tips" value="<?php echo $data->tips; ?>"/>
            </th>
        </tr>
        <tr>
            <th width="160"></th>
            <th colspan="3">
                <button type="submit" class="btn btn-primary">提交</button>
            </th>
        </tr>

    </table>

</form>




