<hgroup class="box">
    <header>
        <h3>地推活动管理</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/setting/groundadd">新增地推</a>
        &nbsp;&nbsp;&nbsp;
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>

        <div>温馨提示：<span style="color:green">有问题 请及时联系</span></div>
    </aside>
</hgroup>


<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">编号</th>
                <th class="size1">类别</th>
                <th class="size1">微信名称</th>
                <th class="size1">注册时间</th>
                <th class="size1">电话</th>
            </tr>
            <?php if (count($data)):  ?>
                <?php foreach ($data as $row): ?>
                    <?php if($row['id']==0){continue;} ?>
                    <tr style="text-align: left">
                        <td class="size1">
                                <?php echo $row['id']; ?>
                        </td>
                        <td class="size1">
                            <?php echo $row['type']==1?'地推活动':'签到'; ?>
                        </td>
                        <td class="size1"><?php echo $row['weixin_name']; ?></td>
                        <td class="size1"><?php echo date('Y-m-d H:i:s', $row['concern_time']); ?></td>
                        <td class="size1"><?php echo $row['phone']; ?></td> 
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无数据</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    $(function () {
    })
</script>