<hgroup class="box">
    <header>
        <h3>小编约稿</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/setting/invitecontent">返回</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>

        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/setting/invitecontentsave" method="post">
    <header class="box-title">小编约稿&nbsp;&nbsp;<?php echo $filtercity; ?></header>

    <table class="table">
        <tr>
            <th width="160">图文详情</th>
            <th colspan="3" width="600">
                <script type="text/plain" id="myEditor" style="width:600px;height:240px;"><?php echo $data ? htmlspecialchars_decode($data->content) : '<p>这里我可以写一些输入提示</p>';?></script>
            </th>
        </tr>


<!--        <tr>-->
<!--            <th width="160">投稿邮箱</th>-->
<!--            <th colspan="3"><input type="text" class="cssInput" name="email" value="--><?php //echo $data->email; ?><!--"/>-->
<!--            </th>-->
<!--        </tr>-->
        <tr>
            <th width="160">奖励提示</th>
            <th colspan="3"><input type="text" class="cssInput" name="award" value="<?php echo $data->award; ?>"/>
            </th>
        </tr>
        <tr>
            <th width="160"></th>
            <th colspan="3">
                <input type="hidden" name="city" value="<?php echo $data->city; ?>" />
                <button type="submit" class="btn btn-primary">提交</button>
            </th>
        </tr>

    </table>

</form>
<script>
    $(function () {
        //实例化编辑器
        var um = UE.getEditor('myEditor');

        // post提交
        $('#ti-place').click(function () {
            $.post('/wftadlogin/place/save', $('#place_save').serialize(), function (data) {
                if (data.status == 1) {
                    alert('保存成功');
                    window.location.href=document.referrer;
                } else {
                    alert(data.message);
                }
            }, 'json');
            return false;
        })
    })

</script>
<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script src="/js/file_upload/jquery.iframe-transport.js"></script>
<script src="/js/file_upload/jquery.fileupload.js"></script>
<script>
    $('#fileupload').fileupload({
        url: '/wftadlogin/index/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='cover']").attr('value', data.result.url);
                $(".fileupload").attr('src', data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });

</script>

