<hgroup class="box">
    <header>
        <h3>营销初始值设置</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/setting/marketing">返回</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>

        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<style>
    .table>thead>tr>th, .table>tbody>tr>th, .table>tfoot>tr>th, .table>thead>tr>td, .table>tbody>tr>td, .table>tfoot>tr>td
    {border-top: 0px;}
</style>
<form class="box box-form" action="/wftadlogin/setting/marketsave" method="post">
    <header class="box-title">营销初始值设置&nbsp;&nbsp;<?php echo $filtercity; ?></header>

    <table class="table">
        <tr style="border-bottom:2px solid #D6CEC9">
            <th width="160">单日签到积分</th>
            <th colspan="1"><input type="text" class="cssInput" name="sign_one" value="<?php echo $data->sign_one; ?>">
            </th>
            <th width="160">连续签到<input type="text" style="width: 40px;" class="cssInput" name="sign_day" value="<?php echo $data->sign_day; ?>">天额外积分</th>
            <th colspan="3"><input type="text" class="cssInput" name="sign_integral"
                                   value="<?php echo $data->sign_integral; ?>">
            </th>
            <th colspan="2"></th>
        </tr>

        <tr style="border-bottom:0px;">
            <th width="160" >更换宝宝头像积分</th>
            <th colspan="1"><input type="text" class="cssInput" name="baby_face" value="<?php echo $data->baby_face; ?>">
            </th>
            <th width="160">更换头像积分</th>
            <th colspan="3"><input type="text" class="cssInput" name="face_integral" value="<?php echo $data->face_integral; ?>">
            </th>
            <th colspan="2"></th>
        </tr>

        <tr style="border-top:0px;">
            <th width="160">补充宝宝资料积分</th>
            <th colspan="1"><input type="text" class="cssInput" name="baby_info" value="<?php echo $data->baby_info; ?>"/>
            </th>
            <th width="160">微信号绑定积分</th>
            <th colspan="3"><input type="text" class="cssInput" name="weixin_bind" value="<?php echo $data->weixin_bind; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>
        <tr style="border-bottom:2px solid #D6CEC9">
            <th width="160">绑定微信提示语</th>
            <th colspan="4"><input type="text" class="cssInput" name="weixin_bind_tips" value="<?php echo $data->weixin_bind_tips; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>
        <tr>
            <th width="160">使用商品获得积分分值与商品价格比例</th>
            <th colspan="4"><input type="text" class="cssInput" name="good_integral_price" value="<?php echo $data->good_integral_price; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>
        <tr style="border-bottom:2px solid #D6CEC9">
            <th width="160">商品评论积分</th>
            <th colspan="1"><input type="text" class="cssInput" name="good_comment_integral" value="<?php echo $data->good_comment_integral; ?>"/>
            </th>
            <th width="160">商品评论获得<input type="text" style="width: 40px;" class="cssInput" name="good_comment_prize_num" value="<?php echo $data->good_comment_prize_num; ?>">个点赞积分</th>
            <th colspan="3"><input type="text" class="cssInput" name="good_comment_prize_integral" value="<?php echo $data->good_comment_prize_integral; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>


        <tr>
            <th width="160">参加活动获得积分分值与活动价格比例</th>
            <th colspan="4"><input type="text" class="cssInput" name="event_integral_price" value="<?php echo $data->event_integral_price; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>
        <tr style="border-bottom:2px solid #D6CEC9">
            <th width="160">活动评论积分</th>
            <th colspan="1"><input type="text" class="cssInput" name="event_comment_integral" value="<?php echo $data->event_comment_integral; ?>"/>
            </th>
            <th width="160">活动评论获得<input type="text" style="width: 40px;" class="cssInput" name="event_comment_prize_num" value="<?php echo $data->event_comment_prize_num; ?>">个点赞积分</th>
            <th colspan="3"><input type="text" class="cssInput" name="event_comment_prize_integral" value="<?php echo $data->event_comment_prize_integral; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>



        <tr>
            <th width="160">圈子发言积分</th>
            <th colspan="1"><input type="text" class="cssInput" name="circle_speak" value="<?php echo $data->circle_speak; ?>"/>
            </th>
            <th width="160">圈子发言获得<input type="text" style="width: 40px;" class="cssInput" name="circle_prize_num" value="<?php echo $data->circle_prize_num; ?>">个点赞积分</th>
            <th colspan="3"><input type="text" class="cssInput" name="circle_prize_integral" value="<?php echo $data->circle_prize_integral; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>



        <tr>
            <th width="160">游玩地评论积分</th>
            <th colspan="1"><input type="text" class="cssInput" name="place_comment_integral" value="<?php echo $data->place_comment_integral; ?>"/>
            </th>
            <th width="160">游玩地评论获得<input type="text" style="width: 40px;" class="cssInput" name="place_comment_prize_num" value="<?php echo $data->place_comment_prize_num; ?>">个点赞积分</th>
            <th colspan="3"><input type="text" class="cssInput" name="place_comment_prize_integral" value="<?php echo $data->place_comment_prize_integral; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>

        <tr>
            <th width="160">每人每日点评游玩地最多获得积分</th>
            <th colspan="4"><input type="text" class="cssInput" name="oneday_place_comment_integral" value="<?php echo $data->oneday_place_comment_integral; ?>"/>
                <span style="color: #802420"></span>
            </th>
            <th colspan="2"></th>
        </tr>

        <tr>
            <th width="160">分享商品积分</th>
            <th colspan="1"><input type="text" class="cssInput" name="share_good_integral" value="<?php echo $data->share_good_integral; ?>"/>
            </th>
            <th width="160">分享游玩地积分</th>
            <th colspan="3"><input type="text" class="cssInput" name="share_place_integral" value="<?php echo $data->share_place_integral; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>

        <tr>
            <th width="160">每人每天分享商品最多获得积分</th>
            <th colspan="1"><input type="text" class="cssInput" name="oneday_share_good_integral" value="<?php echo $data->oneday_share_good_integral; ?>"/>
            </th>
            <th width="160">每人每天分享游玩地最多获得积分</th>
            <th colspan="3"><input type="text" class="cssInput" name="oneday_share_place_integral" value="<?php echo $data->oneday_share_place_integral; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>

        <tr style="border-bottom:2px solid #D6CEC9">
            <th width="160">每日用户积分上限</th>
            <th colspan="4"><input type="text" class="cssInput" name="oneday_integral" value="<?php echo $data->oneday_integral; ?>"/>
                <span style="color: #802420"> 每日积分上限只影响商品、游玩地分享、游玩地评论和点赞、圈子发言和点赞</span>
            </th>
            <th colspan="2"></th>
        </tr>

        <tr style="border-bottom:0px solid #D6CEC9">
            <th width="160">积分兑换限购资格比例</th>
            <th colspan="1"><input type="text" class="cssInput" name="integral_quota" value="<?php echo (int)$data->integral_quota; ?>"/>
            </th>
            <th width="160">资格券有效时间</th>
            <th colspan="3"><input type="text" class="cssInput" name="quota_time" value="<?php echo $data->quota_time; ?>"/>
            </th>
            <th colspan="2"></th>
        </tr>
        <tr>
            <th width="160">默认分享的玩伴圈</th>
            <th colspan="6">
                <select name="share_circle" id="select">
                    <?php foreach($circle as $k => $s): ?>
                    <option value="<?php echo $s['_id'].$id; ?>" <?php echo ($s['_id'].$id === $data->share_circle) ? 'selected' : '';?>><?php echo $s['title']; ?></option>
                    <?php endforeach; ?>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="4">
                <button type="submit" class="btn btn-primary">提交</button>
            </th>
            <th colspan="2"></th>
        </tr>

    </table>

</form>

<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script src="/js/file_upload/jquery.iframe-transport.js"></script>
<script src="/js/file_upload/jquery.fileupload.js"></script>
<script>
    $('#fileupload').fileupload({
        url: '/wftadlogin/index/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='cover']").attr('value', data.result.url);
                $(".fileupload").attr('src', data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });

</script>

