<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <meta name="format-detection" content="telephone=no">
    <title><?php echo $title?></title>
    <link type="text/css" rel="stylesheet" href="/css/share/tag-style.css">
</head>
<body>
<div id="topHeight">
    <div class="bg">
        <img src="<?php echo $cover ?>">
    </div>
    <pre><?php echo $introduce;?></pre>
</div>
<div id="tab" class="tab">
    <a id="place" class="activ" href="javascript:void(0);" onclick="tabClick(this);">游玩地</a>
    <a id="ticket" href="javascript:void(0);" onclick="tabClick(this);">票券</a>

    <div class="line"></div>
    <div class="cl"></div>
</div>
<div class="blank"></div>
<div id="placeCont">
    <ul>
        <?php foreach ($place_list as $m): ?>
            <li>
                <a href="/web/place?id=<?php echo $m['place_id']; ?>">
                    <div class="place-imgDiv">
                        <img src="<?php echo $m['place_cover']; ?>">

                        <div class="place-title"><?php echo $m['place_name'];?></div>
                    </div>
                    <div class="place-det">
                        <span class="place-price">￥<?php echo $m['place_price'];?></span>
                        <?php if ($m['reticket']): ?>
                            <div class="place-hasTicket">
                                <span></span>

                                <div class="place-text">有票</div>
                            </div>
                        <?php endif;?>
                        <div class="cl"></div>
                        <p><?php echo $m['editor_word'];?></p>
                    </div>
                </a>
            </li>
        <?php endforeach;?>
    </ul>
</div>
<div id="ticketCont" class="none">
    <ul>
        <?php foreach ($good_list as $n): ?>
            <li>
                <a href="/web/organizer/shops?id=<?php echo $n['game_id']; ?>">
                    <div class="ticket-boxDiv">
                        <img src="<?php echo $n['good_cover']; ?>">

                        <div class="ticket-det">
                            <h2><?php echo $n['good_name'];?></h2>

                            <p><?php echo $n['editor_word'];?></p>

                            <div>
                                <span class="ticket-price">￥<?php echo $n['good_price'];?></span>
                                <span class="discount"><?php echo $n['discount'];?>折</span>

                                <div class="cl"></div>
                            </div>
                        </div>
                        <div class="cl"></div>
                    </div>
                </a>
            </li>
        <?php endforeach;?>
    </ul>
</div>
</body>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script>
    $(function () {

        var tabEle = $("#tab");
        var blankEle = $(".blank");
        var tabTop = $("#topHeight").outerHeight(true);
        var scrollTop = 0;
        var isFirst = true;

        $(window).scroll(function () {

            scrollTop = $(this).scrollTop();
            if (isFirst) {
                tabTop = $("#topHeight").outerHeight(true);
                isFirst = false;
            }

            if (scrollTop > tabTop || scrollTop == tabTop) {
                tabEle.css("position", "fixed");
                blankEle.css("display", "block");
            } else {
                tabEle.css("position", "relative");
                blankEle.css("display", "none");
            }

        });
        var type =<?php echo $view_type;?>;

        if (type == 1) {
            $('#place').trigger('click');
        }
        else if (type = 2) {
            $('#ticket').trigger('click');
        }
        else if (type == 3) {
            $('#place').trigger('click');
        }
        else if (type == 4) {
            $('#ticket').trigger('click');
        }



    }());

    function tabClick(obj) {
        var idStr = $(obj).attr("id");
        var placeEle = $("#placeCont");
        var ticketEle = $("#ticketCont");

        if (!$(obj).hasClass("activ")) {

            $(obj).addClass("activ").siblings().removeClass("activ");
            $("#" + idStr + "Cont").removeClass("none").addClass("block");
            if (idStr == "place") {
                ticketEle.removeClass("block").addClass("none");
            } else if (idStr == "ticket") {
                placeEle.removeClass("block").addClass("none");
            }
        }
    }
</script>
</html>