<!DOCTYPE html>
<html>
<head lang="en">
    <title>晒宝宝疯玩照片，赢取荟聚周年壕礼！</title>
    <link rel="stylesheet" type="text/css" href="/activity/css/layout.css?t=<?php echo time();?>">
    <meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
</head>
<body>
<div class="banner">
    <img src="http://wan.wanfantian.com/uploads/2016/04/23/29f09e216a7a9dd583d00e6d82ca2300.jpg"/>
</div>
<div class="info">
    <div class="info-title">
        <img src="<?php echo $userInfo['user_img'];?>" />
        <p><?php echo $userInfo['user_name'];?><br/>疯狂指数:<span><?php echo $userInfo['power_num'];?></span></p>
        <a class="btn1" id="fighting" data-user-id="<?php echo $userInfo['id'];?>">为TA助力</a>
    </div>
    <img class="photo" src="<?php echo $userInfo['activity_img'];?>" />
    <div class="info-btn">
        <a class="btn2 yao-ren" href="javascript:void(0)">邀请好友助力</a>
        <a class="btn2" href="/activity/huiju/join?tme=<?php echo time();?>">我要参加</a>
    </div>
    <h5><span>已有<?php echo $click_number;?>人围观</span></h5>
</div>
<div class="link">
    <a class="award" href="/activity/huiju/myprize?tr=<?php echo time();?>">我的奖品</a>
    <a class="raffle" href="/activity/huiju/prize?tp=<?php echo time();?>">我要抽奖</a>
</div>
<div class="records">
    <div class="records-title">好友助力记录</div>
    <ul>
        <?php foreach($powerLog as $log):?>
        <li class="number01">
            <img src="<?php echo $log['img'];?>"/>
           <!-- <p><span class="records-username"><?php /*echo $log['u_name'];*/?></span><span class="records-popularity">疯狂指数:<mark>&nbsp;+10</mark></span></p>
            <p><span class="records-id"><?php /*echo $log['note'];*/?>！</span><span class="records-time"><?php /*echo date('Y-m-d', $log['dateline']);*/?></span></p>
         -->   <p class="times">
                疯狂指数:&nbsp;+10<br/>
                <?php echo date('Y-m-d', $log['dateline']);?>
            </p>
            <p class="details">
                <?php echo $log['u_name'];?><br/>
                <?php echo $log['note'];?>
            </p>
        </li>
        <?php endforeach;?>


    </ul>
</div>
<div class="intro">
    <div class="intro-title">活动介绍</div>
    <p>*活动与奖品咨询，快添加<span>玩翻天小七微信号：wanfantian1 </span></p>
    <p>加微信号 还有机会抢红包</p>
    <p>1. 活动时间：2016年4月20日10:00-5月1日24:00，上传宝宝/儿童 真实疯玩照片（参加人必须是照片是宝宝/儿童的第一监护人），发送给好友帮忙助力。助力成功1次可获得10分。达到50分可参与抽奖。抽一次奖，需消耗50积分。</p>
    <p>2. 奖品及领奖信息在“我的奖品”页查看。在法律范围内活动解释权归玩翻天所有。</p>
</div>
<div class="prizes">
    <div class="prizes-title">活动奖品</div>
    <ul>
        <?php foreach($prizeData as $prize):?>
            <li>
                <img src="<?php echo $prize['prize_img']; ?>"/>
                <p><span><?php echo $prize['prize_name']; ?></span></p>
            </li>
        <?php endforeach;?>
    </ul>
</div>


<div class="matte">
    <img src="/activity/images/matte.png" />
</div>
<div class="black"></div>
<div class="popup">
    <div class="popup-content">
        <p>中国好伙伴！助力成功！ <br/>疯狂指数：<span>+10</span>！<br/>邀请好友赢得更多疯狂指数吧~  </p>
        <div class="cross"></div>
    </div>
    <div class="popup-btn">确认</div>
</div>
<div class="popup2">
    <div class="popup-content">
        <p>宝宝棒棒哒！ <br/>疯狂指数超过<span>+10</span>分！<br/>可以去抽奖咯！</p>
        <div class="cross"></div>
    </div>
    <div class="popup-selection">
        <p class="popup-s">暂时不抽</p>
        <span><a href="/activity/huiju/prize?tp=<?php echo time();?>">我要抽奖</a></span>
    </div>
</div>

<div class="popup6">
    <div class="popup-content">
        <p>已助力过！<br/>快点击右上角，召唤小伙伴为自己助力！<br/>每获得<span>50</span>积分，可抽奖一次噢！</p>
        <div class="cross"></div>
    </div>
    <div class="popup-btn">确认</div>
</div>

</body>
<script type="text/javascript" src="/mabaobao/js/jquery-2.1.3.min.js"></script>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script>
    $(function () {
        //加油
        $('#fighting').on("tap", function() {
            var user_id = $(this).attr('data-user-id');
            $.post('/activity/huiju/power?type=2', {user_id:user_id}, function (data) {
                if (data.status == 1) {
                    if (data.score < 50) {
                        $(".popup").show();
                        $(".black").show();
                    } else {
                        $(".popup2").show();
                        $(".black").show();
                    }
                } else {
                    $(".popup6").show();
                    $(".black").show();
                }
            }, 'json');
            return false;
        });

        $('.yao-ren').click(function(){
            $(".matte").show();
        })

        $(".matte").click(function(){
            $(".matte").hide();
        });

        $('.popup-btn').on("tap",function(){
            $(".popup").hide();
            $(".black").hide();
            $(".popup6").hide();
        })

        $('.popup-s').on("tap",function(){
            $(".popup2").hide();
            $(".black").hide();
        })

        $(".cross").on("tap",function(){
            $(".popup").hide();
            $(".popup2").hide();
            $(".popup6").hide();
            $(".black").hide();
        });

        wx.config({
            debug: false, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
            appId: '<?php echo $jsApi['appid'];?>', // 必填，公众号的唯一标识
            timestamp: <?php echo $jsApi['timestamp'];?>, // 必填，生成签名的时间戳
            nonceStr: '<?php echo $jsApi['noncestr'];?>', // 必填，生成签名的随机串
            signature: '<?php echo $jsApi['signature'];?>',// 必填，签名，见附录1
            jsApiList: ['onMenuShareTimeline', 'onMenuShareAppMessage'] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2

        });

        wx.ready(function () {
// config信息验证后会执行ready方法，所有接口调用都必须在config接口获得结果之后，config是一个客户端的异步操作，所以如果需要在页面加载时就调用相关接口，则须把相关接口放在ready函数中调用来确保正确执行。对于用户触发时才调用的接口，则可以直接调用，不需要放在ready函数中。
            wx.onMenuShareTimeline({
                title: '<?php echo $share['title'];?>', // 分享标题
                link: '<?php echo $toUrl;?>', // 分享链接
                imgUrl: '<?php echo $share['img'];?>', // 分享图标
                success: function () {
                },
                cancel: function () {
                }
            });

            //分享给朋友
            wx.onMenuShareAppMessage({
                title: '<?php echo $share['title'];?>', // 分享标题
                desc: '<?php echo $share['desc'];?>', // 分享描述
                link: '<?php echo $toUrl;?>', // 分享链接
                imgUrl: '<?php echo $share['img'];?>', // 分享图标
                type: '', // 分享类型,music、video或link，不填默认为link
                dataUrl: '', // 如果type是music或video，则要提供数据链接，默认为空
                success: function () {
                },
                cancel: function () {
                }
            });
        });

    });
</script>
</html>