<!DOCTYPE html>
<html>
<head lang="en">
    <title>晒宝宝疯玩照片，赢取荟聚周年壕礼！</title>
    <link rel="stylesheet" type="text/css" href="/activity/css/layout.css">
    <meta charset="UTF-8" name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
</head>
<body>
<div class="banner">
    <img src="http://wan.wanfantian.com/uploads/2016/04/23/29f09e216a7a9dd583d00e6d82ca2300.jpg"/>
</div>
<div class="info3">
    <div class="info-title">
        <img src="<?php echo $userInfo->user_img;?>" />
        <p><?php echo $userInfo->user_name;?><br/>疯狂指数:<span><?php echo $userInfo->power_num;?></span></p>
    </div>
</div>
<div class="click-prize">
    <div class="prize-link">点击福袋  抽取奖品</div>
    <div class="prize">
        <a>
            <h3>荟</h3>
            <div class="fudai">
                <p>恭喜您<br/>玩具反斗城XXX元礼包</p>
            </div>
        </a>
        <a>
            <h3>聚</h3>
            <div class="fudai">
                <p>恭喜您<br/>玩具反斗城XXX元礼包</p>
            </div>
        </a>
        <a>
            <h3>疯</h3>
            <div class="fudai">
                <p>恭喜您<br/>玩具反斗城XXX元礼包</p>
            </div>
        </a>
        <a>
            <h3>送</h3>
            <div class="fudai">
                <p>恭喜您<br/>玩具反斗城XXX元礼包</p>
            </div>
        </a>
        <a>
            <h3>四</h3>
            <div class="fudai">
                <p>恭喜您<br/>玩具反斗城XXX元礼包</p>
            </div>
        </a>
        <a>
            <h3>天</h3>
            <div class="fudai">
                <p>恭喜您<br/>玩具反斗城XXX元礼包</p>
            </div>
        </a>
    </div>
</div>
<div class="info-btn2">
    <a class="btn2 yao-ren" href="javascript:void(0)">邀请好友助力</a>
    <a class="btn2" href="/activity/huiju/myprize?tme=<?php echo time();?>">我的奖品</a>
</div>
<div class="intro">
    <div class="intro-title">活动介绍</div>
    <p>*活动与奖品咨询，快添加<span>玩翻天小七微信号：wanfantian1 </span></p>
    <p>加微信号 还有机会抢红包</p>
    <p>1. 活动时间：2016年4月20日10:00-5月1日24:00，上传宝宝/儿童 真实疯玩照片（参加人必须是照片是宝宝/儿童的第一监护人），发送给好友帮忙助力。助力成功1次可获得10分。达到50分可参与抽奖。抽一次奖，需消耗50积分。</p>
    <p>2. 奖品及领奖信息在“我的奖品”页查看。在法律范围内活动解释权归玩翻天所有。</p>
</div>
<div class="prizes">
    <div class="prizes-title">活动奖品</div>
    <ul>
        <?php foreach($prizeData as $prize):?>
            <li>
                <img src="<?php echo $prize['prize_img']; ?>"/>
                <p><span><?php echo $prize['prize_name']; ?></span></p>
            </li>
        <?php endforeach;?>
    </ul>
</div>
<div class="matte">
    <img src="/activity/images/matte.png" />
</div>
</body>
<script src="/activity/js/zepto.js"></script>
<script src="/activity/js/common.js"></script>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script>
    $(function () {

        //邀请好友助力
        $('.yao-ren').click(function(){
            $(".matte").show();
        })

        $(".matte").click(function(){
            $(".matte").hide();
        });

        wx.config({
            debug: false, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
            appId: '<?php echo $jsApi['appid'];?>', // 必填，公众号的唯一标识
            timestamp: <?php echo $jsApi['timestamp'];?>, // 必填，生成签名的时间戳
            nonceStr: '<?php echo $jsApi['noncestr'];?>', // 必填，生成签名的随机串
            signature: '<?php echo $jsApi['signature'];?>',// 必填，签名，见附录1
            jsApiList: ['onMenuShareTimeline', 'onMenuShareAppMessage'] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2

        });

        wx.ready(function () {
// config信息验证后会执行ready方法，所有接口调用都必须在config接口获得结果之后，config是一个客户端的异步操作，所以如果需要在页面加载时就调用相关接口，则须把相关接口放在ready函数中调用来确保正确执行。对于用户触发时才调用的接口，则可以直接调用，不需要放在ready函数中。
            wx.onMenuShareTimeline({
                title: '<?php echo $share['title'];?>', // 分享标题
                link: '<?php echo $toUrl;?>', // 分享链接
                imgUrl: '<?php echo $share['img'];?>', // 分享图标
                success: function () {
                },
                cancel: function () {
                }
            });

            //分享给朋友
            wx.onMenuShareAppMessage({
                title: '<?php echo $share['title'];?>', // 分享标题
                desc: '<?php echo $share['desc'];?>', // 分享描述
                link: '<?php echo $toUrl;?>', // 分享链接
                imgUrl: '<?php echo $share['img'];?>', // 分享图标
                type: '', // 分享类型,music、video或link，不填默认为link
                dataUrl: '', // 如果type是music或video，则要提供数据链接，默认为空
                success: function () {
                },
                cancel: function () {
                }
            });
        });

    });
</script>
</html>