<!DOCTYPE html>
<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <title>玩翻天</title>
    <link type="text/css" rel="stylesheet" href="/css/web-style.css" />
</head>
<body>
<?php echo $this->content; ?>
</body>
</html>


