<?php
    $share['img']    = $this->layout()->jsconfig['url'].$this->layout()->share_img;
    $share['desc']   = $this->layout()->share_desc;
    $share['title']  = $this->layout()->share_title;
if ($this->layout()->token) {
    $share['link']   = $this->layout()->jsconfig['url'].'/webinvite/index/recieve?token='.$this->layout()->token.'&city='.$this->layout()->city;
} else {
    $share['link']   =$this->layout()->jsconfig['url'].'/webinvite/index/recieve';
}

?>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script type="text/javascript">
    wx.config({
        debug: false, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
        appId: '<?php echo $this->layout()->jsconfig['appid']; ?>', // 必填，公众号的唯一标识
        timestamp: "<?php echo $this->layout()->jsconfig['timestamp']; ?>", // 必填，生成签名的时间戳
        nonceStr: "<?php echo $this->layout()->jsconfig['nonceStr']; ?>", // 必填，生成签名的随机串
        signature: "<?php echo $this->layout()->jsconfig['signature']; ?>",// 必填，签名，见附录1
        jsApiList: ['onMenuShareTimeline', 'onMenuShareAppMessage'] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
    });

    wx.ready(function(){
        wx.error(function(res){
            console.log(res);
        });
        //朋友圈
        wx.onMenuShareTimeline({
            title: '<?php echo $share['title']; ?>', // 分享标题
            link: '<?php echo $share['link']; ?>', // 分享链接
            desc: '<?php echo $share['desc']; ?>', // 分享描述
            imgUrl: '<?php echo $share['img']; ?>', // 分享图标
            success: function () {
                // 用户确认分享后执行的回调函数

            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
            }
        });

        //分享给朋友
        wx.onMenuShareAppMessage({
            title: '<?php echo $share['title']; ?>', // 分享标题
            desc: '<?php echo $share['desc']; ?>', // 分享描述
            link: '<?php echo $share['link']; ?>', // 分享链接
            imgUrl: '<?php echo $share['img']; ?>', // 分享图标
            type: '', // 分享类型,music、video或link，不填默认为link
            dataUrl: '', // 如果type是music或video，则要提供数据链接，默认为空
            success: function () {
                // 用户确认分享后执行的回调函数
            },
            cancel: function () {
                // 用户取消分享后执行的回调函数
            }
        });
    });

</script>
<!--统计-->
<!--<div style="display:none"><script src="http://s11.cnzz.com/stat.php?id=1257017800&web_id=1257017800" language="JavaScript"></script></div>-->
