<ul class="breadcrumb">
    <li>
        <a href="#">Home</a><span class="divider"></span>
    </li>
    <li>
        <span class="divider"><a href="/wftadlogin/activity">活动管理</a></span>
    </li>
    <li class="active">关联卡券</li>
</ul>
<div class="panel panel panel-primary">
    <div class="panel-body">
        <ul class="nav nav-tabs">
            <li class="active"><a href="/wftadlogin/activity/linker?aid=<?php  echo $_GET['aid'];?>">绑定卡券</a></li>
            <form action="#" method="get">
                <table border="0">
                    <tr>
                        <td>
                            <div class="col-lg-6" style="width: 400px;padding-bottom: 10px;">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="搜索卡券或商家名称" name="k" value="">
                      <span class="input-group-btn">
                      <button class="btn btn-default" type="submit">搜索要添加的卡券</button>
                      </span>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <input type="hidden"  name="aid" value="<?php echo $_GET['aid'];?>">
            </form>
            <table class="table table-striped table-hover">
                <tr>
                    <th scope="col">　</th>
                    <th scope="col">卡券ID</th>
                    <th scope="col">卡券名称</th>
                    <th scope="col">
                        <div class="dropdown">
                            <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                                状态
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="/wftadlogin/activity/linker?aid=<?php echo $_GET['aid'];?>&status=0&<?php unset($_GET['status'], $_GET['p']); echo http_build_query($_GET); ?>">所有</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="/wftadlogin/activity/linker?aid=<?php echo $_GET['aid'];?>&status=1&<?php unset($_GET['status'], $_GET['p']); echo http_build_query($_GET); ?>">已结束</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="/wftadlogin/activity/linker?aid=<?php echo $_GET['aid'];?>&status=2&<?php unset($_GET['status'], $_GET['p']); echo http_build_query($_GET); ?>">正在进行</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="/wftadlogin/activity/linker?aid=<?php echo $_GET['aid'];?>&status=3&<?php unset($_GET['status'], $_GET['p']); echo http_build_query($_GET); ?>">未发布</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="/wftadlogin/activity/linker?aid=<?php echo $_GET['aid'];?>&status=4&<?php unset($_GET['status'], $_GET['p']); echo http_build_query($_GET); ?>">即将开始</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="/wftadlogin/activity/linker?aid=<?php echo $_GET['aid'];?>&status=5&<?php unset($_GET['status'], $_GET['p']); echo http_build_query($_GET); ?>">即将上架</a></li>
                            </ul>
                        </div>
                    </th>
                    <th scope="col">价格</th>
                    <th scope="col">所属商家</th>
                    <th scope="col">存量</th>
                    <th scope="col">已售</th>
                    <th scope="col">虚拟票</th>
                </tr>
                <?php foreach ($this->data as $v): ?>
                    <tr>
                        <th scope="col"><input type="checkbox" name="coupon_id" <?php echo (in_array($v->coupon_id, $couponIds)) ? "checked" : '';?> value="<?php echo $v->coupon_id;?>"></th>
                        <td><?php echo $v->coupon_id; ?></td>
                        <td><?php echo $v->coupon_name; ?></td>
                        <td>
                            <?php
                            if ($v->coupon_status == 0) {
                                echo '未发布';
                            } elseif ($v->coupon_uptime > time()) {
                                echo '即将上架';
                            } elseif ($v->coupon_starttime > time()) {
                                echo '即将开始';
                            } elseif ($v->coupon_endtime < time() || $v->coupon_buy == $v->coupon_total) {
                                echo '已结束';
                            }  else {
                                echo '正在进行';
                            }
                            ?>
                        </td>
                        <td><?php echo $v->coupon_price; ?></td>
                        <td><?php echo $v->coupon_marketname; ?></td>
                        <td><?php echo $v->coupon_total; ?></td>
                        <td><?php echo $v->coupon_buy; ?></td>
                        <td><?php echo $v->coupon_vir; ?></td>
                    </tr>
                <?php endforeach; ?>
                <tr class="all-choice">
                    <td></td>
                    <td></td>
                    <td colspan="8"><a id="add-all" data-mid="<?php echo $_GET['aid'];?>" class="btn btn-primary" data-src="/wftadlogin/activity/doLink?aid=<?php echo $_GET['aid'];?>">添加到活动</a></td>
                </tr>
            </table>
        </ul>
        <div>
            <?php echo$this->pagedata; ?>
        </div>
    </div>
</div>
<script src="/js/jquery.cookie.js" type="text/javascript"></script>
<script>
    $("[name='coupon_id']").change(function(){
        var chkCouId = $(this).attr('value');
        if ($(this).prop("checked") == true) {
            $.post($('#add-all').attr("data-src")+'&type=1','coupon_id=' + chkCouId);
        } else {
            $.post($('#add-all').attr("data-src")+'&type=2','coupon_id=' + chkCouId);
        }
        return false;
    })

    $('#add-all').click(function() {
            $.post($(this).attr("data-src")+'&type=3',
                function(result){
                    if(result.status == 1){
                        alert('添加成功');
                        window.location.href=result.href;
                    } else {
                        alert(result.message);
                    }
                }, 'json'
            );
        return false;
    });

    $("input[name='coupon_id']").each(function(){
         if($.cookie('link_coupId'+$('#add-all').attr("data-mid")).indexOf($(this).val()) >= 0) {
             $(this).prop("checked", true);
         }
    })
</script>

