<div class="panel panel panel-primary">
    <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
        <li><a href="/wftadlogin/">Home</a></li>
        <li><a href="/wftadlogin/setting">系统设置</a></li>
        <li class="active">邀约管理</li>
    </ul>
</div>

<!--<hgroup class="box">
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：启动图备用4个</div>
    </aside>
</hgroup>-->

<div class="panel panel panel-primary">
    <div class="panel-heading">邀约设置</div>
    <div class="panel-body" style="height: 70px;"><a style="float: right" href="/wftadlogin/invite/log" >查看设置历史</a>
<div class="setting" style="float: right;height: 41px;margin-right: 50px;margin-bottom: 20px;background: #f5696c;width: 144px;position:relative;cursor: pointer;" onclick="location.href='/wftadlogin/invite/setting'">
    <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">邀约设置</div>


</div>
    </div>
</div>

<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

    $invite_start = null;
    $invite_end = null;
    $device_type = null;
    $sign_start = null;
    $sign_end = null;
    $action_type = null;
    $city = null;
    $token = null;


    if (isset($_GET['invite_start']) && $_GET['invite_start']) {
        $invite_start = $_GET['invite_start'];
    }

    if (isset($_GET['invite_end']) && $_GET['invite_end']) {
        $invite_end = $_GET['invite_end'];
    }


    if (isset($_GET['device_type']) && $_GET['device_type']) {
        $device_type = $_GET['device_type'];
    }

    if (isset($_GET['sign_start']) && $_GET['sign_start']) {
        $sign_start = $_GET['sign_start'];
    }

    if (isset($_GET['sign_end']) && $_GET['sign_end']) {
        $sign_end = $_GET['sign_end'];
    }

    if (isset($_GET['action_type']) && $_GET['action_type']) {
        $action_type = $_GET['action_type'];
    }

    if (isset($_GET['city']) && $_GET['city']) {
        $city = $_GET['city'];
    }

    if (isset($_GET['token']) && $_GET['token']) {
        $token = $_GET['token'];
    }

    ?>

    <table class="table">
        <tr>
            <th width="160">发放时间</th>
            <th>
                <input name="invite_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $invite_start;?>">
                <input name="invite_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $invite_end;?>">
            </th>
            <th width="80">用户角色</th>
            <th>
                <select name="device_type">
<!--                    <option value="-1" --><?php //echo ($device_type == -1) ? 'selected' : '';?><!-->全部</option>-->
                    <option value="0" <?php echo ($device_type == 0) ? 'selected' : '';?>>受邀人</option>
                    <option value="1" <?php echo ($device_type == 1) ? 'selected' : '';?>>邀请人</option>
                </select>
<!--                <input type="text" class="cssInput" name="username" value="--><?php //echo $username;?><!--">-->
            </th>
            <th width="80">事件</th>
            <th>
                <select name="action_type">
                    <option value="-1" <?php echo ($action_type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="0" <?php echo ($action_type == 0) ? 'selected' : '';?>>下载</option>
                    <option value="1" <?php echo ($action_type == 1) ? 'selected' : '';?>>注册</option>
                    <option value="2" <?php echo ($action_type == 2) ? 'selected' : '';?>>首单</option>
                </select>
            </th>
        </tr>


        <tr>
            <th width="160">城市</th>
            <th>
                <select name="city">
                    <option value="WH" <?php echo ($city == 'WH') ? 'selected' : '';?>>武汉</option>
                    <option value="NJ" <?php echo ($city == 'NJ') ? 'selected' : '';?>>南京</option>
                    <option value="CS" <?php echo ($city == 'CS') ? 'selected' : '';?>>长沙</option>
                </select>
            </th>
            <th width="160">邀请码</th>
            <th>
                 <input type="text" class="cssInput" name="token" value="<?php echo $token;?>">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/invite" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">搜索</button>
<!--                <a href="javascript:void(0)" data-src="/wftadlogin/user/putdata?type=1" id="out-data" style="background-color: green" class="ui-button">导出用户信息</a>-->
            </th>
        </tr>
    </table>
</form>



<div class="panel panel panel-primary">
    <div class="panel-heading">信息列表</div>
    <div class="panel-body">

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">奖励时间</th>
                <th scope="col">用户ID</th>
                <th scope="col">邀请码</th>
                <th scope="col">用户名</th>
                <th scope="col">城市</th>
                <th scope="col">用户角色</th>
                <th scope="col">事件</th>
                <th scope="col">现金券</th>
                <th scope="col">现金</th>
                <th scope="col">积分</th>
                <th scope="col">资格券</th>
                <!--  <th scope="col">订单数</th>
                  <th scope="col">评论数</th>
                  <th scope="col">圈子发言数</th>
                  <th scope="col">孩子相关</th>
                  <th scope="col">订单相关</th>-->
<!--                <th scope="col">操作</th>-->
            </tr>


            <?php foreach ($this->data as $v): ?>
                <tr>
                    <td><?php echo date('Y-m-d H:i:s',$v['dateline']); ?></td>
                    <td><?php echo $v['uid']; ?></td>
                    <td><?php echo $v['token']; ?></td>
                    <td><?php echo $v['username']; ?></td>
                    <td><?php if($v['ruleid'] == 1 ){echo 'WH';}elseif($v['ruleid'] == 2){echo 'NJ';}else{echo 'CS';} ?></td>
                    <td><?php echo $device_type == 1 ? '邀请人' : '受邀人'; ?></td>
                    <td><?php if($v['status'] == 1){echo '注册';}elseif($v['status'] == 2){echo '首单';}else{echo '下载';} ?></td>
                    <td><?php if($v['award_type'] == 1){echo  $v['award'];}else{ echo 0;} ?></td>
                    <td><?php if($v['award_type'] == 3){echo  $v['award'];}else{ echo 0;} ?></td>
                    <td><?php if($v['award_type'] == 0){echo  $v['award'];}else{ echo 0;} ?></td>
                    <td><?php if($v['award_type'] == 2){echo  $v['award'];}else{ echo 0;} ?></td>
                    <!--<td><a href="/wftadlogin/order?k=<?php /*echo $v['uid']; */?>&key_type=user_id"><?php /*echo  $v['order_num']; */?></a></td>
                    <td><a href="/wftadlogin/word?uid=<?php /*echo $v['uid']; */?>"><?php /*echo  $v['word_num']; */?></a></td>
                    <td><a href="/wftadlogin/circle/word?uid=<?php /*echo $v['uid']; */?>"><?php /*echo  $v['circle_word_num']; */?></a></td>
                    <td><?php /*echo  $v['child_link']; */?></td>
                    <td><?php /*echo  $v['order_link']; */?></td>-->
<!--                    <td>
                        <a class="btn btn-warning" href="/wftadlogin/user/close?uid=<?php /*echo $v['uid']; */?>">禁用</a>
                        <a class="btn btn-info" href="/wftadlogin/user/open?uid=<?php /*echo $v['uid']; */?>">开启</a>
                        <a class="ui-button" href="/wftadlogin/user/info?uid=<?php /*echo $v['uid']; */?>">查看</a>
                        <a class="btn btn-info" href="/wftadlogin/circle/userpartner?uid=<?php /*echo $v['uid']; */?>">玩伴</a>
                    </td>-->
                </tr>
            <?php endforeach; ?>

        </table>
        <div>
            <?php echo $this->pagedata; ?>
        </div>
    </div>
</div>

<script>
    $(function () {
        //导出订单
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });
    });
</script>






