<hgroup class="box">
    <header>
        <h3>包销库存管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/inventory">库存列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
        <div>
        </div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

        $good_id = null;
        $good_name = null;
        $organizer_id = null;
        $contract_id = null;
        $inventory_num = null;

        if (isset($_GET['good_id']) && $_GET['good_id']) {
            $good_id = $_GET['good_id'];
        }

        if (isset($_GET['good_name']) && $_GET['good_name']) {
            $good_name = $_GET['good_name'];
        }

        if (isset($_GET['organizer_id']) && $_GET['organizer_id']) {
            $organizer_id = $_GET['organizer_id'];
        }

        if (isset($_GET['contract_id']) && $_GET['contract_id']) {
            $contract_id = $_GET['contract_id'];
        }

        if (isset($_GET['inventory_num']) && $_GET['inventory_num']) {
            $inventory_num = $_GET['inventory_num'];
        }

    ?>

    <table class="table">
        <tr>
            <th width="160">商品id</th>
            <th>
                <input name="good_id" type="text" class="cssInput" style="width:190px"  value="<?php echo $good_id;?>">
            </th>
            <th width="160">商品名称</th>
            <th>
                <input name="good_name" type="text" class="cssInput" style="width:190px"  value="<?php echo $good_name;?>">
            </th>
        </tr>

        <tr>
            <th width="160">商家id</th>
            <th>
                <input name="organizer_id" type="text" class="cssInput" style="width:190px"  value="<?php echo $organizer_id;?>">
            </th>
            <th width="160">合同编号</th>
            <th>
                <input name="contract_id" type="text" class="cssInput" style="width:190px"  value="<?php echo $contract_id;?>">
            </th>
        </tr>

        <tr>
            <th width="160">库存id</th>
            <th colspan="3">
                <input type="text" class="cssInput" name="inventory_num"  style="width:190px" value="<?php echo $inventory_num;?>">
            </th>

        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/inventory" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/inventory/outInventory" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>



<div class="panel panel panel-primary">
    <div class="panel-heading">库存列表</div>
    <div class="panel-body">

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">商品id</th>
                <th scope="col">商品名称</th>
                <th scope="col">库存id</th>
                <th scope="col">采购数量</th>
                <th scope="col">采购价</th>
                <th scope="col">预付金</th>
                <th scope="col">商家id</th>
                <th scope="col">合同编号</th>
                <th scope="col">消耗数量</th>
                <th scope="col">库存数量</th>
                <th scope="col">库存地点</th>
                <th scope="col">操作</th>
            </tr>
            <?php foreach ($this->data as $v): ?>
                <tr>
                    <td><?php echo $v['good_id']; ?></td>
                    <td><?php echo $v['good_name']; ?></td>
                    <td><?php echo $v['id']; ?></td>
                    <td><?php echo $v['purchase_number'];?></td>
                    <td><?php echo $v['account_money'];?></td>
                    <td><?php echo $v['pre_money'];?></td>
                    <td><?php echo $v['organizer_id'];?></td>
                    <td><?php echo $v['contract_number']; ?> </td>
                    <td><?php echo  $v['purchase_number'] - $v['inventory_number']; ?></td>
                    <td><?php echo  $v['inventory_number']; ?></td>
                    <td><?php echo  $v['inventory_address'] == 1 ? '玩翻天仓库' : '商家仓库'; ?></td>
                    <td>
                        <a class="ui-button" href="/wftadlogin/inventory/list?id=<?php echo $v['id']; ?>">查看</a>
                    </td>
                </tr>
            <?php endforeach; ?>

        </table>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>

<script>
    $(function () {
        //导出
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');
        });
    });
</script>


