<hgroup class="box">
    <header>
        <h3>包销库存管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/inventory">库存列表</a>
        <i class="icon icon-list"></i>
        <a href="javascript:void(0)">库存记录明细</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
        <div>
        </div>
    </aside>
</hgroup>
<hgroup class="box">
    <aside class="tips">
        <div>
            商品id  <?php echo $inventory->good_id; ?> 　　　商品名称  <?php echo $inventory->good_name;?> 　　　
            库存id  <?php echo $inventory->id; ?> 　　　商家id  <?php echo $inventory->organizer_id;?> 　　　
        </div>

    </aside>
</hgroup>

<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

        $start_time = null;
        $end_time = null;
        $order_sn = null;

        if (isset($_GET['start_time']) && $_GET['start_time']) {
            $start_time = $_GET['start_time'];
        }

        if (isset($_GET['end_time']) && $_GET['end_time']) {
            $end_time = $_GET['end_time'];
        }

        if (isset($_GET['order_sn']) && $_GET['order_sn']) {
            $order_sn = $_GET['order_sn'];
        }

    ?>

    <table class="table">
        <tr>
            <th width="160">订单号</th>
            <th>
                <input name="order_sn" type="text" class="cssInput" style="width:190px"  value="<?php echo $order_sn;?>">
            </th>
        </tr>

        <tr>
            <th width="160">记录时间</th>
            <th>
                <input name="start_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $start_time;?>">
                <input name="end_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $end_time;?>">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/inventory/list?id=<?php echo $inventory->id?>" style="background-color: green" class="ui-button">清空所有选项</a>
                <input name="id" type="hidden" value="<?php echo $inventory->id?>">
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/inventory/outInventoryInfo?id=<?php echo $inventory->id?>" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>



<div class="panel panel panel-primary">
    <div class="panel-heading"> </div>
    <div class="panel-body">

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">记录id</th>
                <th scope="col">记录时间</th>
                <th scope="col">类型</th>
                <th scope="col">订单号</th>
                <th scope="col">交易金额</th>
                <th scope="col">累计金额</th>
                <th scope="col">消耗数量</th>
                <th scope="col">库存数量</th>
                <th scope="col">说明</th>
            </tr>
            <?php foreach ($this->data as $v): ?>
                <tr>
                    <td><?php echo $v['id']; ?></td>
                    <td><?php echo date('Y-m-d H:i:s', $v['dateline']); ?></td>
                    <td><?php echo ($v['types'] == 1) ? '入库' : '出库'; ?></td>
                    <td><?php echo $v['object_id'];?></td>
                    <td><?php echo ($v['types'] == 1) ? '-'. $v['flow_money'] : '+'. $v['flow_money']; ?></td>
                    <td><?php echo $v['inventory_money'];?></td>
                    <td><?php echo ($v['types'] == 1) ? '+'. $v['flow_num'] : '-'. $v['flow_num']; ?></td>
                    <td><?php echo $v['inventory_num']; ?> </td>
                    <td><?php echo $v['description']; ?> </td>
                </tr>
            <?php endforeach; ?>

        </table>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>

<script>
    $(function () {
        //导出
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');
        });
    });
</script>


