<hgroup class="box">
    <header>
        <h3>游玩地</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/place">游玩地列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

        $place_name = null;
        $city_code = 0;

        if (isset($_GET['place_name']) && $_GET['place_name']) {
            $place_name = $_GET['place_name'];
        }

        if (isset($_GET['city_code']) && $_GET['city_code']) {
            $city_code = $_GET['city_code'];
        }

    ?>
    <table class="table">

        <tr>
            <th width="160">游玩地名称</th>
            <th colspan="3">
                <input type="text" class="cssInput" name="place_name" placeholder="游玩地名称" value="<?php echo $place_name;?>">
            </th>
        </tr>

        <tr>
            <th width="160">所属城市</th>
            <th colspan="3">
                <select name="city_code">
                    <option value="0" <?php echo ($city_code == 0) ? 'selected' : '';?>>我的</option>
                    <option value="1" <?php echo ($city_code == 1) ? 'selected' : '';?>>全国所有</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/place" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">
        游玩地列表
        <!--<div style="float:right;margin-right:30px;">
            <form action="" method="get">
                <input type="text" class="cssInput" style="width:200px" placeholder="游玩地名称" name="k" value="">
                <button class="ui-button submit" type="submit">搜索</button>
            </form>
        </div>-->
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="15">id</th>
                <th width="200">游玩地名称</th>
                <th width="50">商品数量</th>
                <th width="100">所属地&nbsp;&nbsp;<?php echo $filtercity; ?></th>
                <th width="50">评论</th>
                <th width="50">浏览</th>
                <th width="50">分享</th>
                <th width="50">整体评分</th>
                <th width="50">产生积分</th>
                <th width="50">发放金额</th>
                <th width="300">操作</th>
            </tr>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td width="15"><?php echo $row['shop_id']; ?></td>
                        <td width="200">
                            <a href="/wftadlogin/place/new?sid=<?php echo $row['shop_id']; ?>"><?php echo $row['shop_name']; ?></a>
                        </td>
                        <td width="50"><a class="good_number" href="/wftadlogin/game?pid=<?php echo $row['shop_id'];?>"><?php echo $row['good_num']; ?></td>
                        <td width="100"><?php echo $city[$row['shop_city']]; ?></td>
                        <td width="50">
                            <a href="/wftadlogin/place/post?sid=<?php echo $row['shop_id']; ?>"><?php echo $row['post_number']; ?></a>
                        </td>
                        <td width="50"><?php echo $row['shop_click']; ?></td>
                        <td width="50"><?php echo $row['share_number']; ?></td>
                        <td width="50"><?php echo floatval($row['star_num']);?></td>
                        <td width="50"><a href="/wftadlogin/place/integral?sid=<?php echo $row['shop_id'];?>"><?php echo $row['produce_integral']; ?></a></td>
                        <td width="50"><?php echo $row['use_money']; ?></td>
                        <td width="300">
                            <?php if(isset($_GET['heiwu']) && $_GET['heiwu']):?>
                                <a href="/wftadlogin/place/change?type=out&sid=<?php echo $row['shop_id']; ?>"
                                   class="ui-button">放出来</a>
                            <?php else:?>
                                <span data-src="/wftadlogin/place/change?type=del&sid=<?php echo $row['shop_id']; ?>"
                                      onclick="if(confirm('确定删除?')==false)return false;" class="check_del ui-button">删除</span>
                                <a href="/wftadlogin/strategy/new?sid=<?php echo $row['shop_id']; ?>"
                                   class="ui-button">添加攻略</a>
                            <?php endif;?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>

</div>
<script>
    $(function () {
        // 删除操作
        $('.check_del').click(function () {
            var that = this;
            $.get($(this).attr('data-src'), function (result) {
                if (result.status == 1) {
                    $(that).closest('tr').remove();
                } else {
                    alert(result.message);
                }
            });
            return false;
        })
    })
</script>