<hgroup class="box">
    <header>
        <h3>游玩地积分明细</h3>
    </header>

</hgroup>
<table class="table">
    <tr>
        <th width="160">游玩地id</th>
        <th colspan="3">
             <?php echo $shopData->shop_id;?>
        </th>
    </tr>

    <tr>
        <th width="160">游玩地名称</th>
        <th colspan="3">
            <?php echo $shopData->shop_name;?>
        </th>
    </tr>

    <tr>
        <th width="160">总积分</th>
        <th colspan="3">
            <?php echo $total_score;?>
        </th>
    </tr>
</table>

<div class="box">
    <div class="box-title">
        积分记录表
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="15">id</th>
                <th width="100">时间</th>
                <th width="50">用户uid</th>
                <th width="80">所属城市</th>
                <th width="150">积分类型</th>
                <th width="50">总积分</th>
                <th width="50">基础积分</th>
                <th width="50">奖励积分</th>
            </tr>

                <?php foreach ($integral as $key => $row): ?>
                    <tr style="text-align: left">
                        <td width="15">
                            <?php echo $row['id']; ?>
                        </td>
                        <td width="100">
                            <?php echo date('Y-m-d H:i:s', $row['create_time']);?>
                        </td>
                        <td width="50">
                            <?php echo $row['uid'];?>
                        </td>
                        <td width="80">
                            <?php echo $city[$row['city']]; ?>
                        </td>
                        <td width="150">
                            <?php echo $row['desc']; ?>
                        </td>
                        <td width="50">
                            <?php echo $row['total_score']; ?>
                        <td width="50">
                            <?php echo $row['base_score']; ?>
                        </td>
                        <td width="50">
                            <?php echo ($row['award_score'] - 1) * $row['base_score']; ?>
                        </td>

                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>

</div>