<hgroup class="box">
    <header>
        <h3>游玩地评论</h3>
    </header>
</hgroup>
<table class="table">
    <tr>
        <th width="160">游玩地id</th>
        <th colspan="3">
            <?php echo $shopData->shop_id;?>
        </th>
    </tr>

    <tr>
        <th width="160">游玩地名称</th>
        <th colspan="3">
            <?php echo $shopData->shop_name;?>
        </th>
    </tr>

    <tr>
        <th width="160">整体评分</th>
        <th colspan="3">
            <?php echo $shopData->star_num;?>
        </th>
    </tr>
</table>

<form class="box box-form" action="#" method="get">
    <header class="box-title">搜索条件</header>
    <?php

    $start_time = null;
    $end_time = null;
    $accept = null;
    $uid = null;
    $username = null;


    if (isset($_GET['start_time']) && $_GET['start_time']) {
        $start_time = $_GET['start_time'];
    }

    if (isset($_GET['end_time']) && $_GET['end_time']) {
        $end_time = $_GET['end_time'];
    }

    if (isset($_GET['accept']) && $_GET['accept']) {
        $accept = $_GET['accept'];
    }

    if (isset($_GET['uid']) && $_GET['uid']) {
        $uid = $_GET['uid'];
    }

    if (isset($_GET['username']) && $_GET['username']) {
        $username = $_GET['username'];
    }

    ?>
    <table class="table">

        <tr>
            <th width="160">评论时间</th>
            <th colspan="3">
                <input name="start_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $start_time;?>">
                <input name="end_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $end_time;?>">
            </th>
        </tr>

        <tr>
            <th width="160">用户id</th>
            <th colspan="3">
                <input type="text" name="uid" value="<?php echo $uid;?>">
            </th>
        </tr>

        <tr>
            <th width="160">用户名称</th>
            <th colspan="3">
                <input type="text" name="username" value="<?php echo $username;?>">
            </th>

        </tr>

        <tr>
            <th width="160">是否小编采纳</th>
            <th colspan="3">
                <select name="accept">
                    <option value="0" <?php echo !$accept ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($accept == 1) ? 'selected' : '';?>>小编采纳</option>
                    <option value="2" <?php echo ($accept == 2) ? 'selected' : '';?>>小编未采纳</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <input type="hidden" name="sid" value="<?php echo $shopData->shop_id;?>">
                <button  class="ui-button">搜索</button>
            </th>
        </tr>
    </table>
</form>




<div class="box">
    <div class="box-title">
        评论列表
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="60">id</th>
                <th width="80">评论时间</th>
                <th width="30">用户uid</th>
                <th width="60">用户名称</th>
                <th width="150">内容</th>
                <th width="50">评分分值</th>
                <th width="50">回复</th>
                <th width="50">点赞</th>
                <th width="50">点评是否有奖</th>
                <th width="50">是否小编采纳</th>
                <th width="50">积分奖励</th>
                <th width="50">现金券奖励</th>
                <th width="50">返利奖励</th>
                <th width="250">操作</th>
            </tr>

            <?php foreach ($data as $row):?>

                <tr style="text-align: left">
                    <td width="60"><?php echo $row['_id'];?></td>
                    <td width="80"><?php echo date('Y-m-d H:i:s',$row['dateline']);?></td>
                    <td width="30"><?php echo $row['uid'];?></td>
                    <td width="60"><?php echo $row['username'];?></td>
                    <td width="150">
                        <a target="_blank" href="/wftadlogin/comment/wordinfo?id=<?php echo $row['_id'];?>">
                            <?php
                                $st = '';
                                foreach($row['msg'] as $v) {
                                    if ((int)$v['t'] === 1 && $v['val']) {
                                        echo $st = substr($v['val'], 0, 60);
                                        break;
                                    }
                                }
                                if (!$st) {
                                    echo '内容无';
                                };
                            ?>
                        </a>
                    </td>
                    <td width="50"><?php echo $row['star_num'];?></td>
                    <td width="50"><?php echo $row['replay_number'];?></td>
                    <td width="50"><?php echo $row['like_number'];?></td>
                    <td width="50">
                        <?php
                        if ($shopData->post_award == 1) {
                            echo '否';
                        } elseif ($shopData->post_award == 2) {
                            echo '是';
                        }
                        ?>
                    </td>
                    <td width="50">
                        <?php
                            if($row['accept'] == 1) {
                                echo '小编采纳';
                            } else {
                                echo '小编未采纳';
                            }
                        ?>
                    </td>
                    <td width="50"><?php echo $row['integral'];?></td>
                    <td width="50"><?php echo $row['cash_money'];?></td>
                    <td width="50"><?php echo $row['rebate_money'];?></td>
                    <td width="250">
                        <a href="/wftadlogin/comment/updateword?id=<?php echo $row['_id']; ?>&uid=<?php echo $row['uid'];?>&type=<?php echo ($row['status'] == 2) ? 'reset' : 'up'; ?>" class="ui-button"><?php echo ($row['status'] == 2) ? '取消置顶' : '置顶'; ?></a>
                        <a href="/wftadlogin/comment/updateword?id=<?php echo $row['_id']; ?>&uid=<?php echo $row['uid'];?>&type=<?php echo ($row['status'] == 0) ? 'reset' : 'hidden'; ?>" class="ui-button"><?php echo ($row['status'] == 0) ? '取消隐藏' : '隐藏'; ?></a>
                        <a href="/wftadlogin/comment/newreply?id=<?php echo $row['_id']; ?>&uid=<?php echo $row['uid'];?>"  class="ui-button">回复</a>
                        <?php if($shopData->post_award == 2):?>
                            <a class="ui-button" href="/wftadlogin/comment/award?id=<?php echo $row['_id'];?>&uid=<?php echo $row['uid'];?>">给予奖励</a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach;?>

            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>

</div>