<hgroup class="box">
    <header>
        <h3>角色分组管理</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/authgroup/new">添加角色</a>
        &nbsp;&nbsp;&nbsp;
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：<span style="color:green">有问题 请及时联系</span> </div>
    </aside>
</hgroup>
<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>

            <tr>
                <th class="size1">id</th>
                <th class="size2">用户组</th>
                <th class="size1">描述</th>
                <th class="size1">授权</th>
                <th class="size1">状态</th>
                <th class="size3">操作</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size1"><?php echo $row['id']; ?></td>
                        <td class="size2">
                            <a href="/wftadlogin/authgroup/new?id=<?php echo $row['id']; ?>">
                                <?php echo $row['title']; ?>
                            </a>
                        </td>
                        <td class="size1"><?php echo $row['description']; ?></td>
                        <td class="size1"><a target="_self" href="/wftadlogin/authmenu/access?id=<?php echo $row['id']; ?>">访问权限</a></td>
                        <td class="size1">
                            <?php if((int)$row['status'] === 0):?>
                                  禁用
                            <?php elseif((int)$row['status'] === 1): ?>
                                  显示
                            <?php endif;?>
                        </td>
                        <td class="size3">
                            <a href="/wftadlogin/authgroup/change?id=<?php echo $row['id']; ?>&type=del" class="ui-button">删除</a>
                            <a href="/wftadlogin/authgroup/new?id=<?php echo $row['id']; ?>" class="ui-button">编辑</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无标签 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pagedata; ?>
        </footer>
    </div>
</div>





<script>
    $(function () {
        //设为焦点图
        $(".check_v").click(function(){$.get($(this).attr('data-src'),
                function(result){
                    if(result.status == 1){
                        window.location.reload();
                    } else {
                        alert(result.message);
                    }
                }, 'json'
            );
            return false;
        });

        /*  //排序
         $(":input, .order").blur(function(){
         $.get($(this).attr('data-src')+'&oid='+$(this).val(),
         function(result){
         if(result.status == 1){
         window.location.reload();
         }
         }, 'json'
         );
         return false;
         });*/




        /*document.getElementById("click").onclick=function(){
            var text=document.getElementById("t");
            var val=text.innerHTML;
            text.innerHTML="<input type='text' id='n' value="+val+" />";
            document.getElementById("n").addEventListener("blur",function(e){
                text.innerHTML=document.getElementById("n").value;
            });
        };*/

        //获取分享记录
        $.each($('.share_number'), function (k, v) {
            var id = $(v).parent().find('td:first').html();
            $(v).load('/wftadlogin/index/sharedata?type=tag&id=' + id);
        })



    })
</script>