<hgroup class="box">
    <header>
        <h3>角色分组管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/authgroup">返回角色分组列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：<span style="color:green">有问题 请及时联系</span> </div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/authgroup/save" method="post" id="news-save">
    <header class="box-title"><?php echo count($data)?'修改分类':'添加分类';?></header>
    <table class="table">
    <tr>
        <th width="160">角色名称</th>
        <th colspan="3"><input type="text" class="cssInput" name="title" value="<?php echo $data ? $data->title : ''; ?>">
        </th>
    </tr>

    <tr>
        <th width="160">角色描述</th>
        <th colspan="3" width="600">
            <textarea class="cssTextArea" name="description"><?php echo $data ? $data->description : '';?></textarea>
        </th>
    </tr>

    <tr>
        <th width="160">角色状态</th>
        <th colspan="3" width="600">
             <input name="status" type="radio" value="1" checked /> 开启 &nbsp;&nbsp;&nbsp;
             <input name="status" type="radio" value="０" /> 关闭
        </th>
    </tr>



    </table>
    <input type="hidden" name="id"  value="<?php echo $data ? $data->id : '';?>">
    <span type="submit" class="btn btn-primary" id="ti-new">提交</span>
</form>

<script>
    $(function () {
        $('#ti-new').click(function () {
            $.post('/wftadlogin/authgroup/save', $('#news-save').serialize(), function (data) {
                if (data.status == 1) {
                    alert('保存成功');
                    window.location.href=document.referrer;
                } else {
                    alert(data.message);
                }
            }, 'json');
            return false;
        });
    })
</script>


