<hgroup class="box">
    <header>
        <h3>菜单管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/authmenu">返回菜单列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：<span style="color:green">有问题 请及时联系</span> </div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/authmenu/save" method="post" id="menu-save">
    <header class="box-title"><?php echo count($data)?'修改分类':'添加分类';?></header>
    <table class="table">
    <tr>
        <th width="160">后台标题</th>
        <th colspan="3"><input type="text" class="cssInput" name="title" value="<?php echo $data ? $data->title : ''; ?>">
        </th>
    </tr>

    <tr>
        <th width="160">布局
        <th colspan="3" width="600">
            <input name="group" type="radio" value="0" <?php if(!$data->group):?> checked <?php endif; ?> /> 左侧 &nbsp;&nbsp;&nbsp;
            <input name="group" type="radio" value="1" <?php if($data->group):?> checked <?php endif; ?> /> 顶部
        </th>
    </tr>

    <tr>
        <th width="160">模块</th>
        <th colspan="3"><input type="text" class="cssInput" name="module" value="<?php echo $data ? $data->module : ''; ?>">
    </tr>

    <tr>
        <th width="160">Url连接</th>
        <th colspan="3"><input type="text" class="cssInput" name="url" value="<?php echo $data ? $data->url : ''; ?>">
    </tr>

        <tr>
            <th width="160">上级菜单</th>
            <th colspan="3">
                <select name="pid">
                    <?php foreach($menus as $menu) : ?>
                        <option value="<?php echo $menu['id']; ?>"><?php echo $menu['title_show']; ?></option>
                    <?php endforeach; ?>
                </select>
            </th>
        </tr>
    <tr>
        <th width="160">是否显示</th>
        <th colspan="3" width="600">
            <input name="hide" type="radio" value="1" checked /> 开启 &nbsp;&nbsp;&nbsp;
            <input name="hide" type="radio" value="０" /> 关闭
        </th>
    </tr>

    <tr>
        <th width="160">是否开发者显示</th>
        <th colspan="3" width="600">
            <input name="is_dev" type="radio" value="1" checked /> 开启 &nbsp;&nbsp;&nbsp;
            <input name="is_dev" type="radio" value="0" /> 关闭
        </th>
    </tr>

    <tr>
        <th width="160">排序</th>
        <th colspan="1"><input type="text" class="cssInput" name="sort" value="<?php echo $data ? $data->sort : ''; ?>">
    </tr>

    </table>
    <input type="hidden" name="id"  value="<?php echo $data ? $data->id : '';?>">
    <span type="submit" class="btn btn-primary" id="ti-new">提交</span>
</form>
<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script>
    $(function () {
        $('#ti-new').click(function () {
            $.post('/wftadlogin/authmenu/save', $('#menu-save').serialize(), function (data) {
                if (data.status == 1) {
                    alert('保存成功');
                    window.location.href=document.referrer;
                } else {
                    alert(data.message);
                }
            }, 'json');
            return false;
        })
    })
</script>



