<hgroup class="box">
    <header>
        <h3>菜单资源管理</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/authmenu/new">添加菜单资源</a>
        &nbsp;&nbsp;&nbsp;
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>

        <div>温馨提示：<span style="color:green">有问题 请及时联系</span></div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

    $word = null;

    if (isset($_GET['word']) && $_GET['word']) {
        $word = $_GET['word'];
    }


    ?>
    <table class="table">
        <tr>
            <th width="160">栏目名/URL</th>
            <th>
                <input type="text" class="cssInput" name="word" value="<?php echo $word;?>">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <button  class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>
<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>

            <tr>
                <th class="size1">id</th>
                <th class="size2">栏目名</th>
                <th class="size1">排序</th>
                <th class="size2">url</th>
                <th class="size1">组名</th>
                <th class="size1">状态</th>
                <th class="size1">是否隐藏</th>
                <th class="size1">是否属于开发</th>
                <th class="size3">操作</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size1"><?php echo $row['id']; ?></td>
                        <td class="size2">
                            <a href="/wftadlogin/authmenu/new?id=<?php echo $row['id']; ?>">
                                <?php echo $row['title']; ?>
                            </a>
                        </td>
                        <td class="size1"><?php echo $row['sort']; ?></td>
                        <td class="size1"><?php echo $row['module'].'/'.$row['url']; ?></td>
                        <td class="size1"><?php echo $row['group']; ?></td>
                        <td class="size1">
                            <?php if ((int)$row['hide'] === 1): ?>
                                隐藏
                            <?php else: ?>
                                显示
                            <?php endif; ?>
                        </td>
                        <td class="size1"><?php echo $row['hide']; ?></td>
                        <td class="size1"><?php echo $row['is_dev']; ?></td>
                        <td class="size3">
                            <?php if ($row['hide']): ?>
                                <a href="/wftadlogin/authmenu/change?id=<?php echo $row['id']; ?>&type=show"
                                   class="ui-button">开启</a>
                            <?php else: ?>
                                <a href="/wftadlogin/authmenu/change?id=<?php echo $row['id']; ?>&type=hide"
                                   class="ui-button">隐藏</a>
                            <?php endif; ?>
                            <a onclick="if(confirm('确定删除，不是隐藏?')==false) return false;" href="/wftadlogin/authmenu/change?id=<?php echo $row['id']; ?>&type=del"
                               class="ui-button">删除</a>
                            <a href="/wftadlogin/authmenu/new?id=<?php echo $row['id']; ?>" class="ui-button">编辑</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无标签 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    $(function () {
    })
</script>