<style type="text/css">

    .from {
        width: 1000px;
    }

    .table_details {
        width: 300px;
        float: left;
        margin: 20px 0px 0px 20px;
    }

    .other_details {
        width: 1000px;
        float: left;
        margin: 20px 0px 0px 20px;
    }

    .td_width {
        width: 120px
    }

</style>

<hgroup class="box">
    <header>
        <h3>财务管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/pact/list">返回</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>


<div class="from">
    <form class="box box-form" action="#" method="post">
        <!--合同 start-->
        <div class="other_details">
            <p>合同明细</p>
            <table class="table table-striped table-hover">
                <tr>
                    <th scope="col">合同编号</th>
                    <th scope="col">合同类型</th>
                    <th scope="col">合同生效时间</th>
                    <th scope="col">合同状态</th>
                </tr>

                <tr>
                    <td><?php echo $contractData['contract_no']?></td>
                    <td>
                        <?php
                        if ($contractData['contracts_type']==1) {
                            echo "包销";
                        } else {
                            echo $contractData['contract_type']==2 ? "自营" : "代销" ;
                        }
                        ?>
                    </td>
                    <td><?php echo date("Y-m-d", $contractData['start_time']). '--'. date("Y-m-d", $contractData['end_time'])?></td>
                    <td>
                        <?php
                        if($contractData['check_status']==0){
                            echo '未审批';
                        } elseif ($contractData['check_status']==1) {
                            echo '已提交审批';
                        } elseif ($contractData['check_status']==2) {
                            echo '已审批';
                        }
                        ?>
                    </td>

                </tr>
            </table>
        </div>
        <!--合同 end-->

        <!--账户 start-->
        <div class="other_details">
            <p>账户明细</p>
            <table class="table table-striped table-hover">
                <tr>
                    <th scope="col">合作商家</th>
                    <th scope="col">开户人</th>
                    <th scope="col">开户行</th>
                    <th scope="col">开户支行</th>
                    <th scope="col">银行卡号</th>
                </tr>

                <tr>
                    <td><?php echo $contractData['organizer_name']?></td>
                    <td><?php echo $accountData['bank_user']?></td>
                    <td><?php echo $accountData['bank_name']?></td>
                    <td><?php echo $accountData['bank_address']?></td>
                    <td><?php echo $accountData['bank_card']?></td>
                </tr>
            </table>
        </div>
        <!--账户 end-->

        <!--商品明细 start-->
        <div class="other_details">
            <p>商品明细</p>

            <table class="table table-striped table-hover">
                    <tr>
                        <th scope="col">商品ID</th>
                        <th scope="col">商品名称</th>
                        <th scope="col">套系名称</th>
                        <th scope="col">原价</th>
                        <th scope="col">售价</th>
                        <th scope="col">结算价</th>
                        <th scope="col">预付金</th>
                        <th scope="col">审核状态</th>
                    </tr>
                    <?php foreach ($goods as $v): ?>
                        <tr>
                            <td><?php echo $v['good_id']; ?></td>
                            <td><?php echo $v['good_name']; ?></td>
                            <td><?php echo $v['price_name']; ?></td>
                            <td><?php echo $v['money']; ?></td>
                            <td><?php echo $v['price']; ?></td>
                            <td><?php echo $v['account_money']; ?></td>
                            <td><?php echo floatval($v['pre_money']); ?></td>
                            <td>
                                <?php
                                    if ($v['status'] == 1) {
                                        echo '未审批';
                                    } elseif ($v['status'] == 2) {
                                        echo '<span class="ui-button">待审批</span>';
                                    } elseif ($v['status'] == 3) {
                                        echo '已审批';
                                    }
                                ?>
                            </td>
                        </tr>
                        <?php if(count($v['link_price'])):?>
                            <?php foreach($v['link_price'] as $link):?>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td><?php echo $link['price_name']; ?></td>
                                    <td><?php echo $link['money']; ?></td>
                                    <td><?php echo $link['price']; ?></td>
                                    <td></td>
                                    <td></td>
                                    <td>
                                        <?php
                                            if ($link['status'] == 1) {
                                                echo '未审批';
                                            } elseif ($link['status'] == 2) {
                                                echo '<span class="ui-button">待审批</span>';
                                            } elseif ($link['status'] == 3) {
                                                echo '已审批';
                                            }
                                        ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif;?>
                    <?php endforeach; ?>
            </table>
        </div>
        <!--商品明细 end-->

        <!--预付金体现记录 start-->
        <div class="other_details">
            <p>预付金提现记录</p>

            <table class="table table-striped table-hover">
                <tr>
                    <th scope="col">审批时间</th>
                    <th scope="col">审批操作人员</th>
                    <th scope="col">预付金</th>
                    <th scope="col">确认到账时间</th>
                    <th scope="col">确认到账操作人员</th>
                    <th scope="col">状态</th>
                </tr>
                <?php foreach ($auditData as $v): ?>
                    <tr>
                        <td><?php echo date("Y-m-d H:i:s", $v['approve_time']); ?></td>
                        <td><?php echo $v['editor']; ?></td>
                        <td><?php echo (float)$v['pre_money']; ?></td>
                        <td><?php echo $v['confirm_time'] ? date("Y-m-d", $v['confirm_time']) : ''; ?></td>
                        <td><?php echo $v['comfirmer']; ?></td>
                        <td><?php echo $v['type']==1?"已审批":"已到账"; ?></td>
                        <td></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <!--预付金体现记录 end-->

        <!--合同操作记录 start-->
        <div class="other_details">
            <p>合同操作记录</p>

            <table class="table table-striped table-hover">
                <tr>
                    <th scope="col">操作时间</th>
                    <th scope="col">操作记录</th>
                    <th scope="col">操作人员</th>
                </tr>
                <?php foreach ($contractLog as $v): ?>
                    <tr>
                        <td><?php echo date("Y-m-d H:i:s", $v['dateline']); ?></td>
                        <td><?php echo $v['action_note']; ?></td>
                        <td><?php echo $v['action_user_name']; ?></td>
                        <td></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <!--合同操作记录 end-->
        <?php if($contractData->check_status == 1):?>
            <div class="other_details checkbox">
                 <a href="/wftadlogin/pact/approve?type=1&id=<?php echo $contractData->id; ?>" class="btn btn-primary" >
                    <?php echo $preMoney['wait'] > 0 ? '批准预付金' : '审批通过'?>
                 </a>
　　　　　
                 <a href="/wftadlogin/pact/approve?type=2&id=<?php echo $contractData->id; ?>" class="btn btn-primary"  >
                    <?php echo $preMoney['wait'] > 0 ? '不批准预付金' : '审批不通过'?>
                 </a>
            </div>
        <?php endif;?>
</div>

<div style="clear: both;height: 240px; width: 700px">　
    　
    </div>
