<hgroup class="box">
    <header>
        <h3>分销</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/distribution/seller">销售员管理</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/distribution/withdraw">提现管理</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/distribution/orderList">订单列表</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/distribution/statistics">业绩统计</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

        $username = null;
        $uid = null;
        $phone = NULL;
        $order_id =  NULL;
        $seller_id = null;
        $coupon_id = NULL;
        $coupon_name = NULL;
        $sell_type = 0;
        if (isset($_GET['username']) && $_GET['username']) {
            $username = $_GET['username'];
        }

        if (isset($_GET['uid']) && $_GET['uid']) {
            $uid = $_GET['uid'];
        }

        if (isset($_GET['phone']) && $_GET['phone']) {
            $phone = $_GET['phone'];
        }

        if (isset($_GET['order_id']) && $_GET['order_id']) {
            $order_id = $_GET['order_id'];
        }

        if (isset($_GET['seller_id']) && $_GET['seller_id']) {
            $seller_id = $_GET['seller_id'];
        }

        if (isset($_GET['coupon_id']) && $_GET['coupon_id']) {
            $coupon_id = $_GET['coupon_id'];
        }

        if (isset($_GET['coupon_name']) && $_GET['coupon_name']) {
            $coupon_name = $_GET['coupon_name'];
        }

        if (isset($_GET['sell_type']) && $_GET['sell_type']) {
            $sell_type = $_GET['sell_type'];
        }

    ?>

    <table class="table">
        <tr>
            <th width="160">用户名</th>
            <th>
                <input type="text" class="cssInput" style="width:190px" name="username" value="<?php echo $username;?>">
            </th>
            <th width="80">用户uid</th>
            <th>
                <input type="text" class="cssInput" style="width: 80px" name="uid" value="<?php echo $uid;?>">
                用户手机号
                <input type="text" class="cssInput" name="phone" value="<?php echo $phone;?>">
            </th>
        </tr>

        <tr>
            <th width="160">订单id</th>
            <th>
                <input name="order_id" type="text" class="cssInput" style="width:190px"  value="<?php echo $order_id;?>">
            </th>
            <th width="80">销售员id</th>
            <th>
                <input type="text" class="cssInput" name="seller_id" value="<?php echo $seller_id;?>">
            </th>
        </tr>

        <tr>
            <th width="160">商品id</th>
            <th>
                <input name="coupon_id" type="text" class="cssInput" style="width:190px"  value="<?php echo $coupon_id;?>">
            </th>
            <th width="80">商品名称</th>
            <th>
                <input type="text" class="cssInput" name="coupon_name" value="<?php echo $coupon_name;?>">
            </th>
        </tr>
        <tr>
            <th width="160">收益状态</th>
            <th colspan="3">
                <select name="sell_type">
                    <option value="0" <?php echo ($sell_type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($sell_type == 1) ? 'selected' : '';?>>未到账</option>
                    <option value="2" <?php echo ($sell_type == 2) ? 'selected' : '';?>>已到账</option>
                    <option value="3" <?php echo ($sell_type == 3) ? 'selected' : '';?>>已扣除</option>
                    <option value="4" <?php echo ($sell_type == 4) ? 'selected' : '';?>>部分到账</option>
                    <option value="5" <?php echo ($sell_type == 5) ? 'selected' : '';?>>部分扣除</option>
                </select>
            </th>

        </tr>
        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/distribution/orderList" style="background-color: green" class="ui-button">清空</a>
                <button  class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>

<div class="panel panel panel-primary">
    <div class="panel-heading">订单列表</div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">订单号</th>
                <th scope="col">交易时间</th>
                <th scope="col">城市</th>
                <th scope="col">用户id</th>
                <th scope="col">用户名</th>
                <th scope="col">用户手机号</th>
                <th scope="col">商品名称</th>
                <th scope="col">商品id</th>
                <th scope="col">购买金额</th>
                <th scope="col">代金券金额</th>
                <th scope="col">退款金额</th>
                <th scope="col">销售员</th>
                <th scope="col">销售员收益</th>
                <th scope="col">收益状态</th>
            </tr>
            <?php foreach ($data as $v): ?>
                <tr>
                    <td><?php echo $v['order_sn']; ?></td>
                    <td><?php echo date('Y-m-d H:i:s', $v['dateline']); ?></td>
                    <td><?php echo $v['city']; ?></td>
                    <td><?php echo $v['user_id']; ?></td>
                    <td><?php echo $v['username']; ?></td>
                    <td><?php echo $v['phone']; ?></td>
                    <td><?php echo $v['coupon_name']; ?></td>
                    <td><?php echo $v['coupon_id']; ?></td>
                    <td><?php echo bcadd($v['account_money'], $v['real_pay'], 2); ?></td>
                    <td><?php echo $v['voucher']; ?></td>
                    <td><?php echo $v['back_money']; ?></td>
                    <td><?php echo $v['seller']; ?></td>
                    <td><?php echo $v['seller_rebate']; ?></td>
                    <td>
                        <?php
                                if ($v['code_number'] ==  $v['code_use']) {
                                    echo '已到账';
                                } elseif ($v['code_number'] ==  $v['code_back']) {
                                    echo '已扣除';
                                } elseif ($v['code_back'] > 0) {
                                    echo '部分扣除';
                                } elseif ($v['code_back'] == 0  AND $v['code_use'] > 0) {
                                    echo '部分到账';
                                } else {
                                    echo '未到账';
                                }
                            ;
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>

        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>



