<script>
    var exdate = new Date();
    exdate.setDate(exdate.getDate()-10);
    document.cookie = "uid=0;path=/;expires="+exdate.toGMTString();
    document.cookie = "token=6;path=/;expires="+exdate.toGMTString();
    document.cookie = "open_id=6;path=/;expires="+exdate.toGMTString();
    document.cookie = "phone=6;path=/;expires="+exdate.toGMTString();

    document.cookie = "uid=6;path=/;domain=test.wan.deyi.com;expires="+exdate.toGMTString();
    document.cookie = "token=6;path=/;domain=test.wan.deyi.com;expires="+exdate.toGMTString();
    document.cookie = "open_id=6;path=/;domain=test.wan.deyi.com;expires="+exdate.toGMTString();
    document.cookie = "phone=6;path=/;domain=test.wan.deyi.com;expires="+exdate.toGMTString();


    document.cookie = "uid=6;path=/web;domain=test.wan.deyi.com;expires="+exdate.toGMTString();
    document.cookie = "token=6;path=/web;domain=test.wan.deyi.com;expires="+exdate.toGMTString();
    document.cookie = "open_id=6;path=/web;domain=test.wan.deyi.com;expires="+exdate.toGMTString();
    document.cookie = "phone=6;path=/web;domain=test.wan.deyi.com;expires="+exdate.toGMTString();

    document.cookie = "uid=6;path=/web;expires="+exdate.toGMTString();
    document.cookie = "token=6;path=/web;expires="+exdate.toGMTString();
    document.cookie = "open_id=6;path=/web;expires="+exdate.toGMTString();
    document.cookie = "phone=6;path=/web;expires="+exdate.toGMTString();
</script>