<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>二维码</title>
    <script>(function(){var w=window.screen.width,s=w/640,u=navigator.userAgent,m='<meta name="viewport" content="width=750,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
    <style>
        body{
            max-width: 750px;
            margin: 0 auto;
        }
        img{
            display: block;
            overflow: hidden;
            width: 500px;
            height: 500px;
            margin: 250px 125px 0 125px;
        }
        .button{
            display: block;
            overflow: hidden;
            font-size: 35px;
            width: 350px;
            height: 80px;
            text-decoration: none;
            font-family: "microsoft yahei";
            line-height: 80px;
            text-align: center;
            background-color: #ff7864;
            color: #fff;
            border-radius: 10px 10px 10px 10px;
            -webkit-border-radius: 10px 10px 10px 10px;
            background-clip: padding-box;
            margin: 120px auto;
        }

        .tips{
            display: block;
            overflow: hidden;
            font-size: 35px;
            width: 350px;
            height: 80px;
            text-decoration: none;
            font-family: "microsoft yahei";
            line-height: 80px;
            text-align: center;
            border-radius: 10px 10px 10px 10px;
            -webkit-border-radius: 10px 10px 10px 10px;
            background-clip: padding-box;
            margin: 120px auto;
        }

    </style>
</head>
<body>

<img src="/images/ground/qrcode.png"/>
<div class="tips" >请长按二维码关注</div>
<!--<a class="button" href="/web/generalize/confirm">我已关注</a>-->
</body>
</html>