<hgroup class="box">
    <header>
        <h3>推广经费  管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/fundscheck">返回</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/fundscheck/cash">现金券审核列表</a>
        <i class="icon icon-list"></i>
        <a href="javascript:void(0)">现金券使用列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<form class="box box-form" action="/wftadlogin/cashcoupon/used" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $order_sn = null;
    $goods = null;
    $base = null;
    $pay_stime = null;
    $pay_etime = null;
    $order_stime = null;
    $order_etime = null;
    $user = null;
    $cash = null;
    $type = null;
    $use_status = null;

    if (isset($_GET['create_stime']) && $_GET['create_stime']) {
        $create_stime = $_GET['create_stime'];
    }
    if (isset($_GET['create_etime']) && $_GET['create_etime']) {
        $create_etime = $_GET['create_etime'];
    }
    if (isset($_GET['pay_stime']) && $_GET['pay_stime']) {
        $pay_stime = $_GET['pay_stime'];
    }
    if (isset($_GET['pay_etime']) && $_GET['pay_etime']) {
        $pay_etime = $_GET['pay_etime'];
    }
    if (isset($_GET['order_stime']) && $_GET['order_stime']) {
        $order_stime = $_GET['order_stime'];
    }
    if (isset($_GET['order_etime']) && $_GET['order_etime']) {
        $order_etime = $_GET['order_etime'];
    }
    if (isset($_GET['user']) && $_GET['user']) {
        $user = $_GET['user'];
    }
    if (isset($_GET['type']) && $_GET['type']) {
        $type = $_GET['type'];
    }
    if (isset($_GET['order_sn']) && $_GET['order_sn']) {
        $order_sn = $_GET['order_sn'];
    }
    if (isset($_GET['goods']) && $_GET['goods']) {
        $goods = $_GET['goods'];
    }
    if (isset($_GET['base']) && $_GET['base']) {
        $base = $_GET['base'];
    }
    if (isset($_GET['cash']) && $_GET['cash']) {
        $cash = $_GET['cash'];
    }
    if (isset($_GET['use_status']) && $_GET['use_status']) {
        $use_status = $_GET['use_status'];
    }
    ?>
    <table class="table">
        <tr>
            <th width="160">商品id/名称</th>
            <th>
                <input type="text" class="cssInput" name="goods" value="<?php echo $goods;?>">
            </th>
            <th width="160">活动id/名称</th>
            <th>
                <input type="text" class="cssInput" name="base" value="<?php echo $base;?>">
            </th>
        </tr>
        <tr>
            <th width="160">订单号</th>
            <th>
                <input type="text" class="cssInput" name="order_sn" value="<?php echo $order_sn;?>">
            </th>
            <th width="160">使用时间</th>
            <th>
                <input name="pay_stime" type="date" class="cssInput" style="width:190px"  value="<?php echo $pay_stime;?>">
                <input name="pay_etime" type="date" class="cssInput" style="width:190px"  value="<?php echo $pay_etime;?>">
            </th>
        </tr>
        <tr>
            <th width="160">现金券类别</th>
            <th>
                <select name="type" >
                    <option value="0">全部</option>
                    <option <?php if($type==1):?>selected="selected" <?php endif; ?> value="1">商品券</option>
                    <option <?php if($type==2):?>selected="selected" <?php endif; ?> value="2">活动券</option>
                </select>
            </th>
            <th width="160">订单完成时间</th>
            <th>
                <input name="order_stime" type="date" class="cssInput" style="width:190px"  value="<?php echo $order_stime;?>">
                <input name="order_etime" type="date" class="cssInput" style="width:190px"  value="<?php echo $order_etime;?>">
            </th>
        </tr>
        <tr>
            <th width="160">用户ID/名称/手机号</th>
            <th>
                <input type="text" class="cssInput" name="user" value="<?php echo $user;?>">
            </th>
            <th width="160">现金券ID/名称</th>
            <th>
                <input type="text" class="cssInput" name="cash" value="<?php echo $cash;?>">
            </th>
        </tr>

        <tr>
            <th width="160">
                <input type="hidden" name="cid" value="<?php echo $_GET['cid']; ?>" />
                <input type="hidden" class="cssInput" name="out" id="out" value="0">
            </th>
            <th colspan="3">
                <a href="/wftadlogin/cashcoupon/used" style="background-color: green" class="ui-button">清空所有选项</a>
                <button id="tijiao" class="ui-button">提交</button>
                <button id="out-data" style="background-color: green" class="ui-button">导出</button>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">
        现金券使用列表
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">领券ID</th>
                <th class="size1">现金券ID</th>
                <th class="size1">领券时间</th>
                <th class="size1">领券原因</th>
                <th class="size1">领券用户</th>
                <th class="size1">使用时间</th>
                <th class="size1">订单号</th>
                <th class="size1">商品/活动名称</th>
                <th class="size1">订单金额</th>
                <th class="size1">支付金额</th>
                <th class="size1">现金券金额</th>
                <th class="size1">已使用金额</th>
                <th class="size1">退款金额</th>
                <th class="size1">推广费用</th>
            </tr>
            <?php if (count($ccu)): ?>
                <?php foreach ($ccu as $key => $data): ?>

                    <tr style="text-align: left">
                        <td class="size1"><?php echo $data['id']; ?></td>
                        <td class="size1"><a target="_blank" href="/wftadlogin/cashcoupon/detail?cid=<?php echo $data['cid']; ?>"><?php echo $data['cid']; ?></a></td>
                        <td class="size1"><?php echo $data['create_time']?date('Y-m-d H:i',$data['create_time']):''; ?></td>
                        <td class="size1"><?php echo $getinfo[$data['id']]; ?></td>
                        <td class="size1"><a target="_blank" href="/wftadlogin/user/info?uid=<?php echo $data['uid'];?>" ><?php echo array_key_exists($data['uid'],$players)?$players[$data['uid']]:''; ?></a></td>
                        <td class="size1"><?php echo $data['pay_time']?date('Y-m-d H:i',$data['pay_time']):'--:--:--'; ?></td>
                        <td class="size1">
                            <?php if($data['order_type']==2): ?>
                                <?php $url = '/wftadlogin/order/info'; ?>
                            <?php elseif($data['order_type']==3): ?>
                                <?php $url = '/wftadlogin/excercise/orderinfo'; ?>
                            <?php endif; ?>
                            <?php echo $data['order_id']?"<a target='_blank' href='{$url}?order_sn={$data['order_id']}'>{$data['order_id']}</a>":'--'; ?>
                        </td>
                        <td class="size1">
                            <?php if($data['order_type']==2): ?>
                                <?php echo $data['coupon_name']?"<a href='/wftadlogin/good/new?gid={$data['coupon_id']}'>{$data['coupon_name']}</a>":'--'; ?>
                            <?php elseif($data['order_type']==3): ?>
                                <?php echo $data['coupon_name']?"<a href='/wftadlogin/excercise/edit?id={$data['bid']}'>{$data['coupon_name']}</a>":'--'; ?>
                            <?php endif; ?>
                        </td>
                        <td class="size1"><?php echo $data['order_money']?:0; ?></td>
                        <td class="size1"><?php echo $data['in_money']?:0; ?></td>
                        <td class="size1"><?php echo $data['cash_money']?:0; ?></td>
                        <td class="size1"><?php echo $data['used_money']?:0; ?></td>
                        <td class="size1"><?php echo $data['back_money']?:0; ?></td>
                        <td class="size1"><?php echo $data['free_money']?:0;; ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无标签 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    $(function () {
        $('#out-data').click(function () {
            $('#out').val(1);
        })

        $('#tijiao').click(function () {
            $('#out').val(0);
        })
    })
</script>