<hgroup class="box">
    <header>
        <h3>首页管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/first/list?type=7">悬浮框列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：① <span style="color:green">有问题 请及时联系</span> ② 请及时 记得删除无效的</div>
    </aside>
    <?php if($count < 1):?>
    <aside class="tips">
        <a href="/wftadlogin/first/add?type=7" class="ui-button">添加关联数据</a>
        <a id="add_url" class="ui-button">添加url地址</a>
    </aside>
    <?php endif;?>
</hgroup>
<div id="add_form" style="display: none">
    <form class="box box-form" action="/wftadlogin/first/urlsave?link_type=7" method="post" id="menu-save">
        <table class="table">
            <tr>
                <th width="160">浮动说明</th>
                <th colspan="3">
                    <input type="text" style="width: 800px;" class="cssInput" name="title" value="">
                </th>

            </tr>
            <tr>
                <th width="160">URL地址</th>
                <th colspan="3">
                    <input type="text" style="width: 800px;" class="cssInput" name="url" value="">
                </th>

            </tr>
            <tr>
                <th>封面图 <mark>128px*128px</mark></th>
                <th colspan="3">
                    <fieldset style="margin: 0px;">
                        <div style="float: left;height: 41px;background: #f5696c;width: 144px;position:relative;">
                            <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">上传</div>
                            <input type="file" id="fileupload1" name="file" style="width: 144px;height: 41px;cursor: pointer;font-size: 30px;outline: medium none;position: absolute;filter:alpha(opacity=0);-moz-opacity:0;opacity:0;left:0px;top: 0px;" multiple/>
                        </div>

                        <input id="cover1" type="hidden" name="cover[]" value="" />
                        <input id="cover2" type="hidden" name="cover[]" value="" />
                        <input id="cover3" type="hidden" name="cover[]" value="" />
                        <input id="cover4" type="hidden" name="cover[]" value="" />
                        <input id="cover5" type="hidden" name="cover[]" value="" />
                    </fieldset>
                    <div>
                        <img width="240px" height="120px" class="fileupload1" src="">
                        <img width="240px" height="120px" class="fileupload2" src="">
                        <img width="240px" height="120px" class="fileupload3" src="">
                        <img width="240px" height="120px" class="fileupload4" src="">
                        <img width="240px" height="120px" class="fileupload5" src="">
                    </div>
                </th>

            </tr>

            <tr>
                <th width="160"></th>
                <th colspan="3">
                    <button  class="ui-button">提交</button>
                </th>
            </tr>
        </table>
    </form>
</div>
<div class="box">
    <div class="box-title">
        悬浮框列表
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="15">id</th>
                <th width="100">悬浮说明</th>
                <th width="100">编辑人</th>
                <th width="30">评论</th>
                <th width="30">点击</th>
                <th width="30">分享</th>
                <th width="30">状态</th>
                <th width="60">类别</th>
                <th width="200">操作</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td  width="15"><?php echo $row['id']; ?></td>
                        <td  width="100">
                            <?php
                            if ($row['type'] == 1) {
                                $url = '/wftadlogin/activity/new?aid='.$row['link_id'];
                            } elseif($row['type'] == 4) {
                                $url = '/wftadlogin/place/new?sid='.$row['link_id'];
                            } elseif($row['type'] == 5) {
                                $url = '/wftadlogin/good/new?gid='.$row['link_id'];
                            } elseif($row['type'] == 6) {
                                $url = array_key_exists('url',$row)?$row['url']:'';
                            } elseif($row['type'] == 7) {
                                $url = '/wftadlogin/circle/wordinfo?id='.$row['link_id'];
                            } elseif($row['type'] == 8) {
                                $url = '/wftadlogin/circle/new?id='.$row['link_id'];
                            }
                            ?>

                            <a href="<?php echo $url;?>"><?php echo $row['block_title']; ?></a>
                        </td>
                        <td  width="100"><?php echo $row['editor']; ?></td>
                        <td width="30"><?php echo $row['post_num']; ?></td>
                        <td width="30"><?php echo $row['click_num']; ?></td>
                        <td width="30"><?php echo $row['share_num']; ?></td>
                        <td width="30"><?php echo $row['status'] ? '有效' : '无效';?></td>
                        <td width="60"><?php echo $label[$row['type'] -1]; ?></td>
                        <td  width="200">
                            <a href="/wftadlogin/first/delete?id=<?php echo $row['id']; ?>" class="ui-button">删除</a>
                           <!-- <a href="/wftadlogin/first/view?id=<?php /*echo $row['id']; */?>" class="ui-button">修改</a>-->
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无数据 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>

<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script src="/js/file_upload/jquery.iframe-transport.js"></script>
<script src="/js/file_upload/jquery.fileupload.js"></script>
<script>
    var i = 0;
    $('#fileupload1').fileupload({
        url: '/wftadlogin/index/upload?type=float_img',
        dataType: 'json',
        done: function (e, data) {
            i++;
            if (data.result.status == 1) {
                //$("input[name='cover']").attr('value', data.result.url);
                $(".fileupload"+i).attr('src' , data.result.url);
                $("#cover"+i).attr('value' , data.result.url);
            } else {
                alert(data.result.message);
            }
        }
    });

    $('#add_url').click(function(){
        $('#add_form').show();
    });

</script>
