<hgroup class="box">
    <header>
        <h3>首页管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/first/list?type=1">精选列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：① <span style="color:green">有问题 请及时联系</span> ② 请及时 记得删除无效的</div>
    </aside>
    <aside class="tips">
        <a href="/wftadlogin/first/add?type=1" class="ui-button">添加关联数据</a>
        <a id="add_url" class="ui-button">添加url地址</a>
    </aside>
</hgroup>
<div id="add_form" style="display: none">
    <form class="box box-form" action="/wftadlogin/first/urlsave?link_type=1" method="post" id="menu-save">
        <table class="table">
            <tr>
                <th width="160">标题文字</th>
                <th colspan="4">
                    <input type="text" style="width: 800px;" class="cssInput" name="title" value="">
                </th>
            </tr>

            <tr>
                <th width="160">说明文字</th>
                <th colspan="4">
                    <textarea class="cssTextArea" name="tip"></textarea>
                </th>

            </tr>

            <tr>
                <th width="160">URL地址</th>
                <th colspan="3">
                    <input type="text" style="width: 800px;" class="cssInput" name="url" value="">
                </th>

            </tr>
            <tr>
                <th>封面图</th>
                <th colspan="3">
                    <fieldset>
                        <div style="float: left;height: 41px;background: #f5696c;width: 144px;position:relative;">
                            <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">上传</div>
                            <input type="file" id="fileupload1" name="file" style="width: 144px;height: 41px;cursor: pointer;font-size: 30px;outline: medium none;position: absolute;filter:alpha(opacity=0);-moz-opacity:0;opacity:0;left:0px;top: 0px;" multiple/>
                        </div>

                        <input type="hidden" id="cover1" name="cover" value="" />
                        <span>　　样片封面图请上传：<mark>720*360px</mark>的“<mark><b>jpg png</b></mark>”格式 size小于<mark>250kb</mark>的图片。</span>
                    </fieldset>
                    <div>
                        <img width="240px" height="120px" class="fileupload1" src="">
                    </div>
                </th>
            </tr>
            <tr>
                <th width="160"></th>
                <th colspan="3">
                    <button  class="ui-button">提交</button>
                </th>
            </tr>
        </table>
    </form>
</div>
<form class="box box-form" action="/wftadlogin/first/list?type=1" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
        $search_type = 5;
        $search_status = 0;
        $search_id = '';

        if (isset($_GET['search_type']) && $_GET['search_type']) {
            $search_type = $_GET['search_type'];
        }

        if (isset($_GET['search_status']) && $_GET['search_status']) {
            $search_status = $_GET['search_status'];
        }

        if (isset($_GET['search_id']) && $_GET['search_id']) {
            $search_id = $_GET['search_id'];
        }
    ?>
    <table class="table">

        <tr>
            <th width="160">类别</th>
            <th colspan="3">
                <select name="search_status">
                    <option value="0" <?php echo ($search_status == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($search_status == 1) ? 'selected' : '';?>>强推</option>
                    <option value="2" <?php echo ($search_status == 2) ? 'selected' : '';?>>置顶</option>
                    <option value="3" <?php echo ($search_status == 3) ? 'selected' : '';?>>有效</option>
                    <option value="4" <?php echo ($search_status == 4) ? 'selected' : '';?>>无效</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">id</th>
            <th colspan="3">
                <select name="search_type">
                    <option value="5" <?php echo ($search_type == 5) ? 'selected' : '';?>>商品</option>
                    <option value="4" <?php echo ($search_type == 4) ? 'selected' : '';?>>游玩地</option>
                    <option value="16" <?php echo ($search_type == 16) ? 'selected' : '';?>>活动</option>
                </select>
                <input type="text" class="cssInput" name="search_id" value="<?php echo $search_id;?>">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <input type="hidden" class="cssInput" name="type" value="1">
                <a href="/wftadlogin/first/list?type=1" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>
<div class="box">
    <div class="box-title">
        精选列表
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="15">id</th>
                <th width="100">标题文字</th>
                <th width="100">说明文字</th>
                <th width="100">编辑人</th>
                <th width="30">评论</th>
                <th width="30">点击</th>
                <th width="30">分享</th>
                <th width="30">状态</th>
                <th width="60">类别</th>
                <th width="200">操作</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td  width="15"><?php echo $row['id']; ?></td>
                        <td  width="100">
                            <?php 
                            if ($row['type'] == 1) {
                                $url = '/wftadlogin/activity/new?aid='.$row['link_id'];
                            } elseif($row['type'] == 4) {
                                $url = '/wftadlogin/place/new?sid='.$row['link_id'];
                            } elseif($row['type'] == 5) {
                                $url = '/wftadlogin/good/new?gid='.$row['link_id'];
                            } elseif($row['type'] == 6) {
                                $url = array_key_exists('url',$row)?$row['url']:'';
                            } elseif($row['type'] == 7) {
                                $url = '/wftadlogin/circle/wordinfo?id='.$row['link_id'];
                            } elseif($row['type'] == 8) {
                                $url = '/wftadlogin/circle/new?id='.$row['link_id'];
                            }elseif($row['type'] == 16) {
                                $url = '/wftadlogin/excercise/edit?id='.$row['link_id'];
                            }
                            ?>

                            <a href="<?php echo $url;?>"><?php echo $row['block_title']; ?></a>
                        </td>
                        <td width="30"><?php echo $row['tip']; ?></td>
                        <td width="30"><?php echo $row['editor']; ?></td>
                        <td width="30"><?php echo $row['post_num']; ?></td>
                        <td width="30"><?php echo $row['click_num']; ?></td>
                        <td width="30"><?php echo $row['share_num']; ?></td>
                        <td width="30">
                            <?php
                            if($row['status'] == 2 && $row['flag']) {
                                echo '置顶';
                            } elseif ($row['flag']) {
                                echo '有效';
                            } else {
                                echo '无效';
                            }
                            ?>
                        </td>
                        <td width="60"><?php echo $label[$row['type'] -1]; ?></td>
                        <td  width="200">
                            <?php if($row['status'] == 1):?>
                                <a href="/wftadlogin/first/up?id=<?php echo $row['id']; ?>" class="ui-button">置顶</a>
                            <?php endif;?>
                            <?php if($row['status'] == 2):?>
                                <a href="/wftadlogin/first/down?id=<?php echo $row['id']; ?>" class="ui-button">取消置顶</a>
                            <?php endif;?>
                            <?php if(!$row['is_top']):?>
                                <a href="/wftadlogin/first/pushUp?id=<?php echo $row['id']; ?>&type=1" class="ui-button">强推</a>
                            <?php endif;?>
                            <?php if($row['is_top'] == 1):?>
                                <a href="/wftadlogin/first/pushDown?id=<?php echo $row['id']; ?>" class="ui-button">取消强推</a>
                            <?php endif;?>
                            <a href="/wftadlogin/first/delete?id=<?php echo $row['id']; ?>" class="ui-button">删除</a>
                            <a href="/wftadlogin/first/view?id=<?php echo $row['id']; ?>" class="ui-button">修改</a>
                            <a href="/wftadlogin/first/float?id=<?php echo $row['id']; ?>" class="ui-button">刷新上浮</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无数据 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>



<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script src="/js/file_upload/jquery.iframe-transport.js"></script>
<script src="/js/file_upload/jquery.fileupload.js"></script>
<script>
    $('#fileupload1').fileupload({
        url: '/wftadlogin/index/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                //$("input[name='cover']").attr('value', data.result.url);
                $(".fileupload1").attr('src' , data.result.url);
                $("#cover1").attr('value' , data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });

    $('#add_url').click(function(){
        $('#add_form').show();
    });

</script>
