<hgroup class="box">
    <header>
        <h3>会员专区首页</h3>
        <i class="icon icon-list"></i>
        &nbsp;&nbsp;&nbsp;
    </header>
</hgroup>

<div class="box">
    <div class="box-title">
        模块列表
        <?php echo $filtercity; ?>
    </div>
    <div>
        <table class="table">
            <tbody>
                <tr>
                    <th width="30">类型</th>
                    <th width="30">模块</th>
                    <th width="30">内容数量</th>
                    <th width="50">更新时间</th>
                    <th width="30">操作</th>
                </tr>
                <tr style="text-align: left">
                    <td  width="30"><?php echo $data['8']['word']; ?></td>
                    <td  width="30"><?php echo $data['8']['name']; ?></td>
                    <td  width="30"><?php echo $data['8']['number']; ?></td>
                    <td  width="50"><?php echo $data['8']['time']; ?></td>
                    <td  width="30"><a class="ui-button" href="/wftadlogin/first/list?type=8">编辑内容</a></td>
                </tr>
                <tr style="text-align: left">
                    <td  width="30"><?php echo $data['9']['word']; ?></td>
                    <td  width="30"><?php echo $data['9']['name']; ?></td>
                    <td  width="30"><?php echo $data['9']['number']; ?></td>
                    <td  width="50"><?php echo $data['9']['time']; ?></td>
                    <td  width="30"><a class="ui-button" href="/wftadlogin/first/excercisefreelist">编辑内容</a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>