<hgroup class="box">
    <header>
        <h3>首页管理</h3>
        <i class="icon icon-list"></i>
        <a href="javascript:history.back(-1);">返回上一页</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系 </div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/first/saveFirst" method="post" id="first-save">
    <table class="table">

        <tr>
            <th width="160">标题</th>
            <th colspan="3">
                <input type="text" class="cssInput" style="width: 350px" name="title" value="<?php echo $data->block_title;?>">
            </th>
        </tr>

        <?php if($data->type == 5 && $data->end_time):?>
            <tr>
                <th width="160">取消推送时间</th>
                <th colspan="3">
                    <input type="date" value="<?php echo date('Y-m-d', $data->end_time); ?>" name="end_timer">
                    <input type="time" value="<?php echo date('H:i', $data->end_time); ?>" name="end_timerl">　
                </th>
            </tr>
        <?php endif;?>

        <?php if($data->link_type == 1):?>
            <tr>
                <th width="160">说明</th>
                <th colspan="3">
                    <textarea class="cssTextArea" name="tip" ><?php echo $data->tip;?></textarea>
                </th>
            </tr>
            <tr>
                <th>封面图</th>
                <th colspan="3">
                    <fieldset>
                        <div style="float: left;height: 41px;background: #f5696c;width: 144px;position:relative;">
                            <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">上传</div>
                            <input type="file" id="fileupload1" name="file" style="width: 144px;height: 41px;cursor: pointer;font-size: 30px;outline: medium none;position: absolute;filter:alpha(opacity=0);-moz-opacity:0;opacity:0;left:0px;top: 0px;" />
                        </div>

                        <input type="hidden" id="cover1" name="cover" value="<?php echo $data->link_img;?>" />
                        <span>　　样片封面图请上传：<mark>720*360px</mark>的“<mark><b>jpg png</b></mark>”格式 size小于<mark>250kb</mark>的图片。</span>
                    </fieldset>
                    <div>
                        <img width="240px" height="120px" class="fileupload1" id="img-src" src="<?php echo $data->link_img;?>">
                    </div>
                </th>
            </tr>
        <?php endif;?>

        <?php if($data->link_type == 4):?>
            <tr>
                <th>封面图</th>
                <th colspan="3">
                    <fieldset>
                        <div style="float: left;height: 41px;background: #f5696c;width: 144px;position:relative;">
                            <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">上传</div>
                            <input type="file" id="fileupload1" name="file" style="width: 144px;height: 41px;cursor: pointer;font-size: 30px;outline: medium none;position: absolute;filter:alpha(opacity=0);-moz-opacity:0;opacity:0;left:0px;top: 0px;" />
                        </div>

                        <input type="hidden" id="cover1" name="cover" value="<?php echo $data->link_img;?>" />
                        <span>片封面图请上传：360*360px的“jpg png”格式 size小于250kb的图片。。</span>
                    </fieldset>
                    <div>
                        <img width="120px" height="120px" class="fileupload1" id="img-src" src="<?php echo $data->link_img;?>">
                    </div>
                </th>
            </tr>
        <?php endif;?>

        <tr>
            <th width="160"></th>
            <th colspan="3">

                <input type="hidden" name="id" value="<?php echo $data->id; ?>">
                <button id="ti-first" type="submit" class="btn btn-primary">保存</button>
            </th>
        </tr>
    </table>
</form>


<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script src="/js/file_upload/jquery.iframe-transport.js"></script>
<script src="/js/file_upload/jquery.fileupload.js"></script>
<script>

    //保存提交
    $('#ti-first').click(function () {
        $.post('/wftadlogin/first/saveFirst', $('#first-save').serialize(), function (data) {
            if (data.status == 1) {
                alert('保存成功');
            } else {
                alert(data.message);
            }
        }, 'json');
        return false;
    });

    $('#fileupload1').fileupload({
        url: '/wftadlogin/index/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $(".fileupload1").attr('src' , data.result.url);
                $("#cover1").attr('value' , data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });
</script>



