<hgroup class="box">
    <header>
        <h3>附近</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/nearby/restaurant">餐厅管理</a>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/nearby/park">停车场管理</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<div class="box">
    统计数据 待定
</div>
