<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
  <!--  <script>(function(){var w=window.screen.width,s=w/750,u=navigator.userAgent,m='<meta name="viewport" content="width=750,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
-->
    <title>玩翻天</title>
    <!--    <link type="text/css" rel="stylesheet" href="/css/web-style.css" />-->
    <style>

        body{
            overflow-x: hidden;
            overflow-y: auto;
            padding: 20px 12px 0px 12px;
            max-width: 640px;
        }
        article * {
            padding: 0;
            margin: 0;
            word-break: break-all !important;
            word-wrap: break-word !important;
            white-space: normal !important;
            max-width: 100% !important;
            height: auto !important;
            width: 100% !important;
            line-height: 1.6 !important;
            font-size: 14px !important;
            /*color:#000 !important;*/
        }
        article  img{
            max-width: 100% !important;
            width: 100% !important;
            height: auto;
        }

        .adv{
            margin-top: 25px;
            border-top: 1px solid #cccccc;
        }
        .adv-head{
            font-size: 18.65px;
            font-weight: 600;
            margin-top: 20px;
            /*margin-bottom: 10px;*/
        }
        .adv-head:before{
            display: inline-block;
            width: 5px;
            height: 18px;
            margin-right: 15px;
            background: #ff565d;
            content: '';
        }
        .adv-info{
            position: relative;
            border-bottom: 1px solid #cccccc;
            line-height: 60px;
        }
        .adv-info:after{
            clear: both;
            display: block;
            content: '';
        }
        .adv-info-img{
            width: 35px;
            height: 35px;
            position: absolute;
            top: -10%;
            /*float: left;*/
            margin: 28px 0;
            -webkit-border-radius: 17.5px;
            border-radius: 17.5px;
            overflow: hidden;
        }
        /*  .adv-info-img:after{
              clear: both;
              display: block;
              content: '';
          }*/
        .adv-info-mes {
            padding-left: 35px;
            float: left;
            margin-top: 8px;
            margin-bottom: 3px;
            font-size: 12.8px;
            margin-left: 16px;
        }
        .adv-info-month{
            position: absolute;
            top: 49%;
            right: 32px;
            line-height: 85%;

            display: block;
            float: right;
            border: 1px solid #000;
            padding: 8px 10px;
            margin-left: 25px;
            margin-top: -10px;
            /*margin-bottom: 15px;*/
            font-size: 10.24px;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
        }

        .arrowent,.arrowent1{
            position: absolute;
            right: 10px;
            height: 12px;
            width: 12px;
            border: 2px solid #999;
            -webkit-transform: rotate(45deg);
            transform: rotate(45deg);
            overflow: hidden;
            border-bottom: none;
            border-left: none;
        }
        .arrowent{
            top: 43%;
        }
        .arrowent1{
            top: 10%;
        }

        .adv-edit{
            position: relative;
            font-size: 18.65px;
            margin-top: 10px;
            padding-bottom: 5px;
        }
        .adv-edit-font {
            padding-left: 24px;
            font-size: 18.65px;
            color: #000;
            background-image: url(/images/order-center/icon1.png);
            background-repeat: no-repeat;
            background-size: 16px auto;
            background-position: 0 -35px;
        }
        .adv-edit-give {
            float: right;
            font-size: 11.945px;
            color: #ec5565;
            position: relative;
            right: 25px;
            bottom: -4px;
        }

    </style>
</head>

<body style="background: white">

<article>
    <?php echo $res; ?>
</article>

<?php if($app):?>

    <section class="adv">
        <?php if(count($all)):?>
            <div class="adv-head">推荐攻略</div>
        <?php endif;?>
        <?php foreach($all as $strategy):?>
            <div class="adv-info">
                <img src="<?php echo $strategy['strategy_image'];?>" class="adv-info-img" width="80" height="80">
                <div class="adv-info-mes jump-web" data-title="<?php echo $strategy['strategy_title'];?>" data-url="<?php echo $url;?>/web/place/strategy?id=<?php echo $strategy['strategy_id'];?>">
                    <?php echo $strategy['strategy_title'];?>
                    <?php if($strategy['suit_month']):?>
                    <span class="adv-info-month">适合<?php echo $strategy['suit_month'];?>月</span>
                    <?php endif;?>
                    <div class="arrowent"></div>
                </div>
            </div>
        <?php endforeach;?>

        <div class="adv-edit" data-url="<?php echo $url;?>/web/h5/invite">
            <span class="adv-edit-font">小编约稿</span>
            <span class="adv-edit-give"><?php echo $award; ?></span>
            <div class="arrowent1"></div>
        </div>
    </section>
<?php endif;?>

</body>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script>
    $(function () {
        $('.jump-web').click(function () {
            var url = encodeURIComponent($(this).attr('data-url'));
            var title = encodeURIComponent($(this).attr('data-title'));
            if (navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/iphone os/i) || navigator.userAgent.match(/ipod/i)) {
                document.location.href = 'jump_web&&url=' + url + '&&title=' + title ;
            } else if (navigator.userAgent.match(/android/i)) {
                window.getdata.jump_web(url, title);
            } else {
                //alert('xx')
            }
            return false;
        });

        $('.adv-edit').click(function () {
            var url = encodeURIComponent($(this).attr('data-url'));
            if (navigator.userAgent.match(/iPad/i) || navigator.userAgent.match(/iphone os/i) || navigator.userAgent.match(/ipod/i)) {
                document.location.href = 'jump_web&&url=' + url + '&&title=小编约稿';
            } else if (navigator.userAgent.match(/android/i)) {
                window.getdata.jump_web(url, '小编约稿');
            } else {
                //alert('xx')
            }
            return false;
        });


    }());
</script>
</html>