<hgroup class="box">
    <header>
        <h3>微信关键字自动回复</h3>

        <i class="icon icon-list"></i>
        <a href="/wftadlogin/weixin">回到微信管理首页</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<div class="box">
    <div class="box-title"><?php echo $this->data ? '修改' : '添加'; ?>自动回复</div>

    <form method="post" action="/wftadlogin/weixin/update<?php echo $this->data ? '?id=' . $this->data['id'] : ''; ?>">
        <table class="table">
            <tr>
                <th width="160">关键字列表</th>
                <th colspan="3">
                    <textarea class="csstextarea" name="keywords"><?php echo isset($this->data['keyword']) ? $this->data['keyword'] : ''; ?></textarea>
                    <p>多个关键字请使用回车</p>
                </th>
            </tr>

            <tr>
                <th width="160">关键字匹配类型</th>
                <th colspan="3">
                    <input type="radio" name="match_all" value="1"
                        <?php echo (isset($this->data['match_all']) && $this->data['match_all'] == 1) ? 'checked' : ''; ?>>全词匹配&nbsp;&nbsp;&nbsp;
                    <input type="radio" name="match_all" value="0"
                        <?php echo !(isset($this->data['match_all']) && $this->data['match_all'] == 1) ? 'checked' : ''; ?>>模糊匹配
                </th>
            </tr>

            <tr>
                <th width="160">回复类型</th>
                <th colspan="3">
                    <select id="cityChange" name="type">
                        <option value="text" id="text"
                            <?php echo (isset($this->data['type']) && $this->data['type'] == 'text') ? 'selected' : ''; ?>>文字回复</option>
                        <option value="news" id="news"
                            <?php echo (isset($this->data['type']) && $this->data['type'] == 'news') ? 'selected' : ''; ?>>图文回复</option>
                    </select>

                    <?php if ($data) : ?>
                        <span id="news-show" class="ui-button">显示全部</span>
                    <?php endif; ?>
                </th>
            </tr>

            <tr class="r-news">
                <th width="160">标题</th>
                <th colspan="3">
                    <input type="text" class="cssInput" name="title"
                           value="<?php echo isset($this->data['title']) ? $this->data['title'] : ''; ?>">
                </th>
            </tr>

            <tr class="r-news">
                <th width="160">描述</th>
                <th colspan="3">
                    <input type="text" class="cssInput" name="description"
                           value="<?php echo isset($this->data['description']) ? $this->data['description'] : ''; ?>">
                </th>
            </tr>

            <?php
                if (!$this->data || ($this->data && preg_match('/^\/uploads/', $this->data['img']))) {
                    //如果是上传的图片则不显示地址
                    $img_src = '';
                } else {
                    $img_src = $this->data['img'];
                }
            ?>
            <tr class="r-news">
                <th width="160">图片地址 <span class="img-keyword">（选填）</span></th>
                <th colspan="3">
                    <input type="text" class="cssInput" name="img" value="<?php echo $img_src; ?>">
                    <span>图片地址和上传图片二选一</span>
                </th>
            </tr>

            <tr class="r-news">
                <th>上传图片<span class="img-keyword">（选填）</span></th>
                <th colspan="3">
                    <fieldset>
                        <div class="img-button">
                            <div class="img-tip">上传</div>
                            <input type="file" id="fileupload2" name="file" multiple/>
                        </div>

                        <input type="hidden" class="hidden" name="thumb" value="<?php echo isset($this->data['img']) ? $this->data['img'] : ''; ?>" />
                        <span>　　请上传：<mark>360*360px</mark>的“<mark><b>jpg png</b></mark>”格式 size小于<mark>250kb</mark>的图片。</span>
                    </fieldset>
                    <div>
                        <img width="120px" height="120px" class="fileupload2"
                             src="<?php echo isset($this->data['img']) ? $this->data['img'] : ''; ?>">
                    </div>
                </th>
            </tr>

            <tr class="r-news">
                <th width="160">跳转地址</th>
                <th colspan="3">
                    <input type="text" class="cssInput" name="to_url"
                           value="<?php echo isset($this->data['to_url']) ? $this->data['to_url'] : ''; ?>">
                </th>
            </tr>

            <tr class="r-text">
                <th width="160">回复内容</th>
                <th colspan="3">
                    <textarea class="csstextarea" name="content"><?php echo isset($this->data['message']) ? $this->data['message'] : ''; ?></textarea>
                </th>
            </tr>

            <tr>
                <th width="160"><button id="ti-place" class="ui-button">提交</button></th>
            </tr>
        </table>
    </form>
</div>

<style>
    .img-keyword {
        line-height: 15px;
        color: red;
    }
    #fileupload2 {
        width: 144px;
        height: 41px;
        cursor: pointer;
        font-size: 30px;outline: medium none;
        position: absolute;
        filter:alpha(opacity=0);
        -moz-opacity:0;
        opacity:0;
        left:0px;
        top: 0px;
    }
    .img-button {
        float: left;
        height: 41px;
        background: #f5696c;
        width: 144px;
        position:relative;
    }
    .img-tip {
        text-align:center;
        line-height:41px;
        font-size:15px;
        font-weight:800;
    }
    .csstextarea {
        width: 300px;
        height: 100px;
    }
</style>

<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script src="/js/file_upload/jquery.iframe-transport.js"></script>
<script src="/js/file_upload/jquery.fileupload.js"></script>
<script>
    $(function(){
        $('.r-news').hide();
        $('.r-text').hide();

        $('#news-show').click(function(){
            if ($('#cityChange').val() == 'news') {
                $('.r-news').show();
                $('.r-text').hide();
            } else {
                $('.r-news').hide();
                $('.r-text').show();
            }
            $('#news-show').hide();

        });

        $('#cityChange').click(function(){
            if ($(this).val() == 'news') {
                $('.r-news').show();
                $('.r-text').hide();
            } else {
                $('.r-news').hide();
                $('.r-text').show();
            }
        });
    });


    //图片上传
    $('#fileupload2').fileupload({
        url: '/wftadlogin/index/upload',
        dataType: 'json',
        /*limitMultiFileUploadSize: 1,
         limitMultiFileUploadSizeOverhead: 30,
         maxFileSize : 34,
         //autoUpload: false,
         acceptFileTypes:  /(\.|\/)(gpg|jpeg|png)$/i,
         maxNumberOfFiles : 1,*/

        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='thumb']").attr('value', data.result.url);
                $(".fileupload2").attr('src' , data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });
</script>

