<hgroup class="box">
    <header>
        <h3>设置微信菜单</h3>

        <i class="icon icon-list"></i>
        <a href="/wftadlogin/weixin">回到微信管理首页</a>

        <i class="icon icon-add"></i>
        <a href="/wftadlogin/weixin/editMenu">添加本地菜单</a>

        <i class="icon icon-add"></i>
        <a href="/wftadlogin/weixin/generateMenu" onclick="return confirm('确定要更新线上微信菜单？微信服务器会有24小时缓存时间，无法实时更新哦！')">更新微信菜单</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<div class="box">
    <div class="box-title">
        菜单列表
    </div>

    <div class="box-table">
        <table class="table">
            <tr>
                <th class="size1">菜单ID</th>
                <th class="size2">菜单标题</th>
                <th class="size1">菜单级别</th>
                <th class="size4">菜单地址</th>
                <th class="size2">操作</th>
            </tr>
            <?php foreach ($this->menus as $me) : ?>
                <tr>
                    <td><?php echo $me->id; ?></td>
                    <td><?php echo $me->menu_name; ?></td>
                    <td><?php echo $me->button == 1 ? '一级菜单' : '二级菜单'; ?></td>
                    <td><?php echo $me->url; ?></td>
                    <td>
                        <a href="/wftadlogin/weixin/setMenu?pmid=<?php echo $me->id; ?>">查看二级菜单</a> |
                        <a href="/wftadlogin/weixin/editMenu?id=<?php echo $me->id; ?>">修改</a> |
                        <a href="/wftadlogin/weixin/deleteMenu?id=<?php echo $me->id; ?>" onclick="return confirm('确定删除吗？不可恢复')">删除</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<style>
    th {
        max-width: 200px;
        -o-text-overflow: ellipsis;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        text-align: left;
    }

    td {
        max-width: 200px;
        -o-text-overflow: ellipsis;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        text-align: left;
    }

    .box-table td{
        text-align: left;
    }
</style>
