<table class="table">
    <tr>
        <th width="160">商品id</th>
        <th colspan="3">
            <?php echo $goodData->id;?>
        </th>
    </tr>

    <tr>
        <th width="160">商品名称</th>
        <th colspan="3">
            <?php echo $goodData->title;?>
        </th>
    </tr>

    <tr>
        <th width="160">商品状态</th>
        <th colspan="3">
            <?php
                if ($goodData->is_together == 1 && $goodData->status == 1 && $goodData->up_time > time()) { //未开始
                    $game_stay = '未开始';
                } elseif ($goodData->is_together == 1 && $goodData->status == 1 && $goodData->up_time < time() && $goodData->down_time > time()) {// 在售卖
                    $game_stay = '在售卖';
                } elseif ($goodData->is_together == 1 && $goodData->status == 1 && $goodData->foot_time > time() && $goodData->down_time < time()) {// 停止售卖
                    $game_stay = '停止售卖';
                } elseif ($goodData->is_together == 1 && $goodData->status == 1 && $goodData->foot_time < time() && $goodData->down_time < time()) {
                    $game_stay = '停止使用';
                } else {
                    $game_stay = '停止使用';
                }

                echo $game_stay;
            ?>
        </th>
    </tr>
</table>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
        $user_name = null;
        $user_phone = null;
        $buy_start = null;
        $buy_end = null;
        $check_start = null;
        $check_end = NULL;
        $people_in = 0;
        $address_in = 0;
        $code_status = 0;

        if (isset($_GET['user_name']) && $_GET['user_name']) {
            $user_name = $_GET['user_name'];
        }

        if (isset($_GET['code_status']) && $_GET['code_status']) {
            $code_status = $_GET['code_status'];
        }

        if (isset($_GET['user_phone']) && $_GET['user_phone']) {
            $user_phone = $_GET['user_phone'];
        }

        if (isset($_GET['buy_start']) && $_GET['buy_start']) {
            $buy_start = $_GET['buy_start'];
        }

        if (isset($_GET['buy_end']) && $_GET['buy_end']) {
            $buy_end = $_GET['buy_end'];
        }

        if (isset($_GET['check_start']) && $_GET['check_start']) {
            $check_start = $_GET['check_start'];
        }

        if (isset($_GET['check_end']) && $_GET['check_end']) {
            $check_end = $_GET['check_end'];
        }

        if (isset($_GET['people_in']) && $_GET['people_in']) {
            $people_in = $_GET['people_in'];
        }

        if (isset($_GET['address_in']) && $_GET['address_in']) {
            $address_in = $_GET['address_in'];
        }

    ?>
    <table class="table">
        <tr>
            <th width="160">购买时间</th>
            <th>
                <input name="buy_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $buy_start;?>">
                <input name="buy_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $buy_end;?>">
            </th>
            <th width="160">验证时间</th>
            <th>
                <input name="check_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $check_start;?>">
                <input name="check_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $check_end;?>">
            </th>
        </tr>

        <tr>
            <th width="160">用户名</th>
            <th>
                <input type="text" class="cssInput" name="user_name" value="<?php echo $user_name;?>">
            </th>
            <th width="160">用户手机号</th>
            <th>
                <input type="text" class="cssInput" name="user_phone" value="<?php echo $user_phone;?>">
            </th>
        </tr>

        <tr>
            <th width="160">出行人录入情况</th>
            <th>
                <select name="people_in">
                    <option <?php echo  !$people_in ? 'selected' : ''; ?> value="0">全部</option>
                    <option <?php echo $people_in == 1 ? 'selected' : ''; ?> value="1">信息未填写</option>
                    <option <?php echo $people_in == 2 ? 'selected' : ''; ?> value="2">未投保</option>
                    <option <?php echo $people_in == 3 ? 'selected' : ''; ?> value="3">投保中</option>
                    <option <?php echo $people_in == 4 ? 'selected' : ''; ?> value="4">已投保</option>
                    <option <?php echo $people_in == 5 ? 'selected' : ''; ?> value="5">投保失败</option>
                </select>
            </th>
            <th width="160">地址填写情况</th>
            <th>
                <select name="address_in">
                    <option <?php echo  !$address_in ? 'selected' : ''; ?> value="0">全部</option>
                    <option <?php echo $address_in == 1 ? 'selected' : ''; ?> value="1">已填写</option>
                    <option <?php echo $address_in == 2 ? 'selected' : ''; ?> value="2">未填写</option>
                </select>　
                验证码状态　
                <select name="code_status">
                    <option <?php echo  !$code_status ? 'selected' : ''; ?> value="0">全部</option>
                    <option <?php echo $code_status == 1 ? 'selected' : ''; ?> value="1">未使用</option>
                    <option <?php echo $code_status == 2 ? 'selected' : ''; ?> value="2">已使用</option>
                    <option <?php echo $code_status == 4 ? 'selected' : ''; ?> value="4">退款中</option>
                    <option <?php echo $code_status == 3 ? 'selected' : ''; ?> value="3">已退款</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/game/order?good_id=<?php echo $goodData->id;?>" style="background-color: green" class="ui-button">清空所有选项</a>
                <input type="hidden" name="good_id" value="<?php echo $goodData->id;?>">
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/game/outData" style="background-color: green" id="out-data" class="ui-button">导出订单</a>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">
        订单列表
    </div>

    <table class="table">
        <tbody>
        <tr>
            <th width="50">选择</th>
            <th width="100">验证码</th>
            <th width="150">订单号</th>
            <th width="150">下单时间</th>
            <th width="150">套系名称</th>
            <th width="80">用户id</th>
            <th width="80">用户名</th>
            <th width="80">联系人</th>
            <th width="80">联系手机</th>
            <th width="150">收货地址</th>
            <th width="100">状态</th>
            <th width="150">操作</th>
        </tr>
        <?php foreach ($data as $key => $row): ?>
            <tr style="text-align: left">
                <td width="50">
                    <?php if($row['status'] == 0):?>
                        <input type="checkbox" name="check_ids" value="<?php echo $row['id']; ?>">
                    <?php endif;?>
                </td>
                <td width="100">
                    <?php echo $row['id']. $row['password']; ?>
                </td>
                <td width="150">
                    <a href="/wftadlogin/order/info?order_sn=<?php echo $row['order_sn'];?>"><?php echo $row['order_sn']; ?></a>
                </td>
                <td width="150"><?php echo date('Y-m-d H:i',$row['dateline']); ?></td>
                <td width="150"><?php echo $row['type_name']; ?></td>
                <td width="80"><?php echo $row['user_id']; ?></td>
                <td width="80"><?php echo $row['username']; ?></td>
                <td width="80"><?php echo $row['buy_name']; ?></td>
                <td width="100"><?php echo $row['buy_phone']; ?></td>
                <td width="150"><?php echo $row['buy_address']; ?></td>
                <td width="100">
                    <?php if ($row['status'] == 0) {
                        echo '未使用';
                    } elseif($row['status'] == 1) {
                        echo '已使用';
                    } elseif($row['status'] == 2) {
                        echo '已退款';
                    } elseif($row['status'] == 3) {
                        echo '退款中';
                    };
                    ?>
                </td>
                <td width="150">
                    <?php if($row['status'] == 0):?>
                        <a href="/wftadlogin/code/useCode?type=1&id=<?php echo $row['id']; ?>" onclick="if(confirm('确定验证使用?')==false) return false;" class="ui-button">验证</a>
                    <?php endif;?>
                    <a href="javascript:void(0)" data-mes="<?php echo $row['buy_address']; ?>" data-src="/wftadlogin/good/updateAddress?order_sn=<?php echo $row['order_sn'];?>" class="ui-button login">补录地址</a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <input type="checkbox" id="check-all">
    <button class="ui-button" id="mark-check">当前页面提交验证</button>
    <footer>
        <?php echo $this->pageData; ?>
    </footer>

</div>

<style>
    .btn {
        position: relative;
        cursor: pointer;
        display: inline-block;
        vertical-align: middle;
        font-size: 12px;
        font-weight: bold;
        height: 27px;
        line-height: 27px;
        min-width: 52px;
        padding: 0 12px;
        text-align: center;
        text-decoration: none;
        border-radius: 2px;
        border: 1px solid #ddd;
        color: #666;
        background-color: #f5f5f5;
        background: -webkit-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: -moz-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: linear-gradient(top, #F5F5F5, #F1F1F1);
    }

    .login-body {
        padding: 60px 15px;
        color: #444;
        height: 148px;
    }

    .ipt {
        border: solid 1px #d2d2d2;
        border-left-color: #ccc;
        border-top-color: #ccc;
        border-radius: 2px;
        box-shadow: inset 0 1px 0 #f8f8f8;
        background-color: #fff;
        padding: 4px 6px;
        height: 21px;
        line-height: 21px;
        color: #555;
        width: 180px;
        vertical-align: baseline;
    }

    .dform {
        padding: 80px 60px 40px;
        text-align: center;
    }

    .signin {
        margin: -50px -20px -50px 90px;
        text-align: left;
        font-size: 14px;
    }

    .signin h4 {
        color: #999;
        font-weight: 100;
        margin-bottom: 20px;
        font-size: 12px;
    }

    .signin li {
        padding-left: 80px;
        margin-bottom: 15px;
    }

    .signin ol {
        list-style-type: none;
    }

    .signin li strong {
        float: left;
        margin-left: -80px;
        width: 80px;
        text-align: right;
        line-height: 32px;
    }

    .signin .btn {
        margin-bottom: 10px;
    }

    .signin p {
        font-size: 12px;
        color: #999;
    }

    .theme-desc,.theme-version {
        padding-top: 0
    }

    .body-color {
        z-index: 9998;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: #000;
        opacity: 0.4;
        filter: alpha(opacity = 40);
        display: none
    }

    .hide-body {
        z-index: 9999;
        position: fixed;
        top: 30%;
        left: 40%;
        width: 1000px;
        height: 618px;
        margin: -180px 0 0 -330px;
        border-radius: 5px;
        border: solid 2px #666;
        background-color: #fff;
        display: none;
        box-shadow: 0 0 10px #666;
    }

    .close-window {
        border-bottom: 1px solid #ddd;
        padding: 22px;
        position: relative;
    }

    .bottom {
        margin-top: 180px;
    }

    .close-window .close {
        float: right;
        color: #999;
        padding: 5px;
        margin: -2px -5px -5px;
        font: bold 14px/14px simsun;
        text-shadow: 0 1px 0 #ddd
    }

    .close-window .close:hover {
        color: #444;
    }
</style>

<div class="hide-body">
    <div class="close-window">
        <a href="javascript:;" title="关闭" class="close">×</a>
        <h3>修改地址</h3>
    </div>
    <div class="login-body dform">
        <form class="signin" name="loginform" action="post" id="zjh" method="post">

            收货地址:   <textarea name="address" id="area-m" class="cssTextArea"></textarea><br /><br /><br /><br />
             <button  type="submit">提交</button>
        </form>
    </div>
</div>

<script>
    $(function () {

        //弹窗
        $('.login').click(function(){ //jquery的点击事件
            $('.body-color').fadeIn(100);//全局变得黑的效果，具体的div就是theme-popover-mask这个
            $('.hide-body').slideDown(200);//将隐藏的窗口div显示出来
            var url = $(this).attr('data-src');
            $('#area-m').val($(this).attr('data-mes'));
            $('#zjh').attr('action', url);


        })
        $('.close-window .close').click(function(){
            $('.body-color').fadeOut(100);//
            $('.hide-body').slideUp(200);//将显示的窗口隐藏起来
        })


        //全选和全不选
        $('#check-all').click(function() {
            if ($(this).is(':checked')) {
                $("[name=check_ids]:checkbox").prop('checked', true);
            } else {
                $("[name=check_ids]:checkbox").prop('checked', false);
            }
        });

        //提交结算
        $('#mark-check').click(function() {
            alert(45);
            if (confirm('确定将所有选中的订单验证使用？不可恢复')) {
                //执行修改操作
                var href = '/wftadlogin/code/useCode?type=2';//跳转的链接
                var check_ids = document.getElementsByName('check_ids');
                var id='';//如果这样定义var s;变量s中会默认被赋个null值
                for (var i = 0; i < check_ids.length; i++) {
                    if (check_ids[i].checked){
                        if (i == check_ids.length - 1) {
                            id += check_ids[i].value;
                        } else {
                            id += check_ids[i].value + ',';
                        }
                    }
                }

                if (id == '') {
                    alert('没有选中任何订单');
                }

                $.post(href, {ids:id}, function (data) {
                    if (data.status == 1) {
                        alert('成功');
                        window.location.reload();
                    } else {
                        alert(data.message);
                    }
                }, 'json');
                return false;
            }
        });

        //导出订单
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });

    });
</script>


