<hgroup class="box">
    <header>
        <h3>网页活动管理</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/outlook/new">创建一个网页活动</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<div class="box">
    <div class="box-title">
        网页活动
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">id</th>
                <th class="size3">标题</th>
                <th class="size2">状态</th>
                <th class="size2">类别</th>
                <th class="size3">操作</th>
            </tr>
            <?php if ($data): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size1"><?php echo $row->id; ?></td>
                        <td class="size3"><?php echo $row->title;?></td>
                        <td class="size2" style="color: red"><?php echo $row->status ? '发布ing' : '未发布';?></td>
                        <td class="size2"><?php echo $typeData[$row->type];?></td>
                        <td class="size3">
                            <a href="/wftadlogin/outlook/new?id=<?php echo $row->id;; ?>" class="ui-button">修改</a>
                            <a href="/wftadlogin/outlook/update?id=<?php echo $row->id;; ?>&status=<?php echo $row->status ? 0 :1;?>" class="ui-button"><?php echo $row->status ? '取消发布' : '发布';?></a>
                            <a href="/wftadlogin/outlook/delete?id=<?php echo $row->id;; ?>" class="ui-button">删除</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无推送, 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>
