<hgroup class="box">
    <header>
        <h3>网页活动管理</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/outlook">返回</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/outlook/save" method="post">
    <header class="box-title"><?php echo $data ? '修改' : '添加';?>网页活动</header>
    <table class="table">
        <tr>
            <th width="160">标题</th>
            <th colspan="3"><input type="text" class="cssInput" name="title" value="<?php echo $data ? $data->title : ''; ?>">
            </th>
        </tr>

        <tr>
            <th width="160">类别</th>
            <th colspan="3">
                <select name="type">
                    <option value="1">右上角</option>
                    <option value="2">焦点图</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">点击跳转链接</th>
            <th colspan="3"><input type="text" class="cssInput" name="chain" value="<?php echo $data ? $data->chain : ''; ?>">
            </th>
        </tr>

        <tr>
            <th width="160">图片</th>
            <th colspan="3">
                <fieldset>
                    <div style="float: left;height: 41px;background: #f5696c;width: 144px;position:relative;">
                        <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">上传</div>
                        <input type="file" id="fileupload" name="file" style="width: 144px;height: 41px;cursor: pointer;font-size: 30px;outline: medium none;position: absolute;filter:alpha(opacity=0);-moz-opacity:0;opacity:0;left:0px;top: 0px;" multiple/>
                    </div>

                    <input type="hidden" name="cover" value="" />
                    <span>　　请根据不同类型 上传不同尺寸的图片 焦点图720*360
                </fieldset>
                <br />

                <div>
                    <img width="120" height="60" class="fileupload" src="<?php echo $data ? $data->img : ''; ?>">
                </div>
            </th>
        </tr>

        <tr>
            <th width="160"> </th>
            <th colspan="3">
                <input type="hidden"   name="id" value="<?php echo $data ? $data->id : ''; ?>">
                <button type="submit" class="btn btn-primary">提交</button>
            </th>
        </tr>

    </table>

</form>

<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script src="/js/file_upload/jquery.iframe-transport.js"></script>
<script src="/js/file_upload/jquery.fileupload.js"></script>
<script>
    $('#fileupload').fileupload({
        url: '/wftadlogin/index/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='cover']").attr('value', data.result.url);
                $(".fileupload").attr('src' , data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });

</script>

