<hgroup class="box">
    <header>
        <h3>推广经费  管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/fundscheck">返回</a>
        <i class="icon icon-list"></i>
        <a href="javascript:void(0)">现金券审核列表</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/cashcoupon/used">现金券使用列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/fundscheck/cash" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $cash = null;
    $use_status = null;


    if (isset($_GET['cash']) && $_GET['cash']) {
        $cash = $_GET['cash'];
    }
    if (array_key_exists('use_status',$_GET) and $_GET['use_status'] !== '') {
        $use_status = (int)$_GET['use_status'];
    }
    ?>
    <table class="table">

        <tr>
            <th width="160">现金券ID/名称</th>
            <th>
                <input type="text" class="cssInput" name="cash" value="<?php echo $cash;?>">
            </th>
            <th width="160">审核状态</th>
            <th>
                <select name="use_status" id="select">
                    <option value="" <?php echo ($use_status === null) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($use_status === 1) ? 'selected' : '';?>>已审核</option>
                    <option value="0" <?php echo ($use_status === 0) ? 'selected' : '';?>>未审核</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">
                <input type="hidden" name="cid" value="<?php echo $_GET['cid']; ?>" />
                <input type="hidden" class="cssInput" name="out" id="out" value="0">
            </th>
            <th colspan="3">
                <a href="/wftadlogin/fundscheck/cash" style="background-color: green" class="ui-button">清空所有选项</a>
                <button id="tijiao" class="ui-button">提交</button>
<!--                <button id="out-data" style="background-color: green" class="ui-button">导出</button>-->
            </th>
        </tr>
    </table>
</form>
<div class="panel panel panel-primary">
    <div class="panel-heading">现金券审核列表</div>
    <div class="panel-body">

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">id</th>
                <th scope="col">现金券名称</th>
                <th scope="col">城市</th>
                <th scope="col">现金券单价</th>
                <th scope="col">申请张数</th>
                <th scope="col">申请金额</th>
                <th scope="col">发放时间段</th>
                <th scope="col">有效期</th>
                <th scope="col">申请时间</th>
                <th scope="col">经办人</th>
                <th scope="col">状态</th>
                <th scope="col">操作</th>
            </tr>
            <?php foreach ($data as $v): ?>
                <tr>
                    <td><a target="_blank" href="/wftadlogin/cashcoupon/detail?cid=<?php echo $v['id']; ?>"> <?php echo $v['id']; ?></a></td>
                    <td><?php echo $v['title']; ?></td>
                    <td><?php echo $cities[$v['city']]; ?></td>
                    <td><?php echo $v['price']; ?></td>
                    <td><?php echo $v['total']; ?></td>
                    <td><?php echo $v['total'] * $v['price']; ?></td>
                    <td><?php echo date('Y-m-d H:i:s', $v['begin_time']).' -- '. date('Y-m-d H:i:s', $v['end_time']); ?></td>
                    <td>
                        <?php
                        if($v['time_type']){//领券后
                            if($v['after_hour'] < 24 or ($v['after_hour']%24)){
                                $dw = '小时';
                                $hour = $data['after_hour'];
                            }elseif(($v['after_hour']%24)==0){
                                $dw = '天';
                                $hour = $v['after_hour']/24;
                            }
                            echo '领券后'.$hour.$dw.'有效';
                        }else{
                            echo date('Y-m-d H:i',$v['use_stime']).'到<br>'.date('Y-m-d H:i',$v['use_etime']);
                        }
                        ?>
                    </td>
                    <td><?php echo date('Y-m-d H:i:s',$v['createtime']); ?></td>
                    <td><?php echo $adminName[$v['creator']]; ?></td>
                    <td>
                        <?php
                            if ($v['status'] == 0) {
                                echo '待审批';
                            } elseif ($v['status'] == 1) {
                                echo '已审批';
                            }
                        ?>
                    </td>

                    <td>
                        <?php if($v['status'] == 0):?>
                            <a class="ui-button" href="/wftadlogin/cashcoupon/status?status=1&id=<?php echo $v['id']; ?>">通过审核</a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>

        </table>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('#out-data').click(function () {
            $('#out').val(1);
        })

        $('#tijiao').click(function () {
            $('#out').val(0);
        })
    })
</script>

