<hgroup class="box">
    <header>
        <h3>推广经费  管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/fundscheck">返回</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/fundscheck/rebate">返现列表</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/fundscheck/detail">返现详情列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：<span style="color:green">有问题 请及时联系</span></div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/fundscheck/detail" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $begin_time = null;
    $end_time = null;
    $coupon_name = null;
    $user = null;
    $good = null;
    $gettype = null;
    $use_status = null;
    $city = null;
    $month = null;

    if (isset($_GET['begin_time']) && $_GET['begin_time']) {
        $begin_time = $_GET['begin_time'];
    }

    if (isset($_GET['end_time']) && $_GET['end_time']) {
        $end_time = $_GET['end_time'];
    }

    if (isset($_GET['user']) && $_GET['user']) {
        $user = $_GET['user'];
    }

    if (isset($_GET['editor']) && $_GET['editor']) {
        $editor = $_GET['editor'];
    }

    if (isset($_GET['coupon_name']) && $_GET['coupon_name']) {
        $coupon_name = $_GET['coupon_name'];
    }
    if (isset($_GET['gettype']) && $_GET['gettype']) {
        $gettype = $_GET['gettype'];
    }

    if (isset($_GET['city']) && $_GET['city']) {
        $city = $_GET['city'];
    }



    ?>

    <table class="table">
        <tr>
            <th width="160">返利时间</th>
            <th>
                <input name="begin_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $begin_time;?>">
                <input name="end_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $end_time;?>">
            </th>

            <th width="160">产生的商品名称/ID</th>
            <th>
                <input type="text" class="cssInput" name="coupon_name" value="<?php echo $coupon_name;?>">
            </th>
        </tr>

        <tr>
            <th width="160">用户查找</th>
            <th>
                <input type="text" class="cssInput" name="user" value="<?php echo $user;?>">
            </th>
            <th width="160">编辑查找</th>
            <th>
                <input type="text" class="cssInput" name="editor" value="<?php echo $editor;?>">
            </th>
        </tr>

        <tr>
            <th width="160">返利方式</th>
            <th>
                <select name="gettype" id="select">
                    <option value="0" <?php echo ($gettype == 0) ? 'selected' : '';?>>全部</option>
                    <?php foreach($back_type as $k => $q): ?>
                        <option value="<?php echo $k; ?>" <?php echo ($gettype == $k) ? 'selected' : '';?>><?php echo $q; ?></option>
                    <?php endforeach; ?>
                </select>
            </th>

            <?php if($_COOKIE['city']==1): ?>
            <th width="160">城市</th>
            <th>
                <?php echo $filtercity; ?>
            </th>
            <?php else: ?>
            <th width="160"></th>
            <th>
            </th>
            <?php endif; ?>
        </tr>

        <tr>
            <th width="160">
                <input type="hidden" class="cssInput" name="out" id="out" value="0">
            </th>
            <th colspan="3">
                <a href="/wftadlogin/fundscheck/detail" style="background-color: green" class="ui-button">清空所有选项</a>
                <button id="tijiao" class="ui-button">提交</button>
                <button id="out-data" style="background-color: green" class="ui-button">导出</button>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">编号</th>
                <th class="size1">返利时间</th>
                <th class="size1">返利现金</th>
                <th class="size1">用户id</th>
                <th class="size1">用户名</th>
                <th class="size1">编辑账号</th>
                <th class="size1">返利类型</th>
                <th class="size1">返利原因</th>
                <th class="size1">商品名称</th>
                <th class="size1">城市</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size1">
                                <?php echo $row['id']; ?>
                        </td>
                        <td class="size1"><?php echo date('Y-m-d H:i:s',$row['dateline']); ?></td>
                        <td class="size1"><?php echo $row['flow_money']; ?></td>
                        <td class="size1"><a target="_blank" href="/wftadlogin/user/info?uid=<?php echo $row['uid']; ?>"> <?php echo $row['uid']; ?></a></td>
                        <td class="size1"><?php echo $row['username']; ?></td>
                        <td class="size1"><?php echo $row['admin_name']; ?></td>
                        <td class="size1"><?php echo $row['back_type']; ?></td>
                        <td class="size1"><?php echo $row['description']; ?></td>
                        <td class="size1"><a href='/wftadlogin/good/new?type=basis&gid=<?php echo $row['coupon_id']; ?>'><?php echo $row['coupon_name']; ?></a></td>
                        <td class="size1"><?php echo $citys[$row['city']]; ?></td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无标签 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    $(function () {
        $('#out-data').click(function () {
            $('#out').val(1);
        })

        $('#tijiao').click(function () {
            $('#out').val(0);
        })
    })
</script>