<hgroup class="box">
    <header>
        <h3>推广经费  管理</h3>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<hgroup class="box">
    <header>
        <h3>返现</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/fundscheck/rebate">返现管理</a>
    </header>
</hgroup>


<hgroup class="box">
    <header>
        <h3>现金券</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/fundscheck/cash">现金券管理</a>
    </header>
</hgroup>


