<hgroup class="box">
    <header>
        <h3>推广经费  管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/fundscheck">返回</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/fundscheck/rebate">返现列表</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/fundscheck/detail">返现详情列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

    $goods = null;
    $user = null;
    $status = null;

    if (isset($_GET['goods']) && $_GET['goods']) {
        $goods = $_GET['goods'];
    }

    if (isset($_GET['user']) && $_GET['user']) {
        $user = $_GET['user'];
    }

    if (isset($_GET['status']) && $_GET['status']) {
        $status = $_GET['status'];
    }

    ?>
    <table class="table">
        <tr>
            <th width="160">返利商品/ID</th>
            <th colspan="3">
                <input type="text" class="cssInput" name="goods" placeholder="商品名/ID" value="<?php echo $goods;?>">
            </th>
            <th width="160">用户名/ID</th>
            <th colspan="3">
                <input type="text" class="cssInput" name="user" placeholder="用户名/ID" value="<?php echo $user;?>">
            </th>
        </tr>

        <tr>
            <th width="160">申请状态</th>
            <th colspan="3">
                <select name="status">
                    <option value="">请选择</option>
                    <option value="1" <?php echo ($status == 1) ? 'selected' : '';?>>未审核</option>
                    <option value="2" <?php echo ($status == 2) ? 'selected' : '';?>>已审核</option>
                </select>
            </th>
            <th width="160"></th>
            <th colspan="3">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/fundscheck/rebate" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
            </th>
            <th width="160"></th>
            <th colspan="3">
            </th>
        </tr>
    </table>
</form>

<div class="panel panel panel-primary">
    <div class="panel-heading">返现列表</div>
    <div class="panel-body">

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">id</th>
                <th scope="col">提交时间</th>
                <th scope="col">城市&nbsp;&nbsp;<?php echo $filtercity; ?></th>
                <th scope="col">单份金额</th>
                <th scope="col">份数</th>
                <th scope="col">申请金额</th>
                <th scope="col">经办人</th>
                <th scope="col">返利商品</th>
                <th scope="col">用户ID</th>
                <th scope="col">返利原因</th>
                <th scope="col">状态</th>
                <th scope="col">操作</th>
            </tr>
            <?php foreach ($data as $v): ?>
                <tr>
                    <td><?php echo $v['id']; ?></td>
                    <td><?php echo date('Y-m-d H:i:s', $v['create_time']); ?></td>
                    <td><?php echo $city[$v['city']]; ?></td>
                    <td><?php echo $v['single_rebate']; ?></td>
                    <td><?php echo $v['total_num']; ?></td>
                    <td><?php echo $v['total_num'] * $v['single_rebate']; ?></td>
                    <td><?php echo $v['editor']; ?></td>
                    <td><?php echo is_numeric($v['gid'])?$v['gid']:0; ?></td>
                    <td><?php echo $v['uid']; ?></td>
                    <td><?php echo $v['get_info']?:'商品后台设置'; ?></td>

                    <td>
                        <?php
                            if ($v['status'] == 0) {
                                echo '已删除';
                            } elseif ($v['status'] == 1) {
                                echo '待审批';
                            } elseif ($v['status'] == 2) {
                                echo '已审批';
                            }
                        ?>
                    </td>

                    <td>
                        <?php if($v['status'] == 1):?>
                            <?php if($v['from_type'] == 1):?>
                            <a class="ui-button" href="/wftadlogin/welfare/checkRebate?id=<?php echo $v['id']; ?>">通过审核</a>
                                <?php else: ?>
                            <a class="ui-button" href="/wftadlogin/welfare/checkRebate?id=<?php echo $v['id']; ?>">通过审核</a>
                                <?php endif; ?>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>

        </table>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>


