<hgroup class="box">
    <header>
        <h3>流水 余额  管理</h3>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<hgroup class="box">
    <header>
        <h3>流水</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/account/record">流水管理</a>
    </header>
</hgroup>


<hgroup class="box">
    <header>
        <h3>余额</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/account/balance">余额管理</a>
    </header>
</hgroup>


