<hgroup class="box">
    <header>
        <h3>财务管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/account/record" id="menu">账户交易流水</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<hgroup class="box">
    <header>
         <mark>账户交易流水</mark> 账户总金额 <?php echo $account['all']; ?>   可提现金额  <?php echo $account['yes']; ?> 不可提现金额  <?php echo $account['no']; ?>
    </header>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

        $username = null;
        $uid = null;
        $time_start = null;
        $time_end = null;
        $check = 0;
        $trade_no = null;
        $order_id = null;
        $action_type = 0;

        if (isset($_GET['username']) && $_GET['username']) {
            $username = $_GET['username'];
        }

        if (isset($_GET['uid']) && $_GET['uid']) {
            $uid = $_GET['uid'];
        }

        if (isset($_GET['time_start']) && $_GET['time_start']) {
            $time_start = $_GET['time_start'];
        }

        if (isset($_GET['time_end']) && $_GET['time_end']) {
            $time_end = $_GET['time_end'];
        }

        if (isset($_GET['check']) && $_GET['check']) {
            $check = $_GET['check'];
        }

        if (isset($_GET['trade_no']) && $_GET['trade_no']) {
            $trade_no = $_GET['trade_no'];
        }

        if (isset($_GET['order_id']) && $_GET['order_id']) {
            $order_id = $_GET['order_id'];
        }

        if (isset($_GET['action_type']) && $_GET['action_type']) {
            $action_type = $_GET['action_type'];
        }

    ?>

    <table class="table">
        <tr>
            <th width="160">用户名</th>
            <th>
                <input type="text" class="cssInput" name="username" value="<?php echo $username;?>">
            </th>
            <th width="160">交易日期</th>
            <th>
                <input name="time_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $time_start;?>">
                <input name="time_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $time_end;?>">
            </th>
        </tr>

        <tr>
            <th width="160">用户uid</th>
            <th colspan="3">
                <input type="text" class="cssInput" name="uid" value="<?php echo $uid;?>">
            </th>
        </tr>


        <tr>
            <th width="160">交易号</th>
            <th>
                <input type="text" class="cssInput" name="trade_no" value="<?php echo $trade_no;?>">
            </th>
            <th width="160">类型</th>
            <th>
                <select name="action_type">
                    <option value="0" <?php echo ($action_type == 0) ? 'selected' : '';?>>全部</option>
                    <?php foreach($recodeType as $key => $value):?>
                    <option value="<?php echo $key;?>" <?php echo ($action_type == $key) ? 'selected' : '';?>><?php echo $value;?></option>
                    <?php endforeach;?>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">订单号</th>
            <th>
                <input type="text" class="cssInput" name="order_id" value="<?php echo $order_id;?>">
            </th>
            <th width="160"> </th>
            <th>

            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/account/record" style="background-color: green" class="ui-button">清空</a>
                <button  class="ui-button">提交</button>
                <input type="hidden" name="type" value="record">
                <a href="javascript:void(0)" data-src="/wftadlogin/account/outData" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>



<div class="panel panel panel-primary">
    <div class="panel-heading">用户流水列表</div>
    <div class="panel-body">

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">用户uid</th>
                <th scope="col">用户名</th>
                <th scope="col">交易时间</th>
                <th scope="col">类型</th>
                <th scope="col">交易号</th>
                <th scope="col">订单号</th>
                <th scope="col">交易金额</th>
               <!-- <th scope="col">商家可提现金额</th>-->
                <th scope="col">交易账号</th>
                <th scope="col">交易渠道</th>
                <th scope="col">账户余额</th>
                <th scope="col">事项</th>
                <th scope="col">充值是否审核</th>
                <th scope="col">商家id</th>
            </tr>
            <?php foreach ($this->data as $v): ?>
                <tr>
                    <td><?php echo $v['uid']; ?></td>
                    <td><?php echo $v['username']; ?></td>
                    <td><?php echo date('Y-m-d H:i:s', $v['dateline']); ?></td>
                    <td>
                        <?php
                            if ($v['action_type'] == 2) {
                                if ($v['action_type_id'] == 1) {
                                    echo '消费';
                                } elseif ($v['action_type_id'] == 2) {
                                    echo '原路返回退款';
                                } elseif ($v['action_type_id'] == 3) {
                                    echo '提现';
                                } elseif ($v['action_type_id'] == 4) {
                                    echo '提现';
                                }
                            } elseif ($v['action_type'] == 1) {
                                if ($v['action_type_id'] == 1 || $v['action_type_id'] == 18) {
                                    echo '退还到余额';
                                } elseif (in_array($v['action_type_id'], array(2, 3, 12, 17, 25))) {
                                    echo '充值';
                                } elseif (in_array($v['action_type_id'], array(4, 5, 6, 7, 8, 9, 10, 11,14, 15, 16, 19, 20, 21, 26, 99))) {
                                    echo '奖励';
                                }
                            }
                        ?>
                    </td>
                    <td><?php echo $v['trade_no']; ?></td>
                    <td>
                        <?php if (($v['action_type'] == 2 && in_array($v['action_type_id'], array(1, 2))) || ($v['action_type'] == 1 && in_array($v['action_type_id'], array(1, 18)))):?>
                            <?php if($v['order_type'] == 2):?>
                                <a href="/wftadlogin/order/info?order_sn=<?php echo $v['object_id']; ?>"><?php echo $v['object_id']; ?></a>
                            <?php elseif($v['order_type'] == 3):?>
                                <a href="/wftadlogin/excercise/orderinfo?order_sn=<?php echo $v['object_id']; ?>"><?php echo $v['object_id']; ?></a>
                            <?php else:?>
                                <?php echo $v['object_id']; ?>
                            <?php endif;?>
                        <?php else:?>
                            <?php echo $v['object_id']; ?>
                        <?php endif;?>

                    </td>
                    <td>
                        <?php if($v['action_type'] == 1):?>
                            <mark>+<?php echo $v['flow_money']; ?></mark>
                            <?php else:?>
                            <mark>-<?php echo $v['flow_money']; ?></mark>
                        <?php endif;?>
                    </td>
                <!--    <td><?php /*echo $v['organizer_get']; */?></td>-->
                    <td><?php echo $v['user_account']; ?></td>
                    <td><?php echo $v['account_type']; ?></td>
                    <td><?php echo $v['surplus_money']; ?></td>
                    <td><?php echo $v['description']; ?></td>
                    <td><?php echo ($v['action_type'] == 1 && in_array($v['action_type_id'], array(2, 3, 12, 17, 25))) ? (($v['check_status']) ? '已审核' : '未审核') : ''; ?></td>
                    <td><a href="/wftadlogin/organizerrecord/record?organizer_id=<?php echo $v['shop_id'];?>"><?php echo $v['shop_id']; ?></a></td>
                </tr>
            <?php endforeach; ?>

        </table>

        <hgroup class="box">
            <header>
                 搜索结果 <?php echo $end['count']; ?>   入账  <?php echo $end['in']; ?> 出账  <?php echo $end['out']; ?>
            </header>
        </hgroup>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>

<script>
    $(function () {
        //导出订单
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });
    });
</script>


