<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge,chrome=1">
    <meta http-equiv=”Cache-Control” content=”no-siteapp” />
    <meta name="apple-mobile-web-app-capable" content="yes" >
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <title>搜索</title>
    <link href="/css/wap/common.css" rel="stylesheet"/>
    <link href="/css/wap/index.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/css/wap/custom.css">
    <link rel="stylesheet" href="/css/wap/iosOverlay.css">
    <script>(function(){var w=window.screen.width,s=w/640,u=navigator.userAgent,m='<meta name="viewport" content="width=640,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
    <style>
        .item{
            width:100%;
        }
        .intro{
            height: 60px; overflow:hidden; white-space: normal; text-overflow:ellipsis;width:100%
        }
    </style>
</head>
<body>
<main class="align" id="content"></main>
<script id="test" type="text/html">
    <section class="wrapper">
        <form class="search-form" method="get" action="#" id="form">
            <header>
                <div class="head_cnt">
                    <i class="icon"></i>
                    <input type="text" name="keyword" class="search" id="key" placeholder="请输入相关票券活动名称" autocomplete="off"/>
                    <input type="hidden" name="city" id="city" value="<?php echo $city;?>">
                    <input type="reset" value="×" />
                    <input type="submit" value="搜索" id="sub"/>
                </div>
            </header>
{{include 'list'}}
</script>
<script id="list" type="text/html">
    <div class="inner">
        <div class="lists">
            {{if response_params[0]}}
            {{each response_params}}
            <div class="search-main">
                <div class="search-head">
                    <a class="img" href="/web/place/index?id={{$value.id}}" title="">
                        {{if $value.ticket_num>0}}
                        <i class="tips">有票</i>
                        {{else}}
                        <i class="tips" style="background:#ccc">售罄</i>
                        {{/if}}
                        <img src="{{$value.cover}}"/>
                    </a>
                    <div class="info">
                        <a class="shopname" href="/web/place/index?id={{$value.id}}" title="">{{$value.title}}</a>
                        <div class="intro"><a class="title" href="/web/place/index?id={{$value.id}}">{{$value.editor_word}}</a></div>
                        <aside class="aside">
                            {{if $value.prise}}
                            {{each $value.prise}}
                                <span class="sale">
                                    {{$value}}
                                </span>
                            {{/each}}
                            {{/if}}
                            <div class="distance"><i class="icon"></i>{{$value.circle}}</div>
                        </aside>
                    </div>
                </div>
                {{if $value.ticket_num>0}}
                <div class="search-list">
                    <div class="arrow-up"></div>
                    {{each $value.ticket_list}}
                    <a href="{{if $value.type==1}}/web/organizer/shops?id={{$value.id}}{{else}}/web/kidsplay/info?id={{$value.id}}{{/if}}" title="" class="item">
                        <i class="icon"></i>
                        <span class="title">{{$value.ticket_name}}</span>
                        <div class="price">
                            <span class="symbol">¥</span>
                            <span class="num"><mark>{{$value.price}}</mark>起</span>
                            <i class="arrowent"></i>
                        </div>
                    </a>
                    {{/each}}
                    <a title="" class="item more">
                        查看全部{{$value.ticket_num}}个热卖票券
                    </a>
                </div>
                {{/if}}
            </div>
            {{/each}}
            {{else}}
            <div class="nodata"><img src="/images/wap/images/nodata.gif" /></div>
            {{/if}}
        </div>
    </div>
</script>
<script id="more" type="text/html">
    {{each response_params}}
    <div class="search-main">
        <div class="search-head">
            <a class="img" href="/web/place/index?id={{$value.id}}" title="">
                {{if $value.ticket_num>0}}
                <i class="tips">有票</i>
                {{else}}
                <i class="tips" style="background:#ccc">售罄</i>
                {{/if}}
                <img src="{{$value.cover}}"/>
            </a>
            <div class="info">
                <a class="shopname" href="/web/place/index?id={{$value.id}}" title="">{{$value.title}}</a>
                <a class="title" href="/web/place/index?id={{$value.id}}">{{$value.editor_word}}</a>
                <aside class="aside">
                    {{if $value.prise}}
                    {{each $value.prise}}
                                <span class="sale">
                                    {{$value}}
                                </span>
                    {{/each}}
                    {{/if}}
                    <div class="distance"><i class="icon"></i>{{$value.circle}}</div>
                </aside>
            </div>
        </div>
        {{if $value.ticket_num>0}}
        <div class="search-list">
            <div class="arrow-up"></div>
            {{each $value.ticket_list}}
            <a href="{{if $value.type==1}}/web/organizer/shops?id={{$value.id}}{{else}}/web/kidsplay/info?id={{$value.id}}{{/if}}" title="" class="item">
                <i class="icon"></i>
                <span class="title">{{$value.ticket_name}}</span>
                <div class="price">
                    <span class="symbol">¥</span>
                    <span class="num"><mark>{{$value.price}}</mark>起</span>
                    <i class="arrowent"></i>
                </div>
            </a>
            {{/each}}
            <a title="" class="item more">
                查看全部{{$value.ticket_num}}个热卖票券
            </a>
        </div>
        {{/if}}
    </div>
    {{/each}}
</script>
</form>
</section>
<a class="toTop toTop01" id="toTop" href="javascript:;"><i class="icon"></i>顶部</a>
</body>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/web.js"></script>
<script type="text/javascript" src="/js/dropload.min.js"></script>
<script src="/js/wap/plugin/custom.js"></script>
<script src="/js/wap/plugin/iosOverlay.js"></script>
<script src="/js/wap/plugin/spin.min.js"></script>
<script src="/js/wap/plugin/prettify.js"></script>
<script src="/js/wap/template.js"></script>
<script>
    $(function(){
        function GetQueryString(name)
        {
            var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
            var r = window.location.search.substr(1).match(reg);
            if(r!=null)return decodeURI(r[2]); return null;
        }

        var word = GetQueryString("keyword");
        var city = '<?php echo $city;?>';
        loading();
        $.ajax({
            type:'POST',
            url:"/search/index/newsearch",
            dataType:'json',
            async: true,
            data:{'uid':<?php echo $_COOKIE['uid'] ? $_COOKIE['uid'] : 0;?>,'word':word},
            headers: {
                "VER": 10,
                "CITY":encodeURI(city)
            },
            success: function (result) {
                if (result.response_params.status == 0) {
                    //alert(result.response_params.message);
                } else {
                    //todo 成功
                    //window.location.href = "";
                    //console.log(result.response_params);
                    var html = template('test', result);
                    document.getElementById('content').innerHTML = html;
                    $("#sub").click(function(){
                        $("#form").attr('/web/search/info').submit();
                    });

                    //加载更多
                    var counter = 1;
                    // dropload
                    var dropload = $('.inner').dropload({
                        scrollArea : window,
                        domDown : {
                            domClass   : 'dropload-down',
                            domRefresh : '<div class="dropload-refresh" style="height:50px;text-align: center;margin-bottom: 25px;">↑上拉加载更多</div>',
                            domLoad    : '<div class="dropload-load" style="height:50px;line-height: 50px;text-align: center;margin-bottom: 30px;"><span class="loading"></span>加载中...</div>',
                            domNoData  : '<div class="dropload-noData" style="height:20px;text-align: center;margin-bottom: 15px;">暂无数据</div>'
                        },
                        loadDownFn : function(me){
                            counter++;
                            $.ajax({
                                type: "POST",
                                url:"/search/index/newsearch",
                                dataType: 'json',
                                async: true,
                                data:{'uid':<?php echo $_COOKIE['uid'] ? $_COOKIE['uid'] : 0;?>,'word':word,'page':counter},
                                headers: {
                                    "VER": 10,
                                    "CITY":encodeURI(city)
                                },
                                success: function(data){
                                    if(data.response_params){
                                        var len= data.response_params.length;
                                        // 为了测试，延迟1秒加载

                                        $('.lists').append(template('more', data));
                                        // 每次数据加载完，必须重置
                                        me.resetload();


                                        if(len==0){
                                            // 锁定
                                            me.lock();
                                            // 无数据
                                            me.noData();
                                            return;
                                        }
                                    }
                                },
                                error: function(XMLHttpRequest, textStatus, errorThrown){
//                                    alert('Ajax error!');
                                    // 即使加载出错，也得重置
                                    me.resetload();
                                }
                            });
                        }
                    });
                }
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                if (XMLHttpRequest.status == 401) {
                    //todo 跳转授权页面
                    //alert(XMLHttpRequest.responseJSON.message);
                    window.location.href = '<?php echo $authorUrl;?>';
                }
                else if (XMLHttpRequest.status == 403) {
                    window.location.href = '<?php echo $authorUrl;?>';
//                    alert('接口验证失败，非法访问');
                }

                else if (XMLHttpRequest.status == 400) {
//                            window.location.href = '<?php //echo $authorUrl;?>//';
                    alert('请求参数错误:' + XMLHttpRequest.error_msg);
                }
                else {
                    alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                }

            }
        })
    })
</script>
</html>