<hgroup class="box">
    <header>
        <h3>渠道统计</h3>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>


    <table class="table">
        <tr>

            <th width="160">筛选条件</th>
            <th>
                <input name="sign_start" id="sign_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $sign_start?:0;?>">
                <input name="sign_end" id="sign_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $sign_end?:0;?>">
            </th>
        </tr>


        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/h5statistics/index" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <div>
                    <a class="ui-button" id="outPutExcel">导出统计Excel表格</a>
                </div>

            </th>
        </tr>
    </table>
</form>



<div class="panel panel panel-primary">
    <div class="panel-heading">统计(会员采用就近充值匹配)</div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <tr>
<!--                <th scope="col">渠道号</th>-->
                <th scope="col">渠道名称</th>
                <th scope="col">充值数量</th>
                <th scope="col">充值总金额</th>
                <th scope="col">688元</th>
                <th scope="col">988元</th>
                <th scope="col">1688元</th>
            </tr>
            <?php foreach ($this->data as $v): ?>
                <tr>
                    <td><?php echo $v['channel']; ?></td>
                    <td><?php echo (int)$v['count']; ?></td>
                    <td> <?php echo $v['all_money']; ?></td>
                    <td><?php echo $v['all_688']; ?></td>
                    <td><?php echo $v['all_988']; ?></td>
                    <td><?php echo $v['all_1688']; ?></td>
                </tr>
            <?php endforeach; ?>

        </table>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>

<script>
    $(document).on("click", "#outPutExcel", function() {
        var sign_start = $('#sign_start').val();
        var sign_end = $('#sign_end').val();
        window.location.href="/wftadlogin/h5statistics/index?out=1&sign_start=" + sign_start + "&sign_end=" + sign_end;
    });
</script>




