<hgroup class="box">
    <header>
        <h3>VIP会员充值统计</h3>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
        $param_device_type      = 0;
        $param_action_type      = 0;
        $param_from_uid_type    = 0;
        $param_from_uid         = null;
        $param_money_service_id = 0;
        $param_start_time       = null;
        $param_end_time         = null;

        if (isset($_GET['device_type']) && $_GET['device_type']) {
            $param_device_type = $_GET['device_type'];
        }

        if (isset($_GET['action_type']) && $_GET['action_type']) {
            $param_action_type = $_GET['action_type'];
        }

        if (isset($_GET['from_uid_type']) && $_GET['from_uid_type']) {
            $param_from_uid_type = $_GET['from_uid_type'];
        }

        if (isset($_GET['from_uid']) && $_GET['from_uid']) {
            $param_from_uid = $_GET['from_uid'];
        }

        if (isset($_GET['money_service_id']) && $_GET['money_service_id']) {
            $param_money_service_id = $_GET['money_service_id'];
        }

        if (isset($_GET['start_time']) && $_GET['start_time']) {
            $param_start_time = $_GET['start_time'];
        }

        if (isset($_GET['end_time']) && $_GET['end_time']) {
            $param_end_time = $_GET['end_time'];
        }
    ?>

    <table class="table">
        <tr>
            <th width="130">充值设备</th>
            <th>
                <select name="device_type" id="device_type" class="cssInput" style="width:190px"  value="<?php echo $param_device_type;?>">
                    <option value="0" <?php echo ($param_device_type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($param_device_type == 1) ? 'selected' : '';?>>安卓</option>
                    <option value="2" <?php echo ($param_device_type == 2) ? 'selected' : '';?>>iOS</option>
                    <option value="3" <?php echo ($param_device_type == 3) ? 'selected' : '';?>>微信</option>
                </select>
            </th>

            <th width="130">充值方式</th>
            <th>
                <select name="action_type" id="action_type" class="cssInput" style="width:190px"  value="<?php echo $param_action_type;?>">
                    <option value="0" <?php echo ($param_action_type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($param_action_type == 1) ? 'selected' : '';?>>支付宝</option>
                    <option value="2" <?php echo ($param_action_type == 2) ? 'selected' : '';?>>银联支付</option>
                    <option value="3" <?php echo ($param_action_type == 3) ? 'selected' : '';?>>微信钱包</option>
                    <option value="4" <?php echo ($param_action_type == 4) ? 'selected' : '';?>>微信网页</option>
                </select>
            </th>

            <th width="130">充值时间</th>
            <th>
                <input name="start_time" type="date" id="start_time" class="cssInput" style="width:190px"  value="<?php echo $param_start_time;?>">
                <input name="end_time" type="date" id="end_time" class="cssInput" style="width:190px"  value="<?php echo $param_start_time;?>">
            </th>
        </tr>

        <tr>
            <th width="130">接受分享充值</th>
            <th>
                <select name="from_uid_type" id="from_uid_type" class="cssInput" style="width:190px"  value="<?php echo $param_from_uid_type;?>">
                    <option value="0" <?php echo ($param_from_uid_type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($param_from_uid_type == 1) ? 'selected' : '';?>>非分享充值</option>
                    <option value="2" <?php echo ($param_from_uid_type == 2) ? 'selected' : '';?>>接受分享充值</option>
                    <option value="3" <?php echo ($param_from_uid_type == 3) ? 'selected' : '';?>>接受指定用户的分享</option>
                </select>
                <input name="from_uid" type="text" id="from_uid" class="cssInput" style="width:190px"  value="<?php echo $param_from_uid;?>">
            </th>

            <th width="130">所充值的套餐</th>
            <th>
                <select name="money_service_id" id="money_service_id" class="cssInput" style="width:190px"  value="<?php echo $param_money_service_id;?>">
                    <option value="0" <?php echo ($param_money_service_id == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($param_money_service_id == 1) ? 'selected' : '';?>>688套餐</option>
                    <option value="2" <?php echo ($param_money_service_id == 2) ? 'selected' : '';?>>988套餐</option>
                    <option value="3" <?php echo ($param_money_service_id == 3) ? 'selected' : '';?>>1688套餐</option>
                </select>
            </th>

            <th width="130"></th>
            <th>
            </th>
        </tr>

        <tr>
            <th width="130"></th>
            <th colspan="3">
                <a href="/wftadlogin/h5statistics/membermoneyservicecount" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <div>
                    <a class="ui-button" id="outPutExcel">导出统计Excel表格</a>
                </div>
                <div>
                    <a class="ui-button" id="outPutNoMemberExcel">导出非会员用户分享统计Excel表格</a>
                </div>
            </th>
        </tr>
    </table>
</form>



<div class="panel panel panel-primary">
    <div class="panel-heading">统计(会员采用就近充值匹配)</div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">序号</th>
                <th scope="col">用户uid</th>
                <th scope="col">手机号</th>
                <th scope="col">充值时间</th>
                <th scope="col">充值金额</th>
                <th scope="col">支付方式</th>
            </tr>
            <?php foreach ($this->data as $k=>$v): ?>
                <tr>
                    <td><?php echo $k + 1; ?></td>
                    <td><?php echo $v['uid']; ?></td>
                    <td><?php echo $v['phone']; ?></td>
                    <td> <?php echo date('Y-m-d H:i:s', $v['dateline']); ?></td>
                    <td><?php echo $v['flow_money']; ?></td>
                    <td>
                        <?php
                            switch ($v['action_type_id']) {
                                case 2 :
                                    $data_pay_type = '支付宝';
                                    break;
                                case 3 :
                                    $data_pay_type = '银联支付';
                                    break;
                                case 12:
                                    $data_pay_type = '微信钱包';
                                    break;
                                case 25:
                                    $data_pay_type = '微信网页';
                                    break;
                                default:
                                    $data_pay_type = '其他方式';
                                    break;
                            }
                            echo $data_pay_type;
                        ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <div>
            <?php echo $this->data_page; ?>
        </div>

    </div>
</div>

<script>
    $(document).on("click", "#outPutExcel", function() {
        var start_time       = $('#start_time').val();
        var end_time         = $('#end_time').val();
        var action_type      = $('#action_type').val();
        var device_type      = $('#device_type').val();
        var from_uid_type    = $('#from_uid_type').val();
        var from_uid         = $('#from_uid').val();
        var money_service_id = $('#money_service_id').val();
        window.location.href="/wftadlogin/h5statistics/membermoneyservicecount?type=2" +
            "&start_time=" + start_time +
            "&end_time=" + end_time +
            "&action_type=" + action_type +
            "&device_type=" + device_type +
            "&from_uid_type=" + from_uid_type +
            "&from_uid=" + from_uid +
            "&money_service_id=" + money_service_id;
    });

    $(document).on("click", "#outPutNoMemberExcel", function() {
        var start_time       = $('#start_time').val();
        var end_time         = $('#end_time').val();
        var action_type      = $('#action_type').val();
        var device_type      = $('#device_type').val();
        var from_uid_type    = $('#from_uid_type').val();
        var from_uid         = $('#from_uid').val();
        var money_service_id = $('#money_service_id').val();
        window.location.href="/wftadlogin/h5statistics/membermoneyservicecount?type=3" +
            "&start_time=" + start_time +
            "&end_time=" + end_time +
            "&action_type=" + action_type +
            "&device_type=" + device_type +
            "&from_uid_type=" + from_uid_type +
            "&from_uid=" + from_uid +
            "&money_service_id=" + money_service_id;
    });
</script>
