<!DOCTYPE html>
<html>
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <title>分享列表</title>
    <link type="text/css" rel="stylesheet" href="/css/share/share-0526.css" />
</head>
<body class="share-list wrapper">
    <?php foreach($res as $game):?>
        <a class="space5" href="/web/organizer/game?id=<?php echo $game['id'];?>">
                <span class="portrait">
                    <img src="<?php echo $game['cover'];?>">
                </span>
            <div class="detail">
                <p class="title"><?php echo $game['title'];?></p>
                <p class="time">活动时间：<?php echo date('Y-m-d H:i', $game['time']);?></p>
                <p class="text">
                    <span class="sold">￥<?php echo $game['low_price'];?></span>
                    <span class="location"><?php echo $game['circle'];?></span>
                </p>
            </div>
        </a>
    <?php endforeach;?>
</body>
</html>