<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html id="join">
    <head lang="en">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width; initial-scale=1.0; minimum-scale=1.0; maximum-scale=1.0">
        <link type="text/css" rel="stylesheet" href="/css/share/share-1104.css">
        <title>>玩翻天_同玩_团失败了</title>
    </head>
    <body>
    <div class="wrapper rule">
        <div class="ru-top">
            <header><img src="/images/tongwan/wft.jpg" /></header>
            <article class="ru-article">
                <h1 class="ru-left">小伙伴们都不来么？<br>
                    参团失败了</h1>
                <p>3个工作日内会把团费退回到你的支付账户，记得查收</p>
            </article>
        </div>
        <div class="ru-main">
            <div class="ru-more">
                <a class="ru-link" href="javascript:void(0)" target="_blank">找到喜欢的商品</a>
                <p class="ru-arrows"></p>
                <a class="ru-link" href="javascript:void(0)" target="_blank">开团/参团</a>
                <p class="ru-arrows"></p>
                <a class="ru-link" href="javascript:void(0)" target="_blank">等待团员</a>
                <p class="ru-arrows"></p>
                <a class="ru-person"><img src="<?php  echo $img ? $img : '/images/tongwan/person.gif'; ?>"/></a>
                <br>
                <a class="ru-link" href="javascript:void(0)" target="_blank">团失败了</a>
            </div>
            <div class="ru-copyright">
                玩翻天有权关闭倒票团,开团后，用户无法主动关闭拼团团
            </div>
        </div>
    </div>
    </body>
</html>