<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html id="join">
    <head lang="en">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width; initial-scale=1.0; minimum-scale=1.0; maximum-scale=1.0">
        <link type="text/css" rel="stylesheet" href="/css/share/share-1104.css">
        <title>玩翻天_同玩_组团中</title>
    </head>
    <body>
    <div class="wrapper rule">
        <div class="ru-top">
            <header><img src="/images/tongwan/wft.jpg" /></header>
            <article class="ru-article">
                <h2><?php echo date('Y-m-d H:i:s', $end_time);?>内再集齐<?php echo $people;?>人来就能享受优惠了</h2>
                <h1>快去邀好友</h1>
                <p>开团后2小时内如果不能达到成团人数，该拼团团会自动取消，支付的团费会在3个工作日内退回到你的支付账户</p>
            </article>
        </div>
        <div class="ru-main">
            <div class="ru-more">
                <a class="ru-link" href="javascript:void(0)" target="_blank">找到喜欢的商品</a>
                <p class="ru-arrows"></p>
                <a class="ru-link" href="javascript:void(0)" target="_blank">开团/参团</a>
                <p class="ru-arrows"></p>
                <a class="ru-person"><img src="<?php  echo $img ? $img : '/images/tongwan/person.gif'; ?>"/></a>
                <p class="ru-arrows"></p>
                <a class="ru-link" href="javascript:void(0)" target="_blank">等待团员</a>
                <div class="ru-notice">
                    <span class="left"></span>
                    <span class="right"></span>
                </div>
                <div class="ru-result">
                    <a class="ru-link left" href="javascript:void(0)" target="_blank">团成功啦</a>
                    <a class="ru-link right" href="javascript:void(0)" target="_blank">团失败了</a>
                </div>
            </div>
            <div class="ru-copyright">
                玩翻天有权关闭倒票团,开团后，用户无法主动关闭拼团团
            </div>
        </div>
    </div>
    </body>

</html>