<div class="panel panel panel-primary">
    <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
        <li><a href="/wftadlogin/statistics/tjactivity">专题统计</a></li>
    </ul>
</div>
<form class="box box-form" action="/wftadlogin/statistics/tjactivity" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $begin_time = null;
    $end_time = null;
    $user = null;
    $goods = null;
    $goods_id = null;
    $city = null;

    if (isset($_GET['begin_time']) && $_GET['begin_time']) {
        $begin_time = $_GET['begin_time'];
    }

    if (isset($_GET['end_time']) && $_GET['end_time']) {
        $end_time = $_GET['end_time'];
    }

    if (isset($_GET['ac_id']) && $_GET['ac_id']) {
        $ac_id = $_GET['ac_id'];
    }

    if (isset($_GET['ac_name']) && $_GET['ac_name']) {
        $ac_name = $_GET['ac_name'];
    }

    if (isset($_GET['city']) && $_GET['city']) {
        $city = $_GET['city'];
    }

    ?>
    <table class="table">
        <!--        <tr>-->
        <!--            <th width="160">咨询时间</th>-->
        <!--            <th>-->
        <!--                <input name="begin_time" type="date" class="cssInput" style="width:190px"  value="--><?php //echo $begin_time;?><!--">-->
        <!--                <input name="end_time" type="date" class="cssInput" style="width:190px"  value="--><?php //echo $end_time;?><!--">-->
        <!--            </th>-->
        <!--            <th width="160"></th>-->
        <!--            <th>-->
        <!--            </th>-->
        <!--        </tr>-->

        <tr>
            <th width="160">专题ID</th>
            <th>
                <input type="text" class="cssInput" name="ac_id" value="<?php echo $ac_id;?>">
            </th>
            <th width="160">专题名称</th>
            <th>
                <input type="text" class="cssInput" name="ac_name" value="<?php echo $ac_name;?>">
            </th>
        </tr>
        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/statistics/tjactivity" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>
<div class="box">
    <div class="box-title">
        统计列表
        <div style="float:right;margin-right:30px">
            <!--            <form action="#" method="get">-->
            <!--                <input type="text" class="cssInput"  style="margin-top: 5px;width:200px" placeholder="搜索发言" name="k" value="">-->
            <!--                <input type="hidden" name="id" value="--><?php //echo $circle ? $circle['_id'] : '';?><!--">-->
            <!--                <button class="btn btn-default" type="submit">搜索</button>-->
            <!--            </form>-->
        </div>
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">专题ID</th>
                <th width="200">专题名称</th>
                <th width="100">商品状态</th>
                <th width="100">专题类别</th>
                <th width="100">展示类型</th>
                <th width="100">关联商品</th>
                <th width="100">关联游玩地</th>
                <th width="100">关联活动</th>
                <th width="100">安卓浏览数</th>
                <th width="100">IOS浏览数</th>
                <th width="100">网页浏览数</th>
                <th width="100">分享数</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $row){ ?>
                    <tr style="text-align: left">
                        <td  width="50"><?php echo $row['_id']; ?></td>
                        <td  width="200"><?php echo $row['ac_name']; ?></td>
                        <td  width="100">
                            <?php
                            if ($row['status'] == -1) {
                                echo '下架';
                            } elseif ($row['s_time'] == 0) {
                                echo '正在进行.长';
                            } elseif ($row['s_time'] > time()) {
                                echo '未开始';
                            } elseif ($row['e_time'] < time()) {
                                echo '已过期';
                            } else {
                                echo '正在进行';
                            }
                            ?>
                        </td>
                        <td  width="100"><?php echo $type[$row['ac_type']]; ?></td>
                        <td  width="100"><?php echo $viewtype[$row['view_type']]; ?></td>
                        <td  width="100"><?php echo $row['linkg']; ?></td>
                        <td  width="100"><?php echo $row['linkp']; ?></td>
                        <td  width="100"><?php echo $row['linke']; ?></td>
                        <td  width="100"><?php echo $row['android_view']; ?></td>
                        <td  width="100"><?php echo $row['ios_view']; ?></td>
                        <td  width="100"><?php echo $row['wx_view']; ?></td>
                        <td  width="100"><?php echo $row['share']; ?></td>
                    </tr>
                <?php } ?>
            <?php else: ?>
                <tr>
                    <td colspan="11"><p>暂无数据</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pagedata; ?>
        </footer>
    </div>
</div>

