<div class="panel panel panel-primary">
    <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
        <li><a href="/wftadlogin/statistics/tjgoods">商品统计</a></li>
    </ul>
</div>
<form class="box box-form" action="/wftadlogin/statistics/tjgoods" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $begin_time = null;
    $end_time = null;
    $user = null;
    $goods = null;
    $goods_id = null;
    $type = null;
    $city = null;

    if (isset($_GET['begin_time']) && $_GET['begin_time']) {
        $begin_time = $_GET['begin_time'];
    }

    if (isset($_GET['end_time']) && $_GET['end_time']) {
        $end_time = $_GET['end_time'];
    }

    if (isset($_GET['goods_id']) && $_GET['goods_id']) {
        $goods_id = $_GET['goods_id'];
    }

    if (isset($_GET['goods']) && $_GET['goods']) {
        $goods = $_GET['goods'];
    }

    if (isset($_GET['type']) && $_GET['type']) {
        $type = $_GET['type'];
    }

    if (isset($_GET['city']) && $_GET['city']) {
        $city = $_GET['city'];
    }

    ?>
    <table class="table">
<!--        <tr>-->
<!--            <th width="160">咨询时间</th>-->
<!--            <th>-->
<!--                <input name="begin_time" type="date" class="cssInput" style="width:190px"  value="--><?php //echo $begin_time;?><!--">-->
<!--                <input name="end_time" type="date" class="cssInput" style="width:190px"  value="--><?php //echo $end_time;?><!--">-->
<!--            </th>-->
<!--            <th width="160"></th>-->
<!--            <th>-->
<!--            </th>-->
<!--        </tr>-->

        <tr>
            <th width="160">商品ID</th>
            <th>
                <input type="text" class="cssInput" name="goods_id" value="<?php echo $goods_id;?>">
            </th>
            <th width="160">商品名称</th>
            <th>
                <input type="text" class="cssInput" name="goods" value="<?php echo $goods;?>">
            </th>
        </tr>

        <!--
        <tr>
            <th width="160">回复状态</th>
            <th>
                <select name="type">
                    <option value="0" <?php echo ($type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($type == 1) ? 'selected' : '';?>>已回复</option>
                    <option value="2" <?php echo ($type == 2) ? 'selected' : '';?>>未回复</option>
                </select>
            </th>
            <th width="160"></th>
            <th>
            </th>
        </tr>
        -->

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/consult" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>
<div class="box">
    <div class="box-title">
        统计列表
        <div style="float:right;margin-right:30px">
<!--            <form action="#" method="get">-->
<!--                <input type="text" class="cssInput"  style="margin-top: 5px;width:200px" placeholder="搜索发言" name="k" value="">-->
<!--                <input type="hidden" name="id" value="--><?php //echo $circle ? $circle['_id'] : '';?><!--">-->
<!--                <button class="btn btn-default" type="submit">搜索</button>-->
<!--            </form>-->
        </div>
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">商品ID</th>
                <th width="200">商品名称</th>
                <th width="100">安卓浏览数</th>
                <th width="120">IOS浏览数</th>
                <th width="100">网页浏览数</th>
<!--                <th width="100">分享链接浏览数</th>-->
                <th width="100">安卓下单量</th>
                <th width="100">IOS下单量</th>
                <th width="100">网页下单量</th>
<!--                <th width="100">分享链接下单量</th>-->
                <th width="100">外链接下单量</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $row){ ?>
                    <tr style="text-align: left">
                        <td  width="50"><?php echo $row['_id']; ?></td>
                        <td  width="200"><?php echo $row['title']; ?></td>
                        <td  width="100"><?php echo $row['android_view']; ?></td>
                        <td  width="100"><?php echo $row['ios_view']; ?></td>
                        <td  width="100"><?php echo $row['wx_view']; ?></td>
<!--                        <td  width="100">--><?php //echo $row['share_order']; ?><!--</td>-->
                        <td  width="100"><?php echo $row['android_order']; ?></td>
                        <td  width="100"><?php echo $row['ios_order']; ?></td>
                        <td  width="100"><?php echo $row['wx_order']; ?></td>
                        <td  width="100"><?php echo $row['share_order']; ?></td>
                    </tr>
                <?php } ?>
            <?php else: ?>
                <tr>
                    <td colspan="11"><p>暂无数据</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pagedata; ?>
        </footer>
    </div>
</div>


