<div class="panel panel panel-primary">
    <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
        <li><a href="/wftadlogin/statistics/tjplace">游玩地统计</a></li>
    </ul>
</div>
<form class="box box-form" action="/wftadlogin/statistics/tjplace" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $begin_time = null;
    $end_time = null;
    $user = null;
    $goods = null;
    $goods_id = null;
    $type = null;
    $city = null;

    if (isset($_GET['begin_time']) && $_GET['begin_time']) {
        $begin_time = $_GET['begin_time'];
    }

    if (isset($_GET['end_time']) && $_GET['end_time']) {
        $end_time = $_GET['end_time'];
    }

    if (isset($_GET['title']) && $_GET['title']) {
        $title = $_GET['title'];
    }

    if (isset($_GET['id']) && $_GET['id']) {
        $id = $_GET['id'];
    }

    if (isset($_GET['type']) && $_GET['type']) {
        $type = $_GET['type'];
    }

    if (isset($_GET['city']) && $_GET['city']) {
        $city = $_GET['city'];
    }

    ?>
    <table class="table">
        <!--        <tr>-->
        <!--            <th width="160">咨询时间</th>-->
        <!--            <th>-->
        <!--                <input name="begin_time" type="date" class="cssInput" style="width:190px"  value="--><?php //echo $begin_time;?><!--">-->
        <!--                <input name="end_time" type="date" class="cssInput" style="width:190px"  value="--><?php //echo $end_time;?><!--">-->
        <!--            </th>-->
        <!--            <th width="160"></th>-->
        <!--            <th>-->
        <!--            </th>-->
        <!--        </tr>-->

        <tr>
            <th width="160">游玩地ID</th>
            <th>
                <input type="text" class="cssInput" name="id" value="<?php echo $id;?>">
            </th>
            <th width="160">游玩地名称</th>
            <th>
                <input type="text" class="cssInput" name="title" value="<?php echo $title;?>">
            </th>
        </tr>


        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/statistics/tjplace" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>
<div class="box">
    <div class="box-title">
        统计列表
        <div style="float:right;margin-right:30px">
            <!--            <form action="#" method="get">-->
            <!--                <input type="text" class="cssInput"  style="margin-top: 5px;width:200px" placeholder="搜索发言" name="k" value="">-->
            <!--                <input type="hidden" name="id" value="--><?php //echo $circle ? $circle['_id'] : '';?><!--">-->
            <!--                <button class="btn btn-default" type="submit">搜索</button>-->
            <!--            </form>-->
        </div>
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">游玩地ID</th>
                <th width="200">游玩地名称</th>
                <th width="200">商品数</th>
                <th width="200">所属地</th>
                <th width="200">评论</th>
                <th width="200">分享数</th>
                <th width="200">整体评分</th>
                <th width="100">安卓浏览数</th>
                <th width="120">IOS浏览数</th>
                <th width="100">网页浏览数</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $row){ ?>
                    <tr style="text-align: left">
                        <td  width="50"><?php echo $row['_id']; ?></td>
                        <td  width="200"><?php echo $row['shop_name']; ?></td>
                        <td  width="200"><?php echo $row['good_num']?:0; ?></td>
                        <td  width="200"><?php echo $row['circle']; ?></td>
                        <td  width="200"><?php echo $row['post_number']?:0; ?></td>
                        <td  width="200"><?php echo $row['share']?:0; ?></td>
                        <td  width="200"><?php echo $row['star_num']; ?></td>
                        <td  width="100"><?php echo $row['android_view']; ?></td>
                        <td  width="100"><?php echo $row['ios_view']; ?></td>
                        <td  width="100"><?php echo $row['wx_view']; ?></td>
                    </tr>
                <?php } ?>
            <?php else: ?>
                <tr>
                    <td colspan="11"><p>暂无数据</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pagedata; ?>
        </footer>
    </div>
</div>


