<hgroup class="box">
    <header>
        <h3>结算明细</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/business/takeCrashList">返回转账审批列表</a>
    </header>
</hgroup>

<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

        $good_name = null;
        $good_id = null;
        $order_id = null;
        $id = null;
        $trade_way = 0;
        $organizer_name = null;
        $organizer_id = 78;

        if (isset($_GET['good_name']) && $_GET['good_name']) {
            $good_name = $_GET['good_name'];
        }

        if (isset($_GET['good_id']) && $_GET['good_id']) {
            $good_id = $_GET['good_id'];
        }

        if (isset($_GET['order_id']) && $_GET['order_id']) {
            $order_id = $_GET['order_id'];
        }

        if (isset($_GET['id']) && $_GET['id']) {
            $id = $_GET['id'];
        }

        if (isset($_GET['trade_way']) && $_GET['trade_way']) {
            $trade_way = $_GET['trade_way'];
        }

        if (isset($_GET['organizer_name']) && $_GET['organizer_name']) {
            $organizer_name = $_GET['organizer_name'];
        } else {
            $organizer_name = $organizerData ? $organizerData->name : '';
        }

        if (isset($_GET['organizer_id']) && $_GET['organizer_id']) {
            $organizer_id = $_GET['organizer_id'];
        } else {
            $organizer_id = $organizerData ? $organizerData->id : '';
        }

    ?>

    <table class="table">
        <tr>
            <th width="160">商品名称</th>
            <th>
                <input type="text" class="cssInput" style="width:150px" name="good_name" value="<?php echo $good_name;?>">
                商品id:
                <input type="text" class="cssInput" style="width:80px" name="good_id" value="<?php echo $good_id;?>">
            </th>
            <th width="160">订单号</th>
            <th>
                <input type="text" class="cssInput" name="order_id" value="<?php echo $order_id;?>">
            </th>
        </tr>

        <tr>
            <th width="160">交易渠道</th>
            <th>
                <select name="trade_way">
                    <option value="0" <?php echo ($trade_way == 0) ? 'selected' : '';?>>交易渠道_全部</option>
                    <option value="1" <?php echo ($trade_way == 1) ? 'selected' : '';?>>交易渠道_支付宝</option>
                    <option value="2" <?php echo ($trade_way == 2) ? 'selected' : '';?>>交易渠道_银联</option>
                    <option value="3" <?php echo ($trade_way == 3) ? 'selected' : '';?>>交易渠道_新微信网页</option>
                    <option value="5" <?php echo ($trade_way == 5) ? 'selected' : '';?>>交易渠道_微信app</option>
                    <option value="4" <?php echo ($trade_way == 4) ? 'selected' : '';?>>交易渠道_旧微信网页</option>
                    <option value="6" <?php echo ($trade_way == 6) ? 'selected' : '';?>>交易渠道_用户账户</option>
                </select>
            </th>
            <th width="160">结算商家</th>
            <th>
                <input type="text" class="cssInput" style="width:150px" name="organizer_name" value="<?php echo $organizer_name;?>">
                结算商家id:
                <input type="text" class="cssInput" style="width:80px" name="organizer_id" value="<?php echo $organizer_id;?>">
                审批id:
                <input type="text" class="cssInput" style="width:80px" name="id" value="<?php echo $id;?>">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/business/auditInfo" style="background-color: green" class="ui-button">清空</a>
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/business/outAuditInfo?id=<?php echo $auditData->id;?>" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">

    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="100">交易时间</th>
                <th width="100">交易渠道</th>
                <th width="200">交易号</th>
                <th width="100">验证码</th>
                <th width="100">订单号</th>
                <th width="60">用户id</th>
                <th width="100">商品id</th>
                <th width="100">支付金额</th>
                <th width="100">现金券金额</th>
                <th width="100">已出账金额</th>
                <th width="100">结算金额</th>
            </tr>
            <?php foreach ($codeData as $key => $row): ?>
                <tr style="text-align: left">
                    <td width="100"><?php echo date('Y-m-d H:i:s',$row['dateline']); ?></td>

                    <td width="100">
                        <?php echo $tradeWay[$row['account_type']]; ?>
                    </td>
                    <td width="200">
                        <?php echo $row['trade_no']; ?>
                    </td>
                    <td width="100">
                        <?php echo $row['code_id']. $row['password']; ?>
                    </td>
                    <td width="100">
                        <?php echo (int)$row['order_sn']; ?>
                    </td>
                    <td width="60">
                        <?php echo $row['user_id']; ?>
                    </td>
                    <td width="100">
                        <?php echo $row['coupon_id']; ?>
                    </td>
                    <td width="100"><?php echo $row['real_pay'] + $row['account_money']; ?></td>
                    <td width="100"><?php echo $row['voucher']; ?></td>
                    <td width="100"><?php echo -$row['back_money'] + ($row['test_status'] == 5 ? $row['flow_money'] : 0); ?></td>
                    <td width="100"><?php echo $row['flow_money']; ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div class="box-title">
            订单个数为 <?php echo $counter['order_number']; ?>
        </div>
        <div class="box-title">
            使用码个数为 <?php echo $counter['code_number']; ?>
        </div>
        <div class="box-title">
            支付金额 <?php echo $counter['pay_money']; ?>
        </div>
        <div class="box-title">
            代金券金额 <?php echo $counter['voucher_money']; ?>
        </div>
        <div class="box-title">
            已出账金额 <?php echo $counter['back_money']; ?>
        </div>
        <div class="box-title">
            待结算金额 <?php echo $counter['need_account_money']; ?>
        </div>
        <div class="box-title">
            申请转账金额 <?php echo $counter['out_pay_money']; ?>
        </div>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    $(function () {
        //导出
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });
    });
</script>




