<hgroup class="box">
    <header>
        <h3>财务管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/business/takeCrashList">商家提现审批</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

        $organizer_name = null;
        $city = null;
        $start_time = null;
        $end_time = null;
        $transfer_start = null;
        $transfer_end = NULL;
        $crash_status = NULL;
        $audit_type = 0;

        if (isset($_GET['organizer_name']) && $_GET['organizer_name']) {
            $organizer_name = $_GET['organizer_name'];
        }

        if (isset($_GET['city']) && $_GET['city']) {
            $city = $_GET['city'];
        }

        if (isset($_GET['start_time']) && $_GET['start_time']) {
            $start_time = $_GET['start_time'];
        }

        if (isset($_GET['end_time']) && $_GET['end_time']) {
            $end_time = $_GET['end_time'];
        }

        if (isset($_GET['transfer_start']) && $_GET['transfer_start']) {
            $transfer_start = $_GET['transfer_start'];
        }

        if (isset($_GET['transfer_end']) && $_GET['transfer_end']) {
            $transfer_end = $_GET['transfer_end'];
        }

        if (isset($_GET['crash_status']) && $_GET['crash_status']) {
            $crash_status = $_GET['crash_status'];
        }

        if (isset($_GET['audit_type']) && $_GET['audit_type']) {
            $audit_type = $_GET['audit_type'];
        }

    ?>
    <table class="table">
        <tr>
            <th width="120">选择城市</th>
            <th>
                <select name="city">
                    <option value="">全部</option>
                    <?php foreach($this->city as $kr => $ty):?>
                    <option <?php echo ($kr == $city) ? 'selected' : ''; ?> value="<?php echo $kr;?>"><?php echo $ty;?></option>
                    <?php endforeach;?>
                </select>
            </th>
            <th width="120">查找商家</th>
            <th>
                <input type="text" class="cssInput" name="organizer_name" placeholder="商家id 或者 商家名称" value="<?php echo $organizer_name;?>">
            </th>
        </tr>

        <tr>
            <th width="160">申请时间</th>
            <th>
                <input name="start_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $start_time;?>">
                <input name="end_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $end_time;?>">
            </th>

            <th width="120">到账时间</th>
            <th>
                <input name="transfer_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $transfer_start;?>">
                <input name="transfer_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $transfer_end;?>">
            </th>
        </tr>

        <tr>
            <th width="160">状态</th>
            <th>
                <select name="crash_status">
                    <option value="0" <?php echo !$crash_status ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($crash_status == 1) ? 'selected' : '';?>>未审批</option>
                    <option value="2" <?php echo ($crash_status == 2) ? 'selected' : '';?>>已审批</option>
                    <option value="3" <?php echo ($crash_status == 3) ? 'selected' : '';?>>已到账</option>
                </select>
            </th>
            <th width="120">类型</th>
            <th>
                <select name="audit_type">
                    <option value="0" <?php echo !$audit_type ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($audit_type == 1) ? 'selected' : '';?>>包销预付金</option>
                    <option value="2" <?php echo ($audit_type == 2) ? 'selected' : '';?>>代销预付金</option>
                    <option value="3" <?php echo ($audit_type == 3) ? 'selected' : '';?>>商家结算</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/business/takeCrashList" style="background-color: green" class="ui-button">清空所有选项</a>
                <input name="approve_type" type="hidden" value="2">
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/business/outData" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">编号id</th>
                <th width="80">流水号</th>
                <th width="80">申请时间</th>
                <th width="80">到账时间</th>
                <th width="50">商家ID</th>
                <th width="100">商家名称</th>
                <th width="80">商家城市</th>
                <th width="100">银行账号</th>
                <th width="100">开户行</th>
                <th width="100">支行</th>
                <th width="100">开户人</th>
                <th width="100">合同编号</th>
                <th width="100">类型</th>
                <th width="80">申请转账金额</th>
                <th width="80">账户余额</th>
                <th width="150">原因</th>
                <th width="80">状态</th>
                <th width="150">操作</th>
            </tr>
            <?php foreach ($data as $key => $row): ?>
                <tr style="text-align: left">
                    <td width="50"><?php echo $row['id']; ?></td>
                    <td width="80"><?php echo $row['serial_number']; ?></td>
                    <td width="80"><?php echo date('Y-m-d H:i',$row['create_time']); ?></td>
                    <td width="80"><?php echo $row['confirm_time'] ? date('Y-m-d H:i',$row['confirm_time']) : ''; ?></td>
                    <td width="50"><?php echo $row['organizer_id'];?></td>
                    <td width="100"><?php echo $row['name'];?></td>
                    <td width="80"><?php echo $this->city[$row['city']]; ?></td>
                    <td width="100"><?php echo $row['bank_card']; ?></td>
                    <td width="100"><?php echo $row['bank_name']; ?></td>
                    <td width="100"><?php echo $row['bank_address']; ?></td>
                    <td width="100"><?php echo $row['bank_user']; ?></td>
                    <td width="100"><?php echo $row['contract_num']; ?></td>
                    <!--<td width="100"><?php /*echo $row['use_start'] ? date('Y-m-d H:i',$row['use_start']) : ''; */?></td>
                    <td width="100"><?php /*echo $row['use_end'] ? date('Y-m-d H:i',$row['use_end']) : ''; */?></td>-->
                    <td width="100">
                        <?php if ($row['audit_type'] == 1) { echo '包销预付金';} elseif ($row['audit_type'] == 2) {
                            echo '代销预付金';
                        } else {
                            echo '商家结算';
                        } ?>
                    </td>
                    <td width="80"><?php echo $row['flow_money']; ?></td>
                    <td width="80">
                        <?php
                            if ($row['audit_type'] == 3) {
                                echo $row['total_money'];
                            }
                        ?>
                    </td>
                    <td width="150"><?php echo $row['reason']; ?></td>
                    <td width="80">
                        <?php

                            if($row['check_status']==1){
                                echo '未审批';
                            }

                            if($row['check_status']==2){
                                echo '已审批';
                            }

                            if($row['check_status']==3){
                                echo '已到账';
                            }
                        ?>
                    </td>
                    <td width="150">
                        <?php if($row['check_status']==1): ?>
                            <a class="ui-button" onclick="if(confirm('审批通过?')==false)return false;" href="/wftadlogin/business/approveAudit?approve_type=1&id=<?php echo $row['id']; ?>">审批通过</a>
                        <?php endif;?>
                        <?php if($row['check_status']==2): ?>
                            <a class="ui-button" onclick="if(confirm('确认到账?')==false)return false;" href="/wftadlogin/business/adoptAudit?approve_type=1&id=<?php echo $row['id']; ?>">确认到账</a>
                        <?php endif;?>
                        <?php if($row['audit_type'] == 3):?>
                        <a class="ui-button" href="/wftadlogin/business/auditInfo?id=<?php echo $row['id'];?>">查看</a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php if($crash_status == 1):?>
            <button data-src="/wftadlogin/business/approveAudit" class="ui-button" id="all-in-charge">当前搜索条件下全部审批通过</button>
        <?php endif;?>
        <?php if($crash_status == 2):?>
            <button data-src="/wftadlogin/business/adoptAudit" class="ui-button" id="all-in-get">当前搜索条件下全部确认到账</button>
        <?php endif;?>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>

<script>
    $(function () {
        //导出提现审批
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });

        //批量操作 审批通过
        $('#all-in-charge').click(function() {
            if (confirm('前搜索条件下全部审批通过?')) {
                $('#out-data-form').attr('action', $(this).attr('data-src'));
                $('#out-data-form').submit();
                $('#out-data-form').attr('action', '');
            }
        });

        //批量操作 确认到账
        $('#all-in-get').click(function() {
            if (confirm('前搜索条件下全部确认到账?')) {
                $('#out-data-form').attr('action', $(this).attr('data-src'));
                $('#out-data-form').submit();
                $('#out-data-form').attr('action', '');
            }
        });
    });
</script>