<hgroup class="box">
    <header>
        <h3>财务</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/order/list">订单管理</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
        $good_name = null;
        $good_id = null;
        $user_name = null;
        $market_name = null;
        $user_phone = null;
        $buy_start = null;
        $buy_end = null;
        $check_start = null;
        $check_end = NULL;
        $back_start = null;
        $back_end = NULL;
        $order_status = 0;
        $check_status = 0;
        $good_status = 0;
        $trade_way = null;
        $admin_name = null;
        $order_id = null;

        if (!isset($_GET['buy_start'])) {
            $buy_start = date('Y-m-d', time() - 3*24*3600);
            $buy_end = date('Y-m-d', time());
        }

        if (isset($_GET['good_name']) && $_GET['good_name']) {
            $good_name = $_GET['good_name'];
        }

        if (isset($_GET['good_id']) && $_GET['good_id']) {
            $good_id = $_GET['good_id'];
        }

        if (isset($_GET['market_name']) && $_GET['market_name']) {
            $market_name = $_GET['market_name'];
        }

        if (isset($_GET['user_name']) && $_GET['user_name']) {
            $user_name = $_GET['user_name'];
        }

        if (isset($_GET['user_phone']) && $_GET['user_phone']) {
            $user_phone = $_GET['user_phone'];
        }

        if (isset($_GET['buy_start']) && $_GET['buy_start']) {
            $buy_start = $_GET['buy_start'];
        }

        if (isset($_GET['buy_end']) && $_GET['buy_end']) {
            $buy_end = $_GET['buy_end'];
        }

        if (isset($_GET['check_start']) && $_GET['check_start']) {
            $check_start = $_GET['check_start'];
        }

        if (isset($_GET['check_end']) && $_GET['check_end']) {
            $check_end = $_GET['check_end'];
        }

        if (isset($_GET['back_start']) && $_GET['back_start']) {
            $back_start = $_GET['back_start'];
        }

        if (isset($_GET['order_status']) && $_GET['order_status']) {
            $order_status = $_GET['order_status'];
        }

        if (isset($_GET['check_status']) && $_GET['check_status']) {
            $check_status = $_GET['check_status'];
        }

        if (isset($_GET['good_status']) && $_GET['good_status']) {
            $good_status = $_GET['good_status'];
        }

        if (isset($_GET['trade_way']) && $_GET['trade_way']) {
            $trade_way = $_GET['trade_way'];
        }

        if (isset($_GET['admin_name']) && $_GET['admin_name']) {
            $admin_name = $_GET['admin_name'];
        }

        if (isset($_GET['order_id']) && $_GET['order_id']) {
            $order_id = $_GET['order_id'];
        }

    ?>
    <table class="table">
        <tr>
            <th width="120">商品名</th>
            <th>
                <input type="text" class="cssInput" name="good_name" value="<?php echo $good_name;?>">
            </th>
            <th width="120">购买时间</th>
            <th>
                <input name="buy_start" type="date" class="cssInput" style="width:200px"  value="<?php echo $buy_start;?>">
                <input name="buy_end" type="date" class="cssInput" style="width:200px"  value="<?php echo $buy_end;?>">
            </th>
            <th width="120">审核状态</th>
            <th>
                <select name="check_status">
                    <option value="0" <?php echo ($check_status == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($check_status == 1) ? 'selected' : '';?>>未审核</option>
                    <option value="2" <?php echo ($check_status == 2) ? 'selected' : '';?>>已审核</option>
                </select>
            </th>
        </tr>

        <tr>
            <th colspan="" width="120">商家名</th>
            <th>
                <input type="text" class="cssInput" name="market_name" value="<?php echo $market_name;?>">
            </th>

            <th width="120">验证时间</th>
            <th>
                <input name="check_start" type="date" class="cssInput" style="width:200px"  value="<?php echo $check_start;?>">
                <input name="check_end" type="date" class="cssInput" style="width:200px"  value="<?php echo $check_end;?>">
            </th>
            <th width="120">订单状态</th>
            <th>
                <select name="order_status">
                    <option value="0" <?php echo ($order_status == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($order_status == 1) ? 'selected' : '';?>>待支付</option>
                    <option value="2" <?php echo ($order_status == 1) ? 'selected' : '';?>>待使用</option>
                    <option value="3" <?php echo ($order_status == 3) ? 'selected' : '';?>>退款中</option>
                    <option value="4" <?php echo ($order_status == 4) ? 'selected' : '';?>>已退款</option>
                    <option value="5" <?php echo ($order_status == 5) ? 'selected' : '';?>>已使用</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="100">商品id</th>
            <th>
                <input type="text" class="cssInput" name="good_id" value="<?php echo $good_id;?>">
            </th>
            <th>退款时间</th>
            <th>
                <input name="back_start" type="date" class="cssInput" style="width:200px"  value="<?php echo $back_start;?>">
                <input name="back_end" type="date" class="cssInput" style="width:200px"  value="<?php echo $back_end;?>">
            </th>
            <th width="120">商品状态</th>
            <th>
                <select name="good_status">
                    <option value="0" <?php echo ($good_status == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($good_status == 1) ? 'selected' : '';?>>未开始</option>
                    <option value="2" <?php echo ($good_status == 2) ? 'selected' : '';?>>在售</option>
                    <option value="3" <?php echo ($good_status == 3) ? 'selected' : '';?>>停止售卖</option>
                    <option value="4" <?php echo ($good_status == 4) ? 'selected' : '';?>>已下架</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">用户名</th>
            <th>
                <input type="text" class="cssInput" name="user_name" value="<?php echo $user_name;?>">
            </th>
            <th>用户手机号</th>
            <th>
                <input type="text" class="cssInput" name="user_phone" value="<?php echo $user_phone;?>" style="width:190px">
            </th>
            <th width="120">支付方式</th>
            <th>
                <select name="trade_way">
                    <option value="0" <?php echo ($trade_way == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($trade_way == 1) ? 'selected' : '';?>>支付宝</option>
                    <option value="2" <?php echo ($trade_way == 2) ? 'selected' : '';?>>银联</option>
                    <option value="3" <?php echo ($trade_way == 3) ? 'selected' : '';?>>旧微信网页</option>
                    <option value="5" <?php echo ($trade_way == 5) ? 'selected' : '';?>>微信</option>
                    <option value="6" <?php echo ($trade_way == 6) ? 'selected' : '';?>>账户支付</option>
                    <option value="7" <?php echo ($trade_way == 7) ? 'selected' : '';?>>新微信网页</option>
                </select>
            </th>
        </tr>

        <tr>
            <th  width="160"> 经办人</th>
            <th>
                <input type="text" class="cssInput" name="admin_name" value="<?php echo $admin_name;?>" style="width:190px">
            </th>
            <th>订单号</th>
            <th colspan="3">
                <input type="text" class="cssInput" name="order_id" value="<?php echo $order_id;?>" style="width:190px">
            </th>

        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="5">
                <a href="/wftadlogin/order/list" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/order/outaccount" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">
        订单列表
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">订单号</th>
                <th width="50">用户名</th>
                <th width="50">用户手机号</th>
                <th width="80">商品ID</th>
                <th width="80">经办人</th>
                <th width="80">购买时间</th>
                <th width="80">验证时间</th>
                <th width="150">商品名称</th>
                <th width="150">套系</th>
                <th width="100">数量</th>
                <th width="100">备注</th>
                <th width="100">入账</th>
                <th width="100">出账</th>
                <th width="100">收益</th>
                <th width="100">商家名称</th>
                <th width="100">商品状态</th>
                <th width="100">订单状态</th>
                <th width="100">支付渠道</th>
                <th width="100">支付账号</th>
                <th width="100">保险人数</th>
                <th width="100">保险金额</th>
            </tr>
            <?php foreach ($data as $key => $row): ?>
                <tr style="text-align: left">
                    <td width="50">
                        <a href="/wftadlogin/order/info?order_sn=<?php echo $row['order_sn'];?>"><?php echo $row['order_sn']; ?></a>
                    </td>
                    <td width="50">
                        <?php echo $row['username'];?>
                    </td>
                    <td width="50"><?php echo $row['buy_phone']; ?></td>
                    <td width="80"><?php echo $row['coupon_id']; ?></td>
                    <td width="80"><?php echo $row['admin_name']; ?></td>
                    <td width="170"><?php echo date('Y-m-d H:i',$row['dateline']); ?></td>
                    <td width="170"><?php echo $row['use_datetime']; ?></td>
                    <td width="150"><?php echo $row['coupon_name']; ?></td>
                    <td width="150"><?php echo $row['type_name']; ?></td>
                    <td width="150"><?php echo $row['buy_number']; ?></td>
                    <td width="150"><?php echo $row['message']; ?></td>
                    <td width="150"><?php echo bcadd($row['real_pay'], $row['account_money'], 2); ?></td>
                    <td width="150"><?php echo $row['back_money']; ?></td>
                    <td width="150"><?php echo bcsub(bcadd($row['real_pay'], $row['account_money'], 2), $row['back_money'], 2); ?></td>
                    <td width="150"><?php echo $row['shop_name']; ?></td>
                    <td width="150"><?php echo $row['good_status']; ?></td>
                    <td width="150"><?php echo $row['order_status']; ?></td>
                    <td width="150"><?php echo $row['account_type']; ?></td>
                    <td width="150"><?php echo $row['account']; ?></td>
                    <td width="150"><?php echo $row['insure']['people']; ?></td>
                    <td width="150"><?php echo $row['insure']['money']; ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <style>
            #tongji{
                padding:5px 5px;
                margin: 5px 5px;
            }
            #tongji span{
                color:red;
                font-size:16px;
                padding: 10px;
            }
        </style>
        <div id="tongji">
            <div>
                <span>总计订单数：<mark><?php echo $order_sum;?></mark></span>
                <span>支付数量：<mark><?php echo $pay_sum;?></mark></span>
            </div>
            <div>
                <span>入账数额：<mark><?php echo $income;?></mark></span>
                <span>出账数额：<mark><?php echo $outSum;?></mark></span>
            </div>
        </div>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>
<script>
    $(function () {
        //导出订单
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');
        });

    });
</script>




