<!DOCTYPE html>
<html lang="zh-cn" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge,chrome=1">
    <meta http-equiv=”Cache-Control” content=”no-siteapp” />
    <meta name="apple-mobile-web-app-capable" content="yes" >
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <title id="title">选择报名人数</title>
    <link href="/css/wap/activestyle.css?ver=<?php echo time();?>" rel="stylesheet" id="order_css"/>
    <script>(function(){var w=window.screen.width,s=w/750,u=navigator.userAgent,m='<meta name="viewport" content="width=750,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
    <style>
        #tipsDia{display: none; width: 60%; background-color: rgba(0,0,0,0.5); color: #fff; position: fixed; left: 50%;top: 40%; z-index: 99999; text-align: center; letter-spacing: 2px; -webkit-transform: translate(-50%, -40%); -moz-transform: translate(-50%, -40%); -ms-transform: translate(-50%, -40%); transform: translate(-50%, -40%); padding: 5%; box-sizing: border-box; border-radius: 10px 10px 10px 10px;font-size: 25px; }
        .back {
            display: block;
            width: 100%;
            height: 80px;
            background-color: #cccccc;
            color: #1a1a1a;
            font-size: 2.2rem;
            text-align: center;
            position: fixed;
            bottom: 0px;
        }
        .backed{
            background-color: #959595;
            border-bottom: 1px solid #959595;
        }
        .grey{background-color:#808080}

        .activity-info p mark {
            font-size: 28px;
        }
        .activity-num-item .ticket-type-age{
            line-height: 55px;
        }
    </style>
</head>
<body>
<div id="order">
    <div class="activity">
        <p class="activity-title"><?php echo $data['title'];?></p>
        <div class="activity-info">
            <p>
                <span>出行时间：</span>
                <mark><?php echo date("Y-m-d H:i",$data['start_time']);?> ~ <?php echo date("Y-m-d H:i",$data['end_time']);?></mark>
                <!--                <mark>--><?php //echo date("Y年m月d日 h:m",$data['start_time']);?><!--~--><?php //echo date("Y年m月d日 h:m",$data['end_time']);?><!--</mark>-->
            </p>
            <p>
                <span>游玩地点：</span>
                <mark><?php echo $data['play_address'];?></mark>
            </p>
        </div>
        <div class="activity-num">
            <div class="activity-num-title">
                <p>出行人数</p>
            </div>
            <?php foreach($data['members'] as $v):?>
                <div class="activity-num-item price_item" data-id="<?php echo $v['id'];?>" data-num="<?php echo $v['people_number'];?>">
                <span class="ticket-type">
                    <span class="ticket-type-age">
                        <mark><?php echo $v['title'];?></mark>
                        <i></i>
                    </span>
                    <!--<span class="ticket-type-num">
                        当前报名<?php /*echo $v['joined_num'];*/?>人
                        <?php
/*                        if($v['residue_num']>0){
                            echo '离成团还差'.$v['residue_num'].'人';
                        }
                        ;*/?>
                    </span>-->
                </span>
                <span class="ticket-num">
                    <a class="minus-btn disable"></a>
                    <mark class="numTotal"><?php echo $v['min_buy'];?></mark>
                    <a class="plus-btn"></a>
                </span>
                    <span class="ticket-price">&yen;<mark class="ticket_price"><?php echo $v['price'];?></mark></span>
                </div>
                <input type="hidden" id="max_num" style="width: 0;" value="<?php echo $v['max_buy'];?>">
                <input type="hidden" id="min_num" style="width: 0;" value="<?php echo $v['min_buy'];?>">
            <?php endforeach;?>
            <?php if($data['save_number']>0 && $data['save_money']>0):?>
            <div class="activity-num-intro">
                <span>惠</span>
                <mark>每满 <a id="full_price"><?php echo $data['save_number'];?></a>元减<a id="less_price"><?php echo $data['save_money'];?></a>元</mark>
<!--                <mark class="activity-num-intro-discount">-￥<a id=discount>0</a></mark>-->
            </div>
            <?php endif;?>
        </div>
        <?php if(count($data['other'])>0):?>
        <div class="activity-num other">
            <div class="activity-num-title">
                <p>其他费用</p>
            </div>
            <?php foreach($data['other'] as $k=>$v):?>
                <div class="activity-num-item other_item">
                <span class="ticket-type">
                    <input type="checkbox" name="cost" id="cost<?php echo $k;?>" data="<?php echo $k;?>" data-type="1" data-id="<?php echo $v['id'];?>"/>
<!--                    <label for="cost--><?php //echo $k;?><!--"></label>-->
                    <mark class="otherCost"><?php echo $v['title'];?></mark>
                </span>
                <span class="ticket-num">
                    <a class="minus-btn" data-type="other"></a>
                    <mark class="numTotal"><?php echo $v['min_num'];?></mark>
                    <a class="plus-btn" data-type="other"></a>
                </span>
                    <span class="ticket-price">&yen;<mark><?php echo $v['price'];?></mark></span>
                </div>
            <?php endforeach;?>
        </div>
        <?php endif;?>
    </div>
    <a class="people-number" href="javascript:;">
        <p>
            <span>出行人数</span>
            <span class="people-name">请选择出行人</span>
        </p>
        <mark>活动出行前会为出行人购买保险，请务必认真选择出行人信息！</mark>
        <i class="arrow-right"></i>
    </a>
    <div class="ticket-info">
        <a href="javascript:;">
            <p><span class="address-name"><?php echo $data['address'][0]['name'];?></span><span class="address-tel"><?php echo $data['address'][0]['phone'];?></span></p>
            <p class="address-line"><span class="address-position"><?php echo $data['address'][0]['province'].$data['address'][0]['city'].$data['address'][0]['region'].$data['address'][0]['address'];?></span></p>
        </a>
    </div>
    <!--    选择集合方式-->
    <?php if($data['meeting']):?>
        <div class="activity-num">
        <div class="activity-num-title">
            <p>集合地点</p>
        </div>
        <a class="activity-num-sel <?php if(count($data['meeting'])>1){echo 'addr_sel';}?>">
            <span><?php if(count($data['meeting'])==1){echo $data['meeting'][0]['meeting_place'];}else{
                    echo '请选择集合地点';
                }?></span>
            <i class="arrow-right"></i>
        </a>
    </div>
    <?php endif;?>
    <p class="declare">同意参加活动，表示您已经同意相关 活动 <a href="/web/h5/disclaimer"><mark>免责声明</mark></a></p>
    <div class="detail-fixed">
        <a class="total-price">
            <span>总价：<mark>￥</mark><mark class="total" id="total">59.9</mark></span>
        </a>
        <a class="next-btn" href="javascript:;" id="submit-btn">提交订单</a>
    </div>
    <!--    选择集合方式弹框-->
    <div class="popup">
        <div class="matte" style="display: none"></div>
        <!--选择上车地点弹窗-->
        <div class="popup-address" style="display: none">
            <div class="popup-address-title">
                <p>选择集合地点</p>
            </div>
            <section class="lists">
                <?php foreach($data['meeting'] as $k=>$v):?>
                <div class="popup-address-item">
                    <span><?php echo $v['meeting_place']."&nbsp;&nbsp;&nbsp;".date("m-d H:i",$v['meeting_time']);?></span>
                    <input type="radio" name="radio" id="address0<?php echo $k+1;?>" data-id="<?php echo $v['id'];?>" />
                    <label for="address0<?php echo $k+1;?>"></label>
                </div>
                <?php endforeach;?>
            </section>
            <div class="popup-address-btn">
                <a class="cancelBtn">否</a>
                <a class="confirmBtn">是</a>
            </div>
        </div>
    </div>
    <input type="hidden" id="good_num" value="<?php echo $good_num;?>">
    <input type="hidden" id="tips" value="<?php echo $tips;?>">
    <input type="hidden" id="sid" value="<?php echo $sid;?>">
    <input type="hidden" name="associates_ids" value="" id="associates_ids">
</div>
<main id="step1" style="display: none;height: auto;"></main>
<script id="test" type="text/html">
    <div class="traveller">
        {{each response_params}}
            <form class="traveller-form">
                <label class="traveller-form-label">
                    <div class="traveller-form-info">
                        <span class="traveller-form-name">{{$value.name}}</span>
                        <span class="traveller-form-id">{{$value.id_num}}</span>
                        <span class="traveller-form-edit">
                            <a href="javascript:;"  data-type="编辑" class="edit" data="1" data-name="{{$value.name}}" data-card="{{$value.id_num}}" data-id="{{$value.associates_id}}">编辑</a>
                        </span>
                    </div>
                </label>
                <input type="checkbox" name="radio" class="traveller-form-radio r_{{$value.associates_id}}" value="0" data="{{$value.name}}" data-id="{{$value.associates_id}}">
            </form>
        {{/each}}
        <div class="traveller-addcontact" style="margin-bottom: 200px">
            <span class="traveller-addcontact-info"><a href="javascript:;" data-type="新增" class="edit" data="2">+添加出行人</a></span>
        </div>
    </div>
    <button class="traveller-button" id="sub">返回</button>
    <div class="matte-detail"></div>
    <div class="popup2-detail">
        <p>确认出行人信息提交后不可修改</p>
        <span>
            <a class="go-del" href="javascript:;">取消</a>
            <a class="go-submit" href="javascript:;">提交</a>
        </span>
    </div>
    <div class="popup-detail">
        <p id="tip"></p>
        <a class="go-travel" href="#">填写出行人信息</a>
    </div>
</script>
<div id="step2" style="display:none">
    <div class="per">
        <form class="per-form">
            <span class="per-form-name per-title">姓名</span>
            <input class="per-form-input" value="" id="name">
        </form>

        <section class="per-info">
            <div class="per-info-id">
                <span class="per-title">身份证号</span>
                <input class="per-form-input" value="" id="id_num" type="text"/>
            </div>
        </section>
        <button class="per-button" id="submit">保存</button>
        <span class="per-notice">出行人信息将被用来购买保险，请如实填写。</span>
    </div>
    <input type="hidden" id="edit_id" value="" name="edit_id">
</div>
<main id="step3" style="display: none;height: auto;"></main>
<script id="test2" type="text/html">
    {{each response_params}}
    <div class="address-info">
        <div class="addr">
            <p><span class="address-name">{{$value.name}}</span><span class="address-tel">{{$value.phone}}</span></p>
            <p class="address-line"><span class="address-position">{{$value.province}}{{$value.city}}{{$value.region}}{{$value.address}}</span></p>
        </div>
        <div class="address-btn">
            {{if $value.is_default==1}}
            <input type="checkbox" class="choose" name="address" value="{{$value.id}}" checked="checked" data-name="{{$value.name}}" data-addr="{{$value.province}}{{$value.city}}{{$value.region}}{{$value.address}}" data-phone="{{$value.phone}}"/>
            {{else}}
            <input type="checkbox" class="choose" name="address" value="{{$value.id}}" data-name="{{$value.name}}" data-addr="{{$value.province}}{{$value.city}}{{$value.region}}{{$value.address}}" data-phone="{{$value.phone}}"/>
            {{/if}}
            <label for="choose" class="address_check" data-name="{{$value.name}}" data-region="{{$value.province}}{{$value.city}}{{$value.region}}" data-phone="{{$value.phone}}" data-addr="{{$value.address}}">
                <span class="address-select">设为默认</span>
            </label>
            <a class="address-edit addr_edit" href="javascript:;" data="1">编辑</a>
            <a class="address-del" href="javascript:;" data="{{$value.id}}">删除</a>
        </div>
    </div>
    {{/each}}
    <a class="add-list addr_edit" href="javascript:;" data="2">+新建收货地址</a>
    <button class="traveller-button" id="addr_back">返回</button>
</script>
<div id="step4" style="display: none;">
    <section class="eaddr">
        <!--        data-url : 请求接口-->
        <form class="eaddr-form" id="myform" data-url="...">
            <label class="eaddr-form-label">
                <span class="eaddr-form-span">姓名</span>
                <input type="text" id="eaddr-name" name="name" class="eaddr-form-input eaddr-name" placeholder="请填写中文姓名" value="">
            </label>

            <label class="eaddr-form-label">
                <span class="eaddr-form-span">联系方式</span>
                <input type="TEL" name="tel" class="eaddr-form-input eaddr-phone" placeholder="请填写手机号" value="" id="phone">
            </label>

            <label class="eaddr-form-label" id="addr">
                <span class="eaddr-form-span">所在地区</span>
                <input class="eaddr-form-input area" type="text" id="txt_area" value="" data-value="" placeholder="请选择所在地区"/>
                <input class="eaddr-form-input" type="hidden" id="hd_area" value="" />

                <div class="eaddr-form-arrow area"></div>
            </label>


            <label class="eaddr-form-label">
                <span class="eaddr-form-span">详细地址</span>
                <span class="eaddr-form-addr">
                <input type="text" id="address" value="" class="eaddr-form-input" placeholder="请填写详细地址">
            </span>
            </label>
            <button class="eaddr-button" id="btn">保存</button>
        </form>
        <button class="traveller-button backed" id="edit_back" >返回</button>
        <input type="hidden" id="sel_addr_id" name="sel_addr_id">
    </section>
</div>
<input type="hidden" name="car_addr" id="car_addr" value="<?php echo ($data['meeting'][1]=='') ? $data['meeting'][0]['id'] : 0;?>">
<div id="tipsDia"></div>
<script src="/js/zepto1.1.6.min.js" type="text/javascript"></script>
<script src="/js/wap/template.js"></script>
<script type="text/javascript" src="/js/strategy.main.js"></script>
<script>
    var step1 = $("#step1"),
        step2= $("#step2"),
        step3= $("#step3"),
        step4= $("#step4"),
        order= $("#order"),
        loginTip = $("#tipsDia"),
        city = localStorage.getItem("select_city"),
        title = $("#title"),
        tips = $("#tips").val(),
        goodObj = $(".price_item"),
        nameObj = $("#name"),
        cardObj = $('#id_num'),
        full = $('#full_price').text(),
        less = $('#less_price').text(),
        people_num= 0;

    var maxVal = $('#max_num').val();
    var minVal = $('#min_num').val();

    (function () {
        var UA = window.navigator.userAgent;
        var CLICK = "click";
        if(/ipad|iphone|android/.test(UA)){
            CLICK = "tap";
        }

        //商品数量加减
        var lists = $(".activity-num");
        lists.find(".numTotal").each(function(){
            if($(this).text() == 0){
                $(this).prev().addClass("disable");
            }
        });
        $("input")[CLICK](function(){
            calculate_total();
        });

        if(minVal==0 && maxVal==0){
            $(".minus-btn")[CLICK](function(){
                var numMinus = $(this).next();
                var minusVal =numMinus.text();
                if(minusVal > 1){
                    minusVal--;
                    numMinus.text(minusVal);
                }else if(minusVal == 1){
                    minusVal--;
                    numMinus.text(minusVal);
                    $(this).attr("disabled",true);
                    $(this).addClass("disable");
                }

                calculate_total();
            });

            $(".plus-btn")[CLICK](function(){
                var numPlus = $(this).prev();i
                var plusVal = numPlus.text();

                numPlus.prev().removeClass("disable");
                plusVal++;
                numPlus.text(plusVal);
                calculate_total();
            });
        }

        if(minVal>0 || maxVal>0){
            $(".minus-btn")[CLICK](function(){
                var numMinus = $(this).next();
                var numVal = numMinus.text();

                var type = $(this).attr('data-type');
                if(type=='other'){
                    minVal = 0;
                }

                if(numVal>minVal){
                    numVal--;
                    numMinus.text(numVal);
                }else if(numVal == minVal){
                    loginTip.text("最少购买"+minVal+"张哦！");
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                    numMinus.text(numVal);
                    $(this).attr("disabled",true);
                    $(this).addClass("disable");
                }

                calculate_total();
            });

            $(".plus-btn")[CLICK](function(){
                var numPlus = $(this).prev();
                var plusVal = parseInt(numPlus.text(), 10);

                var type = $(this).attr('data-type');
                if(type=='other'){
                    maxVal = 1000;
                }
                if(plusVal < maxVal){
                    numPlus.prev().removeClass("disable");
                    plusVal++;
                    numPlus.text(plusVal);
                }else if(plusVal >= maxVal){
                    loginTip.text("最多购买"+maxVal+"张哦！");
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                    $(this).attr("disabled",true);
                }
                calculate_total();
            });

        }

        calculate_total();

        $(".people-number").on("tap",function(e){
            e.preventDefault();
            var data = {"uid":<?php echo $_COOKIE['uid']>0 ? $_COOKIE['uid'] : 0;?>};
            if(getsum(goodObj)<=0){
                loginTip.text("请先选择出行人数后在选择出行人");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                },2000);
                $(this).prop("checked",false);
                return false;
            }
            doAjax(data,"/user/associates/list",1);
        });

        //收货地址
        $(".ticket-info").on("tap",function(e){
            e.preventDefault();
            var data = {"uid":<?php echo $_COOKIE['uid']>0 ? $_COOKIE['uid'] : 0;?>};
            addrlistAjax(data,"/user/phone");
        });

        var selectArea = new MobileSelectArea();
        selectArea.init({
            trigger:'#txt_area',
            value:$('#hd_area').val(),
            data:'/js/wap/area.json'
        });

        var name = $("#eaddr-name"),
            area = $("#txt_area"),
            address = $("#address"),
            nameReg = /^[\u4E00-\u9FA5]+$/,
            phone = $("#phone"),
            phoneReg = /^1\d{10}$/;

        $("#btn").on("touchstart",function(e){
            e.preventDefault();
            var nameValue = $.trim(name.val()),
                phoneValue = $.trim(phone.val()),
                areaValue = $.trim(area.val()),
                addressValue = $.trim(address.val()),
                addr_id = $("#sel_addr_id").val();

            if (nameValue == "") {
                loginTip.text("您还未输入姓名");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    $("#btn").attr('disabled', false);
                },2000);
                name.focus();
                return false;
            }

            if (!nameReg.test(nameValue)) {
                loginTip.text("请输入中文名字");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    $("#btn").attr('disabled', true);
                },2000);
                name.focus();
                return false;
            }

            if (phoneValue == "") {
                loginTip.text("您还未输入手机号");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    $("#btn").attr('disabled', true);
                },2000);
                phone.focus();
                return false;
            }

            if (!phoneReg.test(phoneValue)) {
                loginTip.text("您输入手机号有误");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    $("#btn").attr('disabled', true);
                },2000);
                phone.focus();
                return false;
            }

            if (areaValue == "") {
                loginTip.text("您还选择所在地区");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    $("#btn").attr('disabled', true);
                },2000);
                area.focus();
                return false;
            }

            if (addressValue == "") {
                loginTip.text("您还输入详细地址");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    $("#btn").attr('disabled', true);
                },2000);
                address.focus();
                return false;
            }

            $("#btn").text("提交中...");
            $("#btn").addClass("grey");

            var data = {"uid":<?php echo $_COOKIE['uid'] ? $_COOKIE['uid'] : 0;?>,'name':nameValue,"phone":phoneValue,"address":addressValue,'id':addr_id,'province':areaValue};

            $.ajax({
                type:'POST',
                url:"/user/phone/editphone",
                dataType:'json',
                async: true,
                data:data,
                headers: {
                    "VER": 10
                },
                success: function (result) {
                    if (result.response_params.status == 0) {
                        loginTip.text(result.response_params.message);
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                            $("#btn").attr('disabled', false);
                            $("#btn").text("保存");
                            $("#btn").removeClass("grey");
                        },2000);
                        return false;
                    } else {
                        //todo 成功
                        //window.location.href = "";
                        loginTip.text(result.response_params.message);
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                            $("#btn").attr('disabled', false);
                            $("#btn").text("保存");
                            $("#btn").removeClass("grey");
                        },2000);
                        step4.hide();
                        addrlistAjax({"uid":<?php echo $_COOKIE['uid']>0 ? $_COOKIE['uid'] : 0;?>},'/user/phone');
                        step3.show();
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                    if (XMLHttpRequest.status == 401) {
                        //todo 跳转授权页面
                        //alert(XMLHttpRequest.responseJSON.message);
                        window.location.href = '<?php echo $authorUrl;?>';
                    }
                    else if (XMLHttpRequest.status == 403) {
                        alert('接口验证失败，非法访问');
                    }
                    else if (XMLHttpRequest.status == 400) {
//                            window.location.href = '<?php //echo $authorUrl;?>//';
                        alert('请求参数错误:' + XMLHttpRequest.error_msg);
                    }
                    else {
                        alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                    }
                }
            })

        });

        $("#edit_back").on("tap",function(e){
            e.stopPropagation();
            addrlistAjax({"uid":<?php echo $_COOKIE['uid']>0 ? $_COOKIE['uid'] : 0;?>},'/user/phone');
            step4.hide();step3.show();
        });

        //选择上车地点
        var addr;
        $(".addr_sel").on("tap",function(){
            $(".matte").show();
            $(".popup-address").show();
        });

        $(".confirmBtn").on("tap",function(e){
            e.preventDefault();
            $(".lists").find("input").each(function(){
                var sel = $(this).is(':checked');
                if(sel == true){
                   $("#car_addr").val($(this).attr("data-id"));
                    addr = $(this).prev().text();
                    $(".addr_sel").find("span").text(addr);
                    $(".matte").hide();
                    $(".popup-address").hide();
                }
            })
        });

        $(".cancelBtn").on("tap",function(){
            $(".matte").hide();
            $(".popup-address").hide();
        });

        //进收银台
        $(".next-btn").on("tap", function (e) {
            e.preventDefault();
            var charges = [],
                goodObj = [],
                goodsObj = $(".price_item"),
                othersObj = $("input[type=checkbox][name='cost']");

            var len=goodsObj.length,
                Len = othersObj.length;

            if(getsum(goodsObj)<=0){
                loginTip.text("请选择活动票券");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                },2000);
                return false;
            }

            for(var k=0;k<len;k++){
                if(parseInt($(goodsObj[k]).find(".numTotal").text())>0){
                    goodObj.push({'id':$(goodsObj[k]).attr("data-id"),'buy_number':parseInt($(goodsObj[k]).find(".numTotal").text()),'is_other':0});
                }
            }

            if(Len>0){
                for(var l=0;l<Len;l++){
                    if(parseInt($(othersObj[l]).parent().next().find(".numTotal").text())>0){
                        goodObj.push({'id':$(othersObj[l]).attr("data-id"),'buy_number':parseInt($(othersObj[l]).parent().next().find(".numTotal").text()),'is_other':1});
                    }
                }
            }

            charges.push(JSON.stringify(goodObj));

            var phone= $(".address-tel").text(),
                associates_ids = $("#associates_ids").val(),
                sid= $("#sid").val(),
                name = $(".address-name").text(),
                total_price = $("#total").text(),
                link_address= $(".address-position").text(),
                is_meet = <?php echo $data['meeting'][0] ? 1 : 0;?>,
                meeting = $("#car_addr").val();

            localStorage.setItem('charges',charges);

            if(is_meet){
                if(meeting<=0){
                    /*loginTip.text("请选择上车地点");
                    loginTip.show();*/

                    $(".matte").show();
                    $(".popup-address").show();

                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                    return false;
                }
            }


            $('#submit-btn').val('请稍候..').css({'background-color': '#ccc'}).attr({"disabled": "disabled"});

            window.location.href="/web/wappay/payment?session_id="+sid+"&name="+name+"&phone="+phone+"&city="+encodeURI(city)+"&address="+link_address+"&associates_ids="+associates_ids+"&total="+total_price+'&meet_id='+meeting;
        });
    })();

    //计算总价
    function calculate_total(){
        var num = 0,
            price = 0,
            total = 0,
            other_num= 0,
            other_price= 0,
            other_total = 0,
            discount= 0,
            final=0;


        //其他收费项
        var input = $("input[type=checkbox][name='cost']");
        var len = input.length;
        for(var i=0;i<len;i++){
            other_num = parseInt($(input[i]).parent().next().find(".numTotal").text());
            other_price = parseFloat($(input[i]).parent().next().next().find("mark").text());
            other_total += other_num*other_price;
        }

        //正常收费项
        var priceItem = $(".price_item"),
            Len = priceItem.length;
        for(var i=0;i<Len;i++){
            num = $(priceItem[i]).find(".numTotal").text();
            price = $(priceItem[i]).find('.ticket_price').text();
            total += parseInt(num)*parseFloat(price);
        }
        //求优惠金额
        final = (total+other_total).toFixed(2);
        if(parseFloat(full)>0 && parseFloat(less)>0){
            discount = Math.floor(final/parseInt(full))*parseInt(less);
        }

        final = (final-discount).toFixed(2);

        $("#discount").text(discount);
        $("#total").text(final);
    }

    //求和
    function getsum(arr)
    {
        //数组求和函数
        Array.prototype.sum = function(){
            var sum = 0;
            for(var i = 0;i<this.length;i++)
            {
                sum += parseInt(this[i]);
            }
            return sum;
        };

        //用于装对应值的数组
        var len = arr.length,
            count = [];
        for(var i=0;i<len;i++)
        {
            var type = $(arr[i]).attr('data-type');
            var num = $(arr[i]).attr('data-num');

            if(type==1){
                count.push(num*(parseInt($(arr[i]).parent().next().find(".numTotal").text())));
            }else{
                count.push(num*(parseInt($(arr[i]).find(".numTotal").text())));
            }
        }
        //计算
        return count.sum();
    }

    function createjscssfile(filename, filetype){
        if (filetype=="js"){
            var fileref=document.createElement('script');
            fileref.setAttribute("type","text/javascript");
            fileref.setAttribute("src", filename);
        }
        else if (filetype=="css"){
            var fileref=document.createElement("link");
            fileref.setAttribute("rel", "stylesheet");
            fileref.setAttribute("type", "text/css");
            fileref.setAttribute("href", filename);
        }
        return fileref
    }

    function replacejscssfile(oldfilename, newfilename, filetype) {
        var targetelement = (filetype == "js") ? "script" : (filetype == "css") ? "link" : "none";
        var targetattr = (filetype == "js") ? "src" : (filetype == "css") ? "href" : "none";
        var allsuspects = document.getElementsByTagName(targetelement);
        for (var i = allsuspects.length; i >= 0; i--) {
            if (allsuspects[i] && allsuspects[i].getAttribute(targetattr) != null && allsuspects[i].getAttribute(targetattr).indexOf(oldfilename) != -1) {
                var newelement = createjscssfile(newfilename, filetype);
                allsuspects[i].parentNode.replaceChild(newelement, allsuspects[i]);
            }
        }
    }

    function loadjscssfile(filename, filetype){
        if (filetype=="js"){
            var fileref=document.createElement('script')
            fileref.setAttribute("type","text/javascript")
            fileref.setAttribute("src", filename)
        }
        else if (filetype=="css"){
            var fileref=document.createElement("link")
            fileref.setAttribute("rel", "stylesheet")
            fileref.setAttribute("type", "text/css")
            fileref.setAttribute("href", filename)
        }
        if (typeof fileref!="undefined")
            document.getElementsByTagName("head")[0].appendChild(fileref)
    }


    //tyep:1出行人相关操作，2地址操作
    function doAjax(data,url,type){
        //执行其他操作
        $.ajax({
            type: "POST",
            url: url,
            //        dataType:"json",
            async: true,
            data:data,
            headers:{
                "VER":9
            },

            success: function (result) {
                if(type==1){
                    var html = template('test', result);
                    document.getElementById('step1').innerHTML = html;
                    order.hide();
                    replacejscssfile("/css/wap/activestyle.css?ver=<?php echo time();?>","/css/order-center.css?ver=<?php echo time();?>","css");
                    step1.show();
                    title.text("选择出行人");
                    var chk_num =$('input[type=checkbox][name="radio"]:checked').length;
                    if(chk_num<=0){
                        $("#sub").addClass("back");
                    }
                    $(".popup2-detail").hide();
                    var idsObj = $("#associates_ids").val().split(","),
                        len= idsObj.length;


                    for(var i=0;i<len;i++){
                        $(".r_"+idsObj[i]).attr("checked", true);
                        $(".r_"+idsObj[i]).val("1");
                        $(".r_"+idsObj[i]).addClass("active");
                    }

                    $('.traveller-form-radio').on("change", function (e) {
                        e.preventDefault();
                        var chk_num =$('input[type=checkbox][name="radio"]:checked').length;
                        people_num = getsum(goodObj);
                        if(chk_num>0){
                            $("#sub").text("确认").removeClass("back");
                        }else{
                            $("#sub").text("返回").addClass("back");
                        }

                        if(chk_num>people_num){
                            loginTip.text("抱歉，保险最多人数为"+people_num);
                            loginTip.show();
                            setTimeout(function(){
                                loginTip.hide();
                            },1000);
                            $(this).prop("checked",false);
                            return false;
                        }else{
                            if ($(this).val() == 0) {
                                $(this).attr("checked", true);
                                $(this).val("1");
                            } else {
                                $(this).val("0");
                                $(this).attr("checked", false);
                            }
                        }
                    });

                    $("#sub").on("tap", function (e) {
                        e.preventDefault();
                        var chk = $('input[type=checkbox][name="radio"]:checked'),
                            chk_length = chk.length,
                            names = '',
                            ids = [];
                        for (var i = 0; i < chk_length; i++) {

                            if (i == chk_length - 1) {
                                names += $(chk[i]).attr('data');
                            } else {
                                names+= $(chk[i]).attr('data') + ',';
                            }

                            ids.push($(chk[i]).attr("data-id"));
                        }

                        if(chk_length && !$(this).hasClass("back")){
//                            $(".popup2-detail").show();

//                            $(".go-submit").on("tap",function(e){
//                                e.preventDefault();
                                step1.hide();
                                $(".people-name").text(names);
                                $("#associates_ids").val(ids);
                                var num = ids.length;
                                if(num<people_num){
                                    var diff= parseInt(people_num-num);
                                    loginTip.text("您还有"+diff+"个出行人信息未填写，这些信息将被用于购买保险");
                                    loginTip.show();
                                    setTimeout(function(){
                                        loginTip.hide();
                                    },2000);
                                }
                                order.show();
                                title.text('选择报名人数');
                                replacejscssfile("/css/order-center.css?ver=<?php echo time();?>","/css/wap/activestyle.css?ver=<?php echo time();?>?ver=<?php echo time();?>","css");
//                            });
                        }else{
                            step1.hide();
                            order.show();
                            title.text('选择报名人数');
                            replacejscssfile("/css/order-center.css?ver=<?php echo time();?>","/css/wap/activestyle.css?ver=<?php echo time();?>","css");
                        }

//                        $(".go-del").on("tap",function(e){
//                            e.preventDefault();
//                            $(".popup2-detail").hide();
//                        });
                    });


                    //新增和编辑出行人 1编辑  2新增
                    var subBtn= $('#submit'),
                        nameReg = /^[\u4E00-\u9FA5]+$/,
                        idReg = /^(\d{15}$|^\d{18}$|^\d{17}(\d|X|x))$/,
                        data,
                        url;
                    $(".traveller").on('click',".edit",function(){
                        step1.hide();
                        step2.show();
                        var tips = $(this).attr('data'),
                            name =$(this).attr('data-name'),
                            id =$(this).attr('data-id'),
                            id_num =$(this).attr('data-card'),
                            data_type = $(this).attr('data-type');
                        title.text(data_type+'出行人');
                        if(tips==1){
                            $("#edit_id").val(id);
                            $("#name").val(name);
                            $("#id_num").val(id_num);
                        }else{
                            $("#name").val('');
                            $("#id_num").val('');
                            nameObj.focus();
                            subBtn.text("返回").addClass("backed");
                        }

                        cardObj.on("input", function() {
                            if (idReg.test($("#id_num").val())) {
                                subBtn.text('保存').removeClass("backed");
                            }
                        });

                    });

                    subBtn.on("touchend",function(e) {
                        e.preventDefault();
                        if($(this).hasClass('backed')){
                            step2.hide();
                            step1.show();
                            return false;
                        }
                        var nameValue = $.trim(nameObj.val()),
                            id_numValue = $.trim(cardObj.val());

                        if(nameValue==''){
                            loginTip.text("您还未输入姓名");
                            loginTip.show();
                            setTimeout(function(){
                                loginTip.hide();
                                subBtn.attr('disabled', false);
                            },2000);
                            nameObj.focus();
                            return false;
                        }

                        if (!nameReg.test(nameValue)) {
                            loginTip.text("请输入中文名字");
                            loginTip.show();
                            setTimeout(function(){
                                loginTip.hide();
                                subBtn.attr('disabled', true);
                            },2000);
                            nameObj.focus();
                            return false;
                        }

                        if(id_numValue==''){
                            loginTip.text("您还未输入身份证号");
                            loginTip.show();
                            setTimeout(function(){
                                loginTip.hide();
                                subBtn.attr('disabled', false);
                            },2000);
                            cardObj.focus();
                            return false;
                        }

                        if (!idReg.test(id_numValue)) {
                            loginTip.text("身份证格式不正确！");
                            loginTip.show();
                            setTimeout(function(){
                                loginTip.hide();
                                subBtn.attr('disabled', true);
                            },2000);
                            cardObj.focus();
                            return false;
                        }

                        subBtn.attr('disabled', false);
                        subBtn.text("保存中...");

                        var id = $("#edit_id").val();
                        if(id>0){

                            url = "/user/associates/edit";
                            data = {"uid":<?php echo $_COOKIE['uid']>0 ? $_COOKIE['uid'] : 0;?>,'associates_id':id,'name':nameValue,"id_num":id_numValue};
                        }else{
                            url = "/user/associates/add";
                            data = {"uid":<?php echo $_COOKIE['uid']>0 ? $_COOKIE['uid'] : 0;?>,'name':nameValue,"id_num":id_numValue};
                        }

                        $.ajax({
                            type:'POST',
                            url:url,
                            dataType:'json',
                            async: true,
                            data:data,
                            headers: {
                                "VER": 10
                            },
                            success: function (result) {
                                console.log(result);
                                subBtn.attr('disabled', true);
                                if (result.response_params.status == 0) {
                                    //alert(result.response_params.message);
                                    loginTip.text(result.response_params.message);
                                    loginTip.show();
                                    setTimeout(function(){
                                        loginTip.hide();
//                                        subBtn.attr('disabled', false);
                                    },2000);
                                    step1.show();
                                    step2.hide();
                                } else if(result.error_code==0){
                                    loginTip.text(result.error_msg);
                                    loginTip.show();
                                    setTimeout(function(){
                                        loginTip.hide();
                                    },2000);

                                }else if(result.response_params.status==1){
                                    loginTip.text(result.response_params.message);
                                    loginTip.show();
                                    setTimeout(function(){
                                        loginTip.hide();
                                    },2000);
                                    var data = {"uid":<?php echo $_COOKIE['uid']>0 ? $_COOKIE['uid'] : 0;?>};
                                    doAjax(data,"/user/associates/list",1);
                                    step2.hide();
                                }
                            },
                            error: function (XMLHttpRequest, textStatus, errorThrown) {
                                subBtn.attr('disabled', true);
//                                            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                                if (XMLHttpRequest.status == 401) {
                                    //todo 跳转授权页面
                                    //alert(XMLHttpRequest.responseJSON.message);
                                    window.location.href = '<?php echo $authorUrl;?>';
                                }
                                else if (XMLHttpRequest.status == 403) {
                                    window.location.href = '<?php echo $authorUrl;?>';
                                    alert('接口验证失败，非法访问');
                                }
                                else if (XMLHttpRequest.status == 400) {
//                                    window.location.href = '<?php //echo $authorUrl;?>//';
                                    var res =XMLHttpRequest.response;
                                    loginTip.text(JSON.parse(res).error_msg);
                                    loginTip.show();
                                    setTimeout(function(){
                                        loginTip.hide();
                                    },2000);
//                                    alert('身份证号码不合法');
                                    cardObj.val('');
                                    subBtn.text("返回").addClass("backed");
                                }
                                else {
                                    alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                                }
                            }
                        })
                    });
                }
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                if (XMLHttpRequest.status == 401) {
                    //alert('授权失败');
                    // 跳转授权页面
                    //alert(XMLHttpRequest.responseJSON.message);
                    window.location.href = '<?php echo $authorUrl;?>';

                }
                else if (XMLHttpRequest.status == 403) {
                    window.location.href = '<?php echo $authorUrl;?>';
//                    alert('接口验证失败，非法访问');
                }
                else if (XMLHttpRequest.status == 400) {
                    alert('请求参数错误');
                }
                else {
                    alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                }
            }

        });


    }

    function setdefaultAjax(data){
        $.ajax({
            type:'POST',
            url:"/user/phone/setdefault",
            dataType:'json',
            async: true,
            data:data,
            headers: {
                "VER": 10
            },
            beforeSend:function(){
                loginTip.text("正在操作...");
                loginTip.show();
            },
            success: function (result) {
                if (result.response_params.status == 0) {
                    loginTip.text(result.response_params.message);
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                } else if(result.response_params.status == 1) {
                    //todo 成功
                    //window.location.href = "";
                    loginTip.text(result.response_params.message);
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                }
            },

            error: function (XMLHttpRequest, textStatus, errorThrown) {
                //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                if (XMLHttpRequest.status == 401) {
                    //todo 跳转授权页面
                    //alert(XMLHttpRequest.responseJSON.message);
                    window.location.href = '<?php echo $authorUrl;?>';
                }
                else if (XMLHttpRequest.status == 403) {
                    alert('接口验证失败，非法访问');
                }
                else if (XMLHttpRequest.status == 400) {
//                            window.location.href = '<?php //echo $authorUrl;?>//';
                    alert('请求参数错误:' + XMLHttpRequest.error_msg);
                }
                else {
                    alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                }
            }
        })
    }

    function addrlistAjax(data,url){
        //执行其他操作
        $.ajax({
            type: "POST",
            url: url,
            //        dataType:"json",
            async: true,
            data:data,
            headers:{
                "VER":9
            },

            success: function (result) {
                var html = template('test2', result);
                document.getElementById('step3').innerHTML = html;
                order.hide();
                replacejscssfile("/css/wap/activestyle.css?ver=<?php echo time();?>","/css/order-center.css?ver=<?php echo time();?>","css");
                step3.show();
                title.text("地址管理");


                $(".address_check").on("tap", function (e) {
                    e.preventDefault();
                    $(this).parent().find("input").attr("checked",true);
                    $(this).parent().parent().siblings().find("input").removeAttr("checked");
                    var id = $(this).parent().find('input').val(),
                        name = $(this).attr("data-name"),
                        addr = $(this).attr("data-addr");
                    if(id>0){
                        var data = {"id":id,"uid":<?php echo $_COOKIE['uid']>0 ? $_COOKIE['uid'] : 0;?>};
                        setdefaultAjax(data);
                    }else{
                        loginTip.text("请完善联系人信息");
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                        },2000);
                    }
                });

                $("#addr_back").on("touchend",function(e){
                    e.preventDefault();
                    var chk = $("input[type=checkbox][name='address']:checked");
                    var sel_name = $(chk).attr("data-name"),
                        sel_addr = $(chk).attr("data-addr"),
                        sel_phone = $(chk).attr("data-phone");

                    step3.hide();
                    replacejscssfile("/css/order-center.css?ver=<?php echo time();?>","/css/wap/activestyle.css?ver=<?php echo time();?>","css");
                    order.show();
                    $('.address-name').text(sel_name);
                    $('.address-tel').text(sel_phone);
                    $('.address-position').text(sel_addr);
                });

                $(".addr_edit").on("touchend",function(e){
                    e.preventDefault();
                    var type = $(this).attr("data"),
                        name = $(this).parent().find(".address_check").attr("data-name"),
                        phone = $(this).parent().find(".address_check").attr("data-phone"),
                        region = $(this).parent().find(".address_check").attr("data-region"),
                        id = $(this).parent().find("input").val(),
                        addr = $(this).parent().find(".address_check").attr("data-addr");
                    if(type==1){
                        title.text("编辑联系人");
                        $("#eaddr-name").val(name);
                        $("#phone").val(phone);
                        $("#txt_area").val(region);
                        $("#address").val(addr);
                        $("#sel_addr_id").val(id);
                    }else{
                        $("#eaddr-name").val('');
                        $("#phone").val('');
                        $("#txt_area").val('');
                        $("#address").val('');
                        title.text('新增联系人');
                    }
                    step3.hide();
                    loadjscssfile('/css/mobile-select-area.css',"css");
                    loadjscssfile('/css/dialog.css',"css");

                    step4.show();
                });
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                if (XMLHttpRequest.status == 401) {
                    //alert('授权失败');
                    // 跳转授权页面
                    //alert(XMLHttpRequest.responseJSON.message);
                    window.location.href = '<?php echo $authorUrl;?>';

                }
                else if (XMLHttpRequest.status == 403) {
                    window.location.href = '<?php echo $authorUrl;?>';
//                    alert('接口验证失败，非法访问');
                }
                else if (XMLHttpRequest.status == 400) {
                    alert('请求参数错误');
                }
                else {
                    alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                }
            }

        });
    }
</script>
</html>