<hgroup class="box">
    <header>
        <h3>发货</h3>

        <i class="icon icon-list" style="margin-top: 20px;"></i>
        <a href="/wftadlogin/award" style="margin-top: 8px;">回到商品管理首页</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<div class="box">
    <div class="box-title"><?php echo $this->data ? '修改' : '添加'; ?>物流</div>

    <form method="post"
          action="/wftadlogin/award/update<?php echo $this->data ? '?log_id=' . $this->data['log_id'] : ''; ?>">
        <table class="table">
<!--            <tr>-->
<!--                <th width="160">快递公司</th>-->
<!--                <th colspan="3">-->
<!--                    <input type="text" class="cssInput" style="width:300px" name="gift_name"-->
<!--                           value="--><?php //echo $data ? $data->gift_name : ''; ?><!--">-->
<!--                </th>-->
<!--            </tr>-->

            <tr>
                <th width="160">物流单号</th>
                <th colspan="3">
                    <input type="text" class="cssInput" style="width:300px" name="number"
                           value="<?php echo $data ? $data->number : ''; ?>">
                </th>
            </tr>
            <tr>
                <th width="160">
                    <button id="ti-place" class="ui-button">提交</button>
                </th>
            </tr>
        </table>
    </form>
</div>

<style>
    .img-keyword {
        line-height: 15px;
        color: red;
    }

    #fileupload2 {
        width: 144px;
        height: 41px;
        cursor: pointer;
        font-size: 30px;
        outline: medium none;
        position: absolute;
        filter: alpha(opacity=0);
        -moz-opacity: 0;
        opacity: 0;
        left: 0px;
        top: 0px;
    }

    .img-button {
        float: left;
        height: 41px;
        background: #f5696c;
        width: 144px;
        position: relative;
    }

    .img-tip {
        text-align: center;
        line-height: 41px;
        font-size: 15px;
        font-weight: 800;
    }

    .csstextarea {
        width: 300px;
        height: 100px;
    }
</style>

<script src="/js/file_upload/jquery.iframe-transport.js"></script>

