<hgroup class="box">
    <header>
        <h3>奖品查看</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/award/index">返回领奖管理</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<div class="box">
    <div class="box-title">
        奖品信息
    </div>

    <div class="box-table">
        <table>
            <tr>
                <th class="size3">名称</th>
                <th class="size1">奖项</th>
                <th class="size1">剩余数量</th>
                <th class="size3">描述</th>
                <th class="size1">操作</th>
            </tr>

            <?php foreach ($data as $row) : ?>
                <tr style="text-align: left">
                    <td class="size3"><?php echo $row['title']; ?></td>
                    <td class="size1"><?php echo $row['rank']; ?></td>
                    <td class="size1"><?php echo $row['num']; ?></td>
                    <td class="size3"><?php echo $row['note']; ?></td>
                    <td class="size1">
                        <a href="/wftadlogin/award/edit?award_id=<?php echo $row['award_id']; ?>" class="ui-button">修改</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <footer>
            <?php echo $this->pagedata; ?>
        </footer>
    </div>
</div>

<style>
    th {
        max-width: 200px;
        -o-text-overflow: ellipsis;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        text-align: left;
    }

    td {
        max-width: 200px;
        -o-text-overflow: ellipsis;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        text-align: left;
    }

    .box-table td {
        text-align: left;
    }
</style>
