<hgroup class="box">
    <header>
        <h3>领奖管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/award/award">奖品信息</a>
<!--        <i class="icon icon-list"></i>-->
<!--        <a href="/wftadlogin/award/excel">导出所有邮寄信息</a> -->
<!--        <form method="post" action="/wftadlogin/award/input" enctype="multipart/form-data">-->
<!--            <input type="file" name="mail" class="btn btn-default" />-->
<!--            <input type="submit" value="邮寄杂志发货" class="btn btn-default" style="margin-left: 42px;"/>-->
<!--        </form>-->
    </header>

    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<div class="box">
    <div class="box-title">
        兑换记录
        <div style="float:right;margin-right:30px">
            <form action="#" method="get">
                <input type="text" class="cssInput" style="margin-top: 5px;width:200px"
                       placeholder="输入用户名" name="username"
                       value="<?php echo isset($_GET['username']) ? $_GET['username'] : ''; ?>">
                <input type="text" class="cssInput" style="margin-top: 5px;width:200px"
                       placeholder="输入商品关键字搜索" name="title"
                       value="<?php echo isset($_GET['title']) ? $_GET['title'] : ''; ?>">
                <input type="text" class="cssInput" style="margin-top: 5px;width:200px"
                       placeholder="输入手机号搜索" name="phone"
                       value="<?php echo isset($_GET['phone']) ? $_GET['phone'] : ''; ?>">
                <input type="text" class="cssInput" style="margin-top: 5px;width:200px"
                       placeholder="输入uid搜索" name="uid"
                       value="<?php echo isset($_GET['uid']) ? $_GET['uid'] : ''; ?>">
                <button class="btn btn-default" type="submit">搜索</button>
            </form>
        </div>
    </div>

    <div class="box-table">
        <table>
            <tr>
                <th class="size1">log_id</th>
                <th class="size1">uid</th>
                <th class="size1">用户名</th>
                <th class="size1">电话</th>
                <th class="size1">奖品名称</th>
                <th class="size1">奖项</th>
                <th class="size1">状态</th>
                <th class="size1">时间</th>
                <th class="size4">收货地址</th>
                <th class="size2">单号</th>
                <th class="size1">操作</th>
            </tr>

            <?php foreach ($data as $row) : ?>
            <tr style="text-align: left">
                <td class="size1"><?php echo $row['log_id']; ?></td>
                <td class="size1"><?php echo $row['uid']; ?></td>
                <td class="size1"><?php echo $row['username']; ?></td>
                <td class="size1"><?php echo $row['phone']; ?></td>
                <td class="size1"><?php echo $row['title']; ?></td>
                <td class="size1"><?php echo $row['rank']; ?></td>
                <td class="size1">
                    <?php if ($row['status'] == 0) {
                        echo "未领取";
                    } else {
                        echo "已领取";
                    }; ?>
                </td>
                <td class="size1"><?php echo $row['addtime']; ?> </td>
                <td class="size4"><?php echo $row['address']; ?></td>
                <td class="size2"><?php echo $row['number']; ?></td>
                <td class="size1">
                    <a href="/wftadlogin/award/status?logid=<?php echo $row['log_id']; ?>&status=1" class="ui-button">领</a>
                    <a href="/wftadlogin/award/status?logid=<?php echo $row['log_id']; ?>&status=0" class="ui-button">恢</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <footer>
            <?php echo $this->pagedata; ?>
        </footer>
    </div>
</div>

<style>
    th {
        max-width: 200px;
        -o-text-overflow: ellipsis;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        text-align: left;
    }

    td {
        max-width: 200px;
        -o-text-overflow: ellipsis;
        text-overflow: ellipsis;
        white-space: nowrap;
        overflow: hidden;
        text-align: left;
    }

    .box-table td {
        text-align: left;
    }
</style>
