<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>编辑收货信息</title>
    <!--    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>-->
    <meta name="format-detection" content="telephone=no, email=no" />
    <link href="/css/order-center.css" rel="stylesheet" />
    <link href="/css/mobile-select-area.css" rel="stylesheet">
    <link href="/css/dialog.css" rel="stylesheet">
    <script>(function(){var w=window.screen.width,s=w/750,u=navigator.userAgent,m='<meta name="viewport" content="width=750,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
    <style >
        .grey{background-color:#808080}

        body{
            width: 100%;
            overflow-x: hidden;
            overflow-y: auto;
            box-sizing: border-box;
        }
        #txt_are{
            border: none;
            text-align: center;
            font-size: 32px;
        }
        .ui-confirm-submit,
        .ui-confirm-no {
            width: 100px;
            height: 50px;
            font-size: 24px;
            margin-top: 15px;
            margin-left: -20px;
        }
        .ui-scroller {
            height: 150px;
            min-width: 260px;
            font-size: 28px !important;
            font-weight: normal;
        }
        .ui-scroller>div {
            height: 240px !important;
        }
        .ui-dialog {
            height: 350px !important;
            width: 545px !important;
            left: 90px !important;
        }
        .ui-dialog-action {
            margin-top: 65px;
        }
    </style>
</head>
<body>
<div id="tipsDia"></div>
<section class="eaddr">
    <!--        data-url : 请求接口-->
    <form class="eaddr-form" id="myform" data-url="...">
        <label class="eaddr-form-label">
            <span class="eaddr-form-span">姓名</span>
            <input type="text" id="name" name="name" class="eaddr-form-input eaddr-name" placeholder="请填写中文姓名" value="<?php echo $data->linker_name;?>">
        </label>

        <label class="eaddr-form-label">
            <span class="eaddr-form-span">联系方式</span>
            <input type="TEL" name="tel" class="eaddr-form-input eaddr-phone" placeholder="请填写手机号" value="<?php echo $data->linker_phone;?>" id="phone">
        </label>

        <label class="eaddr-form-label" id="addr">
            <span class="eaddr-form-span">所在地区</span>
            <input class="eaddr-form-input" type="text" id="txt_area" value="<?php echo $data->province.$data->city.$data->region;?>" data-value="<?php echo $data->province.$data->city.$data->region;?>" placeholder="请选择所在地区"/>
            <input class="eaddr-form-input" type="hidden" id="hd_area" value="12,124,3269" />

            <div class="eaddr-form-arrow"></div>
        </label>


        <label class="eaddr-form-label">
            <span class="eaddr-form-span">详细地址</span>
                <span class="eaddr-form-addr">
                <input type="text" id="address" value="<?php echo $data->linker_addr?>" class="eaddr-form-input" placeholder="请填写详细地址">
            </span>
        </label>
        <button class="eaddr-button" id="btn">保存</button>
    </form>
    <input type="hidden" id="linker_id" value="<?php echo $data->linker_id;?>">
    <input type="hidden" id="type" value="<?php echo $type;?>">
</section>
<script src="/js/zepto1.1.6.min.js"></script>
<!--<script src="/js/wap/zepto.deffered.js"></script>-->
<!--<script src="/js/wap/zepto.callbacks.js"></script>-->
<!--<script type="text/javascript" src="/js/wap/dialog.js"></script>-->
<!--<script type="text/javascript" src="/js/wap/mobile-select-area.js"></script>-->
    <script type="text/javascript" src="/js/strategy.main.js"></script>
<script>
    (function(){
        var selectArea = new MobileSelectArea();
        selectArea.init({
            trigger:'#txt_area',
            value:$('#hd_area').val(),
            data:'/js/wap/area.json'
        });

        var subBtn = $("#btn"),
            loginTip = $("#tipsDia"),
            name = $("#name"),
            area = $("#txt_area"),
            address = $("#address"),
            nameReg = /^[\u4E00-\u9FA5]+$/,
            phone = $("#phone"),
            phoneReg = /^1\d{10}$/,
            submitBtn = $("#submitBtn"),
            addr_id = $("#addr_id").val(),
            type=$("#type").val(),
            linker_id = $("#linker_id").val();

        if(linker_id==0 && type!=1){
            name.val(localStorage.getItem("default_linker_name"));
            phone.val(localStorage.getItem("default_linker_tel"))
        }



        subBtn.on("touchstart",function(e){
            e.preventDefault();
            var nameValue = $.trim(name.val()),
                phoneValue = $.trim(phone.val()),
                areaValue = $.trim(area.val()),
                addressValue = $.trim(address.val());


            if (nameValue == "") {
                loginTip.text("您还未输入姓名");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    subBtn.attr('disabled', false);
                },2000);
                name.focus();
                return false;
            }

            if (!nameReg.test(nameValue)) {
                loginTip.text("请输入中文名字");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    subBtn.attr('disabled', true);
                },2000);
                name.focus();
                return false;
            }

            if (phoneValue == "") {
                loginTip.text("您还未输入手机号");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    subBtn.attr('disabled', true);
                },2000);
                phone.focus();
                return false;
            }

            if (!phoneReg.test(phoneValue)) {
                loginTip.text("您输入手机号有误");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    subBtn.attr('disabled', true);
                },2000);
                phone.focus();
                return false;
            }

            if (areaValue == "") {
                loginTip.text("您还选择所在地区");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    subBtn.attr('disabled', true);
                },2000);
                area.focus();
                return false;
            }

            if (addressValue == "") {
                loginTip.text("您还输入详细地址");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    subBtn.attr('disabled', true);
                },2000);
                address.focus();
                return false;
            }

            subBtn.text("提交中...");
            subBtn.addClass("grey");

            var data = {"uid":<?php echo $_COOKIE['uid'] ? $_COOKIE['uid'] : 0;?>,'name':nameValue,"phone":phoneValue,"address":addressValue,'id':linker_id,'province':areaValue};

            $.ajax({
                type:'POST',
                url:"/user/phone/editphone",
                dataType:'json',
                async: true,
                data:data,
                headers: {
                    "VER": 10
                },
                success: function (result) {
                    if (result.response_params.status == 0) {
                        loginTip.text(result.response_params.message);
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                            subBtn.attr('disabled', false);
                            subBtn.text("保存");
                            subBtn.removeClass("grey");
                        },2000);
                        return false;
                    } else {
                        //todo 成功
                        //window.location.href = "";
                        //console.log(result.response_params);
                        loginTip.text(result.response_params.message);
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                            subBtn.attr('disabled', false);
                            subBtn.text("保存");
                            subBtn.removeClass("grey");
                        },2000);

                       window.location.href=document.referrer;
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                    if (XMLHttpRequest.status == 401) {
                        //todo 跳转授权页面
                        //alert(XMLHttpRequest.responseJSON.message);
                        window.location.href = '<?php echo $authorUrl;?>';
                    }
                    else if (XMLHttpRequest.status == 403) {
                        alert('接口验证失败，非法访问');
                    }
                    else if (XMLHttpRequest.status == 400) {
//                            window.location.href = '<?php //echo $authorUrl;?>//';
                        alert('请求参数错误:' + XMLHttpRequest.error_msg);
                    }
                    else {
                        alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                    }
                }
            })

        });
    }());
</script>
</body>

</html>

