<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>玩翻天礼包大派送</title>
    <meta name="format-detection" content="telephone=no, email=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="no-cache,must-revalidate" http-equiv="Cache-Control">
    <meta content="no-cache" http-equiv="pragma">
    <meta content="telephone=no, address=no" name="format-detection">
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <link href="/css/invite.css?t=<?php echo time(); ?>" rel="stylesheet" />
    <style>
        body{
            background: #f7f7f7;
        }
    </style>

    <!--    <script>(function(){var w=window.screen.width,s=w/750,u=navigator.userAgent,m='<meta name="viewport" content="width=750,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>-->
</head>
<body >

<div class="bg-prize">
    <div class="bg-content">
        <a class="invite-btn" href="/webinvite/index">
            <a href="/web/wappay/nindex" style="font-size: 16px;"><?php echo $msg; ?></a>
            <span class="circle-top"></span>
            <span class="circle-right"></span>
            <span class="circle-bottom"></span>
            <span class="circle-left"></span>
        </a>
    </div>

</div>


</body>
</html>