<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="format-detection" content="telephone=no, email=no" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="no-cache,must-revalidate" http-equiv="Cache-Control">
    <meta content="no-cache" http-equiv="pragma">
    <meta content="telephone=no, address=no" name="format-detection">
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <title>玩翻天活动签到</title>
    <link rel="stylesheet" href="/css/h5/ground_new.css?t=<?php echo time(); ?>" />
</head>
<body>
    <section class="gift">
        <div class="gift-box">
            <div class="gift-box-bag">
                <img src="/images/ground/q-wft-check.png" class="gift-box-qcheck">
                <input type="tel" name="tel" placeholder="输入您的手机号" class="gift-box-tel">
                <button class="gift-box-obtain" id="q_submit" style="z-index: 9999;">获取验证码</button>
                <input type="text" name="text" placeholder="输入验证码" class="gift-box-qcode">
                <a href="#" class="gift-box-get" id="submit">
                    <button class="gift-box-btn">
                        <img src="/images/ground/q-btn-check.png" class="gift-box-qbtn">
                    </button>
                </a>
            </div>
        </div>
        <img src="/images/ground/logo.png" class="gift-box-logo">
    </section>
    <?php echo $this->partial('web/generalize/shareq.phtml'); ?>
</body>
<script type="text/javascript" src="/js/jquery.min.js"></script>

<script type="text/javascript">
    (function () {
        var oTel = $('.gift-box-tel');
        var oQcode = $('.gift-box-qcode');
        var getVcodeBtn = $('#q_submit');
        var curCount = 0;
        var city = '<?php echo $city; ?>';
        var backurl = '<?php echo $backurl; ?>';
        var tourl = '<?php echo $tourl; ?>';

        /*获取验证码*/
        getVcodeBtn.on('click', function () {
            if (!(oTel.val() && /^1\d{10}$/.test(oTel.val()))) {
                alert("请输入正确的手机号以获取验证码！");
                return;
            }

            $.ajax({
                type: "POST",
                url: "/user/login/getcode",
                async: true,
                data: {'phone': oTel.val(), 'wap': 1},
                headers: {
                    "VER": 10
                },
                success: function (result) {
                    if (result.response_params.status == 0) {
                        alert(result.response_params.message);
                        $('#q_submit').css("pointer-events", "auto");
                    } else {
                        setVCodeBtn();
                    }
                },
                error: function (XMLHttpRequest) {
                    if (XMLHttpRequest.status == 401) {
                        window.location.href = '<?php echo $authorUrl;?>';
                    }
                    else if (XMLHttpRequest.status == 403) {
                        alert('接口验证失败，非法访问');
                    }
                    else if (XMLHttpRequest.status == 400) {
                        alert('请求参数错误');
                    }
                    else {
                        alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                    }
                }

            });
        });

        function setVCodeBtn() {
            getVcodeBtn.text("" + curCount + "s");
            InterValObj = window.setInterval(SetRemainTime, 1000); //启动计时器，1秒执行一次
            getVcodeBtn.addClass('gray-bg');
        };

        function SetRemainTime() {
            curCount--;
            if (curCount == 0) {
                window.clearInterval(InterValObj);//停止计时器
                getVcodeBtn.css("pointer-events", "auto");
                getVcodeBtn.text("重新获取");
                getVcodeBtn.removeClass('gray-bg');
            }
            else {
                getVcodeBtn.text("" + curCount + "s");
                getVcodeBtn.attr({"disabled": "disabled"});
            }
        }


        /*提交*/
        $("#submit").on('click', function () {
            if (!(oTel.val() && /^1\d{10}$/.test(oTel.val()))) {
                alert("请输入正确的手机号并获取验证码！");
                return;
            }
            if (!oQcode.val()) {
                alert("请输入验证码！");
                return;
            }

            $.ajax({
                type: "POST",
                url: "/user/login/wapregister",
                async: true,
                data: {'phone': oTel.val(), 'code': oQcode.val(), 'uid':<?php echo $uid; ?>, 'wap': 1, 'is_weixin': 1},
                headers: {
                    "VER": 10,
                    "CITY": encodeURI(city)
                },
                success: function (result) {
                    if (result.response_params.status == 0) {
                        alert(result.response_params.message);
                        loginAble = true;
                    } else {
                        // 成功
                        alert('签到成功');
                        window.location.href = tourl;
                        return false;
                    }
                },
                error: function (XMLHttpRequest) {
                    if (XMLHttpRequest.status == 401) {
                        window.location.href = '<?php echo $authorUrl;?>';
                    }
                    else if (XMLHttpRequest.status == 403) {
                        alert('接口验证失败，非法访问');
                    }
                    else if (XMLHttpRequest.status == 400) {
                        alert('请求参数错误');
                    }
                    else {
                        alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                    }
                }

            });
        })
    })();
</script>

</html>