
    <a class="features-choice" href="/web/wappay/nindex">
        <span>精选</span>
    </a>
    <a class="features-find" href="/web/tag/category?order=ticket&age_min=0&age_max=100">
        <span>发现</span>
    </a>
    <a class="features-child" href="/web/kidsplay/index">
        <mark></mark>
        <span>遛娃</span>
    </a>
    <a class="features-ticket" href="/web/coupon/allcoupon">
        <span>买票</span>
    </a>
    <a class="features-person" href="/web/wappay/my" id="my_menu">
        <span>我的</span>
    </a>
    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "//hm.baidu.com/hm.js?a1b66f5bbc7b8808ef15aef7c152d9eb";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        }());
    </script>

