<link rel="stylesheet" href="/js/wap/plugin/laydate/skins/molv/laydate.css?ver=<?php echo time();?>">
<hgroup class="box">
    <header>
        <h3>验证码信息</h3>
        <i class="icon icon-list"></i>
        <a href="javascript:history.go(-1)">活动订单详情</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<header class="box-title">验证码信息 <mark>
<!--        (点击出行人和身份证号可直接修改)-->
    </mark></header>

<div class="box">
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">选择</th>
                <th width="120">验证码</th>
                <th width="120">出行人数</th>
<!--                <th width="160">出行人身份证号</th>-->
<!--                <th width="100">投保状态</th>-->
<!--                <th width="120">保险号</th>-->
                <th width="100">项目名称</th>
                <th width="80">单价</th>
                <th width="100">状态</th>
                <th width="100">操作</th>
            </tr>
            <?php foreach ($codeData as $key => $row): ?>
                <tr style="text-align: left">
                    <td width="50">
                        <input type="checkbox" name="check_ids" value="<?php echo $row['id']; ?>" class="check_ids" data-insure-id="<?php echo $row['insure_id'];?>"></td>
                    <td width="120">
                        <?php echo $row['code'];?>
                    </td>
<!--                    <td width="120" class="policy_name" onclick="QuickModifyVal(this);" data="--><?php //echo $row['order_sn'];?><!--">-->
<!--                        <span class="t_--><?php //echo $row['associates_id'];?><!-- travel" data-id="--><?php //echo $row['associates_id'];?><!--" data-field="name" data-val="--><?php //echo $row['name'];?><!--" data-uid="--><?php //echo $row['uid'];?><!--" style="text-align: center">-->
<!--                           --><?php //echo $row['name'];?>
<!--                        </span>-->
<!--                    </td>-->
                    <td width="50" class="policy_num" >
                        <span>
                            <?php echo $row['person']; ?>
                        </span>
                    </td>
<!--                    <td width="100">-->
<!--                        --><?php
//                            if($row['insure_status']==0){
//                                echo '未填写信息';
//                            }elseif($row['insure_status']==1){
//                                echo '未投保';
//                            }elseif($row['insure_status']==2){
//                                echo '投保中';
//                            }elseif($row['insure_status']==3){
//                                echo '已投保';
//                            }else{
//                                echo '投保失败';
//                            }
//                        ?>
<!--                    </td>-->
<!--                    <td width="150">-->
<!--                        --><?php //echo $row['insure_sn'];?>
<!--                    </td>-->
                    <td width="50">
                        <?php echo $row['price_name'];?>
                    </td>
                    <td width="50"><?php echo $row['price']; ?></td>
                    <td width="50">
                        <?php
                        if($row['status']==0){
                            echo '待使用';
                        }elseif($row['status']==1){
                            echo '已使用';
                        }elseif($row['status']==2){
                            echo '已退款';
                        }elseif($row['status']==3){
                            echo '退款中';
                        }else{
                            echo '已使用';
                        }
                        ?>
                    </td>
                    <td width="300">
                        <a href="/wftadlogin/excercise/validate?code=<?php echo $row['code'];?>&order_sn=<?php echo $row['order_sn'];?>&type=1"  class="
 ui-button validate">验证</a>
                        <a href="javascript:void(0)" class="ui-button policy" data-insure-id="<?php echo $row['insure_id'];?>" data-src="/wftadlogin/excercise/edittravel?order_sn=<?php echo $row['order_sn'];?>">投保</a>
                        <?php if($row['status'] == 0):?>
                        <a href="/wftadlogin/excercise/back?cid=<?php echo $row['id'];?>&order_sn=<?php echo $row['order_sn'];?>&type=1" class="ui-button back" >退款</a>
                        <?php endif;?>
                        <?php if ($row['status'] == 1 && !(int)$row['back_money']): ?>
                            <a href="javascript:void(0)" class="ui-button special_back"
                               data-src="<?php echo $row['id']; ?>" data-money="<?php echo $row['price']; ?>">特殊退款</a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <input type="checkbox" class="check-all" data="1">全选
        <button onclick="if(confirm('批量验证?')==false) return false;" class="ui-button validateAll validate" data="2">批量验证</button>
        <button onclick="if(confirm('批量投保?')==false) return false;" class="ui-button policy" data="2">批量投保</button>
        <button onclick="if(confirm('批量退款?')==false) return false;" class="ui-button backAll back" data="2">批量退款</button>
    </div>
</div>

<header class="box-title" style="margin-top: 50px;">附加码信息</header>

<div class="box">
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">选择</th>
                <th width="120">附加码</th>
                <th width="100">项目名称</th>
                <th width="80">单价</th>
                <th width="100">状态</th>
                <th width="100">操作</th>
            </tr>
            <?php foreach ($extraData as $key => $row): ?>
                <tr style="text-align: left">
                    <td width="50">
                        <input type="checkbox" name="extra_check_ids" value="<?php echo $row['id']; ?>" class="extra_check_ids"></td>
                    <td width="120">
                        <?php echo $row['code'];?>
                    </td>
                    <td width="50">
                        <?php echo $row['price_name'];?>
                    </td>
                    <td width="50"><?php echo $row['price']; ?></td>
                    <td width="50">
                        <?php
                        if($row['status']==0){
                            echo '待使用';
                        }elseif($row['status']==1){
                            echo '已使用';
                        }elseif($row['status']==2){
                            echo '已退款';
                        }elseif($row['status']==3){
                            echo '退款中';
                        }else{
                            echo '已使用';
                        }
                        ?>
                    </td>
                    <td width="300">
                        <a href="/wftadlogin/excercise/validate?code=<?php echo $row['code'];?>&order_sn=<?php echo $row['order_sn'];?>&type=1"  class="
 ui-button validate" >验证</a>
                        <a href="/wftadlogin/excercise/back?cid=<?php echo $row['id'];?>&order_sn=<?php echo $row['order_sn'];?>&type=1" class="ui-button back" >退款</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <input type="checkbox" class="check-all" data="2">全选
        <button onclick="if(confirm('批量验证?')==false) return false;" class="ui-button validateAll validate" data="extra">批量验证</button>
        <button onclick="if(confirm('批量退款?')==false) return false;" class="ui-button backAll back" data="extra">批量退款</button>
    </div>
</div>
<div id="tipsDia"></div>
<input type="hidden" name="ids" id="ids" value="">
<div id="LoginBox">
    <div class="row1">
        请选择保险生效时间<a href="javascript:void(0)" title="关闭窗口" class="close_btn" id="closeBtn">×</a>
    </div>
    <div class="row">
        开始日：<li class="laydate-icon" id="start" style="width:200px; margin-right:10px;"></li>
        结束日：<li class="laydate-icon" id="end" style="width:200px;"></li>
    </div>
    <div class="row" style="margin-top:130px;">
        <a href="#" id="loginbtn">确定</a>
    </div>
</div>
<style>
    #tipsDia{display: none; width: 40%; background-color: rgba(0,0,0,0.5); color: #fff; position: fixed; left: 50%;top: 40%; z-index: 99999; text-align: center; letter-spacing: 2px; -webkit-transform: translate(-50%, -40%); -moz-transform: translate(-50%, -40%); -ms-transform: translate(-50%, -40%); transform: translate(-50%, -40%); padding: 5%; box-sizing: border-box; border-radius: 10px 10px 10px 10px;font-size: 25px; }

    .btn-info {
        background-image: linear-gradient(to bottom, #5bc0de 0px, #2aabd2 100%);
        background-repeat: repeat-x;
        border-color: #28a4c9;
    }
    .btn {
        position: relative;
        cursor: pointer;
        display: inline-block;
        vertical-align: middle;
        font-size: 12px;
        font-weight: bold;
        height: 27px;
        line-height: 27px;
        min-width: 52px;
        padding: 0 12px;
        text-align: center;
        text-decoration: none;
        border-radius: 2px;
        border: 1px solid #ddd;
        color: #666;
        background-color: #f5f5f5;
        background: -webkit-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: -moz-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: linear-gradient(top, #F5F5F5, #F1F1F1);
    }

    .login-body {
        padding: 60px 15px;
        color: #444;
        height: 148px;
    }

    .ipt {
        border: solid 1px #d2d2d2;
        border-left-color: #ccc;
        border-top-color: #ccc;
        border-radius: 2px;
        box-shadow: inset 0 1px 0 #f8f8f8;
        background-color: #fff;
        padding: 4px 6px;
        height: 21px;
        line-height: 21px;
        color: #555;
        width: 180px;
        vertical-align: baseline;
    }

    .dform {
        padding: 80px 60px 40px;
        text-align: center;
    }

    .dform2 {
        padding: 50px 60px 40px;
        text-align: center;
    }

    .signin {
        margin: -50px -20px -50px 90px;
        text-align: left;
        font-size: 14px;
    }

    .signin h4 {
        color: #999;
        font-weight: 100;
        margin-bottom: 20px;
        font-size: 12px;
    }

    .signin li {
        padding-left: 80px;
        margin-bottom: 15px;
    }

    .signin ol {
        list-style-type: none;
    }

    .signin li strong {
        float: left;
        margin-left: -80px;
        width: 80px;
        text-align: right;
        line-height: 32px;
    }

    .signin .btn {
        margin-bottom: 10px;
    }

    .signin p {
        font-size: 12px;
        color: #999;
    }

    .theme-desc,.theme-version {
        padding-top: 0
    }

    .cssInput{
        width:150px;
    }
    #tongji{
        padding:5px 5px;
        margin: 5px 5px;
    }
    #tongji span{
        color:red;
        font-size:16px;
        padding: 10px;
    }
    .body-color {
        z-index: 9998;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: #000;
        opacity: 0.4;
        filter: alpha(opacity = 40);
        display: none
    }

    .hide-body {
        z-index: 9999;
        position: fixed;
        top: 60%;
        left: 50%;
        width: 500px;
        height: 200px;
        margin: -180px 0 0 -250px;
        border-radius: 5px;
        border: solid 2px #666;
        background-color: #fff;
        box-shadow: 0 0 10px #666;
        display: none;
    }

    .close-window {
        border-bottom: 1px solid #ddd;
        padding: 22px;
        position: relative;
    }

    .bottom {
        margin-top: 180px;
    }

    .close-window .close {
        float: right;
        color: #999;
        padding: 5px;
        margin: -2px -5px -5px;
        font: bold 14px/14px simsun;
        text-shadow: 0 1px 0 #ddd
    }

    .close-window .close:hover {
        color: #444;
    }

    .validate {
        color: #fff;
        border-radius: 4px;
        border: 1px solid #FCF8E3;
        background-color: #9CCC65;
        cursor: pointer;
        outline: none;
        user-select: none;
        -moz-user-select: none;
        -webkit-user-select: none;
        text-decoration: none;
    }
    .policy{
        border-radius: 4px;
        background-color: #FFA625;
        border: 1px solid #FCF8E3;
        cursor: pointer;
        outline: none;
        user-select: none;
        -moz-user-select: none;
        -webkit-user-select: none;
        text-decoration: none;
    }
</style>
<div class="hide-body">
    <div class="close-window">
        <!-- 关闭窗口，也就是触发关闭div的事件-->
        <a href="javascript:;" title="关闭" class="close">×</a>
        <h3 style="text-align: center">填写出行人信息</h3>
    </div>
    <!-- 中间主体显示div 可以增加其他的样式-->
    <div class="login-body dform">
        <form class="signin" name="loginform" action="" id="zjh" method="post" autocomplete="off">
            <input name="name" type="text " class="cssInput name" placeholder="请输入姓名"/>
            <input name='id_num' type="text " class="cssInput id_num" placeholder="请输入身份证号" />
            <button  type="submit" id="validate" style="margin-left: 10px">确定</button>
        </form>
    </div>
</div>

<div style="height: 400px;" class="hide-body special_back_body">
    <div class="close-window special_back_close">
        <!-- 关闭窗口，也就是触发关闭div的事件-->
        <a href="javascript:;" title="关闭" class="close">×</a>
        <h3 style="text-align: center">活动订单特殊退款</h3>
    </div>
    <!-- 中间主体显示div 可以增加其他的样式-->
    <div class="login-body dform2">
        <form class="" style="text-align: left;" name="backform" action="/wftadlogin/YardsCode/special" id="spback" method="post" autocomplete="off">
            <input id="code_id" type="hidden" value="" name="code_id" />
            <table>
                <tr><td>退款理由：</td><td><textarea style="width: 300px" name="reason" rows="5" ></textarea></td></tr>
                <tr><td>退款金额：</td><td><input style="width: 80px" name="money" type="text " class="cssInput"/> 可退的金额是<span id="can-back-money"></span></td></tr>
                <tr><td></td><td><button type="submit" id="validate" style="margin-left: 10px">提交</button></td></tr></table>
        </form>
    </div>
</div>

<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/wap/plugin/laydate/laydate.js"></script>
<script>
    var loginTip = $("#tipsDia");

    $(function () {
        //全选和全不选
        $('.check-all').click(function() {
            if($(this).attr('data')==1){
                if ($(this).is(':checked')) {
                    $("[name=check_ids]:checkbox").prop('checked', true);
                } else {
                    $("[name=check_ids]:checkbox").prop('checked', false);
                }
            }else{
                if ($(this).is(':checked')) {
                    $("[name=extra_check_ids]:checkbox").prop('checked', true);
                } else {
                    $("[name=extra_check_ids]:checkbox").prop('checked', false);
                }
            }

        });

        $('.special_back').click(function () { //jquery的点击事件
            $('.special_back_body').fadeIn(100);//全局变得黑的效果，具体的div就是theme-popover-mask这个
            $('.special_back_close').slideDown(200);//将隐藏的窗口div显示出来
            var sn = $(this).attr('data-src');
            var money = $(this).attr('data-money');
            $('#code_id').val(sn);
            $('#can-back-money').html(money);
            $('#special_back').click(function () {
                var rs = $(this).parent().find('textarea').val();
                var money = $(this).parent().find('input').val();
                if (rs && money) {

                } else {
                    alert("理由或金额！");
                    return false;
                }
            });
        });

        //投保
        var start = {
            elem: '#start',
            format: 'YYYY/MM/DD',
//            min: laydate.now(), //设定最小日期为当前日期
            max: '2099-06-16', //最大日期
            istime: true,
            istoday: false,
            choose: function(datas){
                end.min = datas; //开始日选好后，重置结束日的最小日期
                end.start = datas; //将结束日的初始值设定为开始日
            }
        };
        var end = {
            elem: '#end',
            format: 'YYYY/MM/DD',
//            min: laydate.now(),
            max: '2099-06-16',
            istime: true,
            istoday: false,
            choose: function(datas){
                start.max = datas; //结束日选好后，重置开始日的最大日期
            }
        };
        laydate(start);
        laydate(end);

        $(".policy").on("click",function(){

            var data = $(this).attr('data');

            if (confirm('确定将选中的人员投保？不可恢复')){
                var id='';//如果这样定义var s;变量s中会默认被赋个null值
                if(data==2){
                    var check_ids = document.getElementsByName('check_ids');
                    for (var i = 0; i < check_ids.length; i++) {
                        if (check_ids[i].checked){
                            if (i == check_ids.length - 1) {
                                id += check_ids[i].getAttribute('data-insure-id');
                            } else {
                                id += check_ids[i].getAttribute('data-insure-id') + '@';
                            }
                        }
                    }
                }else{
                    id = $(this).attr('data-insure-id');
                }


                if (id == '') {
                    if(data==2){
                        loginTip.text("没有选中任何订单");
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                        },2000);
                        return false;
                    }else{
                        loginTip.text("出行人信息不完整");
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                        },2000);
                        return false;
                    }
                } else {
                    $("body").append("<div id='mask'></div>");
                    $("#mask").addClass("mask").fadeIn("slow");
                    $("#LoginBox").fadeIn("slow");
                    $("#ids").val(id);
                }
            }

        });

        //按钮的透明度
        $("#loginbtn").hover(function () {
            $(this).stop().animate({
                opacity: '1'
            }, 600);
        }, function () {
            $(this).stop().animate({
                opacity: '0.8'
            }, 1000);
        });

        //文本框不允许为空---按钮触发
        $("#loginbtn").on('click', function () {
            var start = $("#start").text();
            var end = $("#end").text();
            if (start == "" || end == "") {
                loginTip.text("保险日期为必填项");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                },2000);
                return false;
            }
            var ids = $("#ids").val();

            $.post("/wftadlogin/excercise/policy",{"insure_id":ids,"start":start,'end':end},function(d){
                if(d.status==0){
                    loginTip.text("请选择要操作的订单");
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                }else{
                    loginTip.text(d.message);
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                    setTimeout(function(){window.location.reload();},2500);
                }
            },'json');

        });

        //关闭
        $(".close_btn").hover(function () { $(this).css({ color: 'black' }) }, function () { $(this).css({ color: '#999' }) }).on('click', function () {
            $("#LoginBox").fadeOut("fast");
            $("#mask").css({ display: 'none' });
        });

        //批量验证
        $('.validateAll').click(function() {
            if (confirm('确定将所有选中的验证码批量验证？不可恢复')) {
                //执行修改操作
                var data = $(this).attr('data');
                var href = '/wftadlogin/excercise/validate?type=2';//跳转的链接
                var check_ids='';
                if(data=='extra'){
                    check_ids = document.getElementsByName('extra_check_ids');
                }else{
                    check_ids = document.getElementsByName('check_ids');
                }

                var id='';//如果这样定义var s;变量s中会默认被赋个null值
                for (var i = 0; i < check_ids.length; i++) {
                    if (check_ids[i].checked){
                        if (i == check_ids.length - 1) {
                            id += check_ids[i].value;
                        } else {
                            id += check_ids[i].value + ',';
                        }
                    }
                }

                if (id == '') {
                    alert('没有选中任何验证码');
                } else {
                    window.location.href = href + '&code=' + id;
                }
            }
        });

        //批量退费
        $('.backAll').click(function() {
            if (confirm('确定将所有选中的验证码批量退费？不可恢复')) {
                //执行修改操作
                var data = $(this).attr('data');
                var href = '/wftadlogin/excercise/back?type=2';//跳转的链接
                var check_ids='';
                if(data=='extra'){
                    check_ids = document.getElementsByName('extra_check_ids');
                }else{
                    check_ids = document.getElementsByName('check_ids');
                }
                var id='';//如果这样定义var s;变量s中会默认被赋个null值
                for (var i = 0; i < check_ids.length; i++) {
                    if (check_ids[i].checked){
                        if (i == check_ids.length - 1) {
                            id += check_ids[i].value;
                        } else {
                            id += check_ids[i].value + ',';
                        }
                    }
                }

                if (id == '') {
                    alert('没有选中任何验证码');
                } else {
                    window.location.href = href + '&cid=' + id;
                }
            }
        });
    });

    //快速修改字段值
    function QuickModifyVal(obj){
        var sVal = $(obj).find('span').text();
        var oldVal = $(obj).find('span').attr('data-val');
        var sField = $(obj).find('span').attr('data-field');
        var sDataID = $(obj).find('span').attr('data-id');
        var sUid = $(obj).find('span').attr('data-uid');
        var order_sn = $(obj).attr('data');
        var type=0;
        if(!sDataID){
            type=1;
            sDataID = order_sn;
        }

        var sHtml = '<input type="text" name="qm_'+ sField +'" id="qm_'+ sField +'" class="form-control" value="'+ sVal +'">';
        $(obj).find('span').html(sHtml);

        $('#qm_'+ sField).focus().blur(function(){
            if($(this).val() != ''){
                ExecModifyVal(obj, sVal, $(this).val(), sField, sDataID,type);
            }else{
                $(obj).find('span').html(oldVal);
            }
        }).keypress(function(e){
            var curKey = e.which;

            if (curKey == 13) {
                if($(this).val() != ''){
                    ExecModifyVal(obj, sVal, $(this).val(), sField, sDataID,type);
                }else{
                    $(obj).find('span').html(oldVal);
                }
            }
        });

    }

    //执行修改操作
    function ExecModifyVal(obj, sval, snewval, sfield, dataid,type){
        if(snewval.trim() == sval.trim() || snewval.trim()==''){
            $(obj).find(span).html(sval);
        }else{
            $.ajax({
                type: "POST",
                url: "/wftadlogin/excercise/quickmodifyval",
                dataType:"json",
                data:{"key":sfield, "val":snewval, "id":dataid,'type':type},
                beforeSend:function(){
                    loginTip.text("正在处理...");
                    loginTip.show();
                },
                success: function(data){
                    if(data.status==1){
                        $(obj).find('span').html(data.data);
                        loginTip.text(data.message);
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                        },1000);
                    }else{
                        loginTip.text(data.message);
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                        },1200);
                    }
                }
            });
        }
    }

    //新增出行人
    function addTravel(obj){
        $('.body-color').fadeIn(100);//全局变得黑的效果，具体的div就是theme-popover-mask这个
        $('.hide-body').slideDown(200);//将隐藏的窗口div显示出来
        var url = $(obj).attr('data-src');
        $('#validate').click(function(){
            var name = $(this).parent().find('.name').val();
            var id_num = $(this).parent().find('.id_num').val();
            if(name && id_num){
                $('#zjh').attr('action', url);
            }else{
                alert("请输入完整信息！");
                return false;
            }
        });
    }
    $('.close-window .close').click(function(){
        $('.body-color').fadeOut(100);//
        $('.hide-body').slideUp(200);//将显示的窗口隐藏起来
    });
</script>



