<hgroup class="box">
    <header>
        <h3>活动列表管理</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/excercise/new">添加活动</a>
        &nbsp;&nbsp;&nbsp;
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>

        <div>温馨提示：<span style="color:green">有问题 请及时联系</span></div>
    </aside>
</hgroup>

<form class="box box-form" action="/wftadlogin/excercise" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $begin_time = null;
    $end_time = null;
    $bid = null;
    $eid = null;
    $name = null;
    $type = null;
    $city = null;

    if (isset($_GET['start_time']) && $_GET['start_time']) {
        $start_time = $_GET['start_time'];
    }

    if (isset($_GET['end_time']) && $_GET['end_time']) {
        $end_time = $_GET['end_time'];
    }

    if (isset($_GET['bid']) && $_GET['bid']) {
        $bid = $_GET['bid'];
    }

    if (isset($_GET['eid']) && $_GET['eid']) {
        $eid = $_GET['eid'];
    }

    if (isset($_GET['name']) && $_GET['name']) {
        $name = $_GET['name'];
    }

    if (isset($_GET['city']) && $_GET['city']) {
        $city = $_GET['city'];
    }

    ?>
    <table class="table">
        <tr>
            <th width="160">场次时间</th>
            <th>
                <input name="start_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $start_time;?>">
                <input name="end_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $end_time;?>">
            </th>
            <th width="160"></th>
            <th>
            </th>
        </tr>

        <tr>
            <th width="160">活动ID</th>
            <th>
                <input type="text" class="cssInput" name="bid" value="<?php echo $bid;?>">
            </th>
            <th width="160">活动名称</th>
            <th>
                <input type="text" class="cssInput" name="name" value="<?php echo $name;?>">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/excercise" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">活动ID</th>
                <th class="size1">活动名称</th>
                <th class="size1">更新时间</th>
                <th class="size1">游玩地</th>
                <th class="size1">区域</th>
                <th class="size1">总场次</th>
                <th class="size1">已举办</th>
                <th class="size1">浏览</th>
                <th class="size1">评论</th>
                <th class="size1">分享</th>
                <th class="size1">咨询</th>
                <th class="size1">已报名</th>
                <th class="size1">虚拟票</th>
                <th class="size1">操作</th>
            </tr>
            <?php if (count($data)): ?>
                <?php $ec = new \Deyi\GetCacheData\ExcerciseCache(); ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size1">
                            <a href="/wftadlogin/excercise/edit?id=<?php echo $row['id']; ?>">
                                <?php echo $row['id']; ?>
                            </a>
                        </td>
                        <td class="size1"><?php echo $row['name']; ?></td>
                        <td class="size1"><?php echo date('Y-m-d H:i',$row['update_dateline']); ?></td>
                        <td class="size1"><?php echo rtrim($shop[$row['id']],',<br>'); ?></td>
                        <td class="size1"><?php echo rtrim($circle[$row['id']],',<br>'); ?></td>
                        <td class="size1">
                            <?php echo $row['all_number']; ?>
                        </td>
                        <td class="size1">
                            <?php echo $su[$row['bid']]?:0; ?>
                        </td>
                        <td class="size1"><?php echo $row['view_number']; ?></td>
                        <td class="size1"><?php echo $row['comment_number']; ?></td>
                        <td class="size1">
                            <?php echo $row['share_number']; ?>
                        </td>
                        <td class="size1">
                            <?php echo $row['query_number']; ?>
                        </td>
                        <td class="size1">
                            <?php echo $row['join_number']; ?>
                        </td>
                        <td class="size1"><?php echo (int)$row['vir_ault'] + (int)$row['vir_child']; ?></td>
                        <td class="size3">
                            <a href="/wftadlogin/excercise/edit?id=<?php echo $row['id']; ?>"
                               class="ui-button">编辑</a>
                            <?php if ($row['release_status']==1): ?>
                                <a onclick= "if(confirm( '确定取消发布？ ')==false)return false;" href="/wftadlogin/excercise/status?id=<?php echo $row['id']; ?>&isclose=0"
                                   class="ui-button">取消发布</a>
                            <?php elseif($row['release_status']==0): ?>
                                <a onclick= "if(confirm( '确定发布？ ')==false)return false;" href="/wftadlogin/excercise/status?id=<?php echo $row['id']; ?>&isclose=1"
                                   class="ui-button">发布</a>
                            <?php endif; ?>
                            <a href="/wftadlogin/excercise/elist?bid=<?php echo $row['id']; ?>"
                               class="ui-button">场次</a>
                            <?php if ($row['release_status']): ?>
                            <a href="/wftadlogin/excercise/personlist?bid=<?php echo $row['id']; ?>"
                               class="ui-button">投保情况</a>
                            <?php endif; ?>
                            <a href="/wftadlogin/excercise/newc?id=<?php echo $row['id']; ?>"
                               class="ui-button">定制</a>
                            <a onclick="del_confirm(<?php echo $row['id']; ?>);" href="#"
                               class="ui-button">删除</a>
                            <a target="_blank" href="/wftadlogin/consult/virPost?type=activity&id=<?php echo $row['id']; ?>" class="ui-button">添加评论</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无内容 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    function del_confirm(id)
    {
        var r=confirm("是否确定要删除？")
        if (r==true)
        {
            window.location.href="/wftadlogin/excercise/status?id="+id+"&isclose=-1";
        }

    }
</script>
