<link rel="stylesheet" href="/js/wap/plugin/laydate/skins/molv/laydate.css">
<style>
    .btn-info {
        background-image: linear-gradient(to bottom, #5bc0de 0px, #2aabd2 100%);
        background-repeat: repeat-x;
        border-color: #28a4c9;
    }
    .btn {
        position: relative;
        cursor: pointer;
        display: inline-block;
        vertical-align: middle;
        font-size: 12px;
        font-weight: bold;
        height: 27px;
        line-height: 27px;
        min-width: 52px;
        padding: 0 12px;
        text-align: center;
        text-decoration: none;
        border-radius: 2px;
        border: 1px solid #ddd;
        color: #666;
        background-color: #f5f5f5;
        background: -webkit-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: -moz-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: linear-gradient(top, #F5F5F5, #F1F1F1);
    }

    .login-body {
        padding: 60px 15px;
        color: #444;
        height: 148px;
    }

    .ipt {
        border: solid 1px #d2d2d2;
        border-left-color: #ccc;
        border-top-color: #ccc;
        border-radius: 2px;
        box-shadow: inset 0 1px 0 #f8f8f8;
        background-color: #fff;
        padding: 4px 6px;
        height: 21px;
        line-height: 21px;
        color: #555;
        width: 180px;
        vertical-align: baseline;
    }

    .dform {
        padding: 80px 60px 40px;
        text-align: center;
    }

    .signin {
        margin: -50px -20px -50px 90px;
        text-align: left;
        font-size: 14px;
    }

    .signin h4 {
        color: #999;
        font-weight: 100;
        margin-bottom: 20px;
        font-size: 12px;
    }

    .signin li {
        padding-left: 80px;
        margin-bottom: 15px;
    }

    .signin ol {
        list-style-type: none;
    }

    .signin li strong {
        float: left;
        margin-left: -80px;
        width: 80px;
        text-align: right;
        line-height: 32px;
    }

    .signin .btn {
        margin-bottom: 10px;
    }

    .signin p {
        font-size: 12px;
        color: #999;
    }

    .theme-desc,.theme-version {
        padding-top: 0
    }

    .cssInput{
        width:300px;
    }
    #tongji{
        padding:5px 5px;
        margin: 5px 5px;
    }
    #tongji span{
        color:red;
        font-size:16px;
        padding: 10px;
    }
    .body-color {
        z-index: 9998;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: #000;
        opacity: 0.4;
        filter: alpha(opacity = 40);
        display: none
    }

    .hide-body {
        z-index: 9999;
        position: fixed;
        top: 30%;
        left: 40%;
        width: 1000px;
        height: 618px;
        margin: -180px 0 0 -330px;
        border-radius: 5px;
        border: solid 2px #666;
        background-color: #fff;
        display: none;
        box-shadow: 0 0 10px #666;
    }

    .close-window {
        border-bottom: 1px solid #ddd;
        padding: 22px;
        position: relative;
    }

    .bottom {
        margin-top: 180px;
    }

    .close-window .close {
        float: right;
        color: #999;
        padding: 5px;
        margin: -2px -5px -5px;
        font: bold 14px/14px simsun;
        text-shadow: 0 1px 0 #ddd
    }

    .close-window .close:hover {
        color: #444;
    }
    
    .til{
        margin-left:10px;
    }
    
    .til span{
        padding: 20px;
    }

    #tipsDia{display: none; width: 40%; background-color: rgba(0,0,0,0.5); color: #fff; position: fixed; left: 50%;top: 40%; z-index: 99999; text-align: center; letter-spacing: 2px; -webkit-transform: translate(-50%, -40%); -moz-transform: translate(-50%, -40%); -ms-transform: translate(-50%, -40%); transform: translate(-50%, -40%); padding: 5%; box-sizing: border-box; border-radius: 10px 10px 10px 10px;font-size: 25px; }
</style>
<hgroup class="box">
    <header>
        <h3>活动管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/excercise">活动列表</a>
        &nbsp;&nbsp;&nbsp;
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/excercise/personlist?bid=<?php echo $_GET['bid']; ?>&id=<?php echo $_GET['id'];?>">人员名单</a>
        &nbsp;&nbsp;&nbsp;

    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $user_id = null;
    $order_sn = null;
    $user_name = null;
    $traveller = null;
    $phone = null;
    $buy_start = null;
    $buy_end = null;
    $pageNum = 10;

    if (isset($_GET['user_id']) && $_GET['user_id']) {
        $user_id = $_GET['user_id'];
    }

    if (isset($_GET['order_sn']) && $_GET['order_sn']) {
        $order_sn = $_GET['order_sn'];
    }

    if (isset($_GET['traveller']) && $_GET['traveller']) {
        $traveller = $_GET['traveller'];
    }

    if (isset($_GET['user_name']) && $_GET['user_name']) {
        $user_name = $_GET['user_name'];
    }

    if (isset($_GET['phone']) && $_GET['phone']) {
        $phone = $_GET['phone'];
    }

    if (isset($_GET['buy_start']) && $_GET['buy_start']) {
        $buy_start = $_GET['buy_start'];
    }
    if (isset($_GET['buy_end']) && $_GET['buy_end']) {
        $buy_end = $_GET['buy_end'];
    }


    ?>
    <div class="til">
       <p>
           <span>
               场次id
               <mark>
                   <?php echo $excerciseData[0]['id'];?>
               </mark>
           </span>
           <span>
               活动名称
               <mark>
                   <?php echo $excerciseData[0]['name'];?>
               </mark>
           </span>
           <span>
               场次时间
               <mark>
                   <?php echo date("Y-m-d",$excerciseData[0]['start_time']);?>~<?php echo date("Y-m-d",$excerciseData[0]['end_time']);?>
               </mark>
           </span>
           <span>
               游玩地
               <mark>
                   <?php echo $excerciseData[0]['shop_name'];?>
               </mark>
           </span>
           <span>
               场次状态
               <mark>
                   <?php if ($excerciseData[0]['sell_status'] ==3): ?>
                       已结束
                   <?php elseif($excerciseData[0]['sell_status'] == 0): ?>
                       暂停中
                   <?php elseif($excerciseData[0]['sell_status'] == -1): ?>
                       已删除
                   <?php elseif($excerciseData[0]['open_time'] >time()): ?>
                       未开始
                   <?php elseif($excerciseData[0]['over_time'] >time() && $excerciseData[0]['join_number']<$excerciseData[0]['perfect_number']): ?>
                       报名中
                   <?php elseif($excerciseData[0]['join_number']>=$excerciseData[0]['perfect_number']): ?>
                       已满员
                   <?php else: ?>
                       已结束
                   <?php endif; ?>
               </mark>
           </span>
       </p>
    </div>

    <input type="hidden" class="cssInput" name="id" value="<?php echo $_GET['id']; ?>">


    <input type="hidden" class="cssInput" name="bid" value="<?php echo $_GET['bid']; ?>">

    <input type="hidden" class="cssInput" name="out" id="out" value="0">

    <table class="table">
        <tr>
            <th width="120">用户ID</th>
            <th>
                <input type="text" class="cssInput" name="user_id" value="<?php echo $user_id;?>">
            </th>
            <th width="120">用户名</th>
            <th>
                <input type="text" class="cssInput" name="user_name" value="<?php echo $user_name;?>">
            </th>
            <th width="120">绑定手机号</th>
            <th>
                <input type="text" class="cssInput" name="phone" value="<?php echo $phone;?>">
            </th>
        </tr>

        <tr>
            <th width="120">订单号</th>
            <th>
                <input type="text" class="cssInput" name="order_sn" value="<?php echo $order_sn;?>">
            </th>

            <th width="120">出行人</th>
            <th>
                <input type="text" class="cssInput" name="traveller" value="<?php echo $traveller;?>">
            </th>
            <th width="120">下单时间</th>
            <th>
                <input type="date" class="cssInput" name="buy_start" value="<?php echo $buy_start;?>" style="width: 140px">
~
                <input type="date" class="cssInput" name="buy_end" value="<?php echo $buy_end;?>"style="width: 140px">
            </th>
        </tr>
        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/excercise/personlist" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button" id="tijiao">提交</button>
                <?php
                if($_GET['id']){
                    $path = 'id='.$_GET['id'];
                }elseif($_GET['bid']){
                    $path = 'bid='.$_GET['bid'];
                }
                ?>

                <button  class="ui-button" id="daochu" style="background-color: green">导出</button>

                <script>
                    $(function () {
                        $('#daochu').click(function () {
                                $('#out').val(1);
                        })

                        $('#tijiao').click(function () {
                            $('#out').val(0);
                        })
                    })
                </script>
            </th>
        </tr>
    </table>
</form>

<header class="box-title">人员名单 <mark>(点击出行人和身份证号可直接修改)</mark></header>
<div class="box">
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">选择</th>
                <th width="120">订单号</th>
                <th width="120">下单时间</th>
                <th width="80">用户ID</th>
                <th width="80">用户名</th>
                <th width="120">出行人</th>
                <th width="150">出行人身份证号</th>
                <th width="120">手机号</th>
                <th width="100">验证码</th>
                <th width="100">保险号</th>
                <th width="100">
                    <div class="dropdown">
                        <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenu1"
                                data-toggle="dropdown">
                            投保状态
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            <?php function getaccounturl($url = array())
                            {
                                $_GET[key($url)] = $url[key($url)];
                                return http_build_query($_GET);
                            }

                            ?>
                            <li role="presentation"><a role="menuitem" tabindex="-1"
                                                       href="/wftadlogin/excercise/personlist?id=<?php echo $excerciseData[0]['id'];?>&status=0">所有</a>
                            </li>
                            <li role="presentation"><a role="menuitem" tabindex="-1"
                                                       href="/wftadlogin/excercise/personlist?id=<?php echo $excerciseData[0]['id'];?>&status=1">未投保</a>
                            </li>
                            <li role="presentation"><a role="menuitem" tabindex="-1"
                                                       href="/wftadlogin/excercise/personlist?id=<?php echo $excerciseData[0]['id'];?>&status=2">投保不成功</a>
                            </li>
                            <li role="presentation"><a role="menuitem" tabindex="-1"
                                                       href="/wftadlogin/excercise/personlist?id=<?php echo $excerciseData[0]['id'];?>&status=3">投保成功</a>
                            </li>
                        </ul>
                    </div>
                </th>
                <th width="100">操作</th>
            </tr>

            <?php foreach ($data as $key => $row): ?>
                <tr style="text-align: left">
                    <td width="50">
                        <input type="checkbox" name="check_ids" value="<?php echo $row['insure_id']; ?>"  class="check_ids">
                    </td>
                    <td width="170"><?php echo $row['order_sn']; ?></td>
                    <td width="170"><?php echo date('Y-m-d H:i',$row['dateline']); ?></td>
                    <td width="50">
                        <?php echo $row['user_id'];?>
                    </td>
                    <td width="100">
                        <?php echo $row['username'];?>
                    </td>
                    <td width="100">
                        <span onclick="QuickModifyVal(this);" class="t_<?php echo $row['associates_id'];?>" data-id="<?php echo $row['associates_id'];?>" data-field="name" data-val="<?php echo $row['name'];?>">
                           <?php echo $row['name'];?>
                        </span>
                    </td>
                    <td width="150">
                        <span onclick="QuickModifyVal(this);" class="id_<?php echo $row['associates_id'];?>" data-id="<?php echo $row['associates_id'];?>" data-field="id_num" data-val="<?php echo $row['id_num'];?>">
                            <?php echo $row['id_num']; ?>
                        </span>
                    </td>
                    <td width="100"><?php echo ($row['buy_phone']);?></td>
                    <td width="100"><?php echo $row['code']; ?></td>
                    <td width="100"><?php echo $row['insure_sn']; ?></td>
                    <td width="100"><?php echo $row['insure_status']<2 ? '未投保' : ($row['insure_status']==3 ? '投保成功' : '投保失败'); ?></td>
                    <td width="300">
                            <a href="/wftadlogin/excercise/orderinfo?order_sn=<?php echo $row['order_sn'];?>"  class="ui-button">相关订单</a>
<!--                            <a href="javascript:void(0)" onclick="SafeData(this);" class="login btn" data-id="--><?php //echo $row['associates_id'];?><!--">修改信息</a>-->
                        <a href="javascript:void(0)" class="ui-button policy" data-insure-id="<?php echo $row['insure_id'];?>">投保</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <input type="checkbox" id="check-all">全选
        <button onclick="if(confirm('批量投保?')==false) return false;" class="ui-button policy" id="approve-by" data="2">批量投保</button>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>
<div id="LoginBox">
    <div class="row1">
        请选择保险生效时间<a href="javascript:void(0)" title="关闭窗口" class="close_btn" id="closeBtn">×</a>
    </div>
    <div class="row">
        开始日：<li class="laydate-icon" id="start" style="width:200px; margin-right:10px;"></li>
        结束日：<li class="laydate-icon" id="end" style="width:200px;"></li>
    </div>
    <div class="row" style="margin-top:130px;">
        <a href="#" id="loginbtn">确定</a>
    </div>
</div>
<div id="tipsDia"></div>
<input type="hidden" name="ids" id="ids">
<script type="text/javascript" src="/js/jquery.min.js"></script>
<!--<script type="text/javascript" src="/js/wap/plugin/loading.js"></script>-->
<script type="text/javascript" src="/js/wap/plugin/laydate/laydate.js"></script>
<script>
    var loginTip = $("#tipsDia");

    $(function () {
        var sell_status = <?php echo $excerciseData[0]['sell_status'];?>;

        var join_number=<?php echo (int)$excerciseData[0]['join_number'];?>;

        var least_number=<?php echo (int)$excerciseData[0]['least_number'];?>;
        //全选和全不选
        $('#check-all').click(function() {
            if ($(this).is(':checked')) {
                $("[name=check_ids]:checkbox").prop('checked', true);
            } else {
                $("[name=check_ids]:checkbox").prop('checked', false);
            }
        });

        var start = {
            elem: '#start',
            format: 'YYYY/MM/DD',
//            min: laydate.now(), //设定最小日期为当前日期
            max: '2099-06-16', //最大日期
            istime: true,
            istoday: false,
            choose: function(datas){
                end.min = datas; //开始日选好后，重置结束日的最小日期
                end.start = datas; //将结束日的初始值设定为开始日
            }
        };
        var end = {
            elem: '#end',
            format: 'YYYY/MM/DD',
//            min: laydate.now(),
            max: '2099-06-16',
            istime: true,
            istoday: false,
            choose: function(datas){
                start.max = datas; //结束日选好后，重置开始日的最大日期
            }
        };
        laydate(start);
        laydate(end);

        $(".policy").on("click",function(){

//            if(tipsDia<least_number){
//                loginTip.text("报名中场次人员不可以投保");
//                loginTip.show();
//                setTimeout(function(){
//                    loginTip.hide();
//                },2000);
//                return false;
//            }
            var data = $(this).attr('data');

            if (confirm('确定将选中的人员投保？不可恢复')){
                var id='';//如果这样定义var s;变量s中会默认被赋个null值
                if(data==2){
                    var check_ids = document.getElementsByName('check_ids');
                    for (var i = 0; i < check_ids.length; i++) {
                        if (check_ids[i].checked){
                            if (i == check_ids.length - 1) {
                                id += check_ids[i].getAttribute('data-insure-id');
                            } else {
                                id += check_ids[i].getAttribute('data-insure-id') + '@';
                            }
                        }
                    }
                }else{
                    id = $(this).attr('data-insure-id');
                }


                if (id == '') {
                    loginTip.text("没有选中任何订单");
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                    return false;
                } else {
                    $("body").append("<div id='mask'></div>");
                    $("#mask").addClass("mask").fadeIn("slow");
                    $("#LoginBox").fadeIn("slow");
                    $("#ids").val(id);
                }
            }

        });

        //按钮的透明度
        $("#loginbtn").hover(function () {
            $(this).stop().animate({
                opacity: '1'
            }, 600);
        }, function () {
            $(this).stop().animate({
                opacity: '0.8'
            }, 1000);
        });

        //文本框不允许为空---按钮触发
        $("#loginbtn").on('click', function () {
            var start = $("#start").text();
            var end = $("#end").text();
            if (start == "" || end == "") {
                loginTip.text("保险日期为必填项");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                },2000);
                return false;
            }
            var ids = $("#ids").val();

            $.post("/wftadlogin/excercise/policy",{"insure_id":ids,"start":start,'end':end},function(d){
                if(d.status==0){
                    loginTip.text("请选择要操作的订单");
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                }else{
                    loginTip.text(d.message);
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                    },2000);
                    setTimeout(function(){window.location.reload();},2500);
                }
            },'json');

        });

        //关闭
        $(".close_btn").hover(function () { $(this).css({ color: 'black' }) }, function () { $(this).css({ color: '#999' }) }).on('click', function () {
            $("#LoginBox").fadeOut("fast");
            $("#mask").css({ display: 'none' });
        });


    }());

    //快速修改字段值
    function QuickModifyVal(obj){
        var sVal = $(obj).text();
        var oldVal = $(obj).attr('data-val');
        var sField = $(obj).attr('data-field');
        var sDataID = $(obj).attr('data-id');

        var sHtml = '<input type="text" name="qm_'+ sField +'" id="qm_'+ sField +'" class="form-control" value="'+ sVal +'">';
        $(obj).html(sHtml);

        $('#qm_'+ sField).focus().blur(function(){
            if($(this).val() != ''){
                ExecModifyVal(obj, sVal, $(this).val(), sField, sDataID);
            }else{
                $(obj).html(oldVal);
            }
        }).keypress(function(e){
            var curKey = e.which;

            if (curKey == 13) {
                if($(this).val() != ''){
                    ExecModifyVal(obj, sVal, $(this).val(), sField, sDataID);
                }else{
                    $(obj).html(oldVal);
                }
            }
        });
    }

    //执行修改操作
    function ExecModifyVal(obj, sval, snewval, sfield, dataid){
        if(snewval.trim() == sval.trim() || snewval.trim()==''){
            $(obj).html(sval);
        }else{
            $.ajax({
                type: "POST",
                url: "/wftadlogin/excercise/quickmodifyval",
                dataType:"json",
                data:{"key":sfield, "val":snewval, "id":dataid},
                beforeSend:function(){
                    loginTip.text("正在处理...");
                    loginTip.show();
                },
                success: function(data){
                    if(data.status==1){
                        $(obj).html(data.data);
                        loginTip.text(data.message);
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                        },1000);
                    }else{
                        loginTip.text(data.message);
                        loginTip.show();
                        setTimeout(function(){
                            loginTip.hide();
                        },1200);
                    }
                }
            });
        }
    }
</script>




