<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge,chrome=1">
    <meta http-equiv=”Cache-Control” content=”no-siteapp”/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <title>羊宝宝们，玩翻天喊你免费领取贝乐园游玩卡啦</title>
    <link type="text/css" rel="stylesheet" href="/mabaobao/css/layout.css">
    <style>
        #zz {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: #000;
            filter: alpha(opacity=90);
            -moz-opacity: 0.9;
            opacity: 0.9;
            z-index: 8;
        }

        #zz img {
            width: 100%;
            height: auto;
        }
    </style>
</head>
<?php echo $this->content; ?>
</html>


