<?php header("Content-type: text/html; charset=utf-8");?>
<div class="alert alert-warning">
    <h1><strong>提示！</strong></h1>
    <hr>
    <h4 style="color: #2aabd2;"><?php echo $this->info; ?></h4>
    <br>

    <p><a href="<?php echo $this->backurl ? $this->backurl : 'javascript:history.back(1)'; ?>" class="btn btn-primary">点击返回/跳转</a>
    </p>
</div>
<script>
    document.onkeydown = function()
    {
        if(event.keyCode==116) {
            event.keyCode=0;
            event.returnValue = false;
        }
    }
    document.oncontextmenu = function() {event.returnValue = false;}
</script>