<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>玩翻天-免责声明</title>
    <meta name="keywords" content="玩翻天" />
    <meta name="description" content="玩翻天" />
    <link rel="dns-prefetch" href="http://wft.deyi.com">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script type="text/javascript">(function(){if(!/*@cc_on!@*/0)return;var e = "abbr,article,aside,audio,canvas,datalist,details,dialog,eventsource,figure,figcaption,footer,header,hgroup,mark,menu,meter,nav,output,progress,section,time,video".split(','),i=e.length;while(i--){document.createElement(e[i])}})();</script>
    <style>
        .state{
            width:80%;
            margin: 50px auto;
        }
    </style>
</head>
<body>
    <div class="state">
        <p>
            <span style=";font-family:微软雅黑;font-size:14px">免责声明</span>
        </p>
        <p style="margin-left:24px">
            <span style="font-family:微软雅黑;font-size:14px">1、&nbsp;</span><span style=";font-family:微软雅黑;font-size:14px">玩翻天作为第三方网络平台，仅作为活动组织者及平台用户双方提供网络平台服务及相应的技术维护与支持；</span>
        </p>
        <p style="margin-left:24px">
            <span style="font-family:微软雅黑;font-size:14px">2、&nbsp;</span><span style=";font-family:微软雅黑;font-size:14px">平台上所展示的所有产品，均由该活动组织者直接提供活动安排及服务；</span>
        </p>
        <p style="margin-left:24px">
            <span style="font-family:微软雅黑;font-size:14px">3、&nbsp;</span><span style=";font-family:微软雅黑;font-size:14px">玩翻天作为第三方平台对平台上发布的任何产品、活动、服务，或进行的交易进程，不作任何担保；</span>
        </p>
        <p style="margin-left:24px">
            <span style="font-family:微软雅黑;font-size:14px">4、&nbsp;</span><span style=";font-family:微软雅黑;font-size:14px">其他应知事项和条款，请详细阅读《用户须知》</span>
        </p>
    </div>
</body>
</html>