<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <meta name="format-detection" content="telephone=no" />
    <title>玩翻天</title>
    <link href="/css/download-style.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/css/download-response.css" media="screen and (max-width: 1024px) and (min-width: 760px)"/>
    <style type="text/css">
        <!--
        .STYLE1 {
            font-size: 55px;
            color: #ff621d;
        }
        .STYLE3 {font-size: 25px}
        .STYLE5 {font-size: 15px}
        .STYLE8 {color: #7da80e}
        .STYLE9 {font-size: 18px}
        .STYLE10 {color: #a0a0a0; font-size: 30px; }
        -->
    </style>

    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "//hm.baidu.com/hm.js?f80b4fc6388574ae63babc35f7551fad";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>



</head>
<body>
<div id="header">
    <div class="header">
        <div class="download">
            <a href="https://itunes.apple.com/cn/app/de-yi-sheng-huo-lun-tan/id950652997?mt=8" target="_blank" class="ios STYLE9">苹果商店下载</a>
            <img class="wxxiao" src="/images/wxxiao.png" alt=""/>
            <a href="http://wft.deyi.com/download/wft.apk" target="_blank" class="android STYLE9">立即下载安卓</a> </div>
    </div>
</div>
<div id="con">
    <div class="detailbg1">
        <div class="details2">
            <div class="message">
                <h2 class="STYLE1" >欢乐共聚</h2>
                <p class="STYLE10">乐享有品质的亲子时光</p>
            </div>
            <img class="photo" src="/images/con1.png" alt=""/>	   </div>
    </div>
    <div class="detailbg2">
        <div class="details2">
            <img class="photo photo2" src="/images/con2.png" alt=""/>
            <div class="message message2">
                <h2>万人疯抢</h2>
                <p align="right" class="STYLE10">惊爆价格聚划算</p>
            </div>
        </div>
    </div>
    <div class="detailbg3">
        <div class="details2">
            <div class="message">
                <h2 class="STYLE8">随时随地</h2>
                <p class="STYLE10">一键支付电子兑换</p>
            </div>
            <img class="photo" src="/images/con3.png" alt=""/>        </div>
    </div>
</div>
<div id="footer">
    <div class="footerbg">
        <div class="footer">
            <div class="kb">
                <img class="wx" src="/images/wx.png" alt=""/>
                <p class="STYLE3">根据手机，选择免费下载</p>
                <span class="STYLE9">也可在Appstore、安卓市场直接搜索玩翻天</span>
                <div class="download dwl">
                    <a class="ios" href="#" target="_blank">苹果商店下载</a>
                    <a class="android" href="http://wft.deyi.com/download/wft.apk" target="_blank">立即下载安卓</a>
                </div>
            </div>
            <p class="copyright STYLE5">Copyright&copy;2014 玩翻天 — <a href="#" target="_blank">联系我们</a></p>
        </div>
    </div>
</div>
</body>
</html>