<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>玩翻天-用户协议</title>
    <meta name="keywords" content="玩翻天" />
    <meta name="description" content="玩翻天" />
    <link rel="dns-prefetch" href="http://wft.deyi.com">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script type="text/javascript">(function(){if(!/*@cc_on!@*/0)return;var e = "abbr,article,aside,audio,canvas,datalist,details,dialog,eventsource,figure,figcaption,footer,header,hgroup,mark,menu,meter,nav,output,progress,section,time,video".split(','),i=e.length;while(i--){document.createElement(e[i])}})();</script>
    <style>
        .state{
            width:80%;
            margin: 50px auto;
        }
    </style>
</head>
<body>
    <div class="state"><p style="text-align: left; margin-top: 0px; margin-bottom: 0px; line-height: 24px;">
            <span style=";font-family:微软雅黑;font-size:14px">&nbsp;尊敬的用户:</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;text-indent:35px;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">在使用玩翻天APP第三方网络平台服务前，请您务必认真阅读和遵守本《用户须知》中规定的所有权利和限制。请您务必审慎阅读、充分理解各条款内容，特别是免除或者限制责任的条款、争议解决和法律适用条款。免除或者限制责任的条款可能将以加粗字体显示，您应重点阅读。如您对协议有任何疑问的或不认可，应立即停止使用服务。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;text-indent:35px;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;text-indent:35px;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">当您按照注册页面提示填写信息、阅读并同意本《用户须知》且完成全部注册程序后，或您以其他玩翻天APP平台允许的方式实际使用本平台服务时，即表示您已充分阅读、理解并接受本《用户须知》的全部内容，并与玩翻天APP达成协议。您承诺接受并遵守本《用户须知》项下的各项约定，届时您不应以未阅读本协议的内容&nbsp;或者未获得本平台对您问询的解答等理由，主张本《用户须知》无效，或要求撤销本《用户须知》。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;text-indent:35px;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第一条&nbsp;服务内容 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">1.1&nbsp;玩翻天APP是由武汉玩翻天科技有限公司或其后继或关联公司所有的亲子活动销售技术平台。包括基于互联网的网站及基于移动手机客户端及应用等（包括但不限于“玩翻天”手机客户端、微信公众号等）。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">1.2&nbsp;玩翻天APP通过为活动组织者提供管理系统、网页版权、装潢设计等技术服务，使得活动组织者通过平台管理系统，自动、自助和自主地将活动组织者的产品信息、图片和价格等产品必要相关信息展示在“玩翻天”的销售平台系统。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">1.3&nbsp;玩翻天APP仅提供网络平台服务。活动组织者通过本亲子活动销售技术平台，推广、介绍、宣传其所有的亲子活动产品，所有产品的活动安排及服务均由该&nbsp;活动组织者直接提供。玩翻天APP作为第三方技术提供者，仅为活动组织者及平台用户双方提供网络平台服务及相应的技术维护与支持，除此之外与平台中的活动组织者不存在其他任何形式的产品、活动、服务合作。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第二条&nbsp;注册与用户信息 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">2.1&nbsp;您确认，在您完成注册程序或以其他玩翻天APP（以下简称“本平台”）允许的方式实际使用本平台服务时，您应当是具备完全民事行为能权利能力和完全民事力的自然人、法人或其他组织。若您不具备前述主体资格，则您及您的监护人应承担因此而导致的一切后果，且本平台有权注销或永久冻结您的账户，并向您及您的监护人索偿相应损失。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">2.2&nbsp;本平台提供一个公共展示与信息交流的渠道，仅帮助用户知悉活动组织者提供和组织相关活动。个人注册成为本平台用户后通过手机号及手机验证码登入本平台。用户对个人手机号的安全负全部责任。在任何情况下，用户均不得授权任何第三方使用本人账户，且对因此产生的后果自行承担全部责任。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">2.3&nbsp;本平台承诺尊重用户个人隐私，不公开用户的任何个人信息，除以下情况外：</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（1）用户授权本平台透露这些信息。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（2）相应的法律及程序要求本平台提供用户的个人资料。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（3）为提供相关的服务而将必要信息提交给第三方。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（4）对公共场合下拍摄的影像资料，本平台有使用权。如肖像权本人对使用权有异议，本平台负责撤下本平台上展示的相关的影像资料，但不承担除此之外的任何其它责任。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第三条&nbsp;条款的修改 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">3.1&nbsp;本平台将可能不定期的修改本《用户须知》的有关条款，一旦条款及服务内容产生变动，&nbsp;本平台将会在重要页面上提示修改内容。如果不同意本平台对条款内容所做的修改，用户可以主动停止对本平台服务的使用。如果用户继续使用本平台的服务，则视为接受服务条款的变动。本平台保留随时修改或中断服务而不需告知用户的权利。本平台行使修改或中断服务的权利，不需对用户或第三方负责。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第四条&nbsp;拒绝提供担保 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">4.1&nbsp;用户个人对网络服务的使用承担风险。本站对此不作任何类型的担保，不论是明确的或隐含的。本站不担保服务一定能满足用户的要求，也不担保服务不会受中断，对服务的及时性，安全性，出错发生都不作担保。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">4.2&nbsp;作为第三方网络平台服务提供者，本平台对本平台上发布的任何产品、活动、服务，或进行的交易进程，不作任何担保。用户在实际参与活动、接受服务产品时与活动组织者发生&nbsp;的任何纠纷，由用户与活动组织者自行协商解决。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第五条&nbsp;关于保险 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">本平台强烈建议您自行购买保险以保障自身权益。为了您和孩子的人身安全及财产安全，切勿抱有侥幸心理。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">5.1&nbsp;本平台提供保险购买工具方便用户在报名参加活动时及时购买保险产品，以保障自身权益。购买保险的行为是客户自主、自愿的行为。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">5.2&nbsp;用户选择在本平台购买保险时对自己提供的身份信息的完整性、准确性负责。本平台不对上述信息进行审核，也不承担如因身份信息错误而引起的保险无效的责任。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">5.3&nbsp;本平台提供给用户的保险购买工具，仅为维护用户利益所为，不代表本平台对用户的任何人身伤害和财产损失承担任何责任，亦不代表用户遭受的伤害或损害必然获得赔偿或保险理赔。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第六条&nbsp;行为免责 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">6.1&nbsp;在日常运营过程中，为确保平台功能的有效实现，保障平台环境的有序与优质，本平台可能会有以下行为：</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（1）协助用户及时与活动组织者取得联系，协助办理合同签订、款项支付的行为；</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（2）督促活动组织者为参与活动的用户购买保险的行为；</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（3）活动组织者未为用户购买保险时，本平台通过划扣保证金为用户购买保险的行为；</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（4）活动组织者违反法律、法规、政策或违反其对用户的任何承诺导致用户受损时，本平台根据独立判断，直接使用保证金对用户进行赔付的行为；</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（5）用户与活动组织者发生纠纷后，协助双方调停、处理纠纷的行为；</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（6）其他对用户及活动组织者的辅助、帮助、协同、监督行为。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">以上行为的实施，不视为本平台以明示或默示方式承诺承担任何责任、提供任何形式的担保或以任何方式实质参与到用户与活动组织者之间的合同中。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第七条&nbsp;有限责任 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">7.1&nbsp;本平台负责按&quot;现状&quot;和&quot;可得到&quot;的状态向用户提供网络平台服务。但本平台对网络平台&nbsp;服务不作任何明示或暗示的保证，包括但不限于网络平台服务的适用性、没有错误或疏漏、&nbsp;持续性、准确性、可靠性、适用于某一特定用途。同时，本平台也不对网络平台服务所涉及的技术及信息的有效性、准确性、正确性、可靠性、质量、稳定、完整和及时性作出任何承诺和保证。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第八条&nbsp;关于链接 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">8.1&nbsp;本平台可能会提供与其他国际互联网网站或资源进行链接。对于前述网站或资源是否可以利用，本平台不予担保。因使用或依赖上述网站或资源所产生的损失或损害，本平台也不&nbsp;承担任何责任。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第九条&nbsp;知识产权及其他权利 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">9.1&nbsp;本平台对平台中所使用的软件和受知识产权或其他法律保护的资料享有相应的权利；&nbsp;经由本平台传送的资讯及内容，受到著作权法、商标法、专利法或其他法律的保护；未经本&nbsp;平台明示授权许可，用户不得进行修改、出租、散布或衍生其他作品。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第十条&nbsp;用户管理 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">10.1&nbsp;用户单独承担使用平台服务的责任。用户对服务的使用是根据所有适用于本站的国家法律、地方法律和国际法律标准的。用户必须遵循：</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（1）从中国境内向外传输技术性资料时必须符合中国有关法规。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（2）使用网络服务不作非法用途。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（3）不干扰或混乱网络服务。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（4）遵守所有使用网络服务的网络协议、规定、程序和惯例。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">用户须承诺不传输任何非法的、骚扰性的、中伤他人的、辱骂性的、恐性的、伤害性的、庸俗的，&nbsp;淫秽等信息资料。另外，用户也不能传输何教唆他人构成犯罪行为的资料；不能传输助长&nbsp;国内不利条件和涉及国家安全的资料；不能传输任何不符合当地法规、国家法律和国际法律的资料。未经许可而非法进入其它电脑系统是禁止的。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">若用户的行为不符合以上提到的服务条款，本平台将作出独立判断立即取消用户服务帐号。&nbsp;用户需对自己在网上的行为承担法律责任。用户若在本平台上散布和传播反动、色情或其它&nbsp;违反国家法律的信息，本平台的系统记录有可能作为用户违反法律的证据。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第十一条&nbsp;结束服务 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">11.1&nbsp;用户或本平台可随时根据实际情况中断一项或多项网络服务。本平台不需对任何个人或第三方负责而随时中断服务。用户对后来的条款修改有异议，或对本站的服务不满，可以&nbsp;行使如下权利：</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（1）停止使用本平台的网络服务。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">（2）通告本平台停止对该用户的服务。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">结束用户服务后，用户使用网络服务的权利马上中止。从那时起，用户有权利，本平台也没&nbsp;有义务传送任何未处理的信息或未完成的服务给户或第三方。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px"><br/></span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">第十二条&nbsp;法律管辖和适用 :</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">12.1&nbsp;本《用户须知》的订立、执行和解释及争议的解决均应适用中国法律。</span>
        </p>
        <p style="margin-top:0;margin-bottom:0;line-height:24px">
            <span style=";font-family:微软雅黑;font-size:14px">12.2&nbsp;如发生本《用户须知》项下条款与中国法律相抵触时，则这些条款将完全按法律规定重&nbsp;新解释，而其它合法条款则依旧保持对用户产生法律效力和影响。</span>
        </p>
        <p>
            <span style=";font-family:微软雅黑;font-size:14px">12.3&nbsp;如双方就本《用户须知》内容或其执行发生任何争议，双方应尽力友好协商解决；协商不成时，任何一方均可向本平台所在地的人民法院提起诉讼。</span>
        </p>
    
    </div>
</body>
</html>
