<body>
<form class="join-form" id="info-save">
    <fieldset>
        <span class="join-info">手机号</span>
        <input id="name" name="phone" value="" type="text" class="text name" />
    </fieldset>
    <fieldset>
        <span class="join-info">宝宝姓名</span>
        <input id="name" name="username" value="" type="text" class="text name" />
    </fieldset>
    <fieldset>
        <span class="join-info">宝宝性别</span>
        <ul class="gender">
            <li class="boy-box">
                <input id="boy" type="radio" name="gender" value="boy" checked />
                <label for="boy" class="boy">王子</label>
            </li>
            <li class="girl-box">
                <input id="girl" type="radio" name="gender" value="girl">
                <label for="girl" class="girl">公主</label>
            </li>
        </ul>
    </fieldset>
    <fieldset>
        <span class="join-info">宝宝生日</span>
        <input type="date" name="birthday" value="2015-01-01" class="text birth" min="2015-01-01" max="2015-12-31" />
    </fieldset>
    <fieldset>
        <span class="join-info">宝宝地址</span>
        <select id="area" name="area" class="adds">
            <option value="" selected >选择区域</option>
            <option value="江岸区">江岸区</option>
            <option value="洪山区">洪山区</option>
            <option value="江汉区">江汉区</option>
            <option value="汉阳区">汉阳区</option>
            <option value="武昌区">武昌区</option>
            <option value="硚口区">硚口区</option>
            <option value="青山区">青山区</option>
            <option value="东西湖区">东西湖区</option>
            <option value="近郊区">近郊区</option>
        </select>​
    </fieldset>
    <fieldset>
        <span class="join-info">照片<i>（2-5张）</i></span>
        <div class="upload_area clearfix">
            <ul id="imglist" class="post_imglist"></ul>
            <div class="upload_btn">
                <input type="file" id="upload_image" value="图片上传" accept="image/jpeg,image/gif,image/png" capture="camera">
            </div>
        </div>
        <div class="tips">
            <p>至少1张出生证明照片，要求出生时间清晰可见；</p>
            <p>至少1张宝宝近照，要根据照片刷脸入场的哦；</p>
        </div>
    </fieldset>
    <button class="btn tijiao" href="javascript:;">提交</button>
</form>
</body>
<script type="text/javascript" src="/mabaobao/js/jquery-2.1.3.min.js"></script>
<script type="text/javascript" src="/mabaobao/js/exif.js"></script>
<script type="text/javascript" src="/mabaobao/js/binaryajax.js"></script>
<script type="text/javascript" src="/mabaobao/js/localResizeIMG2.js"></script>
<script type="text/javascript" src="/mabaobao/js/mobileBUGFix1.mini.js"></script>
<script type="text/javascript">
    (function () {
        $('.tijiao').click(function() {
            $(this).attr('disabled', 'true');
            $(this).addClass("grey");
            var that = $(this);
            $.post('/mabao/index/muss', $('#info-save').serialize(), function (data) {
                if (data.status == 1) {
                    alert(data.message);
                } else {
                    that.attr('disabled', false);
                    that.removeClass("grey");
                    alert(data.message);
                }
            }, 'json');
            return false;
        });

        var viewImg = $("#imglist");
        var imgurl = '';
        var imgcount = 0;
        $('#upload_image').localResizeIMG({
            width: 800,
            quality: 0.8,
            success: function (result) {
                var status = true;
                if (result.height > 1600) {
                    status = false;
                    alert("照片最大高度不超过1600像素");
                }
                if (viewImg.find("li").length > 4) {
                    status = false;
                    alert("最多上传5张照片");
                }
                if (status) {
                    viewImg.append('<li><span class="pic_time"><span class="p_img"></span><em>50%</em></span></li>');
                    viewImg.find("li:last-child").html('<span class="del"></span><img class="wh60" src="' + result.base64 + '"/><input type="hidden" id="file'
                        + imgcount
                        + '" name="fileup[]" value="'
                        + result.clearBase64 + '">');

                    $(".del").on("click",function(){
                        $(this).parent('li').remove();
                        $("#upload_image").show();
                    });
                    imgcount++;
                }
            }
        });
    })();
</script>
