<body>
<div class="shoplist">
    <section>
        <span><img src="/mabaobao/images/shop1.jpg" /></span>
        <div class="shopdetail">
            <h3>贝乐园国广店</h3>
            <a href="tel:027-85809623">电话：027-85809623</a>
            <p>江汉区解放大道688号武商国际广场6楼</p>
        </div>
    </section>
    <section>
        <span><img src="/mabaobao/images/shop2.png" /></span>
        <div class="shopdetail">
            <h3>贝乐园武商店</h3>
            <a href="tel:027-85809623">电话：027-85714179</a>
            <p>江汉区解放大道688号武商广场7楼</p>
        </div>
    </section>
    <section>
        <span><img src="/mabaobao/images/shop3.png" /></span>
        <div class="shopdetail">
            <h3>贝乐园泛海店</h3>
            <a href="tel:027-83739615">电话：027-83739615</a>
            <p>江汉区云杉路199号泛海城市广场购物中心四楼</p>
        </div>
    </section>
    <section>
        <span><img src="/mabaobao/images/shop4.png" /></span>
        <div class="shopdetail">
            <h3>贝乐园光谷店</h3>
            <a href="tel:027-87956667">电话：027-87956667</a>
            <p>洪山区光谷世界城三期意大利风情街F座5号楼3楼</p>
        </div>
    </section>
    <section>
        <span><img src="/mabaobao/images/shop5.png" /></span>
        <div class="shopdetail">
            <h3>贝乐园群星城店</h3>
            <a href="tel:027-88153772">电话：027-88153772</a>
            <p>武昌区徐东大街120号群星城3楼</p>
        </div>
    </section>
    <section>
        <span><img src="/mabaobao/images/shop6.jpg" /></span>
        <div class="shopdetail">
            <h3>贝乐园后湖店</h3>
            <a href="tel:027-82881613">电话：027-82881613</a>
            <p>江岸区后湖大道111号汉口城市广场B区2楼</p>
        </div>
    </section>
    <section>
        <span><img src="/mabaobao/images/shop7.png" /></span>
        <div class="shopdetail">
            <h3>贝乐园汉阳店</h3>
            <a href="tel:027-85714919">电话：027-85714919</a>
            <p>汉阳区龙阳大道特6号摩尔城c栋3楼</p>
        </div>
    </section>
    <section>
        <span><img src="/mabaobao/images/shop8.png" /></span>
        <div class="shopdetail">
            <h3>贝乐园众圆店</h3>
            <a href="tel:027-86411943">电话：027-86411943</a>
            <p>青山区和平大道959号建设二路武商众圆广场四楼C区</p>
        </div>
    </section>
</div>
</body>
