<hgroup class="box">
    <header>
        <h3>推送管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/getui">返回推送列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/getui/keep" method="post">
    <header class="box-title">添加推送</header>
    <table class="table">
        <tr>
            <th width="160">标题</th>
            <th colspan="3"><input type="text" class="cssInput" name="title" value="<?php echo count($data) ? $data->title : ''; ?>">
            </th>
        </tr>

        <tr>
            <th width="160">正文</th>
            <th colspan="3" width="600">
                <textarea class="cssTextArea" name="info" ><?php echo count($data) ? $data->info : ''; ?></textarea><span style="color:red">&nbsp;32个字节以内</span>
            </th>
        </tr>

        <tr>
            <th width="160">周几</th>
            <th colspan="3" width="600">
                <select name="week">
                    <option value="1" <?php echo (date('N', $data->push_time) == 1) ? 'selected' : '';?>>周一</option>
                    <option value="2" <?php echo (date('N', $data->push_time) == 2) ? 'selected' : '';?>>周二</option>
                    <option value="3" <?php echo (date('N', $data->push_time) == 3) ? 'selected' : '';?>>周三</option>
                    <option value="4" <?php echo (date('N', $data->push_time) == 4) ? 'selected' : '';?>>周四</option>
                    <option value="5" <?php echo (date('N', $data->push_time) == 5) ? 'selected' : '';?>>周五</option>
                    <option value="6" <?php echo (date('N', $data->push_time) == 6) ? 'selected' : '';?>>周六</option>
                    <option value="7" <?php echo (date('N', $data->push_time) == 7) ? 'selected' : '';?>>周天</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">时间</th>
            <th colspan="3">
                <input type="time" value="<?php echo $data ? date('H:i', $data->push_time) : '08:00';?>" name="timer">　
            </th>
        </tr>



    </table>
    <input type="hidden" value="<?php echo $data->id;?>" name="id">　
    <button type="submit" class="btn btn-primary">提交</button>
</form>

