<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>"玩翻天"后台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Le styles -->
    <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
    <link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
    <!-- Scripts -->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/js/html5shiv.js"></script><![endif]-->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="/js/respond.min.js"></script><![endif]-->
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
</head>
<body>
<style>
    .modal-body input {
        width: 200px;
        display: inline-block;
    }
</style>

<!-- 模态框（Modal） -->
<form method="post" action="#">
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header" style="height: 50px;">
                    <button type="button" class="close"
                            data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        请登录！
                    </h4>
                </div>
                <div class="modal-body">
                    <p>
                        用户名： <input type="text" class="form-control" name="username">
                    </p>

                    <p>
                        密　码： <input type="password" class="form-control" name="pwd">
                    </p>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">
                        登录
                    </button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal -->
    </div>
</form>
<script>
    $(function () {
        $('#myModal').modal()
    })
</script>
</body>
</html>