<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>绑定手机号</title>
    <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js" type="text/javascript"></script>
</head>



<body>
<div class="tips">
    请绑定手机号
</div>

<div class="input-group">
    <input type="text" class="form-control" placeholder="请输入您的手机号" id="phone">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button" id="send">获取验证码</button>
          </span>

</div>

<div class="code">
    <input type="text" class="form-control" placeholder="请输入验证码" id="code">
</div>
<div class="input-group">
    <button type="button" class="btn btn-default next">下一步</button>
</div>
<!-- Standard button -->

</body>

<script>
    $(function () {

        $(".next").click(function () {
            var code = $('#code').val();
            var phone = $('#phone').val();
            if (!code) {
                alert('验证码不能为空');
            }
            // 请求绑定手机接口
            $.ajax({
                type: "POST",
                url: "/user/login/bindphone",
                //        dataType:"json",
                async: true,
                data: {
                    'phone': phone,
                    'code': code,
                    'uid': <?php echo $uid>0 ? $uid : 0;?>,
                    'is_weixin': 1
                },
                headers: {
                    "VER": 8
                },
                success: function (result) {
                    if (result.response_params.status == 0) {
                        alert(result.response_params.message);
                    } else {
                        // 成功
                        alert('绑定成功');
                        window.location.href = '<?php echo $tourl;?>';
                        return false;
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                    if (XMLHttpRequest.status == 401) {
                        //alert('授权失败');
                        // 跳转授权页面
                        //alert(XMLHttpRequest.responseJSON.message);
                        window.location.href = '<?php echo $authorUrl;?>';

                    }
                    else if (XMLHttpRequest.status == 403) {
                        alert('接口验证失败，非法访问');
                    }
                    else if (XMLHttpRequest.status == 400) {
                        alert('请求参数错误');
                    }
                    else {
                        alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                    }
                }
            });
        });
        $("#send").click(function () {
            var phone = $('#phone').val();
            if (phone.length !== 11) {
                alert('手机号格式错误')
            } else {
                //请求发送短信

                $.ajax({
                    type: "POST",
                    url: "/user/login/getcode",
                    //        dataType:"json",
                    async: true,
                    data: {
                        'phone': phone,
                        'check_phone': 0
                    },
                    headers: {
                        "VER": 8
                    },
                    success: function (result) {
                        if (result.response_params.status == 0) {
                            alert(result.response_params.message);
                        } else {
                            // 成功
                            alert('发送成功');
                            // window.location.href = '<?php echo $tourl;?>';
                        }
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                        if (XMLHttpRequest.status == 401) {
                            // 跳转授权页面
                            //alert(XMLHttpRequest.responseJSON.message);
                            window.location.href = '<?php echo $authorUrl;?>';

                        }
                        else if (XMLHttpRequest.status == 403) {
                            alert('接口验证失败，非法访问');
                        }
                        else if (XMLHttpRequest.status == 400) {
                            alert('请求参数错误');
                        }
                        else {
                            alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                        }


                    }
                });

                /************ 生成订单 end ************/
                return false;


            }
        })
    })
</script>
<style>
    * {
        font-family: -apple-system, "Lantinghei SC", "Open Sans", Arial, "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", "STHeiti", "WenQuanYi Micro Hei", SimSun, sans-serif;
        font-size: 40px;
    }

    .tips {
        text-align: center;
        margin: 60px;
        padding-top: 91px;
    }

    .input-group, .code {
        font-size: 40px;
        margin-left: auto;
        margin-right: auto;
        text-align: center;
        width: 80%;
        margin-top: 64px;
    }

    .next {
        font-size: 40px;
        margin-left: auto;
        margin-right: auto;
        text-align: center;
        width: 60%;
        margin-top: 30px;

    }

    .form-control {
        font-size: 40px;
        background-color: #e9e9e9;
        border: 0px;
        height: 130px;
    }

    .btn-default {
        font-size: 40px;
        background-color: #ffce54;
        border: 1px solid #ffce54;
        height: 130px;
        color: #FFF;
    }

</style>
</html>


