<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge,chrome=1">
    <meta http-equiv=”Cache-Control” content=”no-siteapp” />
    <meta name="apple-mobile-web-app-capable" content="yes" >
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <title>确认支付密码</title>
    <script>(function(){var w=window.screen.width,s=w/640,u=navigator.userAgent,m='<meta name="viewport" content="width=640,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
    <link rel="stylesheet" href="/css/wap/custom.css">
    <link rel="stylesheet" href="/css/wap/iosOverlay.css">
    <style>
        /* CSS RESET */
        * { padding: 0; margin: 0; }
        body { font: 16px "微软雅黑", Arial;  min-width: 400px; max-width: 640px; color: #000;border-radius: 5px; background: #efefef}
        a { text-decoration: none; color: #666666; }
        a, img { border: none; }
        img { vertical-align: middle; }
        ul, li { list-style: none; }
        em, i { font-style: normal; }
        .clear_wl:after { content: "."; height: 0; visibility: hidden; display: block; clear: both; }
        .fl { float: left ;font-size: 16px;}
        /**/

        .step1 .hbbj { width: 100%; height: 100%; position: absolute; z-index: 8; background: #fff; opacity: 0.4; top: 0; left: 0; }
        .step1 .srzfmm_box { position: fixed; z-index: 10; width: 88%; left: 50%; margin-left: -44%; top: 100px;border-radius: 15px;}
        .qsrzfmm_bt { font-size: 16px; border-bottom: 1px solid #c9daca; overflow: hidden;min-height:100px; }
        .qsrzfmm_bt a { display: block; width: 10%; padding: 10px 0; text-align: center; }
        .qsrzfmm_bt img.tx { width: 10%; padding: 10px 0; }
        .qsrzfmm_bt span {
            margin: 30px 180px;
            font-size: 25px;display:block;text-align: center;vertical-align: middle }

        .pwd-box input[type="tel"]{
            color: transparent;
            width: 100%;
            height: 60px;
            opacity: 0;
            border: none;
            font-size: 1px;
            z-index: 2;
            pointer-events: none;
        }

        .pwd-box{
            position: absolute;
            top: 136px;
            left: 50%;
            margin-left: -180px;
            height: 60px;
            width: 360px;
            z-index: 2;
            -webkit-tap-highlight-color: rgba(0,0,0,0);
        }

        .fake-box{
            width: 360px;
            height: 60px;
            margin: 35px auto 0;
        }

        .fake-box > div{
            position: relative;
            width: 58px;
            height: 58px;
            border: 1px solid #e5e5e5;
            background: #fff;
            float: left;
            overflow: hidden;
            margin-left: -1px;
        }

        .box-active:before{
            content: '';
            position: absolute;
            left: 50%;
            top: 50%;
            margin: -3px 0 0 -3px;
            display: block;
            height: 6px;
            width: 6px;
            border-radius: 3px;
            background: #000;
        }

        #sucBtn{
            display: block;
            text-align: center;
            width: 100%;
            font-size: 36px;
            height: 80px;
            line-height: 80px;
            letter-spacing: 1px;
            color: #fff;
            border-radius: 0;
            border: none;
            margin-top: 400px;
            background: #F64730;
            appearance: none;
            -webkit-appearance: none;
        }
    </style>
</head>
<body>

<div class="step1" id="step1">
    <div class="srzfmm_box">
        <div class="qsrzfmm_bt clear_wl"><span class="fl">请确认支付密码</span> </div>
        <label class="pwd-box" for="pwd-input">
            <input type="tel" maxlength="6" class="pwd-input" id="pwd-input">
        </label>
        <div class="fake-box">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</div>
<input type="hidden" name="url" id="url" value="<?php echo $tourl;?>">
<input type="hidden" name="pwd" id="pwd" value="<?php echo $pwd;?>">
<input class="button" type="button" value="确认" id="sucBtn" disabled="disabled"/>
<script src="/js/jquery.min.js"></script>
<script src="/js/wap/plugin/iosOverlay.js"></script>
<script src="/js/wap/plugin/spin.min.js"></script>
<script src="/js/wap/plugin/custom.js"></script>
<script src="/js/wap/plugin/prettify.js"></script>
<script>
    var back_url = decodeURIComponent($("#url").val());
    var reg=new RegExp("amp;","g"); //创建正则RegExp对象
    back_url = back_url.replace(reg,"");
    var pwd = $("#pwd").val();
    var boxs = $(".fake-box").children();
    var tem=false;
    var password = [];
    var field = $("#pwd-input");

    if (/ios|ipad|iphone|ipod/i.test(window.navigator.userAgent)) {
        field.css({
            fontSize: 0
        });
    }

//    function getChar(e) {
//        return e.which ? String.fromCharCode(e.which) : e.target.value.slice(-1);
//    }

    field.on("input", function(e) {
        var length = e.target.value.length,
            char = e.target.value.slice(-1);//监控input键盘输入值
        if (password.length === length + 1) {
            password.pop();
            $(boxs[password.length]).removeClass('box-active');
        } else if (password.length < 6) {
            password.push(char);
            password.forEach(function (box, i) {
                $(boxs[i]).addClass('box-active');
            });
        }

        field.val(password.join(''));
        if (password.length == 6) {
            if(pwd != field.val()){
                loadingErr("两次密码不相同");
                return;
            }else{
                $("#sucBtn").removeAttr("disabled");
                tem=true;
            }
        }

    });

    $("#sucBtn").on('click', function(){
        if(tem){
            loading();
            $.ajax({
                type: "POST",
                url: "/user/account/updatePassword",
                //        dataType:"json",
                async: true,
                data:{"uid":<?php echo $_COOKIE['uid'];?>,'new_password':field.val()},
                headers: {
                    "VER": 10
                },
                success: function (result) {
                    if (result.response_params.status == 0) {
                        loadingErr("设置失败");

                    } else {
                        // 成功
                        loadingSuccess("设置成功！");
                        window.location.href=back_url;

                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                    if (XMLHttpRequest.status == 401) {
                        //alert('授权失败');
                        // 跳转授权页面
                        //alert(XMLHttpRequest.responseJSON.message);
                        window.location.href = '<?php echo $authorUrl;?>';

                    }
                    else if (XMLHttpRequest.status == 403) {
                        alert('接口验证失败，非法访问');
                    }
                    else if (XMLHttpRequest.status == 400) {
                        alert('请求参数错误');
                    }
                    else {
                        alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                    }
                }

            });
        }
    });
</script>
</body>
</html>
