<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge,chrome=1">
    <meta http-equiv=”Cache-Control” content=”no-siteapp” />
    <meta name="apple-mobile-web-app-capable" content="yes" >
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <title>同玩订单详情</title>
    <link href="/css/wap/common.css" rel="stylesheet"/>
    <link href="/css/wap/order.css" rel="stylesheet"/>
    <script>(function(){var w=window.screen.width,s=w/640,u=navigator.userAgent,m='<meta name="viewport" content="width=640,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
</head>
<body>
<a id="download" href="http://wan.wanfantian.com/app/index.php" title="">
    <img src="/images/wap/download.png" alt=""/>
</a>
<main class="align" id="content"></main>
<script id="test" type="text/html">
    <header class="header">
        <a class="header-back" href="javascript:history.go(-1);"></a>
        <a class="header-title">同玩订单详情</a>
        <a class="header-user" href="/web/wappay/my" title=""></a>
    </header>
    <section class="wrapper">
        <div class="order-info bdt-1px">
            <h2 class="title bdb-1px">{{title}}</h2>
            <div class="info bdb-1px">
                <span class="sl">拼团价：</span>
                <mark class="sm">&yen;{{new_price}}</mark>
                <span class="sr">票价：&yen;{{price}}</span>
            </div>
            <div class="user bdt-1px">
                <h4>参与的玩家：</h4>
                <div class="con">
                    <span class="num">{{join_number}}/{{g_limit}}</span>
                    <div class="pic">
                        {{each join_user_list}}
                        <div class="item">
                            <img src="{{$value.userimg}}">
                            <i class="status colo">团</i>
                        </div>
                        {{/each}}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <nav class="tw-nav">
        {{if status==1}}
        <i class="icon-time"></i>
        <span class="info">
            {{if end_time<= time}}
            <time>
                已截团
            </time>
            {{else}}
            <time>
                <span id="t_d">00天</span>
                <span id="t_h">00时</span>
                <span id="t_m">00分</span>
                <span id="t_s">00秒</span>
            </time>
            后截团
            {{/if}}
        </span>
        {{else if status==2}}
        <div class="symbol success"></div>
        <div class="result-info">
            <h2>恭喜！组团成功</h2>
            <p>请在指定日期内出行</p>
        </div>
        {{else}}
        <div class="symbol fail"></div>
        <div class="result-info">
            <h2>抱歉！组团失败</h2>
            <p>未在指定时间达到人数，订单自动进入退款流程</p>
        </div>
        {{/if}}
    </nav>
    <article class="wrapper"   style="margin-bottom: 120px;">
        <div class="d-item">
            <div class="ditem-l">产品名称：</div>
            <div class="ditem-r">{{type_name}}</div>
        </div>
        <div class="d-item bdb-1px">
            <div class="ditem-l">订单号：</div>
            <div class="ditem-r">{{order_sn}}</div>
        </div>
        <div class="d-item">
            <div class="ditem-l">出行时间：</div>
            <div class="ditem-r">{{use_time}}</div>
        </div>
        {{if order_method}}
        <div class="d-item bdb-1px">
            <div class="ditem-l">使用方式：</div>
            <div class="ditem-r">{{order_method}}</div>
        </div>
        {{/if}}
        <div class="d-item i-bnr">
            <div class="ditem-l">商家名称：</div>
            <div class="ditem-r">
                <a href="">{{shop_name}}<i class="arrowent"></i></a>
            </div>
        </div>
        <div class="d-item">
            <div class="ditem-l">出行地点：</div>
            <div class="ditem-r">
                <a href="">
                    <span class="addr">{{address}}</span>
<!--                    <i class="arrowent"></i>-->
                </a>
            </div>
        </div>
        <div class="d-item">
            <div class="ditem-l">预约电话：</div>
            <div class="ditem-r">
                <a href="tel:{{if phone}}{{phone}}{{else}}4008007221{{/if}}">{{if phone}}{{phone}}{{else}}4008007221{{/if}}</a>
            </div>
        </div>
        <div class="d-item i-bnr">
            <div class="ditem-l">联系人：</div>
            <div class="ditem-r">
                {{buy_name}}
            </div>
        </div>
        <div class="d-item">
            <div class="ditem-l">手机号：</div>
            <div class="ditem-r">
                <a href="tel:{{buy_phone}}">{{buy_phone}}</a>
            </div>
        </div>
        {{if status==0}}
        <div class="d-item i-bnr">
            <div class="ditem-l">订单状态：</div>
            <div class="ditem-r">
                <span class="status tk">退款中...</span>
            </div>
        </div>
        {{else if status==2}}
        <div class="d-item i-bnr">
            <div class="ditem-l">验证码：</div>
            <div class="ditem-r">
                {{code}}
            </div>
        </div>
        <div class="d-item">
            <div class="ditem-l">订单状态：</div>
            <div class="ditem-r">
                <span class="status">待使用</span>
            </div>
        </div>
        {{/if}}
    </article>
</script>
<footer id="footer">
    <?php echo $this->render('layoutwap/footer.phtml'); ?>
</footer>
<script type="text/javascript" src="/js/weixin.main.js"></script>
<script src="/js/wap/template.js"></script>
<script type="text/javascript">
    function GetQueryString(name)
    {
        var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
        var r = window.location.search.substr(1).match(reg);
        if(r!=null)return decodeURI(r[2]); return null;
    }

    var order_sn = GetQueryString('order_sn');
    var gid = GetQueryString('gid');
    $.ajax({
        type: "POST",
        url: "/good/index/groupjoininfo",
        dataType:"json",
        async: true,
        data:{'uid':<?php echo $_COOKIE['uid'] ? $_COOKIE['uid'] : 0;?>,'order_sn':order_sn,'gid':gid},
        headers: {
            "VER": 10
        },
        success: function (result) {
//            if (result.response_params.status == 0) {
////                alert(result.response_params.message);
//            } else {
                //todo 成功
                //window.location.href = "";
//                console.log(result.response_params);
            var info =  result.response_params;

            function GetRTime(){
                var EndTime= new Date(parseInt(info.end_time)*1000);
                var NowTime = new Date();
                var t =EndTime.getTime() - NowTime.getTime();
                var d=Math.floor(t/1000/60/60/24);
                var h=Math.floor(t/1000/60/60%24);
                var m=Math.floor(t/1000/60%60);
                var s=Math.floor(t/1000%60);

                document.getElementById("t_d").innerHTML = d + "天";
                document.getElementById("t_h").innerHTML = h + "时";
                document.getElementById("t_m").innerHTML = m + "分";
                document.getElementById("t_s").innerHTML = s + "秒";
            }

            setInterval(GetRTime,0);
            var html = template('test', result.response_params);
            document.getElementById('content').innerHTML = html;
//            }
        },
        error: function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
            if (XMLHttpRequest.status == 401) {
                //todo 跳转授权页面
                alert(XMLHttpRequest.responseJSON.message);
//                window.location.href = '<?php //echo $authorUrl;?>//';
            }
            else if (XMLHttpRequest.status == 403) {
                alert('接口验证失败，非法访问');
            }
            else if (XMLHttpRequest.status == 400) {
//                            window.location.href = '<?php //echo $authorUrl;?>//';
                alert('请求参数错误:' + XMLHttpRequest.error_msg);
            }
            else {
                alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
            }
        }
    });
</script>
</body>
</html>