<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge,chrome=1">
    <meta http-equiv=”Cache-Control” content=”no-siteapp” />
    <meta name="apple-mobile-web-app-capable" content="yes" >
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <title>积分兑换</title>
    <link href="/css/wap/common.css" rel="stylesheet"/>
    <link href="/css/wap/score.css" rel="stylesheet"/>
    <script>(function(){var w=window.screen.width,s=w/640,u=navigator.userAgent,m='<meta name="viewport" content="width=640,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
</head>
<body>
<div id="download">
    <a href="http://a.app.qq.com/o/simple.jsp?pkgname=com.deyi.wanfantian&g_f=991653" target="_blank">
        <img src="/images/wap/logo.png"/>
        <h2>玩翻天客户端下单即可享受更多优惠,立即使用</h2>
    </a>
</div>
<main class="align" id="content">
    <header class="header top">
        <a class="header-back" href=""></a>
        <a class="header-title">积分兑换</a>
    </header>
    <section class="wrapper">
        <div class="in-info">
            <h3 class="num">你有<mark>{n}</mark>次购买资格</h3>
            <a class="button" href="" title="">去APP直接购买商品</a>
        </div>
        <div class="in-main">
            <h2>未安装app用户领取资格券流程</h2>
            <h3 class="step">1.下载玩翻天app</h3>
            <div class="in-pic">
                <img src="/images/wap/upload.png" />
            </div>
            <h3 class="step">2.登录玩翻天app</h3>
            <div class="in-pic">
                <img src="/images/wap/register.png" />
            </div>
            <h3 class="step">3. 打开我的积分</h3>
            <div class="in-pic">
                <img src="/images/wap/score.png" />
            </div>
            <h3 class="step">4. 到我的积分使用秒杀资格购买商品</h3>
            <div class="in-pic">
                <img src="/images/wap/duihuan.png" />
            </div>
        </div>
    </section>
</main>
<a class="toTop toTop01" id="toTop" href="javascript:;"><i class="icon"></i>顶部</a>
</body>
<script type="text/javascript" src="/js/weixin.main.js"></script>
</html>