<!DOCTYPE html>
<html lang="zh-cn" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge,chrome=1">
    <meta http-equiv=”Cache-Control” content=”no-siteapp” />
    <meta name="apple-mobile-web-app-capable" content="yes" >
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <title>套系选择</title>
    <link href="/css/order-center.css?ver=<?php echo time();?>" rel="stylesheet" />
    <link href="/css/datepicker.css?ver=<?php echo time();?>" rel="stylesheet">
    <script>(function(){var w=window.screen.width,s=w/750,u=navigator.userAgent,m='<meta name="viewport" content="width=750,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
    <style>
        body{
            background: #f9f9f9;
        }
        .active{
            background: #fb5f39;
            color: #ffffff;
            border: 1px solid #fb5f39;
        }
        .disabled{color:#9e9e9e;background:none}
        .orderIntro p span{
            width: 475px !important;
        }
    </style>
</head>
<body>
<form id="ticketForm">
    <input type="hidden" name="order-id" id="order-id" value=""/>
    <div class="policy-title">
        <?php if($res['select_date'] == 1):?>
            <p><?php echo $res['way'];?></p>
        <?php else:?>
            <p><?php echo $res['game_order'][0]['way'];?></p>
        <?php endif;?>
    </div>
    <div class="intro-all">
    <a class="orderIntro exchange">
        <p>
            <mark>兑换说明：</mark>
            <span><?php echo $res['get_way'];?></span>
            <i></i>
        </p>
    </a>

    <a class="orderIntro special">
        <p>
            <mark>特别说明：</mark>
            <span><?php echo $res['special_info'];?></span>
            <i></i>
        </p>
    </a>
    <?php if($res['select_date'] ==0):?>
    <a class="orderIntro unsubscribe">
        <p>
            <mark>退订说明：</mark>
            <span><?php echo $res['game_order'][0]['back_money'];?></span>
            <i></i>
        </p>
    </a>
    <?php endif;?>
    </div>

    <div class="policy-sel" id="time-list">
        <p>选择时间</p>
        <div class="red-shape"></div>
        <?php if($res['select_date'] == 1):?>
            <div class="date-btn">
                <input type="text" id="calendar" name="calendar" readonly="readonly" placeholder="请选择出行日期" data-value="" value=""/>
                <i></i>
            </div>
        <?php else:?>
        <?php endif;?>
    </div>
    <?php if($res['select_date'] == 0):?>
        <div class="policy-sel" id="place-list">
            <p>选择地点</p>
            <div class="red-shape"></div>
        </div>
    <?php else:?>
    <?php endif;?>
    <?php if($res['select_date'] == 1):?>
        <div class="ticket-counter">
            <p>
                <span>数量</span>
                <span class="ticket-price">￥ <mark id="price"><?php echo $res['low_price'];?></mark>/份</span>
                <span class="plus-btn" id="add"></span>
                <span class="ticket-number" id="text-box">1</span>
                <span class="minus-btn" id="min"></span>
            </p>
        </div>
        <p class="ticket-tip">最少购买<span id="min_buy"><?php echo $res['min_buy'];?></span>张，最多购买<span id="max_buy"><?php echo $res['max_buy'];?></span>张
            <!--            <span class="state_num"> ，仅剩<span id="ticket_num"></span>张</span>-->
        </p>
    <?php else:?>
        <div class="ticket-counter">
            <p>
                <span>数量</span>
                <span class="ticket-price">￥ <mark id="price"><?php echo $res['game_order'][0]['price'];?></mark>/份</span>
                <span class="plus-btn" id="add"></span>
                <span class="ticket-number" id="text-box"><?php echo $res['good_num'];?></span>
                <span class="minus-btn" id="min"></span>
            </p>
        </div>
        <p class="ticket-tip">最少购买<span id="min_buy"><?php echo $res['game_order'][0]['min_buy'];?></span>张，最多购买<span id="max_buy"><?php echo $res['game_order'][0]['max_buy'];?></span>张
            ，仅剩<span id="ticket_num"><?php echo $res['game_order'][0]['total_num']-$res['game_order'][0]['buy'];?></span>张<?php /*echo $res['surplu_num'];*/?>
        </p>
    <?php endif;?>
    <?php if($res['game_order'][0]['insure_num_per_order']>0):?>
        <a class="people-number" href="javascript:;">
            <p>
                <span>出行人数</span>
                <span class="people-name">请选择出行人</span>
            </p>
            <i class="arrow-right"></i>
        </a>
        <div class="policy-intro">
            <input type="checkbox" id="policy-icon" name="myPolicy" checked="checked"/>
            <label class="policy-radio" for="policy-icon"></label>
            <p>
                <span>免费参加户外运动险（单人最高10000）</span>
                <span id="policy-btn">保险说明</span>
            </p>
        </div>
    <?php endif;?>
    <div class="ticket-info">
        <a href="/web/travel/addrlist?type=1">
            <p><span class="address-name"><?php echo $res['contacts']['name'];?></span><span class="address-tel"><?php echo $res['contacts']['phone'];?></span></p>
            <p class="address-line"><input style="border: none" type="text" value="<?php echo $res['contacts']['province'].$res['contacts']['city'].$res['contacts']['region'].$res['contacts']['address']; ?>" placeholder="点击完善收货地址" class="address-position" readonly="readonly" id="address"></p>
        </a>
    </div>
    <?php if($res['is_comments_value'] == 1):?>
    <div class="remark">
        <span>备注</span>
        <textarea id="remark-info" placeholder="<?php echo $res['message'];?>"></textarea>
    </div>
    <?php endif;?>

    <?php if($res['select_date'] == 1):?>
        <div class="fixed-btn">
            <div class="total-price">
                <span>总价：<mark>￥</mark><mark class="total" id="total"></span>
            </div>
            <a class="next-btn" href="javascript:;" id="submit-btn">提交订单</a>
        </div>
    <?php else:?>
        <div class="fixed-btn">
            <div class="total-price">
                <span>总价：<mark>￥</mark><mark class="total" id="total"><?php echo $res['game_order'][0]['price']*$res['good_num'];?></mark></span>
            </div>
            <a class="next-btn" href="javascript:;" id="submit-btn">提交订单</a>
        </div>
    <?php endif;?>
    <input type="hidden" name="uid" value="<?php echo $_COOKIE['uid'];?>">
    <input type="hidden" name="coupon_id" value="<?php echo $res['id'];?>">
    <input type="hidden" name="group_buy" value="<?php echo $res['group_buy'];?>">
    <input type="hidden" name="group_buy_id" value="<?php echo $res['group_buy_id'];?>">
    <input type="hidden" name="name" value="<?php echo $res['contacts']['name'];?>">
    <input type="hidden" name="phone" value="<?php echo $res['contacts']['phone'];?>">
    <input type="hidden" name="order_type" value="2">
    <input type="hidden" name="order_id" value="<?php echo $res['order_id']; ?>" id="order_id">
    <input type="hidden" name="associates_ids" value="" id="associates_ids">
    <input type="hidden" name="limit_num" value="<?php echo $res['game_order'][0]['min_buy'];?>" id="limit_num">
    <input type="hidden" name="surplus_num" value="<?php echo $res['game_order'][0]['total_num']-$res['game_order'][0]['buy'];?>" id="surplus_num">
    <input type="hidden" name="g_buy" value="<?php echo $res['g_buy'];?>" id="g_buy">
    <input type="hidden" name="message" id="remark" value="<?php echo $res['is_comments_value'];?>">
    <input type="hidden" name="has_addr" id="has_addr" value="<?php echo $res['game_order'][0]['has_addr'];?>">
    <input type="hidden" name="insure_num_per_order" id="insure_num_per_order" value="<?php echo $res['game_order'][0]['insure_num_per_order'];?>">
    <input type="hidden" name="tip" id="tip" value="<?php echo $res['tip'];?>">
    <input type="hidden" name="select_date" id="state" value="<?php echo $res['select_date'];?>"/>
    <input type="hidden" name="order_time" id="order_time" data-start="<?php echo $res['order_start_time'];?>" data-end="<?php echo $res['order_end_time'];?>"/>
</form>
<div id="tipsDia"></div>
<div class="matte" style="z-index: 11;"></div>
<div class="policy-popup">
    <div class="policy-content">
        <h5><span>投保说明</span></h5>
        <div class="policy-text">
            <p>1、本产品由史带财产保险股份有限公司承保，目前该公司在北京、上海、江苏、浙江、宁波、安徽、青岛、福建、苏州有分支机构，客户从保游网购买，后续理赔等相关事务均可由保游网协助您办理。</p>
            <p>2、本产品承保年龄1周岁-80周岁（含1、80周岁），按中国保监会规定，10周岁及以下的未成年人累计身故保险金额不得超过人民币20万元；11至17周岁的未成年人累计身故保险金额不得超过人民币50万元。若未成年被保险人的保险金额超过上述规定，则以上述规定的保险金额为限。</p>
            <p>3、可承保的拓展训练包括但不限于：雷区取水、无敌风火轮 、背摔、断桥、孤岛求生、有轨电车、鳄鱼潭、时速极限、高空拓展训练（不高于15米，且所有从事空中活动的人士，必须绑定安全带）、钻电网、真人CS、毕业墙、信任背摔、模拟电网、移花接木、罐头鞋、梅花桩、盲目障碍、礼让通行、齐心协力、雷阵、吊索桥、情侣桥、水上漂、搭板过河、板桥、缅甸桥、溜索过河、滚筒桥、秋千桥、云梯桥、栈道桥、索道桥等。</p>
            <p>4、本产品不承保自驾车旅游人士，并且不承保被保险人从事潜水、跳伞、攀岩运动、探险活动、摔跤比赛、特技表演等高风险运动。</p>
            <p>5、目前我公司互联网保险业务，均已采用加密传输协议（https）或证书方式进行信息加密传输，通过技术和管理手段，对涉及投保人的信息安全加以保障，保护用户个人信息安全。</p>
            <p>6、本产品指定医院为符合条款要求的医院，除了北京平谷区所有医院。请注意：北京市平谷区所有医院的就医均不给予理赔。</p>
            <p>7、本计划为网络销售产品，网上投保、网上支付、网上即时核保并出具电子保单，您可拨打史带财险客服热线400-999-5507查询、验真。</p>
            <p>8、史带财险24小时全国救援服务热线：021-38295959，提供旅行资讯、医疗咨询和紧急救援服务咨询。</p>
            <table class="grid-table">
                <tr>
                    <td class="first-row">保障范围（个人意外伤害医疗及紧急救援保障）</td><td>保障金额(单位：元)</td><td>保障说明</td>
                </tr>
                <tr>
                    <td>意外身故、伤残及残疾保障</td><td>100,000</td><td>在保险期间内，若被保险人在旅行时遭遇约定的意外伤害事故，保险公司按保险金额给付身故保险金。若被保险人在旅行时遭遇约定的意外伤害事故，保险公司按条款约定比例给付伤残保险金</td>
                </tr>
                <tr>
                    <td>意外医疗</td><td>40,000</td><td>在保险期间内，若被保险人在旅行时遭遇约定的意外伤害事故，保险公司将依据条款约定对被保险人已支出的、必需且合理的实际医药费给付意外医疗费用补偿保险金。（0免赔，80%赔付）</td>
                </tr>
                <tr>
                    <td>意外住院津贴</td><td>80元/天</td><td>在保险期间内，若被保险人在旅行时遭遇约定的意外伤害事故，在二级以上（含二级）医院或保险公司认可的医疗机构接受住院治疗，保险公司将依据条款约定，按其住院日数给付每日住院津贴保险金。（每次住院以30天为限，全年累计以180天为限）</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="close-btn">
        <div class="cross"></div>
    </div>
</div>

<!--兑换说明、特别说明弹窗-->
<div class="introPopup" style="display: none">
    <p></p>
    <span></span>
    <a class="introBtn">关闭</a>
</div>
<script src="/js/zepto1.1.6.min.js"></script>
<script src="/js/zlDate.js?ver=<?php echo time();?>"></script>
<!--<script src="/js/date.js"></script>-->
<!--<script src="/js/order-center/common.js" type="text/javascript"></script>-->

<script>
    (function () {

        //radio单选框取消选中

        $("#policy-btn").on("touchend",function(e){
            e.preventDefault();
            $(".matte").show();
            $(".policy-popup").show();
        });
        $(".close-btn").on("touchend",function(e){
            e.preventDefault();
            $(".matte").hide();
            $(".policy-popup").hide();
        });

        var clickPolicy = $("#policy-icon");

        $(".policy-radio").on("tap",function(){

            if(clickPolicy.attr("checked") == 'checked')
            {
                clickPolicy.removeAttr('checked');
            }
            else{
                clickPolicy.attr("checked","checked");
            }
        });

        var isTouch = ("ontouchend" in document ? "touchend" : "tap");
        var city = localStorage.getItem("select_city"),
            tip =$("#tip").val(),
            num = 1,
            people_num = $("#insure_num_per_order").val(),
            total_people_num = num*people_num;

        $(".people-number").on("click", function (e) {
            e.preventDefault();
            num = parseInt($("#text-box").text());
            total_people_num = num*people_num;
            window.location.href="/web/travel/traveller?total_people_num="+total_people_num+"&type=1&city="+encodeURI(city)+"&good_num="+num;
        });

        if(tip==1){
            var traveller_id = localStorage.getItem("select_traveller_ids"),
                traveller_name = localStorage.getItem("select_traveller_names"),
                select_traveller_num = localStorage.getItem("select_traveller_num");

            num = parseInt($("#text-box").text());
            total_people_num = num*people_num;

            if(select_traveller_num<total_people_num){
                var diff= parseInt(total_people_num-select_traveller_num);
                loginTip.text("您还有"+diff+"个出行人信息未填写，这些信息将被用于购买保险");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                },2000);
            }
            $("#associates_ids").val(traveller_id);
            $(".people-name").text(traveller_name);
        }else{
            localStorage.setItem("select_traveller_ids",'');
            localStorage.setItem("select_traveller_names",'');
        }



        var state = $('#state').val(),
            submitBtn = $("#submit-btn"),
            calendar = $("#calendar");


        var s_month;

        if(!calendar.val()){
            s_month = show_time();
        }

        if(state == 1){
            calendar.on('tap', function() {
                if (!calendar.attr('data-value')) {

                    var start_str = s_month + '-' + '01' + ' 00:00:00',
                        end_str = s_month + '-' + getDays() + ' 24:00:00';
                    start_str=start_str.replace(/-/g,':').replace(' ',':');
                    start_str=start_str.split(':');
                    end_str=end_str.replace(/-/g,':').replace(' ',':');
                    end_str=end_str.split(':');
                    var start_time = new Date(start_str[0],(start_str[1]-1),start_str[2],start_str[3],start_str[4],start_str[5]).getTime()/1000;
                    var end_time = new Date(end_str[0],(end_str[1]-1),end_str[2],end_str[3],end_str[4],end_str[5]).getTime()/1000;
                    if(order_start >= end_time){
                        start_time = order_start;
                        end_time =order_end;
                        AjaxTime(start_time, end_time);
                        pickerEvent.getDetail(start_time);
                    }else{
                        AjaxTime(start_time, end_time);
                        pickerEvent.getToday();
                    }
                }else{
                    var now = calendar.attr('data-value');
                    var now_str = now.split('-');
                    var daycount = DayNumOfMonth(now_str[0],now_str[1]);
                    var start_str = now_str[0] + '-' + now_str[1] + '-01' + ' 00:00:00';
                    var end_str = now_str[0] + '-' + now_str[1] + '-' +daycount + ' 24:00:00';
                    start_str=start_str.replace(/-/g,':').replace(' ',':');
                    start_str=start_str.split(':');
                    end_str=end_str.replace(/-/g,':').replace(' ',':');
                    end_str=end_str.split(':');
                    var start_time = new Date(start_str[0],(start_str[1]-1),start_str[2],start_str[3],start_str[4],start_str[5]).getTime()/1000;
                    var end_time = new Date(end_str[0],(end_str[1]-1),end_str[2],end_str[3],end_str[4],end_str[5]).getTime()/1000;
                    AjaxTime(start_time,end_time);
                }
            })
        }else{
            var order_id ='' ,
                t_menu = $(".t_menu"),
                a_menu = $(".a_menu");
            var obj = <?php echo json_encode($res['game_order']);?>;
            var t_sorted = {};
            var a_sorted = {};
            obj.forEach(function (value) {
                var time = value.s_time + ':' + value.e_time;
                var address = value.address + ':' + value.shop_name;
                if (!t_sorted[time]) {
                    t_sorted[time] = {
                        place: [],
                        start: value.s_time,
                        end: value.e_time
                    };
                }
                t_sorted[time].place.push({
                    address: value.address,
                    shop_name: value.shop_name,
                    id: value.shop_id,
                    order_id: value.order_id,
                    traveller_num:value.insure_num_per_order
                });


                if (!a_sorted[address]) {
                    a_sorted[address] = {
                        date: [],
                        start: value.shop_name,
                        end: value.address,
                        id: value.shop_id
                    };
                }
                a_sorted[address].date.push({
                    s_time: value.s_time,
                    e_time: value.e_time,
                    order_id: value.order_id,
                    traveller_num:value.insure_num_per_order
                });
            });

            function select() {
                if (selectedAddress) {
                    obj.forEach(function (item) {
                        if (item.shop_id == selectedAddress && item.s_time == selectedTime.start && item.e_time == selectedTime.end) {
                            orderId.val(item.order_id);
                        }
                    });
                } else {
                    orderId.get(0).value = '';
                }
            }

            var timeInputs = {},
                placeInputs = {},
                timeList = $('#time-list'),
                placeList = $('#place-list'),
                defaultTime,
                defaultPlace,
                orderId = $('#order-id'),
                selectedAddress,
                selectedTime;

            $.each(t_sorted,function(time, data){
                var input = $('<input type="radio" id="select-time-' + time + '" name="myTime" value=\'' + JSON.stringify(data.place) + '\' data-time=\'{"start":' + data.start + ',"end":' + data.end + '}\' />');
                var s_date = new Date(data.start*1000),
                    e_date = new Date(data.end*1000),
                    now = new Date().getTime();

                t = e_date.getTime()-now;
                if (!defaultTime) {
                    defaultTime = input;
                    selectedTime = {
                        start: data.start,
                        end: data.end
                    };
                }

                timeInputs[time] = input;
                timeList.append(input).append($('<label class="time-first" for="select-time-' + time + '"><span class="time-content">' + s_date.getFullYear()+'/'+(s_date.getMonth()+1 < 10 ? '0'+(s_date.getMonth()+1) : s_date.getMonth()+1)+'/'+(s_date.getDate() < 10 ? '0'+(s_date.getDate()) : s_date.getDate())+' '+ s_date.getHours()+':'+ (s_date.getMinutes()==0 ? '00' :s_date.getMinutes()) + '~' + e_date.getFullYear()+'/'+(e_date.getMonth()+1 < 10 ? '0'+(e_date.getMonth()+1) : e_date.getMonth()+1)+'/'+e_date.getDate()+' '+ e_date.getHours()+':'+ (e_date.getMinutes()==0 ? '00' :e_date.getMinutes()) + '&nbsp;&nbsp;&nbsp;仅剩'+Math.ceil(Math.floor(t/1000/60/60/24))+'天</span></label>'));
            });

            $.each(a_sorted, function(key, place) {
                var input = $('<input type="radio" id="select-address-' + place.id + '" name="myAddress" value=\'' + JSON.stringify(place.date) + '\' data-id="' + place.id + '" />');

                placeInputs[place.id] = input;
                placeList.append(input).append($('<label class="time-first" for="select-address-' + place.id + '"><span class="time-content">' + place.start + '<mark>' + place.end + '</mark></span></label>'));
            });

            timeList.on('change', 'input', function (e) {
                var places = JSON.parse(e.target.value),
                    cancelPlace = true;

                selectedTime = $(e.target).data('time');
                $.each(placeInputs, function (key, input) {
                    input.prop('disabled', true);
                });
                places.forEach(function (place) {
                    if (!defaultPlace) {
                        defaultPlace = placeInputs[place.id].prop('checked', true).trigger('change');
                    }

                    if (selectedAddress == place.id) {
                        cancelPlace = false;
                    }

                    placeInputs[place.id].prop('disabled', false);
                });

                if (cancelPlace && selectedAddress) {
                    placeInputs[selectedAddress].prop('checked', false);
                    selectedAddress = null;
                }
                select();
            });

            placeList.on('change', 'input', function (e) {
                selectedAddress = $(e.target).data('id');
                select();
            });

            defaultTime.prop('checked', true).trigger('change');
        }

        var introPopup = $(".introPopup");
        $(".intro-all").on("touchend",".orderIntro",function(e){
            e.preventDefault();
            var title = $(this).find("p").find("mark").text(),
                desc = $(this).find('p').find('span').text();
            introPopup.find('p').text(title);
            introPopup.find('span').text(desc);
            introPopup.show();
            $(".matte").show();
        });

        $('.introBtn').on("touchend",function(e){
            e.preventDefault();
            introPopup.hide();
            $(".matte").hide();
        });



        //获得文本框对象
        var t = $("#text-box"),
            add = $("#add"),
            min = $("#min"),
            total = $("#total"),
            price = parseFloat($("#price").text()).toFixed(2);


        //数量增加操作
        add.on(isTouch,function(e){
            e.preventDefault();
            min.removeClass("disabled");
            var n= $(this).next().text();
            var num= parseInt(n)+1;
            var t_num = parseInt($('#ticket_num').text());
            var limit_num = $("#max_buy").text(),
                surplus_num = $("#max_buy").text(),
                g_buy = $("#g_buy").val();
            if(num>limit_num || num>surplus_num || num>t_num){
                return false;
            }
            $(this).next().text(num);
            setTotal();
        });
        //数量减少操作
        min.on(isTouch,function(){
            var n=$(this).prev().text();
            var num=parseInt(n)-1;
            if(num==0){ min.addClass("disabled");return;}
            $(this).prev().text(num);
            setTotal();
        });
        //计算操作
        window.setTotal = function(){
            price = parseFloat($("#price").text()).toFixed(2)
            total.html((parseInt(t.text())*price).toFixed(2));
        };
        //初始化
        setTotal();

        submitBtn.on(isTouch, function(e){
            e.preventDefault();
            var orderNum = t.text(),
                order_id=$("#order-id").val(),
                group_buy = $('input[name="group_buy"]').val(),
                group_buy_id = $('input[name="group_buy_id"]').val(),
                coupon_id = $('input[name="coupon_id"]').val(),
                name = $('input[name="name"]').val(),
                phone = $('input[name="phone"]').val(),
                min_buy= $("#min_buy"),
                link_address= $(".address-position").val(),
                is_remark = $("#remark").val(),
                user_remark = $("#remark-info").val(),
                has_addr = $("#has_addr").val(),
                insure_num_per_order = $("#insure_num_per_order").val(),
                associates_ids = $("#associates_ids").val();

            if(orderNum<min_buy.text()){
                loginTip.text("该商品最少购买"+min_buy.text()+"张");
                loginTip.show();
                setTimeout(function(){
                    loginTip.hide();
                    submitBtn.attr('disabled', false);
                },2000);
                return false;
            }

            if(!order_id){
                if(state ==1){
                    setTimeout(function(){
                        loginTip.hide();
                        submitBtn.attr('disabled', false);
                    },2000);
                    var start_str = s_month + '-' + '01',
                        end_str = s_month + '-' + getDays(),
                        start_time = new Date(start_str).getTime() / 1000,
                        end_time = new Date(end_str).getTime() / 1000;
                    if(order_start > end_time){
                        start_time = order_start;
                        end_time =order_end;
                        AjaxTime(start_time, end_time);
                        pickerEvent.getDetail(start_time);
                    }else{
                        AjaxTime(start_time, end_time);
                        pickerEvent.getToday();
                    }
                    loginTip.text("请选择出行日期");
                    loginTip.show();
                }else{
                    loginTip.text("请选择时间地点");
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                        submitBtn.attr('disabled', false);
                    },2000);
                }

                return false;
            }

            if(has_addr==1){
                if(!link_address){
                    loginTip.text("请填写收货地址！");
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                        submitBtn.attr('disabled', false);
                    },2000);
                    return false;
                }
            }

            if(is_remark==1){
                if(!user_remark){
                    loginTip.text("请填写备注！");
                    loginTip.show();
                    setTimeout(function(){
                        loginTip.hide();
                        submitBtn.attr('disabled', false);
                    },2000);
                    return false;
                }
            }
            $('#submit-btn').val('请稍候..').css({'background-color': '#ccc'}).attr({"disabled": "disabled"});
            var city = localStorage.getItem("select_city");
            window.location.href="/web/wappay/payment?coupon_id="+coupon_id+"&number="+orderNum+"&name="+name+"&phone="+phone+"&order_id="+order_id+"&group_buy="+group_buy+"&group_buy_id="+group_buy_id+"&message="+user_remark+"&city="+encodeURI(city)+"&address="+link_address+"&associates_ids="+associates_ids;
        });
    }());
</script>
</body>
</html>

