<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge,chrome=1">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta name="apple-mobile-web-app-capable" content="yes" >
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <title>收银台</title>
    <script>(function(){var w=window.screen.width,s=w/640,u=navigator.userAgent,m='<meta name="viewport" content="width=640,';if(/android (\d+\.\d+)/i.test(u)){if(parseFloat(RegExp.$1>2.3)){m+="minimum-scale = "+s+", maximum-scale = "+s+","}}else{m+="user-scalable=no,"}m+='target-densitydpi=device-dpi">';document.write(m)}());</script>
    <link href="/css/wap/common.css" rel="stylesheet"/>
    <link href="/css/wap/my.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/css/wap/custom.css">
    <link rel="stylesheet" href="/css/wap/iosOverlay.css">
    <style>
        /* CSS RESET */
        * { padding: 0; margin: 0; }
        .ftc_wzsf { font: 16px "微软雅黑", Arial;  min-width: 400px; max-width: 640px; color: #000;border-radius: 5px; }
        a { text-decoration: none; color: #666666; }
        a, img { border: none; }
        img { vertical-align: middle; }
        ul, li { list-style: none; }
        em, i { font-style: normal; }
        .clear_wl:after { content: "."; height: 0; visibility: hidden; display: block; clear: both; }
        .fl { float: left ;font-size: 16px;}
        .fr { float: right }
        /********/
        .gofh a { padding-right: 10px; border-right: 1px solid #2e2f33; }
        .gofh a img { width: 40%; }
        .ttwenz h4 { font-size: 16px; font-weight: 400; margin-top: 2px; }
        .ttwenz h5 { font-size: 14px; font-weight: 400; color: #6c7071; }
        .wenx_xx .wxzf_price { font-size: 45px;    margin-top: 10px; }
        /**/
        .ftc_wzsf { display:none; width: 100%; height: 100%; position: fixed; z-index: 999; top: 0; left: 0; }
        .ftc_wzsf .srzfmm_box { position: fixed; z-index: 10; background: #f8f8f8; width: 88%; left: 50%; margin-left: -44%; top: 100px;min-height:400px;border-radius: 15px;}
        .qsrzfmm_bt { font-size: 16px; border-bottom: 1px solid #c9daca; overflow: hidden; }
        .qsrzfmm_bt a { display: block; width: 10%; padding: 10px 0; text-align: center; }
        .qsrzfmm_bt img.tx { width: 10%; padding: 10px 0; }
        .qsrzfmm_bt span {  margin-left: 190px;
            margin-top: 10px;
            font-size: 25px; }
        .zfmmxx_shop { text-align: center; font-size: 24px; padding: 10px 0; overflow: hidden;
            min-height: 100px;; }
        .zfmmxx_shop .mz { font-size: 25px; float: left; width: 100%;min-height: 50px;
            line-height: 50px; }
        .zfmmxx_shop .wxzf_price { font-size: 30px; float: left; width: 100%; }
        .blank_yh { width: 89%; margin: 0 auto; line-height: 40px; display: block; color: #636363; font-size: 16px; padding: 5px 0; overflow: hidden; border-bottom: 1px solid #e6e6e6; border-top: 1px solid #e6e6e6; }
        .blank_yh img { height: 40px; }
        .ml5 { margin-left: 5px; }
        .zfcg_box img{ width:10%;}

        .spxx_shop td{ color:#7b7b7b; font-size:16px; padding:10px 0;}

        .wzxfcgde_tb img{ width:20.6%;}

        .pwd-box{
            position: absolute;
            top: 286px;
            left: 50%;
            margin-left: -180px;
            height: 60px;
            width: 360px;
            z-index: 2;
            -webkit-tap-highlight-color: rgba(0,0,0,0);
        }
        .pwd-box input[type="tel"]{
            color: transparent;
            width: 100%;
            height: 60px;
            opacity: 0;
            border: none;
            font-size: 1px;
            z-index: 2;
            pointer-events: none;
        }

        .fake-box{
            width: 360px;
            height: 60px;
            margin: 35px auto 0;
        }

        .fake-box > div{
            position: relative;
            width: 58px;
            height: 58px;
            border: 1px solid #e5e5e5;
            background: #fff;
            float: left;
            overflow: hidden;
            margin-left: -1px;
        }
        .fake-box input:nth-last-child(1){
            border:none;
        }
        .box-active:before{
            content: '';
            position: absolute;
            left: 50%;
            top: 50%;
            margin: -3px 0 0 -3px;
            display: block;
            height: 6px;
            width: 6px;
            border-radius: 3px;
            background: #000;
        }
        .pop-notice{
            position: absolute;
            left: 20%;
            top: 40%;
            padding: 15px 20px;
            font-size: 26px;
            text-align: center;
            color: #fff;
            background-color: rgba(0, 0, 0, 0.6);
        }
        .shop-title{
            margin-top: 10px !important;
        }
    </style>
</head>
<body>
<section class="wrapper">
    <form class="shop-form" action="" method="post">
        <div class="shop-info">
            <div class="item"><span class="title">产品名称：</span><?php echo $coupon_data->title;?></div>
            <?php if( date('Y-m-d', $orderGameData->start_time) == date('Y-m-d', $orderGameData->end_time)) :?>
                <div class="item"><span class="title">出行时间：</span><?php echo date('Y-m-d', $orderGameData->start_time)?></div>
            <?php else:?>
                <div class="item"><span class="title">出行时间：</span><?php echo date('Y-m-d', $orderGameData->start_time)?> ~ <?php echo date('Y-m-d', $orderGameData->end_time)?></div>
            <?php endif;?>

            <!--                <div class="item"><span class="title">订单号：</span>--><?php //echo $coupon_data->order_sn;?><!--</div>-->
        </div>
        <main class="align" id="content"></main>
        <h2 class="shop-title"><i class="icon cash"></i>现金券/优惠券</h2>
        <?php if($cashcoupon_data):?>
            <?php if($sid>0 && $flag == -1):?>
<!--                <a class="shop-coupon" href="/web/wappay/mycashcoupon?type=2&pay_price=--><?php //echo $total;?><!--&coupon_id=--><?php //echo $sid;?><!--&tourl=--><?php //echo urlencode($back_url);?><!--&city=--><?php //echo $city;?><!--&sid=--><?php //echo $sid;?><!--">-->
<!--                    --><?php //echo $cashcoupon_data['title'];?><!--&nbsp;&nbsp;&nbsp;&yen;<mark id="cashcoupon">--><?php //echo $cashcoupon_data['price'];?><!--</mark>-->
<!--                    <i class="arrowent"></i>-->
<!--                </a>-->
                <a class="shop-coupon" href="/web/wappay/mycashcoupon?type=3&pay_price=<?php echo $total;?>&coupon_id=<?php echo $coupon_data->id;?>&tourl=<?php echo urlencode($back_url);?>&sid=<?php echo $sid;?>&city=<?php echo $city;?>">
                    选择或兑换现金券
                    <i class="arrowent"></i>
                </a>
            <?php else:?>
                <a class="shop-coupon" href="/web/wappay/mycashcoupon?type=1&pay_price=<?php echo $total;?>&coupon_id=<?php echo $coupon_data->id;?>&tourl=<?php echo urlencode($back_url);?>&city=<?php echo $city;?>&sid=<?php echo $sid;?>">
                    <?php echo $cashcoupon_data['title'];?>&nbsp;&nbsp;&nbsp;&yen;<mark id="cashcoupon"><?php echo $cashcoupon_data['price'];?></mark>
                    <i class="arrowent"></i>
                </a>
            <?php endif;?>

        <?php else:?>
        <a class="shop-coupon" href="/web/wappay/mycashcoupon?type=3&pay_price=<?php echo $total;?>&coupon_id=<?php echo $coupon_data->id;?>&tourl=<?php echo urlencode($back_url);?>&sid=<?php echo $sid;?>&city=<?php echo $city;?>">
            选择或兑换现金券
            <i class="arrowent"></i>
        </a>
        <?php endif;?>

        <h2 class="shop-title"><i class="icon pay"></i>支付方式</h2>
        <div class="shop-pay">
            <label class="item <?php if($surplus>=$total || $total==0){echo 'active radio';}?> " data="account">
                <span class="pay pay01 left"><i class="icon"></i>余额</span>
                <span class="choose right">&yen;<mark><?php echo $surplus;?></mark><i class="icon"></i> </span>
                <input type="radio" class="option-input" name="surplus" value="1" checked="<?php if($surplus>=$total || $total==0){echo 'cheched';}?>">
            </label>
            <!--                <label class="item radio">-->
            <!--                    <span class="pay pay02 left"><i class="icon"></i>支付宝</span>-->
            <!--                    <span class="choose right"><i class="icon"></i> </span>-->
            <!--                    <input type="radio" class="option-input" name="alipay" value="">-->
            <!--                </label>-->
            <!--                <label class="item radio">-->
            <!--                    <span class="pay pay03 left"><i class="icon"></i>银联卡</span>-->
            <!--                    <span class="choose right"><i class="icon"></i> </span>-->
            <!--                    <input type="radio" class="option-input" name="union" value="">-->
            <!--                </label>-->
            <label class="item radio <?php if($surplus<$total && $total>0){echo 'active';}?> " data="weixin">
                <span class="pay pay03 left"><i class="icon"></i>微信支付</span>
                <span class="choose right"><i class="icon"></i> </span>
                <input type="radio" class="option-input" name="wei" value="3" checked="<?php if($surplus<$total && $total>0){echo 'cheched';}?>">
            </label>
        </div>
        <div class="fix shop-last">
            <span class="amount">实付 <i>&yen;</i><mark class="real-pay"><?php echo $total;?></mark></span>
            <a class="submit paysub" href="javascript:;" id="pay"><?php if($total>0){echo "去支付";}else{echo "去报名";}?></a>
        </div>
    </form>
</section>
<!--<a class="toTop toTop01" id="toTop" href="javascript:;"><i class="icon"></i>顶部</a>-->
<!--浮动层-->

<div class="ftc_wzsf" style="z-index: 1001">
    <div class="srzfmm_box">
        <div class="qsrzfmm_bt clear_wl close"><img style="float: right;" src="/images/wap/zf/xx_03.jpg" class="tx close fl" > <span class="fl" style="height: 77px;line-height: 77px;margin-top: 0;">请输入支付密码</span> </div>
        <div class="zfmmxx_shop">
            <div class="mz"><?php echo $coupon_data->title;?></div>
            <div class="wxzf_price">&yen;<mark class="real-pay"><?php echo $total;?></mark></div>
        </div>
        <a href="#" class="blank_yh item"><span class="fl ml5" style="font-size: 25px;">余额支付</span>
<!--            <img src="/images/wap/zf/jftc_09.jpg" class="fr">-->
        </a>
        <label class="pwd-box" for="pwd-input">
            <input type="tel" maxlength="6" class="pwd-input" id="pwd-input">
        </label>
        <div class="fake-box">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</div>
<div class="matte" style="display:none;position: fixed;top: 0;right: 0;bottom: 0;left: 0;background: rgba(0,0,0,0.7);z-index: 1000;"></div>
<input type="hidden" name="pwd" id="pay_pwd" value="<?php echo $pay_pwd;?>">
<input type="hidden" name="surplus" id="surplus" value="<?php echo $surplus;?>">
<input type="hidden" name="group_buy_id" id="group_buy_id" value="<?php echo $group_buy_id;?>">
<input type="hidden" name="price" id="price" value="<?php echo $orderGameData->price;?>">
<input type="hidden" name="cash_coupon_id" id="cash_coupon_id" value="<?php echo $cashcoupon_data['id'];?>">
<input type="hidden" name="cash_coupon_price" id="cash_coupon_price" value="<?php echo $cashcoupon_data['price'];?>">
<input type="hidden" name="coupon_id" id="coupon_id" value="<?php echo $coupon_data->id;?>">
<input type="hidden" name="group_buy" id="group_buy" value="<?php echo $group_buy;?>">
<input type="hidden" name="number" id="number" value="<?php echo $number;?>">
<input type="hidden" name="name" id="name" value="<?php echo $name;?>">
<input type="hidden" name="phone" id="phone" value="<?php echo $phone;?>">
<input type="hidden" name="message" id="message" value="<?php echo $message;?>">
<input type="hidden" name="uid" id="uid" value="<?php echo $_COOKIE['uid'];?>">
<input type="hidden" name="sid" id="sid" value="<?php echo $sid;?>">
<input type="hidden" name="eid" id="eid" value="<?php echo $coupon_data->base_id;?>">
<input type="hidden" name="order_id" id="order_id" value="<?php echo $orderGameData->id;?>">
<input type="hidden" name="total" id="total" value="<?php echo $total;?>">
<input type="hidden" name="address" id="address" value="<?php echo $address;?>">
<input type="hidden" name="associates_ids" id="associates_ids" value="<?php echo $associates_ids;?>">
<input type="hidden" name="url" id="url" value="<?php echo urlencode($back_url);?>">
<input type="hidden" name="meet" id="meet" value="<?php echo $meet;?>">
<input type="hidden" name="share_order_sn" id="share_order_sn" value="<?php echo $share_order_sn;?>">

<!--提醒用户在微信端打开-->
<div id="pop-tell" style="display: none">
    <span class="pop-notice">亲，不是微信端，无法完成支付,<br>请在微信端完成操作！</span>
</div>

</body>
<script src="/js/zepto1.1.6.min.js"></script>
<!--<script type="text/javascript" src="/js/weixin.main.js"></script>-->
<script src="/js/wap/plugin/custom.js"></script>
<script src="/js/wap/plugin/iosOverlay.js"></script>
<script src="/js/wap/plugin/spin.min.js"></script>
<script src="/js/wap/plugin/prettify.js"></script>
<script>
    (function(){
        var surplus = $("#surplus").val(),
            isTouch = ("ontouchend" in document ? "touchend" : "tap"),
            total = $("#total").val(),
            uid = $("#uid").val(),
            cash_coupon_id = $("#cash_coupon_id").val(),
            cash_coupon_price = $("#cash_coupon_price").val(),
            coupon_id = $("#coupon_id").val(),
            group_buy = $("#group_buy").val(),
            number = $("#number").val(),
            name = $("#name").val(),
            phone = $("#phone").val(),
            message = $("#message").val(),
            group_id = $("#group_buy_id").val(),
            price = $('#price').val(),
            address = $('#address').val(),
            associates_ids = $('#associates_ids').val(),
            order_id = $('#order_id').val(),
            sid = $('#sid').val(),
            base_id = $('#eid').val(),
            pay_pwd = $("#pay_pwd").val(),
            meet = $("#meet").val(),
            share_order_sn = $("#share_order_sn").val(),
            use_account_money = 0,
            city = localStorage.getItem("select_city"),
            tourl = $("#url").val();

        if(total>0){
            var realpay = parseFloat(total-cash_coupon_price).toFixed(2);
            var diff = surplus-realpay;
            $(".real-pay").text(realpay);
        }

        $(".radio").on(isTouch,function(e){
            e.preventDefault();
            if(total==0){
                if($(this).attr("data")=='weixin'){
                    $(this).find("input").attr("checked","false");
                    loadingErr("抱歉，0元商品只能使用余额支付");
                }
            }else{
                $(this).addClass("active").siblings(".radio").removeClass("active");
                $(this).find("input").attr("checked","true");
                $(this).siblings().find("input").removeAttr('checked');
            }
        });


        $('#pay').on(isTouch,function (e) {
            e.preventDefault();
            var chk;
            var ua = navigator.userAgent.toLowerCase();
            var isWeixin = ua.indexOf('micromessenger') != -1;
            /* *
             *如果用户不是在微信端打开支付页面，跳出弹框提醒
             * */
            if (!isWeixin) {
                $('#pop-tell').show();
            }else {
                $('#pop-tell').hide();
            }

            if(total==0){
                chk=1;
                use_account_money=1;
            }else{
                if(diff>=0){
//                    chk = $('input:radio:checked').val();
                    chk = $("input[type=radio]:checked").val();//zepto加载时获取选中值需加上type
                    use_account_money=1;
                }else{
                    chk = 3;
                }
            }

            if(sid>0){
               var charges = localStorage.getItem('charges'),
                    data = {'uid':uid,'session_id':coupon_id,'name':name,'phone':phone,'cash_coupon_id':cash_coupon_id,'address':address,'associates_ids':"["+associates_ids+"]",'charges':charges,'id':base_id,'meeting_id':meet,'share_order_sn':share_order_sn>0 ? share_order_sn : 0};
            }else{
               var data = {'uid':uid,'coupon_id':coupon_id,'number':number,'name':name,'phone':phone,'order_id':order_id,'order_type':2,'group_buy':group_buy,'group_buy_id':group_id,'message':message,'cash_coupon_id':cash_coupon_id,'address':address,'associates_ids':"["+associates_ids+"]"};
            }



            if(chk==1){
                if(total>0){
                    if(!pay_pwd){
                        if(confirm("请设置支付密码")){
                            window.location.href="/web/wappay/register?type=1&tourl=/web/wappay/setpaypwd&backurl="+tourl;
                        }
                        return false;
                    }


                    $(".ftc_wzsf").show();
                    $(".matte").show();
                    //关闭浮动
                    $(".close").click(function(){
                        $(".ftc_wzsf").hide();
                        $(".matte").hide();
                    });

                    var boxs = $(".fake-box").children();
                    var password = [];
                    var field = $("#pwd-input");

                    if (/ios|ipad|iphone|ipod/i.test(window.navigator.userAgent)) {
                        field.css({
                            fontSize: 0
                        });
                    }
                    field.on("input", function(e) {
                        var length = e.target.value.length,
                            char = e.target.value.slice(-1);//监控input键盘输入值
                        if (password.length === length + 1) {
                            password.pop();
                            $(boxs[password.length]).removeClass('box-active');
                        } else if (password.length < 6) {
                            password.push(char);
                            password.forEach(function (box, i) {
                                $(boxs[i]).addClass('box-active');
                            });
                        }

                        field.val(password.join(''));
                        if (password.length == 6) {
                            data['use_account_money'] = use_account_money;
                            data['pay_password'] = field.val();
                            doAjax(data,1,sid);
                        }
                    });
                }else{
                    data['use_account_money'] = use_account_money;
                    doAjax(data,1,sid);
                }

            }else if (typeof WeixinJSBridge == "undefined") {
                if (document.addEventListener) {
                    document.addEventListener('WeixinJSBridgeReady', weixinpay, false);
                } else if (document.attachEvent) {
                    document.attachEvent('WeixinJSBridgeReady', weixinpay);
                    document.attachEvent('onWeixinJSBridgeReady', weixinpay);
                }
            } else {
                doAjax(data,3,sid);
            }
            return false;
        });

        function doAjax(data,type,sid){
            var url;
            if(sid>0){
                url = '/pay/excercise/index';
            }else{
                url = '/pay/index/index';
            }
            $(".paysub").text("请稍候...").css({"background-color":"#ccc"}).attr({"disabled": "disabled"}).removeAttr("id");
            //执行其他操作
            loading("正在下单");
            $.ajax({
                type: "POST",
                url: url,
                //        dataType:"json",
                async: true,
                data:data,
                headers:{
                    "VER":10,
                    "CITY":encodeURI(city)
                },

                success: function (result) {
                    var order_sn;
                    var group_buy_id;
                    if(result.response_params.status==1){
                        order_sn = result.response_params.order_sn;
                        if(type==3){
                            wei_ajax({"order_sn":order_sn},'/web/wappay/dopay')
                        }else{
                            order_sn = result.response_params.order_sn;
                            group_buy_id = result.response_params.group_buy_id;
                            if(total>0){
                                if(sid>0){
                                    window.location.href='/web/kidsplay/orderdetail?orderId='+order_sn;
                                }else{
                                    window.location.href='/web/wappay/orderdetail?orderId='+order_sn;
                                }
                            }else{
                                window.location.href='/web/wappay/guideattention';
                            }
//                            if(group_buy_id>0){
//                                window.location.href='/web/organizer/shops?id='+coupon_id+'&group_id='+group_id;
//                            }else{
//                                if(sid>0){
//                                    window.location.href='/web/kidsplay/orderdetail?orderId='+order_sn;
//                                }else{
//                                    window.location.href='/web/wappay/orderdetail?orderId='+order_sn;
//                                }
//                            }
                        }

                    }else if(result.response_params.status==2){
                        order_sn = result.response_params.order_sn;
                        group_buy_id = result.response_params.group_buy_id;
                        if(total>0){
                            if(sid>0){
                                window.location.href='/web/kidsplay/orderdetail?orderId='+order_sn;
                            }else{
                                window.location.href='/web/wappay/orderdetail?orderId='+order_sn;
                            }
                        }else{
                            window.location.href='/web/wappay/guideattention';
                        }
                    }else{
                        alert(result.response_params.message);
                        if(total>0){
                            $(".paysub").text("去支付").css({"background-color":"#fa6e51"}).removeAttr("disabled").attr("id","pay");
                        }else{
                            $(".paysub").text("去报名").css({"background-color":"#fa6e51"}).removeAttr("disabled").attr("id","pay");
                        }
                        window.location.reload()
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                    if (XMLHttpRequest.status == 401) {
                        //alert('授权失败');
                        // 跳转授权页面
                        //alert(XMLHttpRequest.responseJSON.message);
                        window.location.href = '<?php echo $authorUrl;?>';

                    }
                    else if (XMLHttpRequest.status == 403) {
                        window.location.href = '<?php echo $authorUrl;?>';
//                    alert('接口验证失败，非法访问');
                    }
                    else if (XMLHttpRequest.status == 400) {
                        alert('请求参数错误');
                    }
                    else {
                        alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                    }
                }

            });
        }

        function wei_ajax(data,url){
            $.ajax({
                type: "POST",
                url: url,
                dataType:"json",
                async: false,
                data:data,

                success: function (result) {
                    var payData = result.response_params.payData;
                    var orderData = result.response_params.orderData;
                    weixinpay(payData,orderData);
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                    if (XMLHttpRequest.status == 401) {
                        //alert('授权失败');
                        // 跳转授权页面
                        //alert(XMLHttpRequest.responseJSON.message);
                        window.location.href = '<?php echo $authorUrl;?>';

                    }
                    else if (XMLHttpRequest.status == 403) {
//                    alert('接口验证失败，非法访问');
                        window.location.href = '<?php echo $authorUrl;?>';
                    }
                    else if (XMLHttpRequest.status == 400) {
                        alert('请求参数错误');
                    }
                    else {
                        alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                    }
                }

            });
        }
        //
        function weixinpay(payData,orderData) {
            WeixinJSBridge.invoke(
                'getBrandWCPayRequest', {
                    "appId": ""+payData.appId+"",     //公众号名称，由商户传入
                    "timeStamp": ""+payData.timeStamp+"",         //时间戳，自1970年以来的秒数
                    "nonceStr": ""+payData.nonceStr+"", //随机串
                    "package": ""+payData.package+"",
                    "signType": ""+payData.signType+"",         //微信签名方式:
                    "paySign": ""+payData.paySign+"" //微信签名
                },
                function (res) {
                    if (res.err_msg == "get_brand_wcpay_request:ok") {
                        // 使用以上方式判断前端返回,微信团队郑重提示：res.err_msg将在用户支付成功后返回    ok，但并不保证它绝对可靠。
                        loadingSuccess('支付成功');
                        if(group_id){
//                            window.location.href='/web/organizer/shops?id='+orderData.coupon_id+'&group_id='+group_id;
                            window.location.href='/web/wappay/guideattention';
                        }else{
//                            window.location.href='/web/wappay/orderdetail?orderId='+orderData.order_sn;
                            window.location.href='/web/wappay/guideattention';
                        }
//                    window.location.href='/web/wappay/newallorders';  //个人中心
                        return false;

                    } else if (res.err_msg == "get_brand_wcpay_request:cancel") {
                        var ask = confirm('取消支付');
                        if(ask){
                            if(group_id){
                                $.ajax({
                                    type: "POST",
                                    url: "/pay/index/cleanorder",
                                    dataType:"json",
                                    async: true,
                                    data: {
                                        'order_sn':orderData.order_sn
                                    },
                                    headers: {
                                        "VER": 10
                                    },
                                    success: function (result) {
                                        if (result.response_params.status == 0) {
                                            alert(result.response_params.message);
                                            if(total>0){
                                                $(".paysub").text("去支付").css({"background-color":"#fa6e51"}).removeAttr("disabled").attr("id","pay");
                                            }else{
                                                $(".paysub").text("去报名").css({"background-color":"#fa6e51"}).removeAttr("disabled").attr("id","pay");
                                            }
                                        } else {
                                            window.location.href="/web/wappay/nindex"
                                        }
                                    },
                                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                                        //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                                        if (XMLHttpRequest.status == 401) {
                                            //todo 跳转授权页面
                                            alert(XMLHttpRequest.responseJSON.message);
                                            //                window.location.href = '<?php //echo $authorUrl;?>//';
                                        }
                                        else if (XMLHttpRequest.status == 403) {
                                            alert('接口验证失败，非法访问');
                                        }
                                        else if (XMLHttpRequest.status == 400) {
                                            //                            window.location.href = '<?php //echo $authorUrl;?>//';
                                            alert('请求参数错误:' + XMLHttpRequest.error_msg);
                                        }
                                        else {
                                            alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                                        }
                                    }
                                });
                            }else{
                                window.location.href="/web/wappay/orderwait";
                            }
                        }
                    } else if (res.err_msg == "get_brand_wcpay_request:fail") {
                        loadingErr('支付失败');
                        if(total>0){
                            $(".paysub").text("去支付").css({"background-color":"#fa6e51"}).removeAttr("disabled").attr("id","pay");
                        }else{
                            $(".paysub").text("去报名").css({"background-color":"#fa6e51"}).removeAttr("disabled").attr("id","pay");
                        }
                    } else {
                        loadingErr('其他错误:'+res.err_msg);
                        if(total>0){
                            $(".paysub").text("去支付").css({"background-color":"#fa6e51"}).removeAttr("disabled").attr("id","pay");
                        }else{
                            $(".paysub").text("去报名").css({"background-color":"#fa6e51"}).removeAttr("disabled").attr("id","pay");
                        }
                    }
                }
            );
        }
    }());
</script>
</html>