<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <title>玩翻天微信票券购买页</title>
    <link type="text/css" rel="stylesheet" href="/css/wap-pay-style.css"/>
</head>
<body>
<div id="ticket-buy" class="space10">
    <section class="ticket-info">
        <img src="<?php echo $couponData->coupon_cover; ?>">

        <div class="title"><?php echo $couponData->coupon_name; ?></div>
        <div>
            <span class="name">每机限购：</span>
            <span
                class="detail maxnum"><?php echo $couponData->coupon_limitnum > 0 ? $couponData->coupon_limitnum : '不限购'; ?></span>
        </div>
        <div>
            <span class="name">剩余：</span>
            <span class="detail surplus"><?php echo $couponData->coupon_total - $couponData->coupon_buy; ?></span>
        </div>
        <div>
            <span class="name">有效期至：</span>
            <span class="detail"><?php echo date('Y-m-d', $couponData->coupon_close) ?></span>
        </div>
        <div>
            <span class="name">单价：</span>
            <mark class="detail">￥<?php echo $couponData->coupon_price; ?></mark>
        </div>
    </section>
    <section class="ticket-number">
        <div class="title">
            <span>报名数：</span>

            <div class="data">
                <i id="prev" class="grey">-</i>
                <span>1</span>
                <i id="next">+</i>
            </div>
        </div>
        <div class="total">
            <span>总价</span>
            <mark>￥<span id="price"><?php echo $couponData->coupon_price; ?></span></mark>
        </div>
    </section>
    <button id="buy">确定</button>
</div>
<script src="/js/zepto1.1.6.min.js"></script>
<script>
    (function () {

        var num = 1;
        var surplus = $('.surplus').text();
        var limit = <?php echo $couponData->coupon_limitnum;?>;
        var price = $('#price').text();
        //todo 允许的购买数
        var max = 0;
        if (limit > 0) {
            max = (surplus > limit) ? limit : surplus;
        } else {
            max = surplus;
        }
        $("#prev").on('click', function () {
            $("#next").removeClass('grey');
            if (num > 1) {
                num--;
                $('#price').text((price * num).toFixed(2));
                if (num == 1) {
                    $("#prev").addClass('grey');
                }
            } else {
                $("#prev").addClass('grey');
            }
            $(".data span").text(num);
        });

        $("#next").on('click', function () {
            $("#prev").removeClass('grey');
            if (max > num) {
                num++;
                $('#price').text((price * num).toFixed(2));
                if (max == num) {
                    $("#next").addClass('grey');
                }
            } else {
                $("#next").addClass('grey');
            }
            $(".data span").text(num);
        });


        /************ 生成订单************/
        $('#buy').click(function () {

            alert('访问错误');
            //按钮变灰色禁用
            $(this).text('请稍候..').css({'background-color': '#ccc'}).attr({"disabled": "disabled"});

            $.ajax({
                type: "POST",
                url: "/pay/index/index",
                //        dataType:"json",
                async: true,
                data: {
                    'coupon_id': '<?php echo $couponData->coupon_id;?>',
                    'number': num,
                    'order_type': 1
                },
                headers: {
                    "VER": 8
                },
                success: function (result) {
                    if (result.response_params.status == 0) {
                        alert(result.response_params.message);
                    } else {
                        //todo 成功
                        window.location.href = '/web/wappay/ticketpay?showwxpaytitle=1&couponId=<?php echo $couponData->coupon_id;?>&orderId=' + result.response_params.order_sn;
                    }
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    //            alert("XHR=" + XMLHttpRequest + "\ntextStatus=" + textStatus + "\nerrorThrown=" + errorThrown);
                    if (XMLHttpRequest.status == 401) {
                        //todo 跳转授权页面
                        //alert(XMLHttpRequest.responseJSON.message);
                        window.location.href = '<?php echo $authorUrl;?>';
                    }
                    else if (XMLHttpRequest.status == 403) {
                        alert('接口验证失败，非法访问');
                    }
                    else if (XMLHttpRequest.status == 400) {
//                        window.location.href = '<?php //echo $authorUrl;?>//';
                        alert('请求参数错误');
                    }
                    else {
                        alert('网络异常,请刷新重试：' + XMLHttpRequest.status)
                    }


                }
            });

            return false;
        });

        /************ 生成订单 end ************/

    })();
</script>
</body>
</html>