<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <meta name="format-detection" content="telephone=no">
    <title>账户使用说明</title>
    <link href="/css/h5/style.css" rel="stylesheet"/>
</head>
<body>
<header class="tp-header">
    <h2>账户余额来源</h2>
    <p>1、退订余额：退订商品后，退款金额将自动退回至账户余额中</p>
    <p>2、商品返利：购买返利商品，返利将自动放入账户余额</p>
    <p>3、特殊福利：小编采纳的点评或攻略，给予用户的奖励将放入账户余额</p>
    <p>4、会员充值：用户也可自己充值到我的账户余额</p>
</header>
<section class="tp-main">
    <p>账户余额可用于购买任何商品，暂不支持余额与其他支付渠道合并付款</p>
    <p>
        提现规则：除商品返利、特殊福利和会员充值外，购买商品产生的退款退回至余额后，均可申请原路退回至支付账户
    </p>
</section>
<footer class="tp-footer">
    <p>此解释权归武汉玩翻天科技有限公司所有</p>
    <p>客服电话：4008007221 </p>
</footer>
</body>
</html>