<!DOCTYPE html>
<html lang="zh-cmn-Hans">
<head>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=Edge,chrome=1">
    <meta http-equiv=”Cache-Control” content=”no-siteapp” />
    <meta name="apple-mobile-web-app-capable" content="yes" >
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <script>(function () {
            var w = window.screen.width, s = w / 750, u = navigator.userAgent, m = '<meta name="viewport" content="width=750,';
            if (/android (\d+\.\d+)/i.test(u)) {
                if (parseFloat(RegExp.$1 > 2.3)) {
                    m += "minimum-scale = " + s + ", maximum-scale = " + s + ","
                }
            } else {
                m += "user-scalable=no,"
            }
            m += 'target-densitydpi=device-dpi">';
            document.write(m)
        }());</script>
    <title>推广赚钱规则</title>
    <style>
        body{
            padding: 0;
            margin: 0;
            background: #eee;
            max-width: 750px;
            font-family: 'microsoft yaHei';
        }

        .intro-list{
            margin-bottom: 60px;
            overflow: hidden;
        }

        .item-intro{
            width: 715px;
            margin: 60px auto 0;
            font-size: 24px;
        }

        .question{
            display: block;
            font-weight: bold;
            margin-bottom: 25px;
        }

        .answer{
            display: block;
            line-height: 35px;
        }
    </style>
</head>
    <section class="intro-list">
        <div class="item-intro">
            <span class="question">Q：销售员如何赚钱？</span>
            <span class="answer">A：在销售员中心，点击【我要推广赚钱】，进入推广商品列表。只要你在登录状态下分享列表中的商品或活动，7天内好友在登录状态下通过你的链接购买成功，你都可以获得相应的收益。</span>
        </div>
        <div class="item-intro">
            <span class="question">Q：销售员收益如何计算？</span>
            <p class="answer">A：在推广商品列表的每个商品或遛娃活动都有一定的收益比例，列表会标明出单份收益金额区间。购买不同套系可能获得的收益比例不一样。好友通过你分享的链接下单成功，小玩会根据每个套系的收益比例为你计算收益。</p>
        </div>
        <div class="item-intro">
            <p class="question">Q：销售员收益如何提现？</p>
            <p class="answer">A：当好友通过你分享的链接下单成功，你可以在销售员中心看到未到账收益；
                当好友成功使用了订单，你的收益会到账到你的收益账户；<br/>
                当好友退款了订单，则你不能获得对应的收益；<br/>
                为了方便手续费计算，收益账户余额大于20元时才可提现，且小于10元的零钱会放在收益账户，累计到一定金额之后再一起提现；</p>
        </div>
        <div class="item-intro">
            <p class="question">Q：为什么好友通过我的链接购买后，我没有获得收益？</p>
            <p class="answer">
                A：主要可能有以下原因：<br/>
                1.你在未登录状态下分享了链接，小玩识别不到你的账户信息<br/>
                2.你分享的不是在推广列表展示的商品，只有推广列表中的商品或遛娃活动才有推广收益<br/>
                3.好友点击你的链接之后并未在微信中登录玩翻天账号，又到app中购买了此商品<br/>
                4.好友在支付前又点击了其他人的分享链接<br/>
                5.自己点击了自己的链接购买，不计算收益<br/>
                6.系统判定该笔订单数据异常，收益取消<br/></p>
        </div>
    </section>
<body>
</body>