<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <meta name="format-detection" content="telephone=no">
    <title><?php echo $body->award;?></title>
    <link href="/css/h5/style.css" rel="stylesheet"/>
</head>
<body>
<section class="edit-con" style="width: 90%;margin: 20px auto 0">
    <?php echo $body->content;?>
</section>

</body>
</html>