<hgroup class="box">
    <header>
        <h3>订单</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/zyb">智游宝订单列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>注意!  </div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form" _lpchecked="1">
    <header class="box-title">搜索条件</header>
    <?php
     $zyb_status = 1;

     if (isset($_GET['zyb_status'])) {
         $zyb_status = $_GET['zyb_status'];
    }



    ?>
    <table class="table">
        <tbody>
        <tr>
            <th width="160">购买时间</th>
            <th>
                <input type="date" name="t1" value="">
                <input type="date" name="t2" value="">
            </th>
            <th width="160">用户id</th>
            <th>
                <input name="uid" type="text" class="cssInput" style="width:190px" value="">
            </th>
        </tr>

        <tr>
            <th width="160">用户名</th>
            <th>
                <input name="username" type="text" class="cssInput" style="width:190px" value="">
            </th>
            <th width="160">用户手机号</th>
            <th>
                <input name="phone" type="text" class="cssInput" style="width:190px" value="">
            </th>
        </tr>

        <tr>
            <th width="160">商品名称</th>
            <th>
                <input name="coupon_name" type="text" class="cssInput" style="width:190px" value="">
            </th>
            <th width="160">商品id</th>
            <th>
                <input name="good_id" type="text" class="cssInput" style="width:190px" value="">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/zyb/index" style="background-color: green"
                   class="ui-button">清空所有选项</a>
                <button class="ui-button">提交</button>
               <!-- <input type="submit" name="out" value="导出" class="ui-button">-->
            </th>
        </tr>
        </tbody>
    </table>
</form>

<div class="box">
    <div class="box-title">
        列表
    </div>
    <div>
        <table class="table">
            <tr>
                <th width="100">订单号</th>
                <th width="150">下单时间</th>
                <th width="150">商品名称</th>
                <th width="80">套系名称</th>
                <th width="80">用户名</th>
                <th width="170">UID</th>
                <th width="150">手机号</th>
                <th width="300">操作</th>
            </tr>
            <?php foreach ($data as $value): ?>
                <tr style="text-align: left">
                    <td width="100"><?php echo $value['order_sn'];?></td>
                    <td width="150"><?php echo date('Y-m-d H:i:s', $value['dateline']);?></td>
                    <td width="150"><?php echo $value['coupon_name'];?></td>
                    <td width="80"><?php echo $value['type_name'];?></td>
                    <td width="80"><?php echo $value['username'];?></td>
                    <td width="170"><?php echo $value['user_id'];?></td>
                    <td width="170"><?php echo $value['buy_phone'];?></td>
                    <td width="300">
                        <a href="/wftadlogin/zyb/info?order_sn=<?php echo $value['order_sn'];?>" class="ui-button">
                             <?php
                                 if($value['status'] == 1) {
                                     echo '预约';
                                 } else {
                                     echo '查看';
                                 }
                             ?>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
        <footer>
            <footer>
                <?php echo $this->pageData; ?>
            </footer>
        </footer>
    </div>
</div>