<hgroup class="box">
    <header>
        <h3>商品管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/game">返回商品列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系 </div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/good/save" id="game-save" method="post">
    <header class="box-title">
        <?php echo !$goodData ? '添加商品' : '';?>
        <?php if($goodData ):?>
            <a href="/wftadlogin/good/new?type=basis&gid=<?php echo $goodData->id?>">商品--基本信息</a>　　　
            <a href="/wftadlogin/good/new?type=info&gid=<?php echo $goodData->id?>">商品描述</a>　　　
            <?php if($goodData->is_together == 1):?>
                <?php if($goodData->need_use_time): ?>
            <a href="/wftadlogin/good/priceInfo?gid=<?php echo $goodData->id?>">商品——价格套系</a><?php endif?>　　　　
            <?php endif?>
            <a href="/wftadlogin/good/new?type=welfare&gid=<?php echo $goodData->id?>">商品--奖励与返利</a>　　　　
            <?php if(in_array($goodData->id, array(2010, 1987, 2091))):?>
                <a href="/wftadlogin/good/new?type=code&gid=<?php echo $goodData->id?>">商品--美团码发送情况</a>
            <?php endif?>
        <?php endif;?>

    </header>
    <table class="table">

        <?php if(!$goodData):?>
        <!--<tr>
            <th width="160">合同编号</th>
            <th colspan="3">
                <input type="text" class="cssInput" style="width:300px" value="" id="he-value"><br />
                <span  class="ui-button" id="he-tong">搜索</span>
            </th>
        </tr>

        <tr>
            <th width="160">商品名称</th>
            <th colspan="3" id="he-name">

            </th>
        </tr>-->

        <?php else:?>
            <tr>
                <th width="160">商品id</th>
                <th colspan="3">
                     <?php echo $goodData->id;?>
                    <input type="hidden" name="gid"  value="<?php echo $goodData->id;?>">
                </th>
            </tr>

            <tr>
                <th width="160">商品名称</th>
                <th colspan="3">
                    <input type="text" class="cssInput" name="title" value="<?php echo $goodData->title;?>">
                </th>
            </tr>

            <tr>
                <th width="160">分享标题</th>
                <th colspan="3">
                    <input type="text" class="cssInput" name="share_title" value="<?php echo $goodData->share_title;?>">
                </th>
            </tr>


        <?php endif;?>

        <!--
        <tr>
            <th width="160">份数限制</th>
            <th colspan="3" width="600">
                每机限购&nbsp;
                <input type="text" class="cssInput" name="limit_num" style="width: 60px" value="<?php echo $goodData ? $goodData->limit_num : 3; ?>">份　

                最低购买份数&nbsp;
                <input type="text" class="cssInput" name="limit_low_num" style="width: 60px" value="<?php echo $goodData ? $goodData->limit_low_num : 1; ?>">份　
            </th>
        </tr>
        -->

        <tr>
            <th width="160">限制</th>
            <th colspan="3" width="600">
                虚拟票&nbsp;
                <input type="text" class="cssInput" name="coupon_vir" style="width: 60px"
                       value="<?php echo ($goodData && $goodData->coupon_vir) ? $goodData->coupon_vir : ''; ?>">份

                平台&nbsp;
                <select name="buy_way">
                    <option <?php echo $goodData ? (($goodData->buy_way == 1) ? 'selected' : '') : ''; ?> value="1">微信 客户端</option>
                    <option <?php echo $goodData ? (($goodData->buy_way == 2) ? 'selected' : '') : ''; ?> value="2">客户端</option>
                    <option <?php echo $goodData ? (($goodData->buy_way == 3) ? 'selected' : '') : ''; ?> value="3">微信</option>
                </select>　　

        <tr>
            <th width="120px">上架时间：</th>
            <th colspan="3">
            <span>
                <input type="date" value="<?php echo $goodData ? date('Y-m-d', $goodData->start_time) : date('Y-m-d', time());?>" name="start_time">
                <input type="time" value="<?php echo $goodData ? date('H:i', $goodData->start_time) : '08:00';?>" name="start_timel">　
            </span>
                <span style="color:red">上架下架时间 限制是否在手机里面展示</span>
            </th>
        </tr>

        <tr>
            <th width="120px">下架时间：</th>
            <th colspan="3">
        <span>
            <input type="date" value="<?php echo $goodData ? date('Y-m-d', $goodData->end_time) : date('Y-m-d', strtotime('+10 year', time()));?>" name="end_time">
            <input type="time" value="<?php echo $goodData ? date('H:i', $goodData->end_time) : '23:59';?>" name="end_timel">
        </span>
            </th>
        </tr>


        <tr>
            <th width="160">咨询电话</th>
            <th colspan="3">
                <input type="text" class="cssInput" style="width:300px" name="phone" value="<?php echo $phone; ?>">
            </th>
        </tr>

        <tr>
            <th width="160">评论输入框内容</th>
            <th colspan="3">
                <input type="text" class="cssInput" style="width:300px" name="post_area_word" value="<?php echo $goodData ? $goodData->post_area_word : ''; ?>">
            </th>
        </tr>

        <tr>
            <th width="109">适合年龄</th>
            <th colspan="3" width="600">
                开始年龄：
                <select name="age_min">
                    <?php for ($i = 0; $i <= 2.5; $i = $i + 0.5): ?>
                        <option <?php echo ($goodData && $i == (string)$goodData->age_min) ? 'selected' : ''; ?>
                            value="<?php echo $i; ?>"><?php echo $i; ?>岁
                        </option>
                    <?php endfor; ?>
                    <?php for ($i = 3; $i <= 12; $i = $i + 1): ?>
                        <option <?php echo ($goodData && $i == (string)$goodData->age_min) ? 'selected' : ''; ?>
                            value="<?php echo $i; ?>"><?php echo $i; ?>岁
                        </option>
                    <?php endfor; ?>
                </select>
                结束年龄：
                <select name="age_max">
                    <option <?php echo (!$goodData || 100 == $goodData->age_max) ? 'selected' : ''; ?>
                        value="100">以上
                    </option>
                    <?php for ($i = 0.5; $i <= 2.5; $i = $i + 0.5): ?>
                        <option <?php echo ($goodData && $i ==  (string)$goodData->age_max) ? 'selected' : ''; ?>
                            value="<?php echo $i; ?>"><?php echo $i; ?>岁
                        </option>
                    <?php endfor; ?>
                    <?php for ($i = 3; $i <= 12; $i = $i + 1): ?>
                        <option <?php echo ($goodData && $i ==  (string)$goodData->age_max) ? 'selected' : ''; ?>
                            value="<?php echo $i; ?>"><?php echo $i; ?>岁
                        </option>
                    <?php endfor; ?>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">是否包场</th>
            <th width="300">

                <select name="is_private_party">
                    <option <?php echo $goodData ? (($goodData->is_private_party == 0) ? 'selected' : '') : ''; ?> value="0">不包场</option>
                    <option <?php echo $goodData ? (($goodData->is_private_party == 1) ? 'selected' : '') : ''; ?> value="1">包场</option>
                </select>　　　

                是否必填收货地址&nbsp;
                <select name="has_addr">
                    <option <?php echo $goodData ? (($goodData->has_addr == 0) ? 'selected' : '') : ''; ?> value="0">不必填</option>
                    <option <?php echo $goodData ? (($goodData->has_addr == 1) ? 'selected' : '') : ''; ?> value="1">必填</option>
                </select>　　

            </th>
        </tr>

        <?php if($goodData && $goodData->is_together == 1):?>
        <tr>
            <th width="160">备注项是否必填</th>
            <th width="300">
                <select name="is_comments_value">
                    <option <?php echo $goodData ? (($goodData->is_comments_value == 0) ? 'selected' : '') : ''; ?> value="0">不必填</option>
                    <option <?php echo $goodData ? (($goodData->is_comments_value == 1) ? 'selected' : '') : ''; ?> value="1">必填</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">备注输入框内容</th>
            <th colspan="3">
                <textarea name="comments_value" class="csstextarea"><?php echo $goodData ? $goodData->comments_value : '注明您对卖家的留言'; ?></textarea>
            </th>
        </tr>
        <?php endif;?>

        <tr>
            <th width="160">分类</th>
            <th width="300">
            <span id="tag_inner">
                <?php foreach ($labels as $z): ?>
                    <input <?php echo ($goodData && in_array(array('label_id' => $z->id),  $link_label)) ? 'checked' : ''; ?>
                    name="label[]" value=<?php echo $z->id; ?>  type="checkbox" /><?php echo $z->tag_name; ?>
                <?php endforeach; ?>
            </span>
            </th>
        </tr>

        <tr>
            <th width="160">标签(属性)</th>
            <th width="300">
                <span>
                <?php foreach ($tags as $z): ?>
                    <input <?php echo ($goodData && in_array(array('tag_id' => $z->id),  $link_tag)) ? 'checked' : ''; ?>
                    name="tag[]" value=<?php echo $z->id; ?>  type="checkbox" /><?php echo $z->tag_name; ?>
                <?php endforeach; ?>
                </span>
            </th>
        </tr>

        <!-- 支付方式限制 -->
        <tr>
            <th width="160">支付方式限制</th>
            <th width="300">
                <select name="payment_type">
                <?php
                    foreach ($config_payment_type as $key=>$val) {
                ?>
                    <option <?php echo $goodData ? (($goodData->payment_type == $val['id']) ? 'selected' : '') : ''; ?> value="<?php echo $val['id'];?>"><?php echo $val['payment_type_name'];?></option>
                <?php
                    }
                ?>
                </select>
            </th>
        </tr>

        <?php if($goodData && $goodData->need_use_time == 0):?>
        <tr>
            <th width="160">是否必选使用日期</th>
            <th width="300">
                <select name="need_use_time">
                    <option  value="0">请选择</option>
                    <option <?php echo $goodData ? (($goodData->need_use_time == 1) ? 'selected' : '') : ''; ?> value="1">否</option>
                    <option <?php echo $goodData ? (($goodData->need_use_time == 2) ? 'selected' : '') : ''; ?> value="2">是</option>
                </select>
            </th>
        </tr>
            <?php else: ?>
            <tr>
                <th width="160">是否必选使用日期</th>
                <th width="300">
                    <?php echo $goodData->need_use_time == 1?'否':'是'; ?>
                </th>
            </tr>
        <?php endif; ?>

        <!-- <tr>
            <th width="160">是否需要预约酒店</th>
            <th width="300">
                <select name="is_hotal">
                    <option <?php echo $goodData ? (($goodData->is_hotal == 0) ? 'selected' : '') : ''; ?> value="0">否</option>
                    <option <?php echo $goodData ? (($goodData->is_hotal == 1) ? 'selected' : '') : ''; ?> value="1">是</option>
                </select>
            </th>
        </tr> -->

        <!-- 短信模板类型 -->
        <tr>
            <th width="160">短信发送模板</th>
            <th width="300">
                <select name="message_type">
                <?php
                    foreach ($config_message_type as $key=>$val) {
                ?>
                    <option <?php echo $goodData ? (($goodData->message_type == $val['id']) ? 'selected' : '') : ''; ?> value="<?php echo $val['id'];?>"><?php echo $val['message_type_name'];?></option>
                <?php
                    }
                ?>
                </select>
            </th>
        </tr>

        <!-- 自定义短信 -->
        <tr>
            <th width="160">短信自定义内容</th>
            <th colspan="3">
                <textarea name="message_custom_content" class="csstextarea"><?php echo $goodData ? $goodData->message_custom_content : ''; ?></textarea>
            </th>
        </tr>

        <!-- 特权标签 -->
        <tr>
            <th width="160">特权标签</th>
            <th colspan="3">
                <div id="">
                    <?php
                    foreach($config_special_labels as $key=>$val): ?>
                        <input type="checkbox" class="labels" name="special_labels[]" value='<?php echo $val['id'] ?>' /><?php echo $val['tag_name'] ?>
                    <?php endforeach; ?>
                </div>
                <script>
                    $(function(){
                        setchecked('<?php echo $special_labels_str?:0;?>','.labels')
                    });

                    //多选（单选）按钮组设置默认值
                    function setchecked(data_string, classs) {
                        var v = data_string.split(',');
                        $(classs).each(function () {
                            category = $(this);
                            $.each(v, function (index, value) {
                                if (category.val() == value) {
                                    category.attr("checked", true);
                                }
                            });
                        })
                    }
                </script>
            </th>
        </tr>


        <!-- 提交框 -->
        <tr>
            <th></th>
            <th colspan="3">
                <input type="hidden" name="city"  value="<?php echo $goodData ? $goodData->city : $_COOKIE['city'];?>">
                <span type="submit" class="btn btn-primary" id="ti-game">提交</span>
            </th>
        </tr>
    </table>
</form>

<script>
    $(function () {

        //
        $('#he-tong').click(function () {
            var k = $('#he-value').val();
            $.post('/wftadlogin/good/getGoodName?k='+ k,
                function(result){
                    if (result.status == 0) {
                        alert(result.message);
                    } else {
                        $('#he-name').empty();
                        $('#he-name').append(result.message);
                    }
                }, 'json'
            );
        });

        //保存提交
        $('#ti-game').click(function () {
            $.post('/wftadlogin/good/save?type=basis', $('#game-save').serialize(), function (data) {
                if (data.status == 1) {
                    alert('保存成功');
                    window.location.href="/wftadlogin/good/new?gid="+ data.gid;
                } else {
                    alert(data.message);
                }
            }, 'json');
            return false;
        });
    })
</script>
