<hgroup class="box">
    <header>
        <h3>商品管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/game">返回商品列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>


<header class="box-title">
    <a href="/wftadlogin/good/new?type=basis&gid=<?php echo $goodData->id ?>">商品--基本信息</a>　　　
    　 <a href="/wftadlogin/good/new?type=info&gid=<?php echo $goodData->id ?>">商品描述</a>        　　
        <?php if($goodData->is_together == 1):?><?php if($goodData->need_use_time): ?><a href="/wftadlogin/good/priceInfo?gid=<?php echo $goodData->id?>">商品——价格套系</a><?php endif?><?php endif?>　　　　
    　　　　<a href="/wftadlogin/good/new?type=welfare&gid=<?php echo $goodData->id ?>">商品--奖励与返利</a>
</header>

<br/>

<!--<header class="box-title">验证商家</header>
<?php /*foreach($infoUsedData as $fod):*/ ?>
    <?php /*echo $fod->organizer_name. '  ';*/ ?>
<?php /*endforeach;*/ ?>
<br />-->

<br/>

<header class="box-title">合同规定限制</header>
<table class="table">
    <tr>
        <th>原价</th>
        <th>现价</th>
        <th>结算价</th>
       <!-- <th>数量</th>-->
        <th>操作</th>
    </tr>
    <?php foreach ($contractLinkData as $contractLink): ?>
        <tr>
            <td width="80">
                <?php echo $contractLink->money; ?>
            </td>
            <td width="80">
                <?php echo $contractLink->price; ?>
            </td>
            <td width="80">
                <?php echo $contractLink->account_money; ?>
            </td>
            <!--<td width="80">
                <?php /*echo $contractLink->total_num; */?>
            </td>-->
            <td width="80">
                <!--<a onclick="if(confirm('会让合同处于未审核状态?')==false)return false;" href="/wftadlogin/contract/deletePrice?id=<?php /*echo $contractLink->id;*/ ?>">删除</a>-->

                <a class="ui-button"
                   href="/wftadlogin/good/price?gid=<?php echo $goodData->id ?>&lid=<?php echo $contractLink->id; ?>">添加价格系列</a>

            </td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <th colspan="4"><?php echo $tip;?></th>
    </tr>


</table>

<br/>
<br/>

<header class="box-title">套系
    　　<?php echo !$goodData->contract_id ? '<a class="ui-button" href="/wftadlogin/good/price?gid=' . $goodData->id . '">添加</a>' : '' ?></header>
<table class="table">
    <tr>
        <th>系列名称</th>
        <th>原价</th>
        <th>现价</th>
        <th>结算价</th>
       <!-- <th>数量</th>-->
        <th>开始售卖时间</th>
        <th>结束售卖时间</th>
        <th>停止退款时间</th>
        <th>最多购买份数</th>
        <th>最少购买份数</th>
        <th>是否限购</th>
        <th>是否新用户专享</th>
        <th>特别说明</th>
        <th>兑换方式</th>
        <th>操作</th>
    </tr>
    <?php foreach ($priceData as $price): ?>
        <tr>
            <td width="80">
                <?php echo $price->name; ?>
            </td>
            <td width="80">
                <?php echo $price->money; ?>
            </td>
            <td width="80">
                <?php echo $price->price; ?>
            </td>
            <td width="80">
                <?php echo $price->account_money; ?>
            </td>
            <!--<td width="80">
                <?php /*echo $price->total_num; */?>
            </td>-->


            <td width="80">
                <?php echo date('Y-m-d',$price->up_time); ?>
            </td>
            <td width="80">
                <?php echo date('Y-m-d',$price->down_time); ?>
            </td>
            <td width="80">
                <?php echo date('Y-m-d',$price->refund_time); ?>
            </td>
            <td width="80">
                <?php echo $price->limit_num; ?>
            </td>
            <td width="80">
                <?php echo $price->limit_low_num; ?>
            </td>
            <td width="80">
                <?php echo $price->qualified==2?'是':'否'; ?>
            </td>
            <td width="80">
                <?php echo $price->for_new==1?'是':'否'; ?>
            </td>
            <td width="80">
                <?php echo mb_substr($price->remark,0,12,'utf-8').((mb_strlen($price->remark,'utf-8')>12)?"...":''); ?>
            </td>
            <td width="80">
                <?php echo mb_substr($price->order_method,0,12,'utf-8').((mb_strlen($price->order_method,'utf-8')>12)?"...":''); ?>
            </td>

            <td width="80">
                <a onclick="if(confirm('确定删除?')==false)return false;"
                   href="/wftadlogin/good/deletePrice?id=<?php echo $price->id; ?>">删除</a>
                <a class="ui-button" href="/wftadlogin/good/price?id=<?php echo $price->id ?>">修改</a>
            </td>
        </tr>
        <?php
        $money[$price->id] = $price->name;
        ?>
    <?php endforeach; ?>
</table>

<br/>
<br/>

<header class="box-title">时间地点关联 　　　<?php if(count($priceData)): ?>　　<span class="ui-button" id="add-place">添加</span><?php endif; ?></header>

<form method="post" action="/wftadlogin/good/saveGood" id="save-good-form">
    <table class="table">
        <tr>
            <th width="80">关联游玩地</th>
            <th width="80">开始使用时间</th>
            <th width="80">结束使用时间</th>
            <th width="80">支持的价格系列</th>
            <th width="40">接纳人数</th>
            <th width="40">报名人数</th>
            <th width="40">所需积分</th>
            <th width="40">每单保险人数</th>
            <th width="40">保险单价</th>
            <th width="40">保险天数</th>
            <th width="100">验证商家</th>
            <th width="80">智游宝商品码</th>
            <th width="80">操作</th>
        </tr>
        <?php foreach ($goodInfoData as $info): ?>
            <tr <?php if(!$info['status']): ?> style="color: #7f7f7f" <?php endif; ?> >
                <td width="80">
                    <?php echo $info['shop_name']; ?>
                </td>
                <td width="80">
                    <?php echo date('Y-m-d H:i:s', $info['start_time']); ?>
                </td>
                <td width="80">
                    <?php echo date('Y-m-d H:i:s', $info['end_time']); ?>
                </td>
                <td width="80">
                    <?php echo $info['price_name']; ?>
                </td>
                <td width="40">
                    <?php echo $info['total_num']; ?>
                </td>
                <td width="40">
                    <?php echo $info['buy']; ?>
                </td>
                <td width="40">
                    <?php echo $info['integral']; ?>
                </td>
                <td width="40">
                    <?php echo $info['insure_num_per_order']; ?>
                </td>
                <td width="40">
                    <?php echo $info['insure_price']; ?>
                </td>
                <td width="40">
                    <?php foreach ($baoyoulist as $v) {
                        if($v['RateCode']==$info['insure_days'])
                         echo "{$v['PlanName']}({$v['DayRange']}天)";
                    }; ?>
                </td>
                <td width="100">
                    <?php echo $info['organizer_name']; ?>
                </td>
                <td width="80">
                    <?php echo $info['goods_sm']; ?>
                </td>

                <td width="80">
                    <?php if($info['status']): ?>
                    <a href="/wftadlogin/good/good?id=<?php echo $info['id']; ?>">修改</a>
                        <a onclick= "if(confirm( '<?php echo $info['status'] ? '确定隐藏' : '确定取消隐藏'; ?> ')==false)return false; " href="/wftadlogin/good/deleteGoodInfo?id=<?php echo $info['id']; ?>">隐藏</a>
                        <?php else: ?>
                        已隐藏
                    <?php endif; ?>

                </td>
            </tr>
        <?php endforeach; ?>

        <tr style="display: none" id="tr-hidden">
            <td width="80" id="ad-place-view">
                <input type="text" value="" class="orTz">
                <div>
                </div>
            </td>
            <td width="80">
                <input type="date" value="<?php echo date('Y-m-d', time() + 184000); ?>" name="time_startl">
                <input type="time" value="<?php echo '08:00'; ?>" name="time_startr">　
            </td>
            <td width="80">
                <input type="date" value="<?php echo date('Y-m-d', time() + 5184000); ?>" name="time_endl">
                <input type="time" value="<?php echo '08:00'; ?>" name="time_endr">　
            </td>
            <td width="80">
                <select name="price">
                    <?php foreach ($money as $k => $v): ?>
                        <option value="<?php echo $k; ?>"><?php echo $v; ?></option>
                    <?php endforeach; ?>
                </select>
            </td>
            <td width="40">
                <input class="cssInput" style="width: 40px" type="text" name="total_num" value="">
            </td>
            <td width="40">
                <input class="cssInput" style="width: 40px" type="text" disabled value="0">
            </td>
            <td width="40">
                <input class="cssInput" style="width: 40px" type="text" name="integral" value="">
            </td>
            <td width="40">
                <input class="cssInput" style="width: 40px" type="text" name="insure_num_per_order" value="">
            </td>
            <td width="40">
                <input class="cssInput" style="width: 40px" type="text" name="insure_price" value="">
            </td>
            <td width="40">


                <select name="insure_days">
                    <?php foreach ($baoyoulist as $v): ?>
                        <option value="<?php echo $v['RateCode']; ?>"><?php echo "{$v['PlanName']}({$v['DayRange']}天)"; ?></option>
                    <?php endforeach; ?>

                </select>


            </td>

            <td width="100">
                <input type="radio" name="use_organizer_id"
                       value="<?php echo $marketData->id; ?>"><?php echo $marketData->name; ?><br/>
                <?php foreach ($branchData as $branch): ?>
                    <input type="radio" name="use_organizer_id"
                           value="<?php echo $branch->id; ?>"><?php echo $branch->name; ?><br/>
                <?php endforeach; ?>
            </td>

            <td width="80">
                <input class="cssInput" style="width: 100px" type="text" name="goods_sm" value="">
            </td>

            <td width="80">
                <input type="hidden" name="gid" value="<?php echo $goodData->id; ?>">
                <button type="submit" class="ui-button" id="save-good">保存</button>
            </td>
        </tr>
    </table>
</form>


<style>

    .xiala {
        width: 400px;
        position: relative;
        height: 24px;
        background-color: #4F463D;
        color: white;
    }
</style>
<script>
    $(function () {

        //保存提交
        $('#save-good').click(function () {
            $.post('/wftadlogin/good/saveGood', $('#save-good-form').serialize(), function (data) {
                if (data.status == 1) {
                    alert('保存成功');
                    window.location.href = "/wftadlogin/good/priceInfo?gid=" + data.gid;
                } else {
                    alert(data.message);
                }
            }, 'json');
            return false;
        });

        //显示添加商品
        $('#add-place').click(function () {
            $('#tr-hidden').css('display', '');
        });

        //搜索店铺的
        $('#ad-place-view').on('input propertychange', '.orTz', function () {
            var k = $(this).val();
            var that = $(this).next();
            that.empty();
            $.get('/wftadlogin/good/getShop?k=' + k,
                function (result) {
                    $.each(result.data, function (entryIndex, entry) {
                        var html = '<div class="xiala" data-name="' + entry['name'] + '" data-sid="' + entry['sid'] + '">';
                        html += entry['name'] + '</div>';
                        that.append(html);
                    })
                }, 'json'
            );
        });

        $('#ad-place-view').on('click', '.xiala', function () {
            var shop_name = $(this).attr('data-name');
            var shop_id = $(this).attr('data-sid');

            var tk = $(this).parent('div').parent('td');
            var html = '<input type="hidden" name="shop_id"  value="' + shop_id + '"><input type="hidden" name="shop_name"  value="' + shop_name + '">' + shop_name;
            $(this).parent('div').prev().remove();
            $(this).parent('div').remove();
            tk.append(html);
        });


    })
</script>

