<hgroup class="box">
    <header>
        <h3>商品管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/game">返回商品列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系 </div>
    </aside>
</hgroup>

<header class="box-title">
    <a href="/wftadlogin/good/new?type=basis&gid=<?php echo $goodData->id?>">商品--基本信息</a>
    <a href="/wftadlogin/good/new?type=info&gid=<?php echo $goodData->id?>">商品描述</a>        　　
    <?php if($goodData->is_together == 1):?>
        <?php if($goodData->need_use_time): ?>
        <a href="/wftadlogin/good/priceInfo?gid=<?php echo $goodData->id?>">商品——价格套系</a>
        <?php endif?>
    <?php endif?>　　　　
    <a href="/wftadlogin/good/new?type=welfare&gid=<?php echo $goodData->id?>">商品--奖励与返利</a>　　　　
    <a href="/wftadlogin/good/new?type=code&gid=<?php echo $goodData->id?>">商品--美团码发送情况</a>
</header>

<br />

<div class="box">
    <div class="box-title">
        美团码发送情况
    </div>
    <div>
        <table class="table" >
            <tbody>
            <tr>
                <th width="100" style="text-align: center;">订单号</th>
                <th width="100" style="text-align: center;">下单时间</th>
                <th width="100" style="text-align: center;">辅助码发送时间</th>
                <th width="100" style="text-align: center;">用户名</th>
                <th width="100" style="text-align: center;">用户手机号</th>
                <th width="100" style="text-align: center;">辅助码</th>
            </tr>
            <?php foreach ($data_code_list as $key => $row): ?>
                <tr style="text-align: center;">
                    <td width="100">
                        <a href="/wftadlogin/order/info?order_sn=<?php echo $row['order_sn'];?>"><?php echo $row['order_sn']; ?></a>
                    </td>
                    <td width="100"><?php echo $row['dateline'] ? date('Y-m-d H:i:s', $row['dateline']) : ''; ?></td>
                    <td width="100"><?php echo $row['use_datetime'] ? date('Y-m-d H:i:s', $row['use_datetime']) : ''; ?></td>
                    <td width="100"><?php echo $row['username']; ?></td>
                    <td width="100"><?php echo $row['phone']; ?></td>
                    <td width="100"><?php echo $row['code']; ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>



