<hgroup class="box">
    <header>
        <h3>包场活动</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/privateParty/index">包场活动</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

        $good_name = null;
        $good_id = null;
        $time_start = null;
        $time_end = null;
        $reply_start = null;
        $reply_end = null;
        $status_type = 0;

        if (isset($_GET['good_name']) && $_GET['good_name']) {
            $good_name = $_GET['good_name'];
        }

        if (isset($_GET['good_id']) && $_GET['good_id']) {
            $good_id = $_GET['good_id'];
        }

        if (isset($_GET['time_start']) && $_GET['time_start']) {
            $time_start = $_GET['time_start'];
        }

        if (isset($_GET['time_end']) && $_GET['time_end']) {
            $time_end = $_GET['time_end'];
        }

        if (isset($_GET['reply_start']) && $_GET['reply_start']) {
            $reply_start = $_GET['reply_start'];
        }

        if (isset($_GET['reply_end']) && $_GET['reply_end']) {
            $reply_end = $_GET['reply_end'];
        }

        if (isset($_GET['status_type']) && $_GET['status_type']) {
            $status_type = $_GET['status_type'];
        }

    ?>

    <table class="table">
        <tr>
            <th width="160">提交时间</th>
            <th>
                <input name="time_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $time_start;?>">
                <input name="time_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $time_end;?>">
            </th>
            <th width="160">回复时间</th>
            <th>
                <input name="reply_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $reply_start;?>">
                <input name="reply_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $reply_end;?>">
            </th>
        </tr>

        <tr>
            <th width="160">活动id</th>
            <th>
                <input type="text" class="cssInput" name="good_id" value="<?php echo $good_id;?>">
            </th>
            <th width="160">活动时间</th>
            <th>
                <input type="text" class="cssInput" name="good_name" value="<?php echo $good_name;?>">
            </th>
        </tr>

        <tr>
            <th width="160">状态</th>
            <th colspan="3">
                <select name="status_type">
                    <option value="0" <?php echo ($status_type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($status_type == 1) ? 'selected' : '';?>>未回复</option>
                    <option value="2" <?php echo ($status_type == 2) ? 'selected' : '';?>>已回复</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/privateParty/index" style="background-color: green" class="ui-button">清空</a>
                <button  class="ui-button">搜索</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/privateParty/outData" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>



<div class="panel panel panel-primary">
    <div class="panel-heading">包场活动列表</div>
    <div class="panel-body">

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">id</th>
                <th scope="col">提交时间</th>
                <th scope="col">回复时间</th>
                <th scope="col">商品id</th>
                <th scope="col">商品名称</th>
                <th scope="col">用户名</th>
                <th scope="col">电话号码</th>
                <th scope="col">状态</th>
                <th scope="col">操作</th>
            </tr>
            <?php foreach ($this->booking as $book): ?>
                <tr>
                    <td><?php echo $book['id']; ?></td>
                    <td><?php echo date('Y-m-d H:i:s', $book['dateline']); ?></td>
                    <td><?php echo $book['reply_dateline'] ? date('Y-m-d H:i:s', $book['reply_dateline']) : ''; ?></td>
                    <td><?php echo $book['coupon_id']; ?></td>
                    <td><?php echo $book['title']; ?></td>
                    <td><?php echo $book['name']; ?></td>
                    <td><?php echo $book['phone']; ?></td>
                    <td><?php echo $book['reply_dateline'] ? '已回复' : '未回复';?>
                    <td>
                        <?php if(!$book['reply_dateline']):?>
                            <a class="ui-button" href="/wftadlogin/privateParty/book?id=<?php echo $book['id']; ?>">标记为回复</a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>

        </table>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>

<script>
    $(function () {
        //导出
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });
    });
</script>


