<hgroup class="box">
    <header>
        <h3>商家管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/organizer">返回商家列表</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系 </div>
    </aside>
</hgroup>

<br />
<table class="table">
    <tr>
        <th width="160">商家id</th>
        <th colspan="3">
            <?php echo $organizerData->id;?>
        </th>
    </tr>

    <tr>
        <th width="160">商家名称</th>
        <th colspan="3">
            <?php echo $organizerData->name;?>
        </th>
    </tr>
</table>
<br />

<?php if($linkData->count()):?>
<br />
<header class="box-title"><?php echo $organizerData->name;?>__下的分店</header>
<table class="table">

    <tr>
        <th width="160">id</th>
        <th>分店名称</th>
        <th>操作</th>
    </tr>
    <?php foreach($linkData as $link):?>
        <tr>
            <td width="160"><?php echo $link->id;?></td>
            <td><?php echo $link->name;?></td>
            <td><a class="ui-button" href="/wftadlogin/organizer/deleteBranch?oid=<?php echo $link->id;?>">取消关联</a></td>
        </tr>
    <?php endforeach;?>
</table>
<br />
<?php endif;?>

<div class="box">
    <div class="box-title">
        <div style="float:right;margin-right:30px">
            <form action="#" method="get">
                <input type="text" class="cssInput"  style="margin-top: 5px;width:200px" placeholder="商家名称或商家id" name="k" value="">
                <input type="hidden" name="oid" value="<?php echo $organizerData->id;?>">
                <button class="btn btn-default" type="submit">搜索</button>
            </form>
        </div>
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">id</th>
                <th class="size3">商家名称</th>
                <th class="size1">关系</th>
                <th class="size1">操作</th>
            </tr>
                <?php foreach ($likeData as $row): ?>
                    <tr style="text-align: left">
                        <td class="size1"><?php echo $row['id']; ?></td>
                        <td class="size3"><?php echo $row['name']; ?></td>
                        <td class="size1">
                            <?php
                                if ($row['branch_id'] == $organizerData->id) {
                                    echo '已关联';
                                } else {
                                    echo '未关联';
                                }

                            ?>
                        </td>
                        <td class="size1">
                             <?php if(!$row['branch_id']):?>
                                <a class="ui-button" href="/wftadlogin/organizer/branchLink?oid=<?php echo $organizerData->id?>&lid=<?php echo $row['id'];?>">关联</a>
                             <?php endif;?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
