<hgroup class="box">
    <header>
        <h3>圈子管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/circle/main">返回圈子列表</a>
    </header>
</hgroup>
<form class="box box-form" action="/wftadlogin/circle/pass" method="post">
    <header class="box-title"><?php echo $data?'修改圈子':'添加圈子';?></header>
    <table class="table">
        <tr>
            <th width="160">圈子名称</th>
            <th colspan="3"><?php echo $data ? $data['title'] : ''; ?>
            </th>
        </tr>

        <tr>
            <th>封面图</th>
            <th colspan="3">
                <div>
                    <img width="240px" height="120px" class="fileupload1" src="<?php echo $data ? $data['img'] : '';?>">
                </div>
            </th>
        </tr>

        <tr>
            <th>缩略图 </th>
            <th colspan="3">
                <div>
                    <img width="120px" height="120px" class="fileupload2" src="<?php echo $data ? $data['thumb'] : '';?>">
                </div>
            </th>
        </tr>
        <tr>
            <th width="160">申请理由</th>
            <th colspan="3"><input disabled type="text" class="cssInput" name="reason" value="<?php echo $data ? $data['reason'] : ''; ?>">
            </th>
        </tr>

        <tr>
            <th width="160">是否显示</th>
            <th colspan="3" width="600">
                <input name="status" type="radio" value="1" <?php if($data && $data['status'] == 1): ?>checked<?php endif; ?>  /> 通过 &nbsp;&nbsp;&nbsp;
                <input name="status" type="radio" value="-1" <?php if($data && $data['status'] == -1): ?>checked<?php endif; ?> /> 拒绝
            </th>
        </tr>

        <tr>
            <th></th>
            <th colspan="3">
                <input type="hidden" name="id"  value="<?php echo $data ? $data['_id'] : '';?>">

                <button type="submit" class="btn btn-primary" id="ti-new">提交</button>
            </th>
        </tr>

    </table>
</form>

<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script src="/js/file_upload/jquery.iframe-transport.js"></script>
<script src="/js/file_upload/jquery.fileupload.js"></script>
<script>
    $('#fileupload1').fileupload({
        url: '/wftadlogin/index/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='img']").attr('value', data.result.url);
                $(".fileupload1").attr('src' , data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });

    $('#fileupload2').fileupload({
        url: '/wftadlogin/index/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='thumb']").attr('value', data.result.url);
                $(".fileupload2").attr('src' , data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });
</script>


