<hgroup class="box">
    <header>
        <h3>圈子管理</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/circle/new">添加圈子</a>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/circle/check">审核圈子</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<div class="box">
    <div class="box-title">
        圈子列表
        <div style="float:right;margin-right:30px">
            <form action="#" method="get">
              <input type="text" class="cssInput"  style="margin-top: 5px;width:200px" placeholder="搜索圈子名称" name="k" value="">
              <button class="btn btn-default" type="submit">搜索</button>
            </form>
        </div>
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size3">id</th>
                <th class="size3">圈子名称</th>
                <th class="size3">圈子简介</th>
                <th class="size1">
                    <select class="type_change">
                        <option <?php echo (!isset($_GET['type']) || !$_GET['type']) ? 'selected' : ''; ?> data-src="/wftadlogin/circle/main?type=0">全部</option>
                        <option <?php echo (isset($_GET['type']) && $_GET['type'] == 2) ? 'selected' : ''; ?> data-src="/wftadlogin/circle/main?type=2">公开</option>
                        <option <?php echo (isset($_GET['type']) && $_GET['type'] == 1) ? 'selected' : ''; ?> data-src="/wftadlogin/circle/main?type=1">私密</option>
                    </select>
                </th>
                <th class="size2">使用分站</th>
                <th class="size2">操作</th>
            </tr>
            <?php if ($data->count()): ?>
                <?php foreach ($data as $row): ?>
                    <tr style="text-align: left">
                        <td class="size3"><?php echo $row['_id']; ?></td>
                        <td class="size3"><a href="/wftadlogin/circle/new?id=<?php echo $row['_id']; ?>"><?php echo $row['title']; ?></a></td>
                        <td class="size3"><?php echo $row['introduce']; ?></td>
                        <td class="size1"><?php echo $type[$row['type']]; ?></td>
                        <td class="size1"><a href="/wftadlogin/circle/branch?id=<?php echo $row['_id']; ?>"><?php echo $row['branch_number']; ?></a></td>
                        <td class="size2">
                            <a href="/wftadlogin/circle/new?id=<?php echo $row['_id']; ?>" class="ui-button">基本设置</a>
                            <a href="/wftadlogin/circle/word?id=<?php echo $row['_id']; ?>" class="ui-button">话题管理</a>
                            <a href="/wftadlogin/circle/update?id=<?php echo $row['_id']; ?>&type=1" onclick="if(confirm('确定删除?')==false)return false;" class="ui-button">删除</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无圈子 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pagedata; ?>
        </footer>
    </div>
</div>
<script>
    $(function () {

        //类别筛选
        $('.type_change').change(function () {
            var href = $(this).find("option:selected").attr('data-src');
            window.location.href = href;
            return false;
        })
    })
</script>