<hgroup class="box">
    <header>
        <h3>圈子管理</h3>
    </header>
</hgroup>
<form class="box box-form" action="/wftadlogin/circle/savemap" method="post">
    <header class="box-title">推送焦点图</header>
    <table class="table">
        <tr>
            <th>焦点图</th>
            <th colspan="3">
                <fieldset>
                    <div style="float: left;height: 41px;background: #f5696c;width: 144px;position:relative;">
                        <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">上传</div>
                        <input type="file" id="fileupload1" name="file" style="width: 144px;height: 41px;cursor: pointer;font-size: 30px;outline: medium none;position: absolute;filter:alpha(opacity=0);-moz-opacity:0;opacity:0;left:0px;top: 0px;" multiple/>
                    </div>

                    <input type="hidden" name="img" value="" />
                    <span>　　样片封面图请上传：<mark>720*360px</mark>的“<mark><b>jpg png</b></mark>”格式 size小于<mark>250kb</mark>的图片。</span>
                </fieldset>
                <div>
                    <img width="240px" height="120px" class="fileupload1" src="">
                </div>
            </th>
        </tr>

        <tr>
            <th></th>
            <th colspan="3">
                <input type="hidden" name="id"  value="<?php echo $id;?>">
                <button type="submit" class="btn btn-primary" id="ti-new">提交</button>
            </th>
        </tr>

    </table>
</form>

<script src="/js/file_upload/jquery.ui.widget.js"></script>
<script src="/js/file_upload/jquery.iframe-transport.js"></script>
<script src="/js/file_upload/jquery.fileupload.js"></script>
<script>
    $('#fileupload1').fileupload({
        url: '/wftadlogin/index/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='img']").attr('value', data.result.url);
                $(".fileupload1").attr('src' , data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });
</script>


