<ul class="breadcrumb">
    <li>
        <a href="#">Home</a><span class="divider"></span>
    </li>
    <li>
        <span class="divider"><a href="/wftadlogin/seller/marketlist">商家管理</a></span>
    </li>
    <li class="active">
        <?php echo $data ? '店铺修改' : '新建店铺';?>
    </li>
</ul>

<form action="/wftadlogin/seller/saveshop" method="post" id="save_fs">
    <table class="table" style="width: 800px;">
        <tr>
            <th width="100">所属商家</th>
            <th width="100">
                 <?php echo $marketData->market_name;?>
            </th>
            <th width="100"></th>
            <th width="100"></th>
        </tr>

        <tr>
            <?php if(!$data):?>
            <th width="100">店铺名称</th>
            <th colspan="3">
                <input class="form-control" name="shop_name" type="text" value="">
            </th>
            <?php else:?>
            <th width="100">店铺名称</th>
            <th width="100">
                <input class="form-control" name="shop_name" type="text" value="<?php echo $data->shop_name;?>">
            </th>
            <th width="100">店铺编号: <?php echo $data->shop_acr.$marketData->market_id.$data->shop_id;?></th>
            <th width="100">
            </th>
            <?php endif;?>
        </tr>

        <tr>
            <th width="100">营业时间</th>
            <th width="200">
                <input type="time" value="<?php echo $data ? date('H:i', $data->shop_open) : '08:30';?>" name="shop_open" class="time-picker form-control">
            </th>
            <th width="100">
                <input type="time" value="<?php echo $data ? date('H:i', $data->shop_close) : '18:30';?>" name="shop_close" class="time-picker form-control">
            </th>
            <th></th>
        </tr>

        <tr>
            <th width="100">联系电话</th>
            <th width="200">
                <input class="form-control" name="shop_phone" type="text" value="<?php echo $data ? $data->shop_phone : '';?>">
            </th>
            <th colspan="2"></th>
        </tr>

        <tr>
            <th width="100">地  址 ：</th>
            <th width="200">
                <input class="form-control" name="shop_address" type="text" value="<?php echo $data ? $data->shop_address : '';?>">
            </th>
            <th colspan="2"></th>
        </tr>

        <tr>
            <th width="100">坐 标 ：</th>
            <th width="200">
                纬度坐标：<input type="text" class="form-control input-sm" name="addr_y" id="addr_y" value="<?php echo $data ? $data->addr_y : '';?>">
            </th>
            <th width="200">
                经度坐标：<input type="text" class="form-control input-sm" name="addr_x" id="addr_x" value="<?php echo $data ? $data->addr_x : '';?>">
            </th>
            <th><button type="button" class="btn btn-primary btn-sm setmap">设置坐标点</button></th>
        </tr>

        <tr>
            <th width="100">商圈 ：</th>
            <th width="200">
                <div class="dropdown">
                    <a id="dLabel" role="button" data-toggle="dropdown" class="btn btn-primary" data-target="#" href="#"><?php echo $data ? $sData[$data->busniess_circle] : '选择商圈';?><span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu multi-level" role="menu" aria-labelledby="dropdownMenu">
                        <?php foreach ($this->select_circle[1] as $k => $v): ?>
                            <?php if (!empty($v)): ?>
                                <li class="dropdown-submenu circle"><a tabindex="-1" href="#" val="<?php echo $this->select_circle[0][$k]['rid']; ?>"><?php echo $this->select_circle[0][$k]['name']; ?></a>
                                    <ul class="dropdown-menu circle">
                                        <?php for ($i = 1; $i <= count($v); $i++) { ?>
                                            <li><a class="lalala" href="#" val="<?php echo $v[$i]['rid']; ?>"><?php echo $v[$i]['name']; ?></a>
                                            </li>
                                        <?php } ?>
                                    </ul>
                                </li>
                            <?php else: ?>
                                <li class="circle"><a href="#" val="<?php echo $this->select_circle[0][$k]['rid']; ?>"><?php echo $this->select_circle[0][$k]['name']; ?></a>
                                </li>
                            <?php endif ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <input type="hidden" name="business" id="business" value="<?php echo $data ? $data->busniess_circle : 0;?>">
            </th>
            <th colspan="2">
                <input type="hidden" name="market_id" value="<?php echo $marketData->market_id;?>">
                <input type="hidden" name="shop_id" value="<?php echo $data ? $data->shop_id : 0;?>">
            </th>
        </tr>

        <tr>
                <th width="100"></th>
                <th colspan="3">
                    <input type="submit" value="保存" class="btn btn-primary" id="save_shop" data-loading-text="提交中..."/>
                </th>
        </tr>
    </table>
</form>

<!--   地图   -->
<div class="modal fade" id="setmap" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
     style="display: none">
    <div class="modal-dialog" style="width: 1000px;">
        <div class="modal-content" id="modal_addhouse">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h3>获取位置信息</h3>
            </div>
            <div class="modal-body">
                <h4>拖动跳动的点,使用滚轮快速放大缩小 <input type="text" value="搜索" id="skey"> <a class="btn btn-primary btn-sm"
                                                                                  id="mapsearch">搜索</a></h4>

                <iframe name="myFrame" src="/wftadlogin/seller/setmap"
                        style="width:100%; height:500px; border: 0px;border-radius: 5px;"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="ui-button" data-dismiss="modal" aria-hidden="true">关闭</button>
                <button class="ui-button getmap" data-dismiss="modal" aria-hidden="true">确定</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(function () {
        $('#save_shop').click(function () {
            $.post('/wftadlogin/seller/saveshop', $('#save_fs').serialize(), function (data) {
                if (data.status == 1) {
                    alert('保存成功');
                    location.href = document.referrer;
                } else {
                    alert(data.message);
                }
            }, 'json');
            return false;
        })

    });
</script>

<script>
    $(function () {

        $('.dropdown-menu a').click(function () {
            var sval = $(this).text();
            var bval = $(this).attr('val');
            $('#business').val(bval)
            $('#dLabel').text(sval)
            $('.dropdown').removeClass('open')
            return false;
        })

        ////////////////    地图      ///////////////////

        $('.setmap').click(function () {
            //地图框架地址
            posturl = $(this).attr("url");
            init_xy = [];
            init_xy[0] = $('#addr_x').val();
            init_xy[1] = $('#addr_y').val();
            if (init_xy[0] == 0 || init_xy[1] == 0) {
                init_xy[0] = 114.306655;  //湖北武汉
                init_xy[1] = 30.571659;
            }


            $("#setmap").modal()
            try {
                //初始化地图
                myFrame.window.initmap(init_xy[0], init_xy[1]);
            }
            catch (err) {
                setTimeout(function () {
                    myFrame.window.initmap(init_xy[0], init_xy[1]);
                }, 2000)
            }
        })
        $(".getmap").click(function () {
            var mapxy = myFrame.window.getmap().split(',');
            $('#addr_x').val(mapxy[0])
            $('#addr_y').val(mapxy[1])

        })

        $("#mapsearch").click(function () {
            var skey;
            skey = $("#skey").val();
            myFrame.window.baidusearch(skey);
        })
        ////////////////  地图结束 /////////////////
    });
</script>