<div class="panel panel panel-primary">
    <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
        <li><a href="/wftadlogin/comment">评论管理</a></li>　　　
        <li class="active"><?php echo array_key_exists('val',$msg['msg'][0])?$msg['msg'][0]['val']:0;?></li>　
    </ul>
</div>

<form class="box box-form" action="/wftadlogin/comment/doaward" method="post">
    <table class="table">

        <tr>
            <th width="160">奖励方式</th>
            <th colspan="3" width="600">
                <input name="type" type="radio" value="1" checked /> 现金券 &nbsp;&nbsp;&nbsp;
                <input name="type" type="radio" value="2" /> 返现金
            </th>
        </tr>

        <tr id="je">
            <th width="160">金额</th>
            <th colspan="3"><input type="text" class="cssInput" name="cash" value="<?php echo $data ? $data->diffuse_code : ''; ?>">
                目前可以使用的金额:<?php echo $remain; ?>
            </th>
        </tr>
        <tr id="je1">
            <th width="160">可否提现</th>
            <th colspan="3">
                <input name="withdrawal" type="radio" value="1" checked /> 可提现 &nbsp;&nbsp;&nbsp;
                <input name="withdrawal" type="radio" value="0" /> 不可提现
            </th>
        </tr>

        <tr id="pj">
            <th width="160">票券</th>
            <th>
                <select name="coupon" id="select">
                    <?php foreach($cc as $c): ?>
                        <option value="<?php echo $c['id'].'#'.$c['price'];?>" >[<?php echo $c['id'].']'. $c['title'];?></option>
                    <?php endforeach; ?>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <input type="hidden" name="mid"  value="<?php echo $msg_id;?>"> <!--//主贴id-->
                <input type="hidden" name="uid"  value="<?php echo $uid;?>"> <!--//主贴id-->
                <button type="submit" class="btn btn-primary">提交</button>
            </th>
        </tr>
    </table>
</form>
<script>
    $('#je').hide();
    $('#je1').hide();
    $('#pj').show();
    $("input[name='type']").change(function(){
        if('1' == $("input[name='type']:checked").val()){
            $('#je1').hide();
            $('#je').hide();
            $('#pj').show();
        }else if('2' == $("input[name='type']:checked").val()){
            $('#je1').show();
            $('#je').show();
            $('#pj').hide();
        }
    });
</script>