<div class="panel panel panel-primary">
    <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
        <li><a href="/wftadlogin/comment">圈子管理</a></li>
        <li><a href="/wftadlogin/comment?id=<?php echo $circle['_id'];?>"><?php echo $circle['title'];?></a></li>
        <li><a href="/wftadlogin/comment/word?id=<?php echo $circle['_id'];?>">发言管理</a></li>　　　　
        <li class="active"><?php echo $msg ? $msg['title'].'修改': '新的发言';?></li>　
    </ul>
</div>

<form class="box box-form" action="/wftadlogin/comment/saveWord" method="post">
    <table class="table">
        <tr>
            <th width="160">标题</th>
            <th colspan="3"><input type="text" class="cssInput" name="title" value="<?php  echo $msg ? $msg['title'] : '';?>"> <span style="color:red">可不写</span>
            </th>
        </tr>

        <tr>
            <th width="160">内容</th>
            <th colspan="3" width="600">
                <script type="text/plain" id="myEditorThumb" style="width:600px;height:240px;"><?php
                    if ($msg) {
                        foreach($msg['msg'] as $k) {
                            if ($k['t'] == 1) {
                                echo str_replace("\n", '<br />', $k['val']).'<br />';
                            }

                            if ($k['t'] == 2) {
                                echo '<img width="100px" height="100px" src="' . $k['val'] . '"><br />';
                            }
                        }
                    }
                    ;?></script>
            </th>
        </tr>

        <tr>
            <th width="160">区域</th>
            <th colspan="3">
                <input type="checkbox" />全选<br/>
                <?php foreach($city as $c): ?>
                    <input name="city[]" id="c_<?php echo $c['city']; ?>" value="<?php echo $c['city']; ?>" type="checkbox" /><?php echo $c['city_name']; ?>&nbsp;&nbsp;&nbsp;&nbsp;
                <?php endforeach; ?>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <input type="hidden" name="cid"  value="<?php echo $circle['_id'];?>">
                <input type="hidden" name="uid"  value="<?php  echo $msg ? $msg['uid'] : $userData->bind_user_id;?>">
                <input type="hidden" name="mid"  value="<?php  echo $msg ? $msg['_id'] : '';?>">
                <button type="submit" class="btn btn-primary">提交</button>
            </th>
        </tr>
    </table>
</form>

<script type="text/javascript">
    //实例化编辑器
    var um = UE.getEditor('myEditorThumb');

</script>



