<div class="panel panel panel-primary">
    <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
        <li><a href="/wftadlogin/comment">评论管理</a></li>　
        <li class="active"><?php echo $msg_post['title']?>__回复</li>　
    </ul>
</div>

<form class="box box-form" action="/wftadlogin/comment/updateReply?type=change&id=<?php echo $id;?>" method="post">
    <table class="table">

        <tr>
            <th width="160">内容</th>
            <th colspan="3" width="600">
                <textarea class="cssTextArea" name="info"><?php echo($msg_post['msg'][0]['val']) ; ?></textarea>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <input type="hidden" value="<?php echo $msg_post['mid']?>" name="mid" />
                <button type="submit" class="btn btn-primary">提交</button>
            </th>
        </tr>
    </table>
</form>
