<form action="/activity/pingxuanadmin/savebusiness" method="post">
    <table class="table">
        <tr>
            <th width="160">商家名称</th>
            <th colspan="3"><input type="text" class="cssInput" name="name"
                                   value="<?php echo $data ? $data->name : ''; ?>">
            </th>
        </tr>

        <tr>
            <th width="160">入围理由</th>
            <th colspan="3">
                <textarea name="reason"><?php echo $data ? $data->reason : ''; ?></textarea>
            </th>
        </tr>

        <tr>
            <th width="160">票数</th>
            <th colspan="3"><input type="text" class="cssInput" name="votes"
                                   value="<?php echo $data ? (int)$data->votes : '0'; ?>">
            </th>
        </tr>

        <tr>
            <th width="160">地址</th>
            <th colspan="3">
                <textarea name="address"><?php echo $data ? $data->address : ''; ?></textarea>

            </th>
        </tr>


        <tr>
            <th>商家封面</th>
            <th colspan="3">
                <fieldset>
                    <div style="float: left;height: 41px;background: #f5696c;width: 144px;position:relative;">
                        <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">上传</div>
                        <input type="file" id="fileupload1" name="file"
                               style="width: 144px;height: 41px;cursor: pointer;font-size: 30px;outline: medium none;position: absolute;filter:alpha(opacity=0);-moz-opacity:0;opacity:0;left:0px;top: 0px;"
                               multiple/>
                    </div>

                    <input type="hidden" name="img" value="<?php echo $data ? $data->img : ''; ?>"/>
                </fieldset>
                <div>
                    <img width="138px" height="138px" class="fileupload1"
                         src="<?php echo $data ? $data->img : ''; ?>">
                </div>
            </th>
        </tr>


        <tr>
            <th>商家照片2</th>
            <th colspan="3">
                <fieldset>
                    <div style="float: left;height: 41px;background: #f5696c;width: 144px;position:relative;">
                        <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">上传</div>
                        <input type="file" id="fileupload2" name="file"
                               style="width: 144px;height: 41px;cursor: pointer;font-size: 30px;outline: medium none;position: absolute;filter:alpha(opacity=0);-moz-opacity:0;opacity:0;left:0px;top: 0px;"
                               multiple/>
                    </div>

                    <input type="hidden" name="img2" value="<?php echo $data ? $data->img2 : ''; ?>"/>
                </fieldset>
                <div>
                    <img width="138px" height="138px" class="fileupload2"
                         src="<?php echo $data ? $data->img2 : ''; ?>">
                </div>
            </th>
        </tr>

        <tr>
            <th>商家照片3</th>
            <th colspan="3">
                <fieldset>
                    <div style="float: left;height: 41px;background: #f5696c;width: 144px;position:relative;">
                        <div style="text-align:center;line-height:41px;font-size:15px;font-weight:800">上传</div>
                        <input type="file" id="fileupload3" name="file"
                               style="width: 144px;height: 41px;cursor: pointer;font-size: 30px;outline: medium none;position: absolute;filter:alpha(opacity=0);-moz-opacity:0;opacity:0;left:0px;top: 0px;"
                               multiple/>
                    </div>

                    <input type="hidden" name="img3" value="<?php echo $data ? $data->img3 : ''; ?>"/>
                </fieldset>
                <div>
                    <img width="138px" height="138px" class="fileupload3"
                         src="<?php echo $data ? $data->img3 : ''; ?>">
                </div>
            </th>
        </tr>


        <tr>
            <th width="160">印象,添加格式为:
<pre>态度很好:11
态度不错:12</pre>
            </th>
            <th colspan="3">
                <textarea name="impression"><?php echo $data ? $data->impression : ''; ?></textarea>
            </th>
        </tr>


        <tr>
            <th width="160">商家类别
            </th>
            <th colspan="3">
                <select name="type" id="type1">
                    <option value="儿童乐园">儿童乐园</option>
                    <option value="儿童主题">儿童主题</option>
                    <option value="儿童游泳">儿童游泳</option>
                    <option value="周边景点">周边景点</option>
                </select>
            </th>
            <script>
                $(function () {
                    $("#type1").val('<?php echo $data ? $data->type : 0; ?>');
                })
            </script>
        </tr>


        <tr>
            <th width="160"></th>
            <th colspan="3" width="600">
                <input type="hidden" name="id" value="<?php echo $data ? $data->id : 0; ?>">
                <button id="ti-place" class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>

<script>

    $('#fileupload1').fileupload({
        url: '/activity/manage/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='img']").attr('value', data.result.url);
                $(".fileupload1").attr('src', data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });


    $('#fileupload2').fileupload({
        url: '/activity/manage/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='img2']").attr('value', data.result.url);
                $(".fileupload2").attr('src', data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });

    $('#fileupload3').fileupload({
        url: '/activity/manage/upload',
        dataType: 'json',
        done: function (e, data) {
            if (data.result.status == 1) {
                $("input[name='img3']").attr('value', data.result.url);
                $(".fileupload3").attr('src', data.result.url);
            } else {
                alert(data.result.response_params.message);
            }
        }
    });


</script>

