

<div class="box">
    <div class="box-title">
        奖品记录
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">id</th>
                <th width="50">奖品名称</th>
                <th width="50">领取状态</th>
                <th width="50">领取时间</th>
                <th width="50">操作</th>

            </tr>
            <?php foreach ($data as $key => $row): ?>
                <tr style="text-align: left">
                    <td width="50"><?php echo $row['id']; ?></td>
                    <td width="50">
                        <?php echo $row['name']; ?>
                    </td>

                    <td width="50">
                        <?php echo $row['prize_status'] ? '已领' : '未领'; ?>
                    </td>


                    <td width="50">
                        <?php echo date('Y-m-d H:i:s',$row['dateline']); ?>
                    </td>

                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->page; ?>
        </footer>
    </div>
</div>

