<hgroup class="box">
    <header>
        <h3>资格券管理</h3>
        <i class="icon icon-add"></i>
<!--        <a href="/wftadlogin/authmenu/new">添加菜单资源</a>-->
        &nbsp;&nbsp;&nbsp;
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：<span style="color:green">有问题 请及时联系</span></div>
    </aside>
</hgroup>
<form class="box box-form" action="/wftadlogin/qualify" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $begin_time = null;
    $end_time = null;
    $use_stime = null;
    $use_etime = null;
    $user = null;
    $good = null;
    $gettype = null;
    $use_status = null;
    $city = null;
    $month = NULL;


    if (isset($_GET['begin_time']) && $_GET['begin_time']) {
        $begin_time = $_GET['begin_time'];
    }

    if (isset($_GET['end_time']) && $_GET['end_time']) {
        $end_time = $_GET['end_time'];
    }

    if (isset($_GET['use_stime']) && $_GET['use_stime']) {
        $use_stime = $_GET['use_stime'];
    }

    if (isset($_GET['use_etime']) && $_GET['use_etime']) {
        $use_etime = $_GET['use_etime'];
    }

    if (isset($_GET['user']) && $_GET['user']) {
        $user = $_GET['user'];
    }

    if (isset($_GET['good']) && $_GET['good']) {
        $good = $_GET['good'];
    }

    if (isset($_GET['gettype']) && $_GET['gettype']) {
        $gettype = $_GET['gettype'];
    }

    if (isset($_GET['use_status']) && $_GET['use_status']) {
        $use_status = $_GET['use_status'];
    }

    if (isset($_GET['city']) && $_GET['city']) {
        $city = $_GET['city'];
    }

    if (isset($_GET['month']) && $_GET['month']) {
        $month = $_GET['month'];
    }


    ?>
    <table class="table">
        <tr>
            <th width="160">发放时间</th>
            <th>
                <input name="begin_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $begin_time;?>">
                <input name="end_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $end_time;?>">
            </th>
            <th width="160">使用时间</th>
            <th>
                <input name="use_stime" type="date" class="cssInput" style="width:190px"  value="<?php echo $use_stime;?>">
                <input name="use_etime" type="date" class="cssInput" style="width:190px"  value="<?php echo $use_etime;?>">
            </th>
        </tr>

        <tr>
            <th width="160">用户查找</th>
            <th>
                <input type="text" class="cssInput" name="user" value="<?php echo $user;?>">
            </th>
            <th width="160">使用商品</th>
            <th>
                <input type="text" class="cssInput" name="good" value="<?php echo $good;?>">
            </th>
        </tr>

        <tr>
            <th width="160">发放方式</th>
            <th>
                <select name="gettype" id="select">
                    <option value="0" <?php echo ($gettype == 0) ? 'selected' : '';?>>全部</option>
                    <?php foreach($qualify_type as $k => $q): ?>
                        <?php if($k==2) continue; ?>
                        <option value="<?php echo $k; ?>" <?php echo ($gettype == $k) ? 'selected' : '';?>><?php echo $q; ?></option>
                    <?php endforeach; ?>
                </select>
            </th>
            <th width="160">使用状态</th>
            <th>
                <select name="use_status" id="select">
                    <option value="0" <?php echo ($use_status == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($use_status == 1) ? 'selected' : '';?>>待使用</option>
                    <option value="2" <?php echo ($use_status == 2) ? 'selected' : '';?>>已回收</option>
                    <option value="3" <?php echo ($use_status == 3) ? 'selected' : '';?>>已使用</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">城市</th>
            <th>
                <?php echo $filtercity; ?>
            </th>
            <th width="160">时间区间</th>
            <th>
                <select name="month" id="select">
                    <option value="0" <?php echo ($month == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($month == 1) ? 'selected' : '';?>>一月内</option>
                    <option value="2" <?php echo ($month == 2) ? 'selected' : '';?>>三个月内</option>
                    <option value="3" <?php echo ($month == 3) ? 'selected' : '';?>>半年内</option>
                </select>
            </th>
        </tr>
        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/qualify" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/order/outaccount" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>
<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">编号</th>
                <th class="size2">发放方式</th>
                <th class="size1">发放时间</th>
                <th class="size2">用户ID</th>
                <th class="size1">用户名</th>
                <th class="size1">城市</th>
<!--                <th class="size1">积分汇率</th>-->
                <th class="size1">使用状态</th>
                <th class="size1">使用时间</th>
                <th class="size3">操作</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size2">
                                <?php echo $row['id']; ?>
                        </td>
                        <td class="size1"><?php echo $qualify_type[$row['give_type']]; ?></td>
                        <td class="size1"><?php echo date('Y-m-d',$row['create_time']); ?></td>
                        <td class="size1"><?php echo $row['uid']; ?></td>
                        <td class="size1"><?php echo $row['username']; ?></td>
                        <td class="size1"><?php echo $citys[$row['city']]; ?></td>
<!--                        <td class="size1">--><?php //echo $row['Integral_ratio']; ?><!--</td>-->
                        <td class="size1">
                            <?php if ((int)$row['pay_time'] === 0): ?>
                                待使用
                            <?php else: ?>
                                已使用
                            <?php endif; ?>
                        </td>
                        <td class="size1"><?php echo $row['pay_time']?date('Y-m-d',$row['pay_time']):'－'; ?></td>
                        <td class="size3">
                            <?php if ($row['status']){ ?>
                                <a href="/wftadlogin/qualify/recycle?id=<?php echo $row['id']; ?>&recycle=0" class="ui-button">回收</a>
                            <?php }else{ ?>
                                <a href="/wftadlogin/qualify/recycle?id=<?php echo $row['id']; ?>&recycle=1" class="ui-button">撤销回收</a>
                            <?php }; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无标签 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    $(function () {
    })
</script>