<hgroup class="box">
    <header>
        <h3>标签(属性)</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/tag/edit" id="new-tag">标签(属性)</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<div class="box">
    <div class="box-title">
        标签(属性)列表
    </div>
    <div>
        <?php $sort=$data[(count($data)-1)]['sort']; ?>
        <table class="table">
            <tbody>
            <tr>
                <th width="15">id</th>
                <th width="200">标签(属性)名称</th>
                <th width="300">操作</th>
            </tr>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td width="15">
                            <?php echo $row['id']; ?>
                        </td>

                        <td width="200">
                            <?php echo $row['tag_name']; ?>
                        </td>

                        <td width="300">
                            <a href="/wftadlogin/tag/update?type=del&id=<?php echo $row['id']; ?>" onclick="if(confirm('确定删除?')==false)return false;" class="ui-button">删除</a>
                            <a href="/wftadlogin/tag/sort?id=<?php echo $row['id']; ?>&sort=<?php echo $sort;?>&t=<?php echo $row['sort']?>" class="ui-button">上移</a>
                            <a href="/wftadlogin/tag/edit?id=<?php echo $row['id']; ?>" class="ui-button">修改</a>
                        </td>
                    </tr>

                    <?php $sort=$row['sort'];?>


                <?php endforeach; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


