<hgroup class="box">
    <header>
        <h3>咨询详情</h3>
        <i class="icon icon-list"></i>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>
            <?php echo $data['object_data']['object_title']. '的咨询'?>
        </div>
    </aside>
</hgroup>

<header class="box-title">咨询内容</header>
<table class="table">
    <tr>
        <th width="160">咨询时间：</th>
        <th colspan="3">
            <?php echo date('Y-m-d', $data['dateline']);?>
        </th>
    </tr>

    <tr>
        <th width="160">用户 名: </th>
        <th colspan="3">
            <?php echo  $data['username'];?>
        </th>
    </tr>

    <tr>
        <th width="160">用户 id: </th>
        <th colspan="3">
            <?php echo  $data['uid'];?>
        </th>
    </tr>

    <tr>
        <th width="160">咨询内容</th>
        <th colspan="3" width="600">
            <textarea class="cssTextArea"><?php echo  $data['msg'];?></textarea>
        </th>
    </tr>

</table>

<?php if(count($data['reply'])):?>
<header class="box-title">回复内容</header>
<table class="table">
    <tr>
        <th width="160">回复时间：</th>
        <th colspan="3">
            <?php echo date('Y-m-d', $data['reply']['dateline']);?>
        </th>
    </tr>

    <tr>
        <th width="160">编辑 名: </th>
        <th colspan="3">
            <?php echo  $data['reply']['username'];?>
        </th>
    </tr>

    <tr>
        <th width="160">编辑 uid: </th>
        <th colspan="3">
            <?php echo  $data['reply']['uid'];?>
        </th>
    </tr>

    <tr>
        <th width="160">回复内容</th>
        <th colspan="3" width="600">
            <textarea class="cssTextArea"><?php echo  $data['reply']['msg']; ?></textarea>
        </th>
    </tr>

</table>
<?php endif;?>

