<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>系统消息</title>
</head>
<style type="text/css">
    #winpop {
        width: 200px;
        height: 0px;
        position: fixed;
        right: 0;
        bottom: 0;
        border: 1px solid #999999;
        margin: 0;
        padding: 1px;
        overflow: hidden;
        display: none;
        background: #FFFFFF
    }

    #winpop .title {
        width: 100%;
        height: 20px;
        line-height: 20px;
        background: #FFCC00;
        font-weight: bold;
        text-align: center;
        font-size: 12px;
    }

    #winpop .con {
        width: 100%;
        height: 180px;
        line-height: 20px;
        font-weight: bold;
        font-size: 12px;
        color: #FF0000;
        text-decoration: underline;
        text-align: center
    }

    #silu {
        font-size: 13px;
        color: #999999;
        position: absolute;
        right: 0;
        text-align: right;
        text-decoration: underline;
        line-height: 22px;
    }

    .close {
        position: absolute;
        right: 4px;
        top: -1px;
        color: #FFFFFF;
        cursor: pointer
    }
</style>
<body>
<div id="winpop">
    <div class="title">您有新的消息<span class="close" onclick="tips_hide()">X</span></div>
    <div class="con">
        <?php if(array_key_exists('orderalert', $this->alert_windows)):?>
         <a href="/wftadlogin/code/index?message_type=2"> 未处理预约订单(<span id="count">0</span>) </a>
        <?php endif;?>
        <br />
        <?php if(array_key_exists('alertConsult', $this->alert_windows)):?>
        <a href="/wftadlogin/consult/index?type=2&hidden=2"> 未处理的咨询(<span id="count_consult">0</span>) </a>
        <?php endif;?>
    </div>
</div>
</body>
</html>
<script language=javascript>
    //??
    document.getElementById('winpop').style.height = '0px';

    $.ajaxSetup({
        async : false
    });

    clock();

    function clock()
    {
        var order_alert = getOrderAlert();
        var consult_alert = getConsultAlert();

        if (order_alert || consult_alert) {
            tips_pop();
        } else {
            tips_hide();
        }

        return false;
    }

    function getOrderAlert()
    {
        $.get("/wftadlogin/order/orderalert", function(result){
            $('#count').html(result.status);
            if(result.status > 0) {
                order_alert = true;
            } else {
                order_alert = false;
            }
        });

        return order_alert;
    }

    function getConsultAlert()
    {
        $.get("/wftadlogin/consult/alertConsult", function(result){
            $('#count_consult').html(result.status);
            if (result.status > 0) {
                consult_alert = true;
            }else{
                consult_alert = false;
            }
        });

        return consult_alert;
    }

    function tips_pop() {
        var MsgPop = document.getElementById("winpop");//获取窗口这个对象,即ID为winpop的对象
        var popH = parseInt(MsgPop.style.height);//用parseInt将对象的高度转化为数字,以方便下面比较
        if (popH == 0) {         //如果窗口的高度是0
            MsgPop.style.display = "block";//那么将隐藏的窗口显示出来
            show = setInterval("changeH('up')", 2);//开始以每0.002秒调用函数changeH("up"),即每0.002秒向上移动一次
        }
    }

    function tips_hide(){
        hide = setInterval("changeH('down')", 2);//开始以每0.002秒调用函数changeH("down"),即每0.002秒向下移动一次
    }

    function changeH(str) {
        var MsgPop = document.getElementById("winpop");
        var popH = parseInt(MsgPop.style.height);
        if (str == "up") {     //如果这个参数是UP
            if (popH < 100) {    //如果转化为数值的高度小于等于100
                MsgPop.style.height = (popH + 100).toString() + "px";//高度增加4个象素
            }
            else {
                clearInterval(show);//否则就取消这个函数调用,意思就是如果高度超过100象度了,就不再增长了
            }
        }
        if (str == "down") {
            if (popH >= 100) {       //如果这个参数是down
                MsgPop.style.height = (popH - 100).toString() + "px";//那么窗口的高度减少4个象素
            }
            else {        //否则
                clearInterval(hide);    //否则就取消这个函数调用,意思就是如果高度小于4个象度的时候,就不再减了
                MsgPop.style.display = "none";  //因为窗口有边框,所以还是可以看见1~2象素没缩进去,这时候就把DIV隐藏掉
            }
        }
    }

     var int=self.setInterval("clock()",30000);

</script>