<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="format-detection" content="telephone=no">
    <meta charset="utf-8">
    <link href="/css/h5/prize.css" rel="stylesheet"/>
    <title>天使宝宝大赛—中奖查询</title>
</head>
<body>
<header class="header">
    <img src="/images/prize-bg1.jpg"/>
</header>
<section class="wrapper">
    <form class="prize-result" action="javascript:void(0)">
        <fieldset class="info">
            <input class="phone" id="phone" type="text" name="phone" placeholder="请输入报名参赛的手机号码" autocomplte="off">
            <aside class="in-error" id="loginTip"></aside>
        </fieldset>
        <a class="submitBtn" id="submitBtn" type="submit" data-id="token">查询</a>
    </form>
</section>
</body>
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/prize.js"></script>
</html>