<hgroup class="box">
    <header>
        <h3>个人信息</h3>
        <i class="icon icon-add"></i>
        <!--        <a href="/wftadlogin/authmenu/new">添加菜单资源</a>-->
        &nbsp;&nbsp;&nbsp;
    </header>
    <div class="panel panel panel-primary">
        <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
            <li><a href="/wftadlogin/user/info?uid=<?php echo $userData->uid; ?>">基本信息</a></li>
            <li><a href="/wftadlogin/user/order?uid=<?php echo $userData->uid; ?>">订单</a></li>
            <li><a href="/wftadlogin/user/speak?uid=<?php echo $userData->uid; ?>">用户发言</a></li>
            <li><a href="/wftadlogin/user/integral?uid=<?php echo $userData->uid; ?>">积分</a></li>
            <li><a href="/wftadlogin/user/balance?uid=<?php echo $userData->uid; ?>">余额</a></li>
            <li><a href="/wftadlogin/user/cashCoupon?uid=<?php echo $userData->uid; ?>">现金券</a></li>
            <li><a href="/wftadlogin/user/qualify?uid=<?php echo $userData->uid; ?>">抢购资格</a></li>
            <li><a href="/wftadlogin/user/partner?uid=<?php echo $userData->uid; ?>">玩伴</a></li>
            <li><a href="/wftadlogin/user/favorite?uid=<?php echo $userData->uid; ?>">收藏</a></li>
            <li><a href="/wftadlogin/user/travel?uid=<?php echo $userData->uid; ?>">出行人</a></li>
            <li><a href="/wftadlogin/user/address?uid=<?php echo $userData->uid; ?>">地址</a></li>
        </ul>
    </div>
</hgroup>

<div class="box">
    <div class="box-title">
        地址列表
    </div>
    <div class="box-table">
        <table>
            <tr>
                <th class="size1">
                    姓名
                </th>
                <th class="size2">
                    联系方式
                </th>
                <th class="size1">
                    所在地区
                </th>
                <th class="size2">
                    详细地址
                </th>
            </tr>
            <?php foreach ($data as $row): ?>
                <tr>
                    <td class="size1"><?php echo $row['name']; ?></td>
                    <td class="size2"><?php echo $row['phone']; ?></td>
                    <td class="size1"><?php echo $row['province']. '　'. $row['city']. '　'. $row['region']; ?></td>
                    <td class="size1"><?php echo $row['address'] ; ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

