<hgroup class="box">
    <header>
        <h3>个人信息</h3>
        <i class="icon icon-add"></i>
        <!--        <a href="/wftadlogin/authmenu/new">添加菜单资源</a>-->
        &nbsp;&nbsp;&nbsp;
    </header>
    <div class="panel panel panel-primary">
        <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
            <li><a href="/wftadlogin/user/info?uid=<?php echo $userData->uid; ?>">基本信息</a></li>
            <li><a href="/wftadlogin/user/order?uid=<?php echo $userData->uid; ?>">订单</a></li>
            <li><a href="/wftadlogin/user/speak?uid=<?php echo $userData->uid; ?>">用户发言</a></li>
            <li><a href="/wftadlogin/user/integral?uid=<?php echo $userData->uid; ?>">积分</a></li>
            <li><a href="/wftadlogin/user/balance?uid=<?php echo $userData->uid; ?>">余额</a></li>
            <li><a href="/wftadlogin/user/cashCoupon?uid=<?php echo $userData->uid; ?>">现金券</a></li>
            <li><a href="/wftadlogin/user/qualify?uid=<?php echo $userData->uid; ?>">抢购资格</a></li>
            <li><a href="/wftadlogin/user/partner?uid=<?php echo $userData->uid; ?>">玩伴</a></li>
            <li><a href="/wftadlogin/user/favorite?uid=<?php echo $userData->uid; ?>">收藏</a></li>
            <li><a href="/wftadlogin/user/travel?uid=<?php echo $userData->uid; ?>">出行人</a></li>
            <li><a href="/wftadlogin/user/address?uid=<?php echo $userData->uid; ?>">地址</a></li>
        </ul>
    </div>
</hgroup>

<div class="box">
    <div class="box-title">
        现金券列表
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">
                    现金券编号
                </th>
                <th class="size2">
                    领券时间
                </th>
                <th class="size1">
                    领券原因
                </th>
                <th class="size2">
                    使用情况
                </th>
                <th class="size2">
                    使用时间
                </th>
                <th class="size2">
                    订单号
                </th>
                <th class="size2">
                    商品/活动名称
                </th>
                <th class="size2">
                    订单金额
                </th>
                <th class="size2">
                    支付金额
                </th>
                <th class="size2">
                    现金券金额
                </th>
                <th class="size2">
                    操作
                </th>
            </tr>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size2"><a href="/wftadlogin/cashcoupon/detail?cid=<?php echo $row['cid'];?>"><?php echo $row['cid']; ?></a></td>
                        <td class="size1"><?php echo date('Y-m-d',$row['create_time']); ?></td>
                        <td class="size1"><?php echo $row['get_info']; ?></td>
                        <td class="size1"><?php echo $row['pay_time'] ? '已使用' : ($row['use_etime'] > time() ? '待使用' : '已过期'); ?></td>
                        <td class="size1"><?php echo $row['pay_time'] ? date('Y-m-d',$row['pay_time']) : ''; ?></td>
                        <?php
                            if($row['order_type'] == 2) {
                                $order_url = '/wftadlogin/order/info?order_sn='. $row['use_order_id'];
                                $coupon_url = '/wftadlogin/good/new?gid='. $row['coupon_id'];
                            } elseif ($row['order_type'] == 3) {
                                $order_url = '/wftadlogin/excercise/orderinfo?order_sn='. $row['use_order_id'];
                                $coupon_url = '/wftadlogin/excercise/edite?id='. $row['coupon_id'];
                            }
                        ?>
                        <td class="size1">
                            <a href="<?php echo $order_url;?>">
                                <?php echo $row['use_order_id'] > 0 ? $row['use_order_id'] : '' ; ?>
                            </a>
                        </td>
                        <td class="size1"><a href="<?php echo $coupon_url;?>"><?php echo $row['coupon_name']; ?></a></td>
                        <td class="size1"><?php echo $row['real_pay'] + $row['voucher'] + $row['account_money']; ?></td>
                        <td class="size1"><?php echo $row['real_pay'] + $row['account_money']; ?></td>
                        <td class="size1"><?php echo $row['voucher']; ?></td>
                        <td class="size1">
                            <?php if(!$row['pay_time']):?>
                            <a onclick="if(confirm( '确定要删除吗，不可恢复')==false) return  false;" href="/wftadlogin/cashcoupon/delete?id=<?php echo $row['id']; ?>" class="ui-button">删除</a>
                            <?php endif;?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>