<hgroup class="box">
    <header>
        <h3><?php if($_GET['is_vir']): ?>虚拟<?php endif; ?>用户管理</h3>
        <i class="icon icon-list"></i>
        <?php if(!$_GET['is_vir']): ?>
        <a href="/wftadlogin/user">用户列表</a>
        <?php endif; ?>
        <a href="/wftadlogin/user">&nbsp;&nbsp;&nbsp;&nbsp;</a>
        <a  href="/wftadlogin/user/addVir">添加虚拟用户</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

        $username = null;
        $uid = null;
        $device_type = null;
        $sign_start = null;
        $sign_end = null;
        $phone = null;
        $login_type = null;
        $is_vir = 0;


        if (isset($_GET['username']) && $_GET['username']) {
            $username = $_GET['username'];
        }

        if (isset($_GET['uid']) && $_GET['uid']) {
            $uid = $_GET['uid'];
        }

        if (isset($_GET['device_type']) && $_GET['device_type']) {
            $device_type = $_GET['device_type'];
        }

        if (isset($_GET['sign_start']) && $_GET['sign_start']) {
            $sign_start = $_GET['sign_start'];
        }

        if (isset($_GET['sign_end']) && $_GET['sign_end']) {
            $sign_end = $_GET['sign_end'];
        }

        if (isset($_GET['login_type']) && $_GET['login_type']) {
            $login_type = $_GET['login_type'];
        }

        if (isset($_GET['phone']) && $_GET['phone']) {
            $phone = $_GET['phone'];
        }

        if (isset($_GET['invite_code']) && $_GET['invite_code']) {
            $invite_code = $_GET['invite_code'];
        }

        if (isset($_GET['is_vir']) && $_GET['is_vir']) {
            $is_vir = $_GET['is_vir'];
        }

        if (isset($_GET['is_vip']) && $_GET['is_vip']) {
            $is_vip = $_GET['is_vip'];
        }
    ?>

    <table class="table">
        <tr>
            <th width="160">用户名</th>
            <th>
                <input type="text" class="cssInput" name="username" value="<?php echo $username;?>">
            </th>
            <th width="160">用户注册时间</th>
            <th>
                <input name="sign_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $sign_start;?>">
                <input name="sign_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $sign_end;?>">
            </th>
        </tr>

        <tr>
            <th width="160">id</th>
            <th>
                <input type="text" class="cssInput" name="uid" value="<?php echo $uid;?>">
            </th>
            <th width="160">渠道</th>
            <th>
                <select name="device_type">
                    <option value="0" <?php echo ($device_type == 0) ? 'selected' : '';?>>全部</option>
                    <?php foreach($channel as $k => $v): ?>
                        <option value="<?php echo $k; ?>" <?php echo ($device_type == $k) ? 'selected' : '';?>><?php echo $v; ?></option>
                    <?php endforeach; ?>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">手机号</th>
            <th>
                <input type="text" class="cssInput" name="phone" value="<?php echo $phone;?>">
            </th>
            <th width="160">注册类型</th>
            <th>
                <select name="login_type">
                    <option value="0" <?php echo ($login_type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="qq" <?php echo ($login_type == 'qq') ? 'selected' : '';?>>qq</option>
                    <option value="weixin" <?php echo ($login_type == 'weixin') ? 'selected' : '';?>>微信</option>
                    <option value="weibo" <?php echo ($login_type == 'weibo') ? 'selected' : '';?>>微博</option>
                    <option value="deyi" <?php echo ($login_type == 'deyi') ? 'selected' : '';?>>得意</option>
                    <option value="phone" <?php echo ($login_type == 'phone') ? 'selected' : '';?>>手机本地</option>
                    <option value="weixin_wap" <?php echo ($login_type == 'weixin_wap') ? 'selected' : '';?>>微信平台</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">邀请码</th>
            <th colspan="1">
                <input type="text" class="cssInput" name="invite_code" value="<?php echo $invite_code;?>">
            </th>
            <th width="160">是否虚拟用户</th>
            <th>
                <select name="is_vir">
                    <option value="0" <?php echo (!$is_vir) ? 'selected' : '';?>>非虚拟用户</option>
                    <option value="1" <?php echo ($is_vir) ? 'selected' : '';?>>虚拟用户</option>
                </select>
            </th>
        </tr>
        <tr>
            <th width="160">会员等级</th>
            <th colspan="1">
                <select name="is_vip">
                    <option value="0" <?php echo (!$is_vip) ? 'selected' : '';?>>全部会员</option>
                    <option value="1" <?php echo ($is_vip == 1) ? 'selected' : '';?>>普通会员</option>
                    <option value="2" <?php echo ($is_vip == 2) ? 'selected' : '';?>>VIP会员</option>
                </select>
            </th>
            <th width="160"></th>
            <th>

            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/user" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/user/putdata?type=1" id="out-data" style="background-color: green" class="ui-button">导出用户信息</a>
            </th>
        </tr>
    </table>
</form>



<div class="panel panel panel-primary">
    <div class="panel-heading">用户列表</div>
    <div class="panel-body">
        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">用户ID</th>
                <th scope="col">城市</th>
                <th scope="col">用户名</th>
                <th scope="col">会员等级</th>
                <th scope="col">手机号</th>
                <th scope="col">是否在线</th>
                <th scope="col">注册类型</th>
                <th scope="col">状态</th>
                <th scope="col">注册时间</th>
                <th scope="col">是否虚拟用户</th>
                <th scope="col">渠道</th>
                <th scope="col">邀请人</th>
                <th scope="col">邀请码</th>
                <th scope="col">是否绑定微信SDK</th>
                <th scope="col">总积分</th>
                <th scope="col">操作</th>
            </tr>
            <?php foreach ($this->data as $v): ?>
                <tr>
                    <td><?php echo $v['uid']; ?></td>
                    <td><?php echo $v['city']; ?></td>
                    <td><?php echo $v['username']; ?></td>
                    <td><?php echo $v['member_level'] > 0 ? 'VIP会员' : '普通会员'; ?></td>
                    <td><?php echo $v['phone']; ?></td>
                    <td><?php echo $v['is_online']; ?></td>
                    <td><?php echo $v['login_type']; ?></td>
                    <td><?php echo $v['status'] == 1 ? '正常' : '禁用'; ?></td>
                    <td><?php echo $v['register_time']; ?></td>
                    <td><?php echo $is_vir ? '是' : '否'; ?></td>
                    <td><?php echo $v['device_type']; ?></td>
                    <td><?php echo $v['invite_people']; ?></td>
                    <td><?php echo $v['invite_code']; ?></td>
                    <td><?php echo $v['wei_uid']; ?></td>
                    <td><?php echo $v['integral']; ?></td>
                    <td>
                        <?php if($v['status'] == 1):?>
                            <a class="btn btn-warning" href="/wftadlogin/user/close?uid=<?php echo $v['uid']; ?>">禁用</a>
                        <?php else:?>
                            <a class="btn btn-info" href="/wftadlogin/user/open?uid=<?php echo $v['uid']; ?>">开启</a>
                        <?php endif;?>
                        <a class="ui-button" href="/wftadlogin/user/info?uid=<?php echo $v['uid']; ?>">查看</a>
                        <a class="btn btn-info" href="/wftadlogin/user/award?uid=<?php echo $v['uid']; ?>">奖励</a>
                        <?php if($v['is_vir'] == 1):?>
                            <a href="/wftadlogin/user/addVir?uid=<?php echo $v['uid']; ?>">修改</a>
                        <?php elseif($v['is_seller'] == 0):?>
                            <a class="ui-button" href="/wftadlogin/distribution/sellMan?uid=<?php echo $v['uid']; ?>&man_type=1">设为销售员</a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>

        </table>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>

<script>
    $(function () {
        //导出订单
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });
    });
</script>


