<hgroup class="box">
    <header>
        <h3>个人信息</h3>
        <i class="icon icon-add"></i>
        <!--        <a href="/wftadlogin/authmenu/new">添加菜单资源</a>-->
        &nbsp;&nbsp;&nbsp;
    </header>
    <div class="panel panel panel-primary">
        <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
            <li><a href="/wftadlogin/user/info?uid=<?php echo $userData->uid; ?>">基本信息</a></li>
            <li><a href="/wftadlogin/user/order?uid=<?php echo $userData->uid; ?>">订单</a></li>
            <li><a href="/wftadlogin/user/speak?uid=<?php echo $userData->uid; ?>">用户发言</a></li>
            <li><a href="/wftadlogin/user/integral?uid=<?php echo $userData->uid; ?>">积分</a></li>
            <li><a href="/wftadlogin/user/balance?uid=<?php echo $userData->uid; ?>">余额</a></li>
            <li><a href="/wftadlogin/user/cashCoupon?uid=<?php echo $userData->uid; ?>">现金券</a></li>
            <li><a href="/wftadlogin/user/qualify?uid=<?php echo $userData->uid; ?>">抢购资格</a></li>
            <li><a href="/wftadlogin/user/partner?uid=<?php echo $userData->uid; ?>">玩伴</a></li>
            <li><a href="/wftadlogin/user/favorite?uid=<?php echo $userData->uid; ?>">收藏</a></li>
            <li><a href="/wftadlogin/user/travel?uid=<?php echo $userData->uid; ?>">出行人</a></li>
            <li><a href="/wftadlogin/user/address?uid=<?php echo $userData->uid; ?>">地址</a></li>
        </ul>
    </div>
</hgroup>

<div class="box">
    <div class="box-title">
        用户资格券
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">
                    编号
                </th>
                <th class="size1">
                    发放方式
                </th>
                <th class="size1">
                    发放时间
                </th>
                <th class="size1">
                    积分汇率
                </th>
                <th class="size1">
                    使用状态
                </th>
                <th class="size1">
                    使用时间
                </th>
                <th class="size1">
                    订单号
                </th>

                <th class="size1">
                    相关商品
                </th>

            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size1"><?php echo $row['id']; ?></td>
                        <td class="size1">
                            <?php $way = array('1' => '用户兑换', '2' => '邀约', '3' => '参加活动', '4' => '注册');?>
                            <?php echo in_array($row['give_type'], array(1, 2, 3, 4)) ? $way[$row['give_type']] : ''; ?>
                        </td>
                        <td class="size1"><?php echo date('Y-m-d',$row['create_time']); ?></td>
                        <td class="size1"><?php echo $row['integral_ratio']; ?></td>
                        <td class="size1">
                            <?php echo ($row['pay_time'] > 0) ? '已使用' : (($row['valid_time'] > time()) ? '待使用' : '已过期'); ?>
                        </td>
                        <td class="size1"><?php echo ($row['pay_time'] > 0) ? date('Y-d-m',$row['pay_time']) : ''; ?></td>
                        <td class="size1">
                            <?php if($row['pay_time'] > 0):?>
                            <a href="/wftadlogin/order/info?order_sn=<?php echo $row['use_order_id'];?>"><?php echo $row['use_order_id']; ?></a>
                            <?php endif;?>
                        </td>
                        <td class="size1">
                            <?php if($row['pay_time'] > 0):?>
                            <a href="/wftadlogin/good/new?gid=<?php echo $row['pay_object_id'];?>"><?php echo $row['pay_object_name']; ?></a>
                            <?php endif;?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无数据</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>


<script>
    $(function () {
    })
</script>