<hgroup class="box">
    <header>
        <h3>个人信息</h3>
        <i class="icon icon-add"></i>
        <!--        <a href="/wftadlogin/authmenu/new">添加菜单资源</a>-->
        &nbsp;&nbsp;&nbsp;
    </header>
    <div class="panel panel panel-primary">
        <ul class="breadcrumb" style="margin-top:10px;margin-bottom: 10px;background-color: #FFF">
            <li><a href="/wftadlogin/user/info?uid=<?php echo $userData->uid; ?>">基本信息</a></li>
            <li><a href="/wftadlogin/user/order?uid=<?php echo $userData->uid; ?>">订单</a></li>
            <li><a href="/wftadlogin/user/speak?uid=<?php echo $userData->uid; ?>">用户发言</a></li>
            <li><a href="/wftadlogin/user/integral?uid=<?php echo $userData->uid; ?>">积分</a></li>
            <li><a href="/wftadlogin/user/balance?uid=<?php echo $userData->uid; ?>">余额</a></li>
            <li><a href="/wftadlogin/user/cashCoupon?uid=<?php echo $userData->uid; ?>">现金券</a></li>
            <li><a href="/wftadlogin/user/qualify?uid=<?php echo $userData->uid; ?>">抢购资格</a></li>
            <li><a href="/wftadlogin/user/partner?uid=<?php echo $userData->uid; ?>">玩伴</a></li>
            <li><a href="/wftadlogin/user/favorite?uid=<?php echo $userData->uid; ?>">收藏</a></li>
            <li><a href="/wftadlogin/user/travel?uid=<?php echo $userData->uid; ?>">出行人</a></li>
            <li><a href="/wftadlogin/user/address?uid=<?php echo $userData->uid; ?>">地址</a></li>
        </ul>
    </div>
</hgroup>

<div class="box">
    <div class="box-title">
        发言列表
    </div>
    <div class="box-table">
        <table>
            <tr>
                <th class="size1">
                    id
                </th>
                <th class="size2">
                    发言时间
                </th>
                <th class="size2">
                    评论对象
                </th>
                <th class="size2">
                    内容
                </th>
                <th class="size1">
                    回复数
                </th>
                <th class="size1">
                    点赞数
                </th>
               <!-- <th class="size1">
                    是否小编采纳
                </th>-->
                <th class="size1">
                    积分
                </th>
                <th class="size1">
                    现金券
                </th>
                <th class="size1">
                    返利
                </th>
            </tr>
            <?php foreach ($data as $row): ?>
                <tr>
                    <td class="size1"><?php echo $row['_id']; ?></td>
                    <td class="size2"><?php echo date('Y-m-d H:i:s', $row['dateline']); ?></td>
                    <td class="size2">
                        <?php
                        if($row['msg_type']==2){
                            $path = 'good/new';
                            $parameter = 'gid';
                            $title = '商品';
                        }elseif($row['msg_type']==3){
                            $path = 'place/new';
                            $parameter = 'sid';
                            $title = '游玩地';
                        }elseif($row['msg_type']==7){
                            $path = 'excercise/edite';
                            $parameter = 'id';
                            $title = '活动';
                        }
                        ?>
                        <a href="/wftadlogin/<?php echo $path;?>?<?php echo $parameter;?>=<?php echo $row['object_data']['object_id']; ?>">
                            <?php echo $row['object_data']['object_title']; ?>
                        </a>
                    </td>
                    <td class="size2">
                        <a href="/wftadlogin/comment/wordinfo?id=<?php echo $row['_id'];?>">
                            <?php
                                $st = '';
                                foreach($row['msg'] as $v) {
                                    if ((int)$v['t'] === 1 && $v['val']) {
                                        echo $st = substr($v['val'], 0, 60);
                                        break;
                                    }
                                }
                                if (!$st) {
                                    echo '内容无';
                                };
                            ?>
                        </a>
                    </td>
                    <td class="size1"><?php echo $row['replay_number']; ?></td>
                    <td class="size1"><?php echo $row['like_number']; ?></td>
                    <td class="size1">
                        <?php echo $row['integral']; ?>
                    </td>
                    <td class="size1">
                        <?php echo $row['cash_money']; ?>
                    </td>
                    <td class="size1">
                        <?php echo $row['rebate_money']; ?>
                    </th>
                </tr>
            <?php endforeach; ?>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>
