<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>玩翻天--商家版</title>
    <link href="/seller/css/layout.css" rel="stylesheet" />
    <link href="/seller/css/components.css" rel="stylesheet" />
    <script src="/seller/js/modernizr.js"></script>
</head>
<body>
<header id="header">
    <div class="center">
        <div id="header-tips">
            <a id="header-logo" target="_blank" href=""><img src="/seller/images/logo.gif" alt=""></a>
            <h2 id="header-title">商家版</h2>
        </div>
        <div id="header-member">
            <figure>
                <a href="" title="" class="portrait">
                    <img alt="" src="/seller/images/demo01.png">
                </a>
                <figcaption>
                    <a class="username" title="世界儿童乐园" href="">世界儿童乐园</a>
                </figcaption>
            </figure>
            <nav id="header-nav">
                <a class="set" href=""></a>
                <a class="exit" href=""></a>
            </nav>
        </div>
    </div>
</header>

<div id="container" class="center">
    <nav id="navigator">
        <ul>
            <li>
                <a class="user-self" href="/" title="">
                    <i></i>首页
                </a>
            </li>
            <li>
                <a class="user-order" href="/order.html" >
                    <i></i>订单
                </a>
            </li>
            <li>
                <a class="user-shops" href="/shops.html" >
                    <i></i>分店管理
                </a>
            </li>
            <li>
                <a class="user-info" href="/article.html" >
                    <i></i>基本信息
                </a>
            </li>
            <li>
                <a class="user-account  active" href="/account.html" >
                    <i></i>绑定银行账号
                </a>
            </li>
        </ul>
    </nav>
    <main id="content">
        <header id="top-nav">
            <nav id="top-nav-crumb">
                <a href="/">首页</a>
                <span>&gt;</span>
                <span>编辑基本信息</span>
            </nav>
        </header>
        <section class="wrapper">
            <form class="general-form gf-account" action="" method="post" h-com="form time select" id="form1">
                <fieldset>
                    <label class="gf-title">开卡人：</label>
                    <input class="text" type="text" name="bang_user" value="" placeholder="" tabindex="1" id="bang_user">
                </fieldset>

                <fieldset>
                    <label class="gf-title">开户行：</label>
                    <input class="text" type="text" name="bank_name" value="" placeholder="" tabindex="1" id="bank_name">
                </fieldset>

                <fieldset>
                    <label class="gf-title">开户支行：</label>
                    <input class="text" type="text" name="bank_address" value="" placeholder="" tabindex="1" id="bank_address">
                </fieldset>

                <fieldset>
                    <label class="gf-title">卡号：</label>
                    <input class="text" type="text" name="bank_card" value="" placeholder="" tabindex="1" id="bank_card">
                </fieldset>

                <fieldset>
                    <label class="gf-title">请再次输入卡号：</label>
                    <input class="text" type="text" name="re_bank_card" value="" placeholder="" tabindex="1" id="re_bank_card">
                </fieldset>

                <fieldset class="gf-submit"  id="gf-submit">
                    <input class="submit button" type="button" value="保存修改" id="subBtn">
                </fieldset>

                <fieldset class="tips">
                    已经提交了开户信息，如果需要修改，请与客服联系
                </fieldset>
            </form>
        </section>
    </main>
</div>
<footer id="footer"></footer>
</body>
<template id="alert">
    <div class="modal-alert">
        <h1 class="modal-alert-title">{{message}}</h1>
        <input class="button modal-alert-button modal-close" type="button" value="确定" />
    </div>
</template>
<script src="/seller/js/jquery.js"></script>
<script src="/seller/js/lodash.js"></script>
<script src="/seller/js/horcrux.js"></script>
<script src="/seller/js/components.js" charset="utf-8"></script>
<script>
    $(function(){
        $("#subBtn").click(function(){
            var bang_user = $("#bang_user").val();
            var bank_name = $("#bank_name").val();
            var bank_address = $("#bank_address").val();
            var bank_card = $("#bank_card").val();
            var re_bank_card = $("#re_bank_card").val();
            if(!bang_user){
                alert('请输入开卡人');
                return false;
            }
            if(!bank_name){
                alert('请输入开户行');
                return false;
            }
            if(!bank_address){
                alert('请输入开户支行');
                return false;
            }
            if(!bank_card){
                alert('请输入卡号');
                return false;
            }
            if(!re_bank_card){
                alert('请输入确认卡号');
                return false;
            }
            if(re_bank_card != bank_card){
                alert('两次卡号不相同');
            }
            $("#form1").attr('action','/selleradmin/index/account').submit();
        })
    })
</script>
</html>

