<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>玩翻天--商家版</title>
    <link href="/seller/css/layout.css" rel="stylesheet" />
    <link href="/seller/css/components.css" rel="stylesheet" />
    <script src="/seller/js/modernizr.js"></script>
</head>
<body>
<header id="header">
    <div class="center">
        <div id="header-tips">
            <a id="header-logo" target="_blank" href="#"><img src="/seller/images/logo.gif" alt=""></a>
            <h2 id="header-title">商家版</h2>
        </div>
    </div>
</header>
<main id="con-bg">
    <div class="center login-con">
        <section class="login-main">
            <h1>玩翻天APP</h1>
            <h2>超过<mark>1000</mark>家商户认可和信赖的新媒体平台</h2>
            <ul>
                <li>景点、商场、游乐园等娱乐休闲业态</li>
                <li>-剧院、少年宫等文化体育场馆</li>
                <li>-科技馆、博物馆等科普教育基地</li>
                <li>-烘焙、陶艺、DIY等趣味体验形式……</li>
                <li>只要符合0—12岁儿童玩乐需求，你就是玩翻天的精准合作商户！</li>
            </ul>
            <a class="login-add button" href="join.html" title="" target="_blank">我也要入驻</a>
        </section>
        <form class="login-form" action="/" method="post" h-com="select checkbox form">
<!--            <fieldset>-->
<!--                <div class="ui-select gf-select" id="select-box">-->
<!--                    <input type="hidden" name="typeid" value="0">-->
<!--                    <div class="ui-select-title" tabindex="1" id="select">商家</div>-->
<!--                    <ul class="ui-select-options ui-scroll ui-scroll-y ui-scroll-hidden" style="position: relative;" id="select-ul">-->
<!--                        <li data-value="1">商家</li>-->
<!--<!--                        <li data-value="2">游玩地</li>-->
<!--                    </ul>-->
<!--                </div>-->
<!--            </fieldset>-->
            <fieldset>
                <label class="gf-title" for="lf-name">商家名/ID</label><input class="text" id="lf-name" name="user" type="text" placeholder="请输入商家名/ID">
            </fieldset>
            <fieldset>
                <label class="gf-title" for="lf-password">密码</label><input class="text" id="lf-password" name="password" type="password" placeholder="请输入密码">
                <aside class="lf-error password-error"></aside>
            </fieldset>
            <fieldset>
                <div class="in-checkbox">
                    <input type="checkbox" value="" name="choice_checkbox" id="checkbox">
                </div>
                <label class="in-title">记住密码</label>
            </fieldset>
            <fieldset class="gf-submit">
                <input class="submit button" type="button" name="submit" value="确定" id="submitBtn">
            </fieldset>
            <fieldset>
                <a class="forget-cord" href="/selleradmin/index/forget" title="" target="_blank">忘记密码</a>
                <a class="change-cord" href="/selleradmin/index/change" title="" target="_blank">修改密码</a>
            </fieldset>
        </form>
    </div>
    <section class="center wrapper con">
        <img class="photo" src="/seller/images/title01.gif" alt="">
        <div class="message">
            <h1>权威的原创报道！</h1>
            <p>第一时间采编最新活动，精确传递商家信息！</p>
            <p>权威热门玩法、游玩地推荐，深受家长信赖和追捧！</p>
            <div class="mess-sty">
                <p class="style">编辑推荐特色遛娃地，微信软文阅读量1.7万！</p>
            </div>
        </div>
    </section>
    <section class="con1">
        <div class="wrapper center">
            <div class="message message01">
                <h1>有效的营销方式！</h1>
                <p>秒杀、转发、推送、同玩，</p>
                <p>移动端用户最习惯的玩法，APP与朋友圈的充分结合！</p>
                <div class="mess-sty">
                    <p class="style">策划3波特价预售，日销量与美团网相当！</p>
                    <p class="style">2周内售出3000张门票！</p>
                </div>
            </div>
            <img class="photo" src="/seller/images/title02.gif" alt="">
        </div>
    </section>
    <section class="center wrapper con">
        <img class="photo" src="/seller/images/title03.gif" alt="">
        <div class="message">
            <h1>真实的用户反馈！</h1>
            <p>第一手的家长汇报贴及图文评论，</p>
            <p>有效增强商家好评度，全面提升商家口碑！</p>
            <div class="mess-sty">
                <p class="style">有效用户评论100+，各大亲子论坛汇报帖30+！</p>
            </div>
        </div>
    </section>
    <section class="con2">
        <div class="wrapper center">
            <img class="photo1" src="/seller/images/wan.gif" alt="">
        </div>
    </section>
    <p class="style1">20万爸爸妈妈和宝宝都在用玩翻天APP</p>
    <section class="con3">
        <div class="wrapper center">
            <div class="message">
                <h1>精准用户，一键直达！</h1>
                <p>“真心好用，孩子可喜欢了。”——艺星妈妈</p>
                <p>“玩翻天，太迎合我们这群麻麻的口味了，再也不用担心周末去哪遛娃了。”——梦境不完美</p>
                <p>“App里的很多活动都很有意义，假期刚好可以带孩子去体验，<br>而且票价都便宜好多，非常实惠。”——~啊区</p>
                <p>“感谢玩翻天的优惠！不仅有优惠，还给我们提供了大量的遛娃信息点。感谢！感谢! <br> 最近推荐了很多朋友使用玩翻天，她们也是乐坏了！” ——苏妹妹</p>
            </div>
            <img class="photo2" src="/seller/images/footer.gif" alt="">
        </div>
    </section>
</main>
<footer id="footer" class="center">
    <section class="foot-lx">
        <h1>联系我们</h1>
        <p>地址：武汉市汉阳区龟山北路一号汉阳造文化创意产业园9栋2楼3号</p>
        <p>座机：027-85866499</p>
        <p>商务合作：186 7296 2818</p>
        <p>QQ：7462764 </p>
    </section>
    <ul class="chat">
        <li>
            <figure>
                <img src="/seller/images/chat1.gif" alt="">
                <figcaption>
                    订阅攻略天天看
                </figcaption>
            </figure>
        </li>
        <li>
            <figure>
                <img src="/seller/images/chat2.gif" alt="">
                <figcaption>
                    微信也能买买买
                </figcaption>
            </figure>
        </li>
        <li>
            <figure>
                <img src="/seller/images/chat3.gif" alt="">
                <figcaption>
                    下载APP专享一元秒
                </figcaption>
            </figure>
        </li>
    </ul>
</footer>
</body>
<template id="alert">
    <div class="modal-alert">
        <h1 class="modal-alert-title">{{message}}</h1>
        <input class="button modal-alert-button modal-close" type="button" value="确定" />
    </div>
</template>
<script src="/js/jquery.min.js"></script>
<script>
    $(function(){
        $("#submitBtn").click(function(){
            var user = $("#lf-name").val();
            var password = $("#lf-password").val();
            var type = $("#checkbox").prop('checked');
            if(!user){
                alert('请输入用户名');
                return false;
            }
            if(!password){
                alert('请输入密码');
                return false;
            }
            $.post("/selleradmin/index/login",{'user':user,'password':password,'type':type},function(d){
                if(d.status==0){
                    alert(d.message)
                }else{
                    window.location.href='/selleradmin/index/info';
                }
            },'json')
        })
    })
</script>
</html>

