<hgroup class="box">
    <header>
        <h3>合同</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/contract">返回合同列表</a>
    </header>
    <aside class="tips">
    </aside>
</hgroup>
<body>
<header class="box-title">
    <a href="/wftadlogin/contract/addContract?cid=<?php echo $contractData->id ;?>">合同基本信息</a>　　　　
    <a href="/wftadlogin/contract/contractGood?cid=<?php echo $contractData->id ;?>">商品管理</a>
</header>
<table class="table">
    <tr>
        <th width="160">合同编号</th>
        <th colspan="3">
            <?php echo $contractData->contract_no;?>
        </th>
    </tr>

    <tr>
        <th width="160">类别</th>
        <th colspan="3">
            <?php
            if($contractData->contracts_type == 1) {
                echo '包销合同';
            } elseif ($contractData->contracts_type == 2) {
                echo '自营合同';
            } elseif ($contractData->contracts_type == 3) {
                echo '代销合同';
            }
            ?>
        </th>
    </tr>

</table>

<header class="box-title">
    商品明细 　　　　
    <a class="ui-button" href="/wftadlogin/contract/good?cid=<?php echo $contractData->id; ?>">添加商品</a>
</header>
<table class="table">
    <th>商品ID</th>
    <th>商品名称</th>
    <th>相关</th>
    <th>原价</th>
    <th>售价</th>
    <th>结算价</th>
    <th>预付金</th>
    <th>操作</th>　
    <?php foreach($contractLinkData as $kt => $pt):?>
        <tr>
            <td><?php echo $pt['good_id'];?></td>
            <td><?php echo $pt['good_name'];?></td>
            <td><?php echo ($pt['account_type'] == 2) ? '有预付金' : '无预付金';?>___ <?php echo ($pt['account_organizer'] == 1) ? '合同商家结算' : '使用商家结算';?></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <a class="ui-button" href="/wftadlogin/contract/price?gid=<?php echo $kt;?>">添加价格方案</a>
                <?php if(!isset($pt['price'])):?>
                <a class="ui-button" href="/wftadlogin/contract/deleteGood?id=<?php echo $pt['good_id'];?>">删除</a>
                <?php endif;?>
            </td>
        </tr>
        <?php if(isset($pt['price'])):?>
            <?php foreach($pt['price'] as $price):?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><?php echo $price['money'];?></td>
                    <td><?php echo $price['price'];?></td>
                    <td><?php echo $price['account_money'];?></td>
                    <td><?php echo $price['pre_money'];?></td>
                    <td>
                        <?php if($price['status'] < 2):?>
                            <a onclick="if(confirm('确定删除?')==false)return false;" class="ui-button" href="/wftadlogin/contract/deletePrice?id=<?php echo $price['id'];?>">删除</a>
                            <a class="ui-button" href="/wftadlogin/contract/updatePrice?id=<?php echo $price['id'];?>">修改</a>
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach;?>
        <?php endif;?>
    <?php endforeach;?>　
</table>

</body>


