<hgroup class="box">
    <header>
        <h3>合同</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/contract">返回合同列表</a>
    </header>
    <aside class="tips">
    </aside>
</hgroup>
<body>
    <header class="box-title">
        <a href="/wftadlogin/contract/addContract?cid=<?php echo $contractData->id ;?>">合同基本信息</a>　　　　
        <a href="/wftadlogin/contract/contractGood?cid=<?php echo $contractData->id ;?>">商品管理</a>
    </header>
    <table class="table">
        <tr>
            <th width="160">合同编号</th>
            <th colspan="3">
                <?php echo $contractData->contract_no;?>
            </th>
        </tr>

        <tr>
            <th width="160">类别</th>
            <th colspan="3">
                <?php
                    if($contractData->contracts_type == 1) {
                        echo '包销合同';
                    } elseif ($contractData->contracts_type == 2) {
                        echo '自营合同';
                    } elseif ($contractData->contracts_type == 3) {
                        echo '代销合同';
                    }
                ?>
            </th>
        </tr>
        <tr>
            <th width="160">商品名称</th>
            <th colspan="3"><?php echo $goodData->title;?></th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a class="ui-button" href="/wftadlogin/contract/inventory?cid=<?php echo $contractData->id; ?>&gid=<?php echo $goodData->id;?>">添加库存</a>
            </th>
        </tr>
    </table>

    <header class="box-title">
        库存列表
    </header>
    <table class="table">
        <th>商品ID</th>
        <th>商品名称</th>
        <th>采购价</th>
        <th>采购数量</th>
        <th>预付金</th>
        <th>库存地点</th>
        <th>原价</th>
        <th>售价</th>
        <th>操作</th>
        <?php foreach($contractLinkData as $inventory):?>
            <tr>
                <td><?php echo $inventory['good_id']?></td>
                <td><?php echo $inventory['good_name']?></td>
                <td><?php echo $inventory['account_money']?></td>
                <td><?php echo $inventory['purchase_number']?></td>
                <td><?php echo $inventory['pre_money']?></td>
                <td>
                    <?php echo $inventory['inventory_address'] == 1 ? '玩翻天仓库' : '商家仓库';?>
                </td>
                <td></td>
                <td></td>
                <td>
                    <a class="ui-button" href="/wftadlogin/contract/inventoryPrice?gid=<?php echo $goodData->id; ?>&invent_id=<?php echo $inventory['id']; ?>">添加价格方案</a>
                    <?php if($inventory['inventory_status'] < 2):?>
                        <?php if(!isset($inventory['price'])):?>
                        <a class="ui-button"   onclick="if(confirm('确定删除?')==false) return false;" href="/wftadlogin/contract/deleteInventory?id=<?php echo $inventory['id']; ?>">删除</a>
                        <?php endif;?>
                        <a class="ui-button" href="/wftadlogin/contract/updateInventory?id=<?php echo $inventory['id']; ?>">修改</a>
                    <?php endif;?>
                </td>
            </tr>
            <?php if(isset($inventory['price'])):?>
                <?php foreach($inventory['price'] as $price):?>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><?php echo $price['money'];?></td>
                        <td><?php echo $price['price'];?></td>
                        <td>
                            <?php if($price['status'] < 2):?>
                                <a onclick="if(confirm('确定删除?')==false)return false;" class="ui-button" href="/wftadlogin/contract/deletePrice?id=<?php echo $price['id'];?>">删除</a>
                                <a class="ui-button" href="/wftadlogin/contract/updatePrice?id=<?php echo $price['id'];?>">修改</a>
                            <?php endif;?>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
        <?php endforeach;?>
    </table>
</body>


