<form class="box box-form" action="/wftadlogin/contract/saveGood" method="post">
    <header class="box-title">添加合同商品 　　　　
        <a href="/wftadlogin/contract/addContract?cid=<?php echo $contractData->id; ?>">暂时不添加商品</a>
    </header>
    <table class="table">

        <tr>
            <th width="160">商品名称</th>
            <th colspan="3">
                <input type="text" class="cssInput" name="good_name" value="">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <input type="hidden" name="cid" value="<?php echo $contractData->id; ?>">
            </th>
        </tr>

        <?php if($contractData->contracts_type == 1):?>
            <tr>
                <th width="160"></th>
                <th colspan="3">
                    <input type="hidden" name="account_type" value="1">
                </th>
            </tr>
        <?php else:?>
            <tr>
                <th width="160">是否需要预付金</th>
                <th colspan="3">
                    <select name="account_type">
                        <option value="0">请选择</option>
                        <option value="2">付预付金</option>
                        <option value="3">不付预付金</option>
                    </select>
                </th>
            </tr>
        <?php endif;?>

        <?php if($contractData->contracts_type == 1):?>
            <tr>
                <th width="160"></th>
                <th colspan="3">
                    <input type="hidden" name="account_organizer" value="1">
                </th>
            </tr>
        <?php else:?>
            <tr>
                <th width="160">结算商家</th>
                <th colspan="3">
                    <select name="account_organizer">
                        <option value="1">合同商家</option>
                        <option value="2">使用商家</option>
                    </select>
                </th>
            </tr>
        <?php endif;?>

        <tr>
            <th width="160">　　</th>
            <th colspan="3">
                <button type="submit" class="btn btn-primary">保存</button>
            </th>
        </tr>

    </table>
</form>


