<hgroup class="box">
    <header>
        <h3>账户角色分配管理</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/authaccess/new">添加</a>
        &nbsp;&nbsp;&nbsp;
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：<span style="color:green">有问题 请及时联系</span> </div>
    </aside>
</hgroup>
<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>

            <tr>
                <th class="size1">uid</th>
                <th class="size2">分组</th>
                <th class="size1">其它权限</th>
                <th class="size3">操作</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size1"><?php echo $row['uid']; ?></td>
                        <td class="size2">
                            <a href="/wftadlogin/authaccess/new?uid=<?php echo $row['uid']; ?>">
                                <?php echo $row['group_name']; ?>
                            </a>
                        </td>
                        <td class="size1"><?php echo $row['other_auth']; ?></td>

                        <td class="size3">
                            <a href="/wftadlogin/authaccess/new?uid=<?php echo $row['uid']; ?>" class="ui-button">编辑</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无标签 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pagedata; ?>
        </footer>
    </div>
</div>





<script>
    $(function () {
        //设为焦点图




    })
</script>