<hgroup class="box">
    <header>
        <h3>财务管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/finance/contract">合同审核</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php

    $start_time = null;
    $contract_no = null;
    $operator = null;
    $organizer = null;
    $organizer_id = null;
    $contract_type = null;
    $contract_status = null;
    $city = null;


    if (isset($_GET['create_time']) && $_GET['create_time']) {
        $start_time = $_GET['create_time'];
    }


    if (isset($_GET['contract_no']) && $_GET['contract_no']) {
        $contract_no = $_GET['contract_no'];
    }

    if (isset($_GET['operator']) && $_GET['operator']) {
        $operator = $_GET['operator'];
    }

    if (isset($_GET['organizer']) && $_GET['organizer']) {
        $organizer = $_GET['organizer'];
    }

    if (isset($_GET['organizer_id']) && $_GET['organizer_id']) {
        $organizer_id = $_GET['organizer_id'];
    }

    if (isset($_GET['contract_type']) && $_GET['contract_type']) {
        $contract_type = $_GET['contract_type'];
    }

    if (isset($_GET['contract_status']) && $_GET['contract_status']) {
        $contract_status = $_GET['contract_status'];
    }

    ?>

    <table class="table">
        <tr>
            <th width="160">合同创建时间</th>
            <th>
                <input name="create_time" type="date" class="cssInput" style="width:190px"  value="<?php echo $start_time;?>">
            </th>
            <th colspan="2">
                商家名称<input name="organizer" type="text" class="cssInput" style="width:190px"  value="<?php echo $organizer;?>">
                商家id<input name="organizer_id" type="text" class="cssInput" style="width:90px"  value="<?php echo $organizer_id;?>">
            </th>
        </tr>

        <tr>
            <th width="160">合同编号</th>
            <th>
                <input type="text" class="cssInput" name="contract_no" value="<?php echo $contract_no;?>">
            </th>
            <th width="160">合同类型</th>
            <th>
                <select name="contract_type">
                    <option value="0" <?php echo ($contract_type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($contract_type == '1') ? 'selected' : '';?>>包销</option>
                    <option value="2" <?php echo ($contract_type == '2') ? 'selected' : '';?>>自营</option>
                    <option value="3" <?php echo ($contract_type == '3') ? 'selected' : '';?>>代销</option>
                </select>
            </th>
        </tr>


        <tr>
            <th width="160">经办人</th>
            <th>
                <input type="text" class="cssInput" name="operator" value="<?php echo $operator;?>">
            </th>
            <th width="160">合同状态</th>
            <th>
                <select name="contract_status">
                    <option value="0" <?php echo !$contract_status ? 'selected' : '';?>>全部</option>
                    <?php foreach($this->contract_status as $tra => $v):?>
                        <option value="<?php echo $tra;?>" <?php echo ($contract_status == $tra) ? 'selected' : '';?>><?php echo $v?></option>
                    <?php endforeach;?>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/finance/contract" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/finance/outData" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>



<div class="panel panel panel-primary">
    <div class="panel-heading">合同列表</div>
    <div class="panel-body">

        <table class="table table-striped table-hover">
            <tr>
                <th scope="col">合同编号</th>
                <th scope="col">创建时间</th>
                <th scope="col">经办人</th>
                <th scope="col">商家</th>
                <th scope="col">合同类型</th>
                <th scope="col">预付金</th>
                <th scope="col">合同状态</th>
                <th scope="col">商品数</th>
                <th scope="col">商品订单数</th>
                <th scope="col">商家预计收入</th>
                <th scope="col">商家实际收入</th>
                <th scope="col">平台收入</th>
                <th scope="col" width="100">操作</th>
            </tr>
            <?php foreach ($this->data as $v): ?>
                <tr>
                    <td><?php echo $v['contract_no']; ?></td>
                    <td><?php echo date('Y-m-d H:i:s', $v['create_time']); ?></td>
                    <td><?php echo $v['admin_name']; ?></td>
                    <td><?php echo $v['organizer_name'];?></td>
                    <td><?php echo $this->contract_type[$v['contracts_type']]; ?></td>
                    <td><?php echo $v['pre_money']; ?></td>
                    <td>
                        <?php
                        if($v['status']==0){
                            if($v['contracts_type']==1){
                                echo '已终止';
                            }
                        }
                        if($v['status']==1){
                            if($v['check_status']==0){
                                echo '未审批';
                            }
                            if($v['check_status']==1){
                                echo '已提交审批';
                            }
                            if($v['check_status']==2){
                                if($v['pay_pre_status']==1){
                                    echo '预付金审批已通过';
                                }
                                if($v['pay_pre_status']==2 and $v['contracts_type'] !=3){
                                    echo '预付金已到账';
                                }
                                if($v['contracts_type']==3){
                                    echo '正在生效';
                                }
                            }

                        }
                        if($v['status']==2){
                            if($v['pay_pre_status']<3){
                                echo '结束，要求结款';
                            }else{
                                if($v['contracts_type']!=3){
                                    echo '已结束';
                                }else{
                                    echo '已终止';
                                }
                            }

                        }

                        if($v['status']==3){
                            echo '已提交结束';
                        }

                        if($v['status']==4 and $v['contracts_type']==1){
                            echo '已提交终止';
                        }
                        ?>
                    </td>
                    <td><?php echo  $v['goods_num']; ?></td>
                    <td><?php echo  $v['order_num']; ?></td>
                    <td><?php echo  $v['shop_pre_income']; ?></td>
                    <td><?php echo  $v['shop_real_income']; ?></td>
                    <td><?php echo  $v['deyi_income']; ?></td>
                    <td>
                        <?php if($v['status']==1 and $v['check_status']<2 and $v['pay_pre_status']==1 and $v['contracts_type']<3):?>
                        <a class="btn btn-info" href="/wftadlogin/finance/approveContract?type=2&id=<?php echo $v['id']; ?>">批准预付金</a>
                        <?php endif;?>
                        <?php if($v['status']==1 and $v['check_status']<2 and $v['contracts_type']==3):?>
                        <a class="btn btn-info" href="/wftadlogin/finance/approveContract?type=1&id=<?php echo $v['id']; ?>">审批通过</a>
                        <?php endif;?>
                        <?php if($v['status']==4 and $v['contracts_type']==1):?>
                            <a class="btn btn-info" href="/wftadlogin/finance/approveContract?type=3&id=<?php echo $v['id']; ?>">审批终止</a>
                        <?php endif;?>
                        <?php if($v['status']==3 and $v['contracts_type']==1):?>
                            <a class="btn btn-info" href="/wftadlogin/finance/approveContract?type=4&id=<?php echo $v['id']; ?>">批准结款</a>
                        <?php endif;?>
                        <?php if($v['status']==3 and $v['contracts_type'] != 1):?>
                            <a class="btn btn-info" href="/wftadlogin/finance/approveContract?type=7&id=<?php echo $v['id']; ?>">确认结束</a>
                        <?php endif;?>
                        <a class="ui-button" href="/wftadlogin/contract/addContract?cid=<?php echo $v['id']; ?>">查看</a>
                    </td>
                </tr>
            <?php endforeach; ?>

        </table>
        <div>
            <?php echo $this->pageData; ?>
        </div>
    </div>
</div>


<style>
    .btn {
        position: relative;
        cursor: pointer;
        display: inline-block;
        vertical-align: middle;
        font-size: 12px;
        font-weight: bold;
        height: 27px;
        line-height: 27px;
        min-width: 52px;
        padding: 0 12px;
        text-align: center;
        text-decoration: none;
        border-radius: 2px;
        border: 1px solid #ddd;
        color: #666;
        background-color: #f5f5f5;
        background: -webkit-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: -moz-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: linear-gradient(top, #F5F5F5, #F1F1F1);
    }

    .login-body {
        padding: 60px 15px;
        color: #444;
        height: 148px;
    }

    .ipt {
        border: solid 1px #d2d2d2;
        border-left-color: #ccc;
        border-top-color: #ccc;
        border-radius: 2px;
        box-shadow: inset 0 1px 0 #f8f8f8;
        background-color: #fff;
        padding: 4px 6px;
        height: 21px;
        line-height: 21px;
        color: #555;
        width: 180px;
        vertical-align: baseline;
    }

    .dform {
        padding: 80px 60px 40px;
        text-align: center;
    }

    .signin {
        margin: -50px -20px -50px 90px;
        text-align: left;
        font-size: 14px;
    }

    .signin h4 {
        color: #999;
        font-weight: 100;
        margin-bottom: 20px;
        font-size: 12px;
    }

    .signin li {
        padding-left: 80px;
        margin-bottom: 15px;
    }

    .signin ol {
        list-style-type: none;
    }

    .signin li strong {
        float: left;
        margin-left: -80px;
        width: 80px;
        text-align: right;
        line-height: 32px;
    }

    .signin .btn {
        margin-bottom: 10px;
    }

    .signin p {
        font-size: 12px;
        color: #999;
    }

    .theme-desc,.theme-version {
        padding-top: 0
    }

    .body-color {
        z-index: 9998;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: #000;
        opacity: 0.4;
        filter: alpha(opacity = 40);
        display: none
    }

    .hide-body {
        z-index: 9999;
        position: fixed;
        top: 30%;
        left: 40%;
        width: 1000px;
        height: 618px;
        margin: -180px 0 0 -330px;
        border-radius: 5px;
        border: solid 2px #666;
        background-color: #fff;
        display: none;
        box-shadow: 0 0 10px #666;
    }

    .close-window {
        border-bottom: 1px solid #ddd;
        padding: 22px;
        position: relative;
    }

    .bottom {
        margin-top: 180px;
    }

    .close-window .close {
        float: right;
        color: #999;
        padding: 5px;
        margin: -2px -5px -5px;
        font: bold 14px/14px simsun;
        text-shadow: 0 1px 0 #ddd
    }

    .close-window .close:hover {
        color: #444;
    }
</style>

<div class="hide-body">
    <div class="close-window">
        <!-- 关闭窗口，也就是触发关闭div的事件-->
        <a href="javascript:;" title="关闭" class="close">×</a>
        <h3>终止合同</h3>
    </div>
    <!-- 中间主体显示div 可以增加其他的样式-->
    <div class="login-body dform">
        <form class="signin" name="loginform" action="" id="zjh" method="post">
            <ol>
                <li><input name="stop_type" checked="checked"  type="radio" value="1" /> 主动终止</li>
                <li><input name="stop_type" type="radio" value="2" />商家违约
                <li><button type="submit" class="ui-button">提交</button></li>
            </ol>
        </form>
    </div>
</div>

<script>
    $(function () {
        //导出订单
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');
        });

        //终止合同
        $('.stop-contract').click(function(){ //jquery的点击事件
            $('.body-color').fadeIn(100);//全局变得黑的效果，具体的div就是theme-popover-mask这个
            $('.hide-body').slideDown(200);//将隐藏的窗口div显示出来
            var url = $(this).attr('data-src');
            $('#zjt').attr('href', url);
            $('#zjh').attr('action', url);

        })
        $('.close-window .close').click(function(){
            $('.body-color').fadeOut(100);//
            $('.hide-body').slideUp(200);//将显示的窗口隐藏起来
        })
    });
</script>


