<style>
    #tongji{
        padding:5px 5px;
        margin: 5px 5px;
    }
    #tongji span{
        color:red;
        font-size:16px;
        padding: 10px;
    }
</style>
<hgroup class="box">
    <header>
        <h3>财务</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/finance/index">订单管理</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $good_name = null;
    $good_id = null;
    $user_name = null;
    $shop_name = null;
    $user_phone = null;
    $buy_start = null;
    $buy_end = null;
    $check_start = null;
    $check_end = NULL;
    $back_start = null;
    $back_end = NULL;
    $order_status = 0;
    $check_status = 0;
    $good_status = 0;
    $pay_type = null;
    $pageNum = 10;
    $admin=null;

    if (isset($_GET['good_name']) && $_GET['good_name']) {
        $good_name = $_GET['good_name'];
    }

    if (isset($_GET['good_id']) && $_GET['good_id']) {
        $good_id = $_GET['good_id'];
    }

    if (isset($_GET['shop_name']) && $_GET['shop_name']) {
        $shop_name = $_GET['shop_name'];
    }

    if (isset($_GET['user_name']) && $_GET['user_name']) {
        $user_name = $_GET['user_name'];
    }

    if (isset($_GET['user_phone']) && $_GET['user_phone']) {
        $user_phone = $_GET['user_phone'];
    }

    if (isset($_GET['buy_start_date']) && $_GET['buy_start_date']) {
        $buy_start = $_GET['buy_start_date'];
    }

    if (isset($_GET['buy_end_date']) && $_GET['buy_end_date']) {
        $buy_end = $_GET['buy_end_date'];
    }

    if (isset($_GET['ver_start_date']) && $_GET['ver_start_date']) {
        $check_start = $_GET['ver_start_date'];
    }

    if (isset($_GET['ver_end_date']) && $_GET['ver_end_date']) {
        $check_end = $_GET['ver_end_date'];
    }

    if (isset($_GET['sub_back_start_date']) && $_GET['sub_back_start_date']) {
        $back_start = $_GET['sub_back_start_date'];
    }

    if (isset($_GET['sub_back_end_date']) && $_GET['sub_back_end_date']) {
        $back_end = $_GET['sub_back_end_date'];
    }

    if (isset($_GET['pay_status']) && $_GET['pay_status']) {
        $order_status = $_GET['pay_status'];
    }

    if (isset($_GET['ver_status']) && $_GET['ver_status']) {
        $check_status = $_GET['ver_status'];
    }

    if (isset($_GET['good_status']) && $_GET['good_status']) {
        $good_status = $_GET['good_status'];
    }

    if (isset($_GET['pay_type']) && $_GET['pay_type']) {
        $pay_type = $_GET['pay_type'];
    }

    if (isset($_GET['page']) && $_GET['page']) {
        $pageNum = $_GET['page'];
    }

    if (isset($_GET['admin']) && $_GET['admin']) {
        $admin = $_GET['admin'];
    }

    ?>
    <table class="table">
        <tr>
            <th width="120">商品名</th>
            <th>
                <input type="text" class="cssInput" name="good_name" value="<?php echo $good_name;?>">
            </th>
            <th width="120">购买时间</th>
            <th>
                <input name="buy_start_date" type="date" class="cssInput" style="width:130px"  value="<?php echo $buy_start;?>">
                <input name="buy_end_date" type="date" class="cssInput" style="width:130px"  value="<?php echo $buy_end;?>">
            </th>
            <th width="120"></th>
            <th width="120">审核状态</th>
            <th>
                <select name="check_status" id="select">
                    <option value="0" <?php echo ($check_status == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($check_status == 1) ? 'selected' : '';?>>未审核</option>
                    <option value="2" <?php echo ($check_status == 2) ? 'selected' : '';?>>已审核</option>
                </select>
            </th>
        </tr>

        <tr>
            <th colspan="" width="120">商家名</th>
            <th>
                <input type="text" class="cssInput" name="shop_name" value="<?php echo $shop_name;?>">
            </th>

            <th width="120">验证时间</th>
            <th>
                <input name="ver_start_date" type="date" class="cssInput" style="width:130px"  value="<?php echo $check_start;?>">
                <input name="ver_end_date" type="date" class="cssInput" style="width:130px"  value="<?php echo $check_end;?>">
            </th>
            <th width="120"></th>
            <th width="120">订单状态</th>
            <th>
                <select name="order_status" id="select">
                    <option value="0" <?php echo ($order_status == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($order_status == 1) ? 'selected' : '';?>>未支付</option>
                    <option value="3" <?php echo ($order_status == 3) ? 'selected' : '';?>>退款处理中</option>
                    <option value="4" <?php echo ($order_status == 4) ? 'selected' : '';?>>已退款</option>
                    <option value="5" <?php echo ($order_status == 5) ? 'selected' : '';?>>已结算</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="100">商品id</th>
            <th width="100">
                <input type="text" class="cssInput" name="good_id" value="<?php echo $good_id;?>">
            </th>
            <th width="160">退款时间</th>
            <th>
                <input name="sub_back_start_date" type="date" class="cssInput" style="width:130px"  value="<?php echo $back_start;?>">
                <input name="sub_back_end_date" type="date" class="cssInput" style="width:130px"  value="<?php echo $back_end;?>">
            </th>
            <th width="120"></th>
            <th width="120">商品状态</th>
            <th>
                <select name="good_status" id="select">
                    <option value="0" <?php echo ($good_status == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($good_status == 1) ? 'selected' : '';?>>未开始</option>
                    <option value="2" <?php echo ($good_status == 2) ? 'selected' : '';?>>在售</option>
                    <option value="3" <?php echo ($good_status == 3) ? 'selected' : '';?>>停止使用</option>
                    <option value="4" <?php echo ($good_status == 4) ? 'selected' : '';?>>已下架</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160">用户名</th>
            <th>
                <input type="text" class="cssInput" name="user_name" value="<?php echo $user_name;?>">
            </th>
            <th width="120" colspan="2">
                用户手机号
                <input type="text" class="cssInput" name="user_phone" value="<?php echo $user_phone;?>" style="width:190px">
                经办人
                <input type="text" class="cssInput" name="admin" value="<?php echo $admin;?>" style="width:190px">
            </th>
            <th width="120">支付方式</th>
            <th>
                <select name="pay_type" id="select">
                    <option value="0" <?php echo ($pay_type == 0) ? 'selected' : '';?>>全部</option>
                    <option value="1" <?php echo ($pay_type == 1) ? 'selected' : '';?>>支付宝</option>
                    <option value="2" <?php echo ($pay_type == 2) ? 'selected' : '';?>>银联</option>
                    <option value="3" <?php echo ($pay_type == 3) ? 'selected' : '';?>>微信</option>
                    <option value="4" <?php echo ($pay_type == 4) ? 'selected' : '';?>>余额支付</option>
                    <option value="5" <?php echo ($pay_type == 5) ? 'selected' : '';?>>微信SDK</option>
                </select>
            </th>
        </tr>
        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/finance/index" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/finance/outOrder" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">
        订单列表
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">订单号</th>
                <th width="50">用户名</th>
                <th width="50">用户手机号</th>
                <th width="80">商品ID</th>
                <th width="80">经办人</th>
                <th width="80">购买时间</th>
                <th width="150">验证时间</th>
                <th width="150">商品名称</th>
                <th width="150">套系</th>
                <th width="100">数量</th>
                <th width="100">备注</th>
                <th width="100">入账</th>
                <th width="100">出账</th>
                <th width="100">收益</th>
                <th width="100">手续费</th>
                <th width="100">商家名称</th>
                <th width="100">审核状态</th>
                <th width="100">订单状态</th>
                <th width="100">商品状态</th>
                <th width="100">支付渠道</th>
                <th width="100">支付账号</th>
            </tr>
            <?php foreach ($data as $key => $row): ?>
                <tr style="text-align: left">
                    <td width="50">
                        <a href="/wftadlogin/order/info?order_sn=<?php echo $row['order_sn'];?>"><?php echo $row['order_sn']; ?></a>
                    </td>
                    <td width="50">
                        <?php echo $row['username'];?>
                    </td>
                    <td width="50"><?php echo $row['buy_phone']; ?></td>
                    <td width="80"><?php echo $row['coupon_id']; ?></td>
                    <td width="80"><?php echo $row['admin_name']; ?></td>
                    <td width="170"><?php echo date('Y-m-d H:i',$row['dateline']); ?></td>
                    <td width="150"><?php echo $row['use_dateline'] ? date('Y-m-d H:i',$row['use_dateline']) : ''; ?></td>
                    <td width="150"><?php echo $row['coupon_name']; ?></td>
                    <td width="150"><?php echo $row['price_name']; ?></td>
                    <td width="150"><?php echo $row['buy_number']; ?></td>
                    <td width="150"><?php echo $row['message']; ?></td>
                    <td width="150"><?php echo $row['buy_number']*$row['coupon_unit_price']; ?></td>
                    <td width="150"><?php echo $row['back_money']>0 ? $row['back_money'] : 0 ; ?></td>
                    <td width="150"><?php echo $row['income']; ?></td>
                    <td width="150"><?php echo $row['fees']; ?></td>
                    <td width="150"><?php echo $row['shop_name']; ?></td>
                    <td width="100"><?php echo ($row['check_status'] == 2) ? '已审核' : '未审核'; ?></td>
                    <td width="150"><?php echo $row['order_status']; ?></td>
                    <td width="150"><?php echo $row['good_status']; ?></td>
                    <td width="150"><?php echo $row['account_type']; ?></td>
                    <td width="150"><?php echo $row['account']; ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <div id="tongji">
            <div>
                <span>总计订单数：<mark><?php echo $order_sum;?></mark></span>
                <span>支付数量：<mark><?php echo $pay_sum;?></mark></span>
            </div>
            <div>
                <span>入账数额：<mark><?php echo $income;?></mark></span>
                <span>出账数额：<mark><?php echo $outSum;?></mark></span>
            </div>
        </div>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>

<style>
    .btn {
        position: relative;
        cursor: pointer;
        display: inline-block;
        vertical-align: middle;
        font-size: 12px;
        font-weight: bold;
        height: 27px;
        line-height: 27px;
        min-width: 52px;
        padding: 0 12px;
        text-align: center;
        text-decoration: none;
        border-radius: 2px;
        border: 1px solid #ddd;
        color: #666;
        background-color: #f5f5f5;
        background: -webkit-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: -moz-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: linear-gradient(top, #F5F5F5, #F1F1F1);
    }
    .cssInput{
        width:200px;
    }

    .login-body {
        padding: 60px 15px;
        color: #444;
        height: 148px;
    }

    .ipt {
        border: solid 1px #d2d2d2;
        border-left-color: #ccc;
        border-top-color: #ccc;
        border-radius: 2px;
        box-shadow: inset 0 1px 0 #f8f8f8;
        background-color: #fff;
        padding: 4px 6px;
        height: 21px;
        line-height: 21px;
        color: #555;
        width: 180px;
        vertical-align: baseline;
    }

    .dform {
        padding: 80px 60px 40px;
        text-align: center;
    }

    .signin {
        margin: -50px -20px -50px 90px;
        text-align: left;
        font-size: 14px;
    }

    .signin h4 {
        color: #999;
        font-weight: 100;
        margin-bottom: 20px;
        font-size: 12px;
    }

    .signin li {
        padding-left: 80px;
        margin-bottom: 15px;
    }

    .signin ol {
        list-style-type: none;
    }

    .signin li strong {
        float: left;
        margin-left: -80px;
        width: 80px;
        text-align: right;
        line-height: 32px;
    }

    .signin .btn {
        margin-bottom: 10px;
    }

    .signin p {
        font-size: 12px;
        color: #999;
    }

    .theme-desc,.theme-version {
        padding-top: 0
    }

    .body-color {
        z-index: 9998;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: #000;
        opacity: 0.4;
        filter: alpha(opacity = 40);
        display: none
    }

    .hide-body {
        z-index: 9999;
        position: fixed;
        top: 30%;
        left: 40%;
        width: 1000px;
        height: 618px;
        margin: -180px 0 0 -330px;
        border-radius: 5px;
        border: solid 2px #666;
        background-color: #fff;
        display: none;
        box-shadow: 0 0 10px #666;
    }

    .close-window {
        border-bottom: 1px solid #ddd;
        padding: 22px;
        position: relative;
    }

    .bottom {
        margin-top: 180px;
    }

    .close-window .close {
        float: right;
        color: #999;
        padding: 5px;
        margin: -2px -5px -5px;
        font: bold 14px/14px simsun;
        text-shadow: 0 1px 0 #ddd
    }

    .close-window .close:hover {
        color: #444;
    }
</style>
<script>
    $(function () {
        //导出订单
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');
        });

    });
</script>



