
<hgroup class="box">
    <header>
        <h3>财务管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/finance/shopAccount">商家账户</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>
<!--<form class="box box-form" action="#" method="get" id="out-data-form">-->
    <header class="box-title">商家流水</header>
<!--    --><?php
//    $shop_name = null;
//
//
//    if (isset($_GET['shop_name']) && $_GET['shop_name']) {
//        $shop_name = $_GET['shop_name'];
//    }
//
//
//    ?>
<!--    <table class="table">-->
<!--        <tr>-->
<!--            <th width="120">查找商家</th>-->
<!--            <th>-->
<!--                <input type="text" class="cssInput" name="shop_name" value="--><?php //echo $shop_name;?><!--">-->
<!--            </th>-->
<!--        </tr>-->
<!---->
<!--        <tr>-->
<!--            <th width="160"></th>-->
<!--            <th colspan="3">-->
<!--                <a href="/wftadlogin/finance/shopAccount" style="background-color: green" class="ui-button">清空所有选项</a>-->
<!--                <button  class="ui-button">提交</button>-->
<!--                <a href="javascript:void(0)" data-src="/wftadlogin/order/outaccount" id="out-data" style="background-color: green" class="ui-button">导出</a>-->
<!--            </th>-->
<!--        </tr>-->
<!--    </table>-->
<!--</form>-->

<div class="box">
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">交易时间</th>
                <th width="80">流水类型</th>
                <th width="80">商家ID</th>
                <th width="80">商家名称</th>
                <th width="100">出账</th>
                <th width="100">入账</th>
                <th width="100">可提现金额</th>
                <th width="100">操作流水号</th>
            </tr>
            <?php foreach ($data as $key => $row): ?>
                <tr style="text-align: left">
                    <td width="50">
                        <?php echo date("Y-m-d H:i:s",$row['dateline']);?>
                    </td>
                    <td width="50">
                        <?php
                            if($row['object_type']==1){
                                echo '订单分润';
                            }else{
                                echo '提现';
                            }
                        ?>

                    </td>
                    <td width="50"><?php echo $row['oid']; ?></td>
                    <td width="50">
                        <?php echo $row['name'];?>
                    </td>
                    <td width="50"><?php echo $row['object_type']==1 ? 0 : $row['flow_money']; ?></td>
                    <td width="50"><?php echo $row['object_type']==2 ? 0 : $row['flow_money']; ?></td>
                    <td width="50"><?php echo $row['use_money']; ?></td>
                    <td width="80">
                        <?php echo $row['trade_no'].'-'.$row['id']; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <footer>
<!--            --><?php //echo $this->pageData; ?>
        </footer>
    </div>
</div>

<style>
    .btn {
        position: relative;
        cursor: pointer;
        display: inline-block;
        vertical-align: middle;
        font-size: 12px;
        font-weight: bold;
        height: 27px;
        line-height: 27px;
        min-width: 52px;
        padding: 0 12px;
        text-align: center;
        text-decoration: none;
        border-radius: 2px;
        border: 1px solid #ddd;
        color: #666;
        background-color: #f5f5f5;
        background: -webkit-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: -moz-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: linear-gradient(top, #F5F5F5, #F1F1F1);
    }

    .login-body {
        padding: 60px 15px;
        color: #444;
        height: 148px;
    }

    .ipt {
        border: solid 1px #d2d2d2;
        border-left-color: #ccc;
        border-top-color: #ccc;
        border-radius: 2px;
        box-shadow: inset 0 1px 0 #f8f8f8;
        background-color: #fff;
        padding: 4px 6px;
        height: 21px;
        line-height: 21px;
        color: #555;
        width: 180px;
        vertical-align: baseline;
    }

    .dform {
        padding: 80px 60px 40px;
        text-align: center;
    }

    .signin {
        margin: -50px -20px -50px 90px;
        text-align: left;
        font-size: 14px;
    }

    .signin h4 {
        color: #999;
        font-weight: 100;
        margin-bottom: 20px;
        font-size: 12px;
    }

    .signin li {
        padding-left: 80px;
        margin-bottom: 15px;
    }

    .signin ol {
        list-style-type: none;
    }

    .signin li strong {
        float: left;
        margin-left: -80px;
        width: 80px;
        text-align: right;
        line-height: 32px;
    }

    .signin .btn {
        margin-bottom: 10px;
    }

    .signin p {
        font-size: 12px;
        color: #999;
    }

    .theme-desc,.theme-version {
        padding-top: 0
    }

    .cssInput{
        width:300px;
    }
    .body-color {
        z-index: 9998;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: #000;
        opacity: 0.4;
        filter: alpha(opacity = 40);
        display: none
    }

    .hide-body {
        z-index: 9999;
        position: fixed;
        top: 30%;
        left: 40%;
        width: 1000px;
        height: 618px;
        margin: -180px 0 0 -330px;
        border-radius: 5px;
        border: solid 2px #666;
        background-color: #fff;
        display: none;
        box-shadow: 0 0 10px #666;
    }

    .close-window {
        border-bottom: 1px solid #ddd;
        padding: 22px;
        position: relative;
    }

    .bottom {
        margin-top: 180px;
    }

    .close-window .close {
        float: right;
        color: #999;
        padding: 5px;
        margin: -2px -5px -5px;
        font: bold 14px/14px simsun;
        text-shadow: 0 1px 0 #ddd
    }

    .close-window .close:hover {
        color: #444;
    }
</style>

<script>
    $(function () {

        $('.login').click(function(){ //jquery的点击事件
            $('.body-color').fadeIn(100);//全局变得黑的效果，具体的div就是theme-popover-mask这个
            $('.hide-body').slideDown(200);//将隐藏的窗口div显示出来
            var url = $(this).attr('data-src');
            $('#zjt').attr('href', url);
            $('#zjh').attr('action', url);

        })
        $('.close-window .close').click(function(){
            $('.body-color').fadeOut(100);//
            $('.hide-body').slideUp(200);//将显示的窗口隐藏起来
        })

        //导出订单
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });
    });
</script>




