<form class="box box-form" action="/wftadlogin/welfare/save" method="post">
    <header class="box-title">修改积分奖励</header>
    <table class="table">
        <tr>
            <th width="160">奖励积分类型</th>
            <th colspan="3">
                <?php
                    echo (($data->object_type == 1) ? '游玩地' : '商品'). '的' . (($data->welfare_type == 3) ? '评论' : '分享')
                ?>
            </th>
        </tr>

        <?php if($data->object_type != 2 || $data->welfare_type != 3):?>
        <tr>
            <th width="160">该奖励积分份数</th>
            <th colspan="3">
                <input type="text" class="cssInput" name="total_num" value="<?php echo $data ? $data->total_num : ''; ?>">
            </th>
        </tr>

        <tr>
            <th width="160">每个用户限领多少份</th>
            <th colspan="3">
                <input type="text" class="cssInput" name="limit_num" value="<?php echo $data ? $data->limit_num : ''; ?>">
            </th>
        </tr>
        <?php endif;?>


        <tr>
            <th width="160">基础积分倍数</th>
            <th colspan="3">
                <select name="double">
                    <option <?php echo ($data && $data->double == 1) ? 'selected' : ''; ?> value="1">1倍</option>
                    <option <?php echo ($data && $data->double == 2) ? 'selected' : ''; ?> value="2">2倍</option>
                    <option <?php echo ($data && $data->double == 3) ? 'selected' : ''; ?> value="3">3倍</option>
                    <option <?php echo ($data && $data->double == 4) ? 'selected' : ''; ?> value="4">4倍</option>
                    <option <?php echo ($data && $data->double == 5) ? 'selected' : ''; ?> value="5">5倍</option>
                </select>
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3" width="600">
                <input type="hidden" name="id" value="<?php echo $data->id;?>">
                <input type="hidden" name="object_id" value="<?php echo $data->object_id;?>">
                <input type="hidden" name="object_type" value="<?php echo $data->object_type;?>">
                <input type="hidden" name="welfare_type" value="<?php echo $data->welfare_type;?>">
                <button id="ti-welfare" class="ui-button">提交</button>
            </th>
        </tr>
    </table>
</form>



