<hgroup class="box">
    <header>
        <h3>订单</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/yards/backlist">活动退款</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/code/drawback">商品退款</a>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/code/back">原路返回退款</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
        $activity_name = null;
        $order_id = null;
        $buy_start = null;
        $buy_end = null;
        $accept_start = null;
        $accept_end = null;
        $back_true_start= null;
        $back_true_end = null;
        $pageNum = 10;
        $trade_way = 0;
        $code_status = 2;


        if (isset($_GET['page_num']) && $_GET['page_num']) {
            $pageNum = $_GET['page_num'];
        }

        if (isset($_GET['activity_name']) && $_GET['activity_name']) {
            $activity_name = $_GET['activity_name'];
        }

        if (isset($_GET['order_id']) && $_GET['order_id']) {
            $order_id = $_GET['order_id'];
        }

        if (isset($_GET['buy_start']) && $_GET['buy_start']) {
            $buy_start = $_GET['buy_start'];
        }

        if (isset($_GET['buy_end']) && $_GET['buy_end']) {
            $buy_end = $_GET['buy_end'];
        }

        if (isset($_GET['accept_start']) && $_GET['accept_start']) {
            $accept_start = $_GET['accept_start'];
        }

        if (isset($_GET['accept_end']) && $_GET['accept_end']) {
            $accept_end = $_GET['accept_end'];
        }

        if (isset($_GET['back_true_start']) && $_GET['back_true_start']) {
            $back_true_start = $_GET['back_true_start'];
        }

        if (isset($_GET['back_true_end']) && $_GET['back_true_end']) {
            $back_true_end = $_GET['back_true_end'];
        }

        if (isset($_GET['trade_way']) && $_GET['trade_way']) {
            $trade_way = $_GET['trade_way'];
        }

        if (isset($_GET['code_status']) && $_GET['code_status']) {
            $code_status = $_GET['code_status'];
        }

    ?>

    <table class="table">
        <tr>
            <th width="160">活动名称</th>
            <th>
                <input type="text" class="cssInput" name="activity_name" value="<?php echo $activity_name;?>">
            </th>
            <th width="160">订单号</th>
            <th>
                <input type="text" name="order_id" value="<?php echo $order_id;?>">
            </th>
        </tr>

        <tr>
            <th width="160">订单交易时间</th>
            <th>
                <input name="buy_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $buy_start;?>">
                <input name="buy_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $buy_end;?>">
            </th>
            <th width="160">确定退款时间</th>
            <th>
                <input name="back_true_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $back_true_start;?>">
                <input name="back_true_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $back_true_end;?>">
            </th>
        </tr>

        <tr>
            <th width="160">状态</th>
            <th>
                <select name="code_status">
                    <option value="1" <?php echo ($code_status == 1) ? 'selected' : '';?>>全部</option>
                    <option value="2" <?php echo ($code_status == 2) ? 'selected' : '';?>>状态_退款中</option>
                    <option value="3" <?php echo ($code_status == 3) ? 'selected' : '';?>>状态_已退款</option>
                </select>

                <select name="trade_way">
                    <option value="0" <?php echo ($trade_way == 0) ? 'selected' : '';?>>交易渠道_全部</option>
                    <option value="1" <?php echo ($trade_way == 1) ? 'selected' : '';?>>交易渠道_支付宝</option>
                    <option value="2" <?php echo ($trade_way == 2) ? 'selected' : '';?>>交易渠道_银联</option>
                    <option value="3" <?php echo ($trade_way == 3) ? 'selected' : '';?>>交易渠道_新微信网页</option>
                    <option value="5" <?php echo ($trade_way == 5) ? 'selected' : '';?>>交易渠道_微信app</option>
                    <option value="4" <?php echo ($trade_way == 4) ? 'selected' : '';?>>交易渠道_旧微信网页</option>
                    <option value="6" <?php echo ($trade_way == 6) ? 'selected' : '';?>>交易渠道_用户账户</option>
                </select>


                <select name="page_num">
                    <option value="10" <?php echo ($pageNum == 10) ? 'selected' : '';?>>展示个数_10</option>
                    <option value="50" <?php echo ($pageNum == 50) ? 'selected' : '';?>>展示个数_50</option>
                    <option value="100" <?php echo ($pageNum == 100) ? 'selected' : '';?>>展示个数_100</option>
                    <option value="150" <?php echo ($pageNum == 150) ? 'selected' : '';?>>展示个数_150</option>
                </select>　　
            </th>
            <th width="160">受理退款时间</th>
            <th>
                <input name="accept_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $accept_start;?>">
                <input name="accept_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $accept_end;?>">
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/yards/backlist" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <input type="hidden" name="activity_type" value="2">
                <a href="javascript:void(0)" data-src="/wftadlogin/yards/outData" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">
        活动使用码列表
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">选择</th>
                <th width="100">交易时间</th>
                <th width="100">确定退款时间</th>
                <th width="100">验证码</th>
                <th width="150">交易号</th>
                <th width="100">订单号</th>
                <th width="100">退款金额</th>
                <th width="100">交易渠道</th>
                <th width="60">用户id</th>
                <th width="100">用户名</th>
                <th width="150">活动名称</th>
                <th width="150">操作</th>
            </tr>
            <?php foreach ($data as $key => $row): ?>
                <tr style="text-align: left" class="ter-change" >
                    <td width="50">
                        <?php /*if(!in_array($row['id'], $code_minute)):*/?><!--
                        <input type="checkbox"  name="check_ids" value="<?php /*echo $row['id']; */?>"></td>
                        --><?php /*endif;*/?>
                    <td width="100">
                        <?php echo date('Y-m-d H:i:s',$row['dateline']); ?>
                    </td>
                    <td width="100">
                        <?php echo $row['back_money_time'] ? date('Y-m-d H:i:s',$row['back_money_time']) : ''; ?>
                    </td>
                    <td width="100">
                        <?php echo $row['code']; ?>
                    </td>
                    <td width="150">
                        <?php echo $row['trade_no']; ?>
                    </td>
                    <td width="100"><a href="/wftadlogin/excercise/orderinfo?order_sn=<?php echo $row['order_sn'];?>"><?php echo $row['order_sn']; ?></a></td>
                    <td width="100"><?php echo $row['back_money']; ?></td>
                    <td width="100"><?php echo $tradeWay[$row['account_type']]; ?></td>
                    <td width="60"><?php echo $row['user_id']; ?></td>
                    <td width="100"><?php echo $row['username']; ?></td>
                    <td width="150"><?php echo $row['coupon_name']; ?></td>
                    <td width="150">
                        <?php if(!in_array($row['id'], $code_minute)):?>
                            <?php if($row['accept_status'] == 2):?>
                                <?php if($row['action_id']):?>
                                    <span class="ui-button">退款失败</span>
                                <?php elseif($row['account_type'] == 'jsapi'):?>
                                    旧微信网页暂不支持退款
                                <?php else:?>
                                    <span>待处理</span>
                                    <!--<a style="background-color: green" href="/wftadlogin/yards/back?type=1&id=<?php /*echo $row['id']; */?>" class="ui-button">确认退款</a>-->
                                <?php endif;?>
                            <?php else:?>
                                已退款
                            <?php endif;?>
                        <?php else:?>
                            退款中
                        <?php endif;?>

                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <input type="checkbox" id="check-this">全选
        <?php /*if($trade_way): */?><!--
        <button data-trade="<?php /*echo $trade_way;*/?>"  data-src="<?php /*echo $doUrl*/?>&all=1" class="ui-button" id="mark-check">所选项确认退款</button>
        --><?php /*endif;*/?>
        <style>
            #tongji{
                padding:5px 5px;
                margin: 5px 5px;
            }
            #tongji span{
                color:red;
                font-size:16px;
                padding: 10px;
            }
        </style>
        <div id="tongji">
            <div>
                <span>已退款金额：<mark><?php echo $counter['back_money'];?></mark></span>
                <span>等待退款金额：<mark><?php echo $counter['wait_money'];?></mark></span>
                <span>订单个数 : <?php echo $counter['order_num'];?></span>
            </div>
        </div>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>

</div>


<script>
    $(function () {

        //导出订单
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });

        //选择本页
        $('#check-this').click(function() {
            $("#check-all").attr('checked',false);
            if ($(this).is(':checked')) {
                $("[name=check_ids]:checkbox").prop('checked', true);
            } else {
                $("[name=check_ids]:checkbox").prop('checked', false);
            }
        });


        //确认退款
        /*$('#mark-check').click(function() {
            if (confirm('确定将所有选中的确认退款？不可恢复')) {
                //执行修改操作
                var check_ids = document.getElementsByName('check_ids');
                var id='';//如果这样定义var s;变量s中会默认被赋个null值
                for (var i = 0; i < check_ids.length; i++) {
                    if (check_ids[i].checked){
                        if (i == check_ids.length - 1) {
                            id += check_ids[i].value;
                        } else {
                            id += check_ids[i].value + ',';
                        }
                    }
                }

                if (id == '') {
                    alert('没有选中');
                    return false;
                }

                var trade_type = $(this).attr('data-trade');

                $.post('/wftadlogin/yards/back?type=2&trade_type=' + trade_type, {ids:id}, function (data) {
                    if (data.status == 1) {
                        if (trade_type == 1) {
                            $("#content").html(data.message);return;
                        }
                        alert('成功');
                        window.location.reload();
                    } else {
                        alert(data.message);
                    }
                }, 'json');
                return false;
            }
        });*/

    });
</script>




