<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>玩翻天——关注我吧！</title>
    <link type="text/css" rel="stylesheet" href="/css/share/circle-style.css" />
</head>
<body>
<section class="qrcode">
    <img src="/application/index/phpqrcode?code=<?php echo $url;?>" />
    <h3><?php echo $username?></h3>
    <p>用玩翻天扫一扫二维码图案，关注我吧！</p>
</section>
<footer>
    <i></i>
    <div><h4>玩翻天</h4><p>玩翻天，孩子们的游玩管家。</p></div>
    <a href="/app/index.php">免费下载</a>
</footer>
</body>
</html>