<hgroup class="box">
    <header>
        <h3>分类管理</h3>
        <i class="icon icon-add"></i>
        <a href="/wftadlogin/label/choose">选择分类</a>
        &nbsp;&nbsp;&nbsp;
<!--        <select id="cityChange">-->
<!--           --><?php //foreach ($cityData as $k => $v): ?>
<!--                <option --><?php //echo ($city == $k) ? 'selected' : ''; ?>
<!--                    data-src="/wftadlogin/coupons?city=--><?php //echo $k; ?><!--">--><?php //echo $v; ?><!--</option>-->
<!--           --><?php //endforeach; ?>
<!--        </select>-->
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：<span style="color:green">有问题 请及时联系</span> </div>
    </aside>
</hgroup>
<div class="box">
    <div class="box-title">
        分类列表
    </div>
    <div class="box-table">
        <table>
            <tbody>

            <tr>
                <th class="size1">id</th>
                <th class="size2">分类名</th>
                <th class="size1">类型</th>
                <th class="size1">游玩地数量</th>
                <th class="size1">商品数量</th>
                <th class="size1">浏览数</th>
                <th class="size1">分享数</th>
                <th class="size3">操作</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size1"><?php echo $row['id']; ?></td>
                        <td class="size2">
                            <a href="/wftadlogin/label/new?lid=<?php echo $row['id']; ?>">
                                <?php echo $row['tag_name']; ?>
                            </a>
                        </td>
                        <td class="size1"><?php echo $labelType[$row['label_type']];?></td>
                        <td class="size1"><?php echo $row['place_num'];?></td>
                        <td class="size1"><?php echo $row['good_num'];?></td>
                        <td class="size1"><?php echo $row['label_click'];?></td>
                        <td class="size1 share_number">0</td>
                        <td class="size3">
                            <a href="/wftadlogin/label/edit?lid=<?php echo $row['id']; ?>&type=del" class="ui-button">删除</a>
                            <a href="/wftadlogin/label/edit?lid=<?php echo $row['id']; ?>&type=push" class="ui-button"><?php echo ($row['status'] <= 1) ? '发布' : '取消发布'?></a>
                            <a href="/wftadlogin/label/edit?lid=<?php echo $row['id']; ?>&type=first" class="ui-button"><?php echo ($row['status'] == 3) ? '从发现删除' : '添加到发现'?></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>暂无标签 你可以添加哦</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>





<script>
    $(function () {
        //获取分享记录
        $.each($('.share_number'), function (k, v) {
            var id = $(v).parent().find('td:first').html();
            $(v).load('/wftadlogin/index/sharedata?type=tag&id=' + id);
        })



    })
</script>