<hgroup class="box">
    <header>
        <h3>分类管理</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/label/new?lid=<?php echo $lid?>">返回分类</a>
    </header>
</hgroup>
<div class="panel panel panel-primary">
    <div class="panel-body">
        <ul class="nav nav-tabs">
            <form action="#" method="get">
                <table border="0">
                    <tr>
                        <td>
                            <div class="col-lg-6" style="width: 400px;padding-bottom: 10px;">
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="搜索要添加的商品名称" name="k" value="">
                      <span class="input-group-btn">
                      <button class="btn btn-default" type="submit">搜索要添加的商品名称</button>
                      </span>
                                </div>
                            </div>
                        </td>
                    </tr>
                </table>
                <input type="hidden"  name="lid" value="<?php echo $lid;?>">
            </form>
            <table class="table table-striped table-hover">
                <tr>
                    <th scope="col">商品id</th>
                    <th scope="col">商品名称</th>
                    <th scope="col">状态</th>
                    <th scope="col">操作</th>
                </tr>
                <?php foreach ($this->data as $v): ?>
                    <tr>
                        <td><?php echo $v->id; ?></td>
                        <td><?php echo $v->title; ?></td>
                        <td><?php echo in_array($v->id, $gameIds) ? '已经关联了' : ''; ?></td>
                        <td>
                            <?php if(!in_array($v->id, $gameIds)):?>
                                <a class="btn btn-primary" href="/wftadlogin/label/dogame?lid=<?php echo $lid;?>&gid=<?php echo $v->id; ?>&type=add">添加到分类</a>
                            <?php endif;?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </ul>
    </div>
</div>

