<hgroup class="box">
    <header>
        <h3>标签管理</h3>
        <i class="icon icon-add"></i>
        <a href="javascript:history.go(-1)">后退</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示：① <span style="color:green">有问题 请及时联系</span> ② 请及时 记得删除无效的</div>
    </aside>
</hgroup>
<div class="box">
    <div class="box-title">
        关联卡券列表
    </div>
    <div class="box-table">
        <table>
            <tbody>
            <tr>
                <th class="size1">id</th>
                <th class="size2">商品名</th>
            </tr>
            <?php if (count($data)): ?>
                <?php foreach ($data as $key => $row): ?>
                    <tr style="text-align: left">
                        <td class="size1"><?php echo $row['id']; ?></td>
                        <td class="size2">
                            <a href="/wftadlogin/coupons/new?mid=<?php echo $row['mid'];?>&id=<?php echo $row['id']; ?>">
                                <?php echo $row['coupon_name']; ?>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="7"><p>xxxx</p></td>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>
</div>