<hgroup class="box">
    <header>
        <h3>订单</h3>
        <i class="icon icon-list"></i>
        <a href="/wftadlogin/YardsCode/index">活动订单提交退款退款 及 受理退款</a>
    </header>
    <aside class="tips">
        <i class="icon icon-notice"></i>
        <div>温馨提示： 有问题 请及时联系</div>
    </aside>
</hgroup>

<form class="box box-form" action="#" method="get" id="out-data-form">
    <header class="box-title">搜索条件</header>
    <?php
    $activity_name = null;
    $order_id = null;
    $buy_start = null;
    $buy_end = null;
    $back_start = null;
    $back_end = null;
    $pageNum = 10;
    $trade_way = 0;
    $code_status = 1;


    if (isset($_GET['page_num']) && $_GET['page_num']) {
        $pageNum = $_GET['page_num'];
    }

    if (isset($_GET['activity_name']) && $_GET['activity_name']) {
        $activity_name = $_GET['activity_name'];
    }

    if (isset($_GET['order_id']) && $_GET['order_id']) {
        $order_id = $_GET['order_id'];
    }

    if (isset($_GET['buy_start']) && $_GET['buy_start']) {
        $buy_start = $_GET['buy_start'];
    }

    if (isset($_GET['buy_end']) && $_GET['buy_end']) {
        $buy_end = $_GET['buy_end'];
    }

    if (isset($_GET['back_start']) && $_GET['back_start']) {
        $back_start = $_GET['back_start'];
    }

    if (isset($_GET['back_end']) && $_GET['back_end']) {
        $back_end = $_GET['back_end'];
    }

    if (isset($_GET['trade_way']) && $_GET['trade_way']) {
        $trade_way = $_GET['trade_way'];
    }

    if (isset($_GET['code_status']) && $_GET['code_status']) {
        $code_status = $_GET['code_status'];
    }

    ?>

    <table class="table">
        <tr>
            <th width="160">活动名称</th>
            <th>
                <input type="text" class="cssInput" name="activity_name" value="<?php echo $activity_name;?>">
            </th>
            <th width="160">订单号</th>
            <th>
                <input type="text" name="order_id" value="<?php echo $order_id;?>">
            </th>
        </tr>

        <tr>
            <th width="160">订单交易时间</th>
            <th>
                <input name="buy_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $buy_start;?>">
                <input name="buy_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $buy_end;?>">
            </th>
            <th width="160">提交退款时间</th>
            <th>
                <input name="back_start" type="date" class="cssInput" style="width:190px"  value="<?php echo $back_start;?>">
                <input name="back_end" type="date" class="cssInput" style="width:190px"  value="<?php echo $back_end;?>">
            </th>
        </tr>

        <tr>
            <th width="160">状态</th>
            <th colspan="3">
                <select name="code_status">
                    <option value="1" <?php echo ($code_status == 1) ? 'selected' : '';?>>状态_已提交退款</option>
                    <option value="2" <?php echo ($code_status == 2) ? 'selected' : '';?>>状态_已使用</option>
                    <option value="3" <?php echo ($code_status == 3) ? 'selected' : '';?>>状态_已受理退款</option>
                </select>

                <select name="trade_way">
                    <option value="0" <?php echo ($trade_way == 0) ? 'selected' : '';?>>交易渠道_全部</option>
                    <option value="1" <?php echo ($trade_way == 1) ? 'selected' : '';?>>交易渠道_支付宝</option>
                    <option value="2" <?php echo ($trade_way == 2) ? 'selected' : '';?>>交易渠道_银联</option>
                    <option value="3" <?php echo ($trade_way == 3) ? 'selected' : '';?>>交易渠道_新微信网页</option>
                    <option value="5" <?php echo ($trade_way == 5) ? 'selected' : '';?>>交易渠道_微信app</option>
                    <option value="4" <?php echo ($trade_way == 4) ? 'selected' : '';?>>交易渠道_旧微信网页</option>
                    <option value="6" <?php echo ($trade_way == 6) ? 'selected' : '';?>>交易渠道_用户账户</option>
                </select>


                <select name="page_num">
                    <option value="10" <?php echo ($pageNum == 10) ? 'selected' : '';?>>展示个数_10</option>
                    <option value="50" <?php echo ($pageNum == 50) ? 'selected' : '';?>>展示个数_50</option>
                    <option value="100" <?php echo ($pageNum == 100) ? 'selected' : '';?>>展示个数_100</option>
                    <option value="150" <?php echo ($pageNum == 150) ? 'selected' : '';?>>展示个数_150</option>
                </select>　　
            </th>
        </tr>

        <tr>
            <th width="160"></th>
            <th colspan="3">
                <a href="/wftadlogin/YardsCode/index" style="background-color: green" class="ui-button">清空所有选项</a>
                <button  class="ui-button">提交</button>
                <a href="javascript:void(0)" data-src="/wftadlogin/YardsCode/outData" id="out-data" style="background-color: green" class="ui-button">导出</a>
            </th>
        </tr>
    </table>
</form>

<div class="box">
    <div class="box-title">
        活动使用码列表
    </div>
    <div>
        <table class="table">
            <tbody>
            <tr>
                <th width="50">选择</th>
                <th width="100">交易时间</th>
                <th width="100">提交退款时间</th>
                <th width="100">验证码</th>
                <th width="150">交易号</th>
                <th width="100">订单号</th>
                <th width="100">退款金额</th>
                <th width="100">交易渠道</th>
                <th width="60">用户id</th>
                <th width="100">用户名</th>
                <th width="150">活动名称</th>
                <th width="150">退款原因</th>
                <th width="150">操作</th>
            </tr>
            <?php foreach ($data as $key => $row): ?>
                <tr style="text-align: left" class="ter-change" >
                    <td width="50">
                        <?php if(!in_array($row['id'], $code_minute)):?>
                        <input type="checkbox"  name="check_ids" value="<?php echo $row['id']; ?>"></td>
                    <?php endif;?>
                    <td width="100">
                        <?php echo date('Y-m-d H:i:s',$row['dateline']); ?>
                    </td>
                    <td width="100">
                        <?php echo $row['back_time'] ? date('Y-m-d H:i:s',$row['back_time']) : ''; ?>
                    </td>
                    <td width="100">
                        <?php echo $row['code']; ?>
                    </td>
                    <td width="150">
                        <?php echo $row['trade_no']; ?>
                    </td>
                    <td width="100"><a href="/wftadlogin/excercise/orderinfo?order_sn=<?php echo $row['order_sn'];?>"><?php echo $row['order_sn']; ?></a></td>
                    <td width="100"><?php echo $row['back_money']; ?></td>
                    <td width="100"><?php echo $tradeWay[$row['account_type']]; ?></td>
                    <td width="60"><?php echo $row['user_id']; ?></td>
                    <td width="100"><?php echo $row['username']; ?></td>
                    <td width="150"><?php echo $row['coupon_name']; ?></td>
                    <td width="150"><?php echo $row['back_reason']; ?></td>
                    <td width="150">
                        <?php if(($row['status'] == 3 AND $row['accept_status'] == 0) OR $row['accept_status'] == 1):?>
                            <a style="background-color: green" href="/wftadlogin/YardsCode/check?check_type=1&id=<?php echo $row['id']; ?>" class="ui-button">受理退款</a>
                        <?php endif;?>
                        <?php if($row['status'] == 1 AND $row['accept_status'] == 0):?>
                            <a href="javascript:void(0)" data-id="<?php echo $row['id']; ?>" class="ui-button loginr">提交特殊退费</a>
                        <?php endif;?>
                        <?php if($row['accept_status'] == 2):?>
                             已受理退款
                        <?php endif;?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <input type="checkbox" id="check-this">全选
        <?php if($code_status == 1): ?>
            <button class="ui-button" id="mark-check">所选项受理退款</button>
        <?php endif;?>
        <footer>
            <?php echo $this->pageData; ?>
        </footer>
    </div>

</div>

<style>
    .btn {
        position: relative;
        cursor: pointer;
        display: inline-block;
        vertical-align: middle;
        font-size: 12px;
        font-weight: bold;
        height: 27px;
        line-height: 27px;
        min-width: 52px;
        padding: 0 12px;
        text-align: center;
        text-decoration: none;
        border-radius: 2px;
        border: 1px solid #ddd;
        color: #666;
        background-color: #f5f5f5;
        background: -webkit-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: -moz-linear-gradient(top, #F5F5F5, #F1F1F1);
        background: linear-gradient(top, #F5F5F5, #F1F1F1);
    }

    .login-body {
        padding: 60px 15px;
        color: #444;
        height: 148px;
    }

    .ipt {
        border: solid 1px #d2d2d2;
        border-left-color: #ccc;
        border-top-color: #ccc;
        border-radius: 2px;
        box-shadow: inset 0 1px 0 #f8f8f8;
        background-color: #fff;
        padding: 4px 6px;
        height: 21px;
        line-height: 21px;
        color: #555;
        width: 180px;
        vertical-align: baseline;
    }

    .dform {
        padding: 80px 60px 40px;
        text-align: center;
    }

    .signin {
        margin: -50px -20px -50px 90px;
        text-align: left;
        font-size: 14px;
    }

    .signin h4 {
        color: #999;
        font-weight: 100;
        margin-bottom: 20px;
        font-size: 12px;
    }

    .signin li {
        padding-left: 80px;
        margin-bottom: 15px;
    }

    .signin ol {
        list-style-type: none;
    }

    .signin li strong {
        float: left;
        margin-left: -80px;
        width: 80px;
        text-align: right;
        line-height: 32px;
    }

    .signin .btn {
        margin-bottom: 10px;
    }

    .signin p {
        font-size: 12px;
        color: #999;
    }

    .theme-desc,.theme-version {
        padding-top: 0
    }

    .body-color {
        z-index: 9998;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: #000;
        opacity: 0.4;
        filter: alpha(opacity = 40);
        display: none
    }

    .hide-body {
        z-index: 9999;
        position: fixed;
        top: 30%;
        left: 40%;
        width: 1000px;
        height: 618px;
        margin: -180px 0 0 -330px;
        border-radius: 5px;
        border: solid 2px #666;
        background-color: #fff;
        display: none;
        box-shadow: 0 0 10px #666;
    }

    .close-window {
        border-bottom: 1px solid #ddd;
        padding: 22px;
        position: relative;
    }

    .bottom {
        margin-top: 180px;
    }

    .close-window .close {
        float: right;
        color: #999;
        padding: 5px;
        margin: -2px -5px -5px;
        font: bold 14px/14px simsun;
        text-shadow: 0 1px 0 #ddd
    }

    .close-window .close:hover {
        color: #444;
    }
</style>

<div class="hide-body">
    <div class="close-window">
        <!-- 关闭窗口，也就是触发关闭div的事件-->
        <a href="javascript:;" title="关闭" class="close">×</a>
        <h3>特殊退费操作</h3>
    </div>
    <!-- 中间主体显示div 可以增加其他的样式-->
    <div class="login-body dform">
        <form class="signin" name="loginform" action="/wftadlogin/YardsCode/special" method="post">
            <ol>
                <li>原因: <input name="reason" placeholder="特殊退款" class="cssInput" type="text " /></li>
                <li>金额:
                    <input name="money" placeholder="默认支付金额" class="cssInput" style="width:90px" type="text " />
                    <input name="code_id" type="hidden" id="zjh" value="" />
                </li>
                <li><button  type="submit">提交</button></li>
            </ol>
        </form>
    </div>
</div>


<script>
    $(function () {

        $('.loginr').click(function(){ //jquery的点击事件
            $('.body-color').fadeIn(100);//全局变得黑的效果，具体的div就是theme-popover-mask这个
            $('.hide-body').slideDown(200);//将隐藏的窗口div显示出来
            var code_id = $(this).attr('data-id');
            $('#zjh').val( code_id);

        })
        $('.close-window .close').click(function(){
            $('.body-color').fadeOut(100);//
            $('.hide-body').slideUp(200);//将显示的窗口隐藏起来
        })

        //导出
        $('#out-data').click(function() {
            $('#out-data-form').attr('action', $(this).attr('data-src'));
            $('#out-data-form').submit();
            $('#out-data-form').attr('action', '');

        });

        //选择本页
        $('#check-this').click(function() {
            $("#check-all").attr('checked',false);
            if ($(this).is(':checked')) {
                $("[name=check_ids]:checkbox").prop('checked', true);
            } else {
                $("[name=check_ids]:checkbox").prop('checked', false);
            }
        });


        //确认退款
        $('#mark-check').click(function() {
            if (confirm('确定将所有选中的受理退款？不可恢复')) {
                //执行修改操作
                var check_ids = document.getElementsByName('check_ids');
                var id='';//如果这样定义var s;变量s中会默认被赋个null值
                for (var i = 0; i < check_ids.length; i++) {
                    if (check_ids[i].checked){
                        if (i == check_ids.length - 1) {
                            id += check_ids[i].value;
                        } else {
                            id += check_ids[i].value + ',';
                        }
                    }
                }

                if (id == '') {
                    alert('没有选中任何数据');
                    return false;
                }

                $.post('/wftadlogin/YardsCode/check?check_type=2', {ids:id}, function (data) {
                    alert(data.message);
                    window.location.reload();
                }, 'json');
                return false;
            }
        });

    });
</script>




